bugsnag/bugsnag-android

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.h

Makes safe all invocations of `GetMethodId`, `GetStaticMethodId`, and `FindClass` within the NDK module. This is achieved by calling [ExceptionClear](https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html#exceptionclear) to remove any pending JVM exceptions that could lead to app termination. The return value of all these invocations is checked for `NULL`, and no-ops if this is the case.
- Replaced `FindClass` with `bsg_safe_find_class` (and equivalents for `GetMethodId/GetStaticMethodId`)
- When loading a class, check if there was an exception in the JVM, and if so clear it and return `NULL`. The following errors can be thrown. As these are not recoverable, Bugsnag should no-op rather than crashing the process:
- `NoSuchMethodError`
- `ExceptionInInitializerError`
- …

Check internal JNI calls for pending exceptions and no-op

---

Gemfile
Gemfile.lock

Correct the Gemfile entry for MazeRunner to use a tagged release rather than local reference.

Correct MazeRunner reference

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.quick.yml
CHANGELOG.md
bugsnag-android-core/build.gradle
bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt
bugsnag-android-ndk/build.gradle
bugsnag-android/build.gradle
bugsnag-plugin-android-anr/build.gradle
bugsnag-plugin-android-ndk/build.gradle
bugsnag-plugin-react-native/build.gradle
build.gradle
docker-compose.yml
gradle.properties

Ensures that proguard.txt is added to AARs so that consumers of the library can use ProGuard and R8 for obfuscation.
Alters the gradle script so that each module declares the `consumerProguardFiles`, rather than setting it in an [afterEvaluate](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#afterEvaluate-groovy.lang.Closure-) closure. The AGP version used to build the project has recently changed, so it seems probable that newer versions of AGP read this information before the `afterEvaluate` block triggers, thus ignoring the consumer proguard file.
Confirmed that a locally generated AAR contains a proguard.txt file with the appropriate contents, and checked that the [deployed artefact](https://search.maven.org/artifact/com.bugsnag/bugsnag-plugin-android-ndk/5.5.1/aar) …

Ensure proguard files are included in AAR

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
bugsnag-plugin-android-anr/src/test/java/com/bugsnag/android/AnrDetailsCollectorTest.kt
bugsnag-plugin-android-anr/src/test/java/com/bugsnag/android/BugsnagTestUtils.java
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/EventDeserializerTest.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestHooks.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingScenario.kt
features/smoke_tests/unhandled.feature

Ensures that global metadata is added to ANR error reports. These were previously omitted.
When creating an event in `NativeInterface`, call `client.getMetadataState().getMetadata();` to pass into the `metadata` parameter
Unit test coverage has been updated to mock `client.getMetadataState().getMetadata();` where necessary. The ANR smoke scenario has also been updated to confirm that local & global metadata can be added to ANRs.

Add global metadata to ANR error reports

---

bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt
features/full_tests/batch_1/detect_anr_cxx.feature

PLAT-5853
Older Android systems made much more complicated jumps through native code, often fooling the native code detection heuristics. The only heuristics that work across all versions are:
- Java stack traces leading to native calls will respond true to `isNative`, but this is also true of system-based native bridges out of Java land.
- User-generated JNI functions always start with "Java_", whereas system-generated bridges never do.
Modified the native detection heuristics
Re-ran e2e ANR tests for all supported Android versions

Fix ANR detection for all Android versions

---

features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/AnrHelper.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmAnrDisabledScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmAnrLoopScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmAnrMinimalFixtureScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmAnrOutsideReleaseStagesScenario.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmAnrSleepScenario.kt
features/full_tests/batch_1/detect_anr_cxx.feature
features/full_tests/batch_1/detect_anr_jvm.feature
features/full_tests/batch_2/native_crash_handling.feature
features/minimal/detect_anr_minimal.feature
features/smoke_tests/unhandled.feature
features/support/env.rb

Update the mechanism by which ANRs are generated in tests, in order that they run successfully on Samsung devices (which the previous mechanism did not).
The idea and code for generating ANRs using a deadlock is taken directly from [this post](https://stackoverflow.com/a/45587343/15097391).  With the scenarios running on Samsung devices we no longer need to skip Android 8.1 (it was only coincidence that our 8.1 device is a Samsung).  It also opens the door to running scenarios on alternative Android 5/6 devices, increasing our diversity and resilience to things like unavailable devices.
- New `AnrKelper.kt` to centralize the ANR mechanism.
- Tests no longer skipped on Android 8.1
- Clearing of error popups removed - it's unnecessary and I found that trying to press buttons during an ANR …

Update ANR tests to run on Samsung devices

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.h

Checks additional JNI calls in the NDK module for pending exceptions and no-ops, building on #1088. This is achieved by calling [ExceptionClear](https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html#exceptionclear) to remove any pending JVM exceptions that could lead to app termination.
Added safe versions of the following methods and updated code to check the return value where appropriate:
```
GetStaticFieldID
GetStaticObjectField
NewObject
CallObjectMethod
CallStaticVoidMethod
CallStaticObjectMethod
```

Handle remaining JNI calls error handling

---

Gemfile
Gemfile.lock
features/steps/android_steps.rb

Reduce end-to-end test run times by handling system error dialogs smarter.
Reworks the Cucumber step that's run after a crash so that it times out much quicker (1s), making the assumption that if an element is not visible in that time it's because of a system error dialog taking the focus.  This process will be repeated up to 15 times, equivalent to the default timeout for `find_element`.
Cucumber step reworked, MazeRunner version bumped for local running.
I ran 6 full builds overnight and clearing of the error dialog can be seen working well.  Looking at a couple of Android 5/6 runs, the dialog was dismissed ~40 times, saving at least a couple of minutes on each.
It's worth noting that the Android 5 tests are currently set to `soft_fail` and there is a strange (but existing) issue where …

Improve handling of system dialogs in end-to-end tests

---

bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt
bugsnag-plugin-android-anr/src/main/jni/anr_google.c
bugsnag-plugin-android-anr/src/main/jni/anr_google.h
bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
bugsnag-plugin-android-anr/src/main/jni/bsg_unwind.h
bugsnag-plugin-android-anr/src/main/jni/bugsnag_anr.c
bugsnag-plugin-android-anr/src/main/jni/unwind_func.h
bugsnag-plugin-android-ndk/src/main/jni/bsg_unwind.h
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/event.h
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmAnrLoopScenario.kt

The current method of native trace detection doesn't work anymore on Android 11.
Use only the built-in `isNative` call to detect native frames.
Re-ran e2e tests

Only use isNative for detecting native stack transitions

---

.buildkite/pipeline.yml
bugsnag-plugin-android-anr/src/main/jni/anr_google.c
bugsnag-plugin-android-anr/src/main/jni/anr_google.h
bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
scripts/run-clang-format-ci-check.sh
scripts/run-clang-format.sh

Fixes the script for running Clangformat checks on CI so that errors from any line result in the build step failing.  Also fixes existing format violation in the code base.

Fix Clangformat script and violations

---

bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/ManualSessionSmokeScenario.kt
features/smoke_tests/sessions.feature

Removes a source of flakiness from the `ManualSessionSmokeScenario`, which suddenly started failing on Android 4.4 devices only.
The source of flakiness was introduced by setting an `InterceptingDelivery` in the constructor parameter. The `Scenario` is always constructed before Bugsnag is initialized, which meant on the second launch that although the crashy code should not be invoked, the `InterceptingDelivery` will notify/start sessions when cached payloads are sent from disk.
The fix has been to remove the wait from the mazerunner steps and to disable delivery interception on the second launch.
It's unclear why this has suddenly started failing on Android 4 - I'd hypothesise that these older devices are more sluggish and therefore take longer to respond to Appium commands, giving …

Fix flaky session smoke test

---

CONTRIBUTING.md
Makefile
RELEASING.md

Enforces that the 'clean' task should always be run before generating artefacts. This ensures that the build is always in a consistent state when building or testing a release.

Tweak release command to include 'clean'

---

features/fixtures/mazerunner/app/proguard-rules.pro
features/smoke_tests/handled.feature
features/smoke_tests/unhandled.feature

Enables obfuscation in the test fixture and updates assertions around lineNumbers where necessary. This ensures that the tests run against a minified and obfuscated bugsnag SDK, which should highlight any failures in ProGuard keep rules for the SDK.
This can be verified by inspecting the classes.dex of the fixture APK on Buildkite in Android Studio's APK analyzer.

Enable full obfuscation in test fixture

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c

Avoids calling `DeleteLocalRef` for `jmethodID` and `jfieldID` pointers, which are regular [C-style pointers](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html#wp9502). Invoking this method on an Android emulator results in a SIGABRT when triggering a handled C++ error report in Bugsnag. This behaviour is not triggered on BrowserStack or physical devices, even when loading the same APK.
Ran the example app on an emulator and triggered the C++ error report, confirming that no SIGABRT was raised. This interacts with all the Bugsnag C APIs that use the JNI.
```
SIGABRT Abort program 
[vdso]:2756 __kernel_vsyscall
/system/lib/libc.so:482109 tgkill
/system/lib/libc.so:127055 abort
/system/lib/libart.so:5442750 0xaa348cbe
/system/lib/libart.so:5445018 …
```

Avoid calling DeleteLocalRef for jmethodID and jfieldID pointers

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.quick.yml
.buildkite/pipeline.yml

Ensure the latest available Maze Runner image is always used.
The initial `build` step was completely useless and a hangover from how we used to do things.  Adding the `pull:` to every `run:` step should mean that we receive the newest `latest-v4-cli` Maze Runner image every time - for example when a new release is made and the EC2 instances are already up and running (with their local Docker registries).

Always pull maze runner image before running

---

bugsnag-plugin-android-anr/build.gradle
bugsnag-plugin-android-ndk/build.gradle

The build script on Unity fails as modern versions of Android Studio (4.1.1) are unable to build the armeabi ABI. This fixes the buildscript by removing armeabi from the targets. This brings Unity into line with Android on the architectures it supports.

Allow assembling with Android Studio 4.1.1

---

features/full_tests/batch_1/detect_anr_jvm.feature

Resolves a test failure in e2e scenario `JvmAnrSleepScenario`.  As there is still a question mark over the direction in which the product is going to go, I have opted for the simplest change possible just to get it passing CI.  The scenario should be reviewed before the completion of the integration branch.

Fix failing test

---

CHANGELOG.md
bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/event.c
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.h
bugsnag-plugin-android-ndk/src/main/jni/utils/string.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.h

Performs additional checking of JNI calls for pending exceptions, and no-ops if these are detected. This changeset also wraps all JNI calls in a `bsg_safe` wrapper, which checks for disallowed parameter values such as `NULL` and no-ops.
The changeset is roughly broken up into individual commits for each affected JNI method:
```
DeleteLocalRef
ReleaseByteArrayElements
ReleaseStringUTFChars
GetStringUTFChars
IsInstanceOf
GetArrayLength
```
Each affected method has been added to `safejni.h` and its parameters checked according to the [JNI docs](https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html). For `GetStringUTFChars` the calling method has been updated to handle a `NULL` return value where necessary.
JNI calls in the ANR plugin have also been updated to perform …

Check additional JNI calls for pending exceptions and no-op

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceIdStore.kt

The `DeviceIdStore` can throw an `AssertionError` from [JsonReader#peek()](https://developer.android.com/reference/android/util/JsonReader#peek()) if the file contents are empty. Because `DeviceIdStore` only catches `Exception`, this can result in a crash when initializing Bugsnag.
Catching `Throwable` rather than `Exception` fixes the problem.
Looking at the implementation of `JsonReader`, it appears that the error can get thrown when reading from an empty file. This could be caused by some an I/O or JSON serialization error - e.g. when there is no space left on the device.
The implementation can't currently recover from this scenario but should be able to do so with this fix. This fix allows the notifier to attempt to persist a new device ID each initialization if one was not present, …

Fix rare crash when loading device ID

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.h

Ensures that `JNI_COMMIT` is always used when calling `ReleaseByteArrayElements`, and that any variables allocated via malloc/new are freed manually. This is preferable to the default mode which calls `delete []` on elems, leading to undesirable behaviour.

Improve how NDK payload is freed

---

.buildkite/pipeline.yml
bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.h
bugsnag-plugin-android-ndk/src/main/jni/utils/string.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.h
docker-compose.yml
dockerfiles/Dockerfile.android
examples/sdk-app-example/build.gradle
tests/features/plugin_interface.feature

Backports the following PRs to the v4 branch for use in bugsnag-unity: #1088 #1091 #1092 #1117
These enhance the error handling around JNI calls by ensuring that exceptions are checked and cleared.
The PR consists of 4 commits, which add the new `safejni.h` functions, then applies them to the source files in the NDK module.
Broadly speaking this was mostly a case of just copying functions over. There were a few structs that were renamed between v4 and v5 (e.g. `bsg_metadata_t` to `bugsnag_metadata`) that required alterations, and some method names on the `NativeInterface` class were renamed. The `bugsnag_notify_env` and `bugsnag_populate_crumb_metadata` functions have also been split into multiple functions in v5 - this change has been carried across.
Performed a smoke test by comparing …

Backport JNI error handling fixes to v4

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c

Moves a `free()` to the exit block so that it is always called when cleaning up the `deliverReportAtPath` function.

Move free() call to exit block

---

bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c

The `activity` can be `NULL` - if this is the case then the in foreground state should be updated, rather than returning early.

Remove unnecessary null check for inForeground update

---

RELEASING.md

Updates the release steps to mention that the AAR/POMs/ProGuard rules should be inspected for the uploaded artefacts.
This also clarifies a couple of points that have changed over time:
- A PR from `next` should be required for anything that isn't a hot fix
- The Github tag should occur after the release to avoid premature RSS feeds being triggered
- The bintray maven repo URL points at the bugsnag repo, as several artefacts are now released rather than just 2

Update release steps

---

Gemfile.lock
bugsnag-plugin-android-anr/src/main/jni/anr_handler.c

Adds safe wrapper calls to the ANR handler code which invokes the JNI.
Because the ANR handler is in a separate module to the NDK code, the relevant methods have been temporarily duplicated until the project can be restructured to the point where it can share C code between modules. A ticket has been raised to do this but it will likely require a major version bump.

Ensure ANR handler calls JNI code safely

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.c

Wraps all usages of `strncpy()` in a safe function call. This was first identified in #1143 and needs porting to `next`.

Replace strncpy() usage with safe function call

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryHeaders.kt

Prevents an NPE when the `apiKey` is null - as in the case of internal error reports. This prevents internal error reports from being sent, and was discovered in #1144, which reenables these E2E tests. It does not affect normal functioning of Bugsnag for the end-user.
Ran locally against new tests added in #1144 to confirm issue is no longer present.

Prevent NPE when delivering internal error reports

---

RELEASING.md

It seems to be possible to test against the artefacts uploaded to Sonatype, although the official docs and Android guides are quite unclear on how do this. This changeset adds a note to the release steps on how this can be achieved.

Detail how to test against sonatype staging artefact

---

bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.h
bugsnag-plugin-android-ndk/src/main/jni/utils/string.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.h
tests/features/native_api.feature

Backport of #1133 to the v4 branch for bugsnag-unity..
Performs additional checking of JNI calls for pending exceptions, and no-ops if these are detected. This changeset also wraps all JNI calls in a `bsg_safe` wrapper, which checks for disallowed parameter values such as `NULL` and no-ops.
The changeset is roughly broken up into individual commits for each affected JNI method:
```
DeleteLocalRef
ReleaseByteArrayElements
ReleaseStringUTFChars
GetStringUTFChars
IsInstanceOf
GetArrayLength
```
Each affected method has been added to `safejni.h` and its parameters checked according to the [JNI docs](https://docs.oracle.com/en/java/javase/11/docs/specs/jni/functions.html). For `GetStringUTFChars` the calling method has been updated to handle a `NULL` return value where necessary.
JNI calls in …

Plat 5957/additional backports

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.quick.yml
features/steps/android_steps.rb

Attempts to improve the stability of Android 5 testing by increasing the timeout when waiting for elements and upping the Appium version to the latest possible at this time. 
We were seeing some failures to find the `scenario_name` element, despite the field being visible in the screenshot that was taken for the failure.  This change seems to improve the situation, but it's not perfect and we should explore using the very latest version of Appium now available.  Trying this now uncovered another problem, in that at least one of our scenarios fails consistently with a newer version (more investigation needed and internal ticket raised).
Use Appium 1.8.0 on Android 5 (1.9.1 causes scenario failures at present) and increase timeout when finding elements.
Covered by CI.

Improve stability of Android 5 testing

---

.buildkite/pipeline.yml
docker-compose.yml
tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
tests/features/support/env.rb

Improve stability of builds for v4 back-ported changes.
Applies some techniques that we've learnt since v4, as well as allowing retries on e2e test scenarios (for these v4-basd changes only).
- Update Buildkite pipeline pipeline to allow retries
- Use latest v2 Maze Runner
- Dismiss error dialogs when app launches
Covered by CI.

Improve build stability for v4 back-ports

---

bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/jnicache.c
bugsnag-plugin-android-ndk/src/main/jni/jnicache.h
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.c
bugsnag-plugin-android-ndk/src/main/jni/utils/jni_utils.c
bugsnag-plugin-android-ndk/src/main/jni/utils/jni_utils.h

https://bugsnag.atlassian.net/browse/PLAT-6090
The JNI cache used by the metadata and breadcrumb system is now initialised once at app start, and is made available as a global.
Manual testing with the example app, and e2e tests.

Global JNI cache

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
features/fixtures/mazerunner/app/src/main/AndroidManifest.xml

Sets up [GWP-ASan](https://developer.android.com/ndk/guides/gwp-asan) so that is enabled in our mazerunner test fixture. If memory is misused in the NDK layer this tool should detect this by randomly sampling memory usage, and raise SIGABRT. 
This should provide us insight into whether there are use-after free/buffer overflows problems in the use of our NDK code when the Android 11 tests are run. By extension this should find any latent issues in the implementation of v4 too.

Setup gwp-asan for CI fixture

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java

Persists the `LastRunInfo` so that previous launch information can be retrieved by the user. This also sets the value of `app.isLaunching` on JVM events.
The implementation of this behaviour for NDK errors will be done in a separate changeset to ease review.
- Added `LaunchCrashTracker`, which tracks the state of whether the application is currently launching or not
- Created `LastRunInfoStore`, which loads and saves the `LastRunInfo` object from disk in the key-value format
- Reset the `LastRunInfo` to the defaults on `Client` initialization
- Set the `LastRunInfo` whenever an unhandled exception occurred so that the next launch allows the user to check that the app crashed
Added unit tests for new classes. Updated JVM events to assert that the `app.isLaunching` field is set to the …

Persist LastRunInfo and populate app.isLaunching for JVM errors

---

Gemfile
Gemfile.lock
docker-compose.yml
features/steps/android_steps.rb

Use the newly introduce `click_element_if_present` method on the Maze Runner Appium driver class instead of handling raised `NoSuchElementError`s.
The previous method of calling `driver.click_element`, which can raise a `NoSuchElementError` meant that Android could not use Maze Runner's resilient driver.  Because `NoSuchElementError` extends `WebDriverError`, the resilient driver would catch it before it reached the Android step code, causing a retry loop that would never succeed.
This change has no overall effect in itself, but should allow the resilient driver to be used should be find ourselves needing to.
Covered by CI.

e2e tests: Use click_element_if_present

---

features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/cxx-scenarios-bugsnag.cpp
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXNotifySmokeScenario.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/HandledJavaSmokeScenario.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/UnhandledJavaLoadedConfigScenario.java
features/full_tests/batch_2/native_metadata.feature
features/smoke_tests/handled.feature
features/smoke_tests/unhandled.feature

Adds more checks that `password` fields in metadata are redacted by default.  
This seems to have found a bug in the NDK layer, as the value was coming through in plain text.  The corresponding step has been commented out internal ticket raised.

Add tests that password metadata is redacted by default

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CrashHandlerScenario.kt
features/full_tests/batch_1/crash_handler.feature

Adds an assertion that a secondary error handler will be called correctly, using the log assertions added recently

[PLAT-5874] Add assertions for secondary error handlers using logs

---

features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/cxx-scenarios-bugsnag.cpp
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXCrashLoopScenario.kt
features/full_tests/batch_1/identify_crashes_on_launch.feature

Adds E2E scenarios where Bugsnag allows an application to recover from a crash loop by checking the value of `Bugsnag.getLastRunInfo()`. Along with #1180 this adds the required E2E test coverage for the project.
- Added scenario code which triggers a fatal JVM + NDK crash loop by crashing as soon as the scenario is run
- If `Bugsnag.getLastRunInfo().crashedDuringLaunch` is true, the application enables a 'safe-mode' which avoids the crashy path
- Confirmed that the values of `LastRunInfo` are populated as expected.
Note: the NDK `LastRunInfo` functionality hasn't been implemented yet so the scenario fails. This will be addressed in PLAT-5978 which will uncomment the E2E test.

Add E2E tests for crash loop scenarios

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/BackgroundTaskService.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BackgroundTaskServiceTest.kt

Adds `BackgroundTaskService` with the intent of replacing the `Async` class. For general motivations of why this is necessary, please read [the following](https://github.com/bugsnag/bugsnag-android/pull/1172#issue-584912344).
- Added `BackgroundTaskService` class which will have the responsibility of controlling how all lengthy tasks are run in the background
- Created `submitTask` method to which callers can submit a `Runnable` or `Callable` and receive a `Future` in return
- Created a `TaskType` enumeration that determines what single-threaded executor the task is executed on
- Added a more nuanced shutdown strategy that only waits for IO/Error/Session requests to complete on process termination
- Diverged from the `Async` implementation by ensuring that each executor is single-threaded …

Add BackgroundTaskService to replace Async.java

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionTrackerConfinementTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerPauseResumeTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerTest.java

Updates `SessionTracker` to use `BackgroundTaskService` rather than `Async`. This allows for better control over asynchronous operations and negates the need for a `Semaphore` which was a source of non-deterministic behaviour that could lead to some session requests not immediately being sent. This is based on changes made in #1182.
- Create a `BackgroundTaskService` in the `Client`
- Updated `SessionTracker` to require a `BackgroundTaskService` constructor param
- Refactored `SessionTracker` to submit two types of task to the session request executor: flushing stored sessions from disk, and flushing in-memory sessions
Added a unit test to confirm that requests on the session tracker are confined to a thread, otherwise relied on existing E2E test coverage for sessions.

Update SessionTracker to use BackgroundTaskService

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/EventStoreConfinementTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java
bugsnag-android-core/src/main/java/com/bugsnag/android/EventPayload.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java
bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventStoreMaxLimitTest.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/ManualSessionSmokeScenario.kt

Updates the event delivery mechanism to use `BackgroundTaskService` rather than `Async`. This allows for better control over asynchronous operations and negates the need for a `Semaphore` which was a source of non-deterministic behaviour that could lead to some session requests not immediately being sent. This is based on changes made in #1182.
- Converted `DeliveryDelegate` and `EventStore` to use `BackgroundTaskService`
- Altered `ManualSessionSmokeTest` to account for deterministic behaviour, and avoid flaky delivery limitations.
- Called `bgTaskService.shutdown()` after a fatal JVM error, which avoids dropping in-flight requests
Added a unit test to confirm that event requests are confined to a thread, otherwise relied on existing E2E test coverage.

Deliver events using BackgroundTaskService

---

.buildkite/pipeline.quick.yml

Soft fail the Android 5 smoke tests while we continue to investigate Appium stability issues.

Soft fail Android 5 smoke tests

---

features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/cxx-scenarios-bugsnag.cpp
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmCrashLoopScenario.kt

Removes the unused `CXXCrashLoopScenario` and replaced it with `JvmCrashLoopScenario`, which was removed from version control due to a bad merge.

Fix deletion of JvmCrashLoopScenario

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/AppWithState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/LaunchCrashTracker.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/StateEvent.kt
bugsnag-plugin-android-ndk/src/androidTest/resources/app_serialization_0.json
bugsnag-plugin-android-ndk/src/main/assets/include/event.h
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/event.c
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c
bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c
features/fixtures/mazerunner/cxx-scenarios/src/main/cpp/cxx-scenarios.cpp
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXDelayedErrorScenario.kt
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXMarkLaunchCompletedScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmDelayedErrorScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmMarkLaunchCompletedScenario.kt
features/full_tests/batch_1/identify_crashes_on_launch.feature
features/smoke_tests/unhandled.feature

Currently `app.isLaunching` is only set on JVM error reports. This changeset adds it to NDK error reports and adds verification that it has been set for both in the form of E2E tests.
- `LaunchCrashTracker` extends `BaseObservable` and notifies its observers when `isLaunching` is set to false
- The `NativeBridge` which communicates with the NDK layer invokes a JNI function which updates `bsg_event->app.is_launching` to false
- Fixed JVM serialization bug where `inForeground` rather than `isLaunching` value was serialized
- Added `is_launching` to `bsg_app_info` struct
- Added `bugsnag_app_get_is_launching/bugsnag_app_set_is_launching` functions to allow users to alter the value in an on_error callback.
When a fatal NDK error occurs, the memory contents of `bsg_event` struct is persisted …

Propagate changes in app.isLaunching to the NDK layer

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/EventStoreConfinementTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/EventFilenameInfo.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java
bugsnag-android-core/src/test/java/com/bugsnag/android/EventFilenameTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/LaunchCrashDeliveryTest.kt

Updates the existing synchronous reporting of launch crashes so that they fit the behaviour of the new spec. Specifically, synchronous delivery should only be attempted for the most recent startup crash.
- "_startupcrash" is appended to the filename based on whether `app.isLaunching` is set to true, rather than the previous `app.duration` exceeding a threshold
- Refactored `flushOnLaunch()` so that it creates a `Future` and blocks for 2 seconds calling `get()`. This avoids a busy wait that the previous implementation used
- Altered `EventStore` so that it only looks for the most recent startupcrash, as determined by the timestamp and "_startupcrash_ suffix encoded in the filename
- Fixed a bug where .json was encoded in the filename twice (this does not affect any functionality)
- …

Update synchronous crash reporting logic

---

features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXMarkLaunchCompletedScenario.kt

The `CxxMarkLaunchCompletedScenario` triggers an NDK crash immediately after calling `Bugsnag.notify()`. This triggers a race where the NDK crash can terminate the process before the JVM error has a chance to make a request.
This fixes the scenario to only trigger the NDK crash after the first request has been delivered.

Refactor test to avoid request flakes

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/FileStoreTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ConnectivityCompat.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ObjectJsonStreamer.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ConnectivityLegacyTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventStoreMaxLimitTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/SessionStoreMaxLimitTest.kt
buildSrc/src/main/kotlin/com/bugsnag/android/BugsnagBuildPluginExtension.kt
buildSrc/src/main/kotlin/com/bugsnag/android/Versions.kt
dockerfiles/Dockerfile.android-common

Bumps the [compileSdkVersion](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd) to apiLevel 30 from 28. This ensures that our SDK is compiled against the latest version of Android while retaining compatibility for previously supported versions.
- Bumped compileSdkVersion to 30
- Removed unused API 28 system image from CI, reducing docker image size
- Suppressed new deprecations where necessary
- Altered internal code and tests where nullability annotations have been changed between 28/30, e.g. `fun onAvailable(network: Network?)` was altered to `fun onAvailable(network: Network)`. This should have no effect on our public API or customer behaviour.
Relied on existing test coverage. Additionally read the [Android …

Bump compileSdkVersion to apiLevel 30

---

features/fixtures/mazerunner/app/src/main/AndroidManifest.xml
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MazerunnerApp.kt

Android 9 and onwards [added restrictions](https://developer.android.com/guide/app-compatibility/restrictions-non-sdk-interfaces) on the use of hidden Android APIs, which can trigger warnings/crashes if they are used within an app. This changeset alters the test fixture so that it will throw an exception if any non-sdk API is used by Bugsnag.
Setup `StrictMode` to throw an exception if any non-SDK API is used in the E2E tests.
It's worth noting that I also investigated [veridex](https://developer.android.com/guide/app-compatibility/restrictions-non-sdk-interfaces#test-veridex-tool) for setting up on CI. I don't think it's necessary as `StrictMode` should cover this functionality (I also encountered a segfault when trying to use the latest version of the tool).
Relied on existing test …

Detect non-sdk usages in E2E tests

---

CHANGELOG.md
bugsnag-android-core/CMakeLists.txt
bugsnag-android-core/build.gradle
bugsnag-android-core/src/main/CMakeLists.txt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/RootDetector.kt
bugsnag-android-core/src/main/jni/root_detection.c
bugsnag-android-core/src/test/java/com/bugsnag/android/RootDetectorTest.kt

Creates a native library loaded by the `bugsnag-android-core` module that is responsible for detecting rooted devices. This is independent from the ANR/NDK native libraries and its sole purpose is to detect rooted devices.
- Created a new native library named `bugsnag-core`
- Loaded `bugsnag-core` library within the `RootDetector` class
- Perform a JNI call as part of the root detection. Currently this is unimplemented but a future PR will perform various root detection measures
- If the library cannot be loaded, default to false. This could either be due to root detection countermeasures blocking the library from loading, or genuine bugs with how the Android OS loads libraries.
- Added some additional logging
- Confirmed that the native library loads through manual testing
- Confirmed …

Setup native library for root detection

---

bugsnag-android-core/src/main/jni/root_detection.c

https://bugsnag.atlassian.net/browse/PLAT-6106
Use `lstat` to check for file existence and mode. We can't safely use syscalls since later versions of Android lock down certain functions, and some syscalls aren't directly accessible without guessing their numbers (which could break if they ever change).
Check for existence of a number of files, and writability of other files, per https://github.com/scottyab/rootbeer
Ran on jailbroken and non-jailbroken devices (emulated and real)

Root files detection

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/AppDataCollectorTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt
bugsnag-plugin-android-ndk/src/main/jni/metadata.c

Collects whether the system has restricted background work for the app, as reported by [`isBackgroundRestricted()`](https://developer.android.com/reference/android/app/ActivityManager#isBackgroundRestricted()), which is available on Android 9+.
This is useful information as some users do enable battery optimizations that throttle the amount of work an app can do in the background. For example, scheduled services and alarms may not execute. It seems probable that this could lead to bugs in some apps so this would be useful information to collect.
- Added `backgroundWorkRestricted` to the `app` metadata (only when restrictions are enabled, otherwise the field is not added)
- Added unit tests to confirm the functionality works as expected

Collect whether the system has restricted background work for the app

---

.buildkite/pipeline.quick.yml
bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/BugsnagConfig.kt
features/full_tests/batch_1/internal_error_reports.feature
features/full_tests/batch_1/load_configuration.feature
features/smoke_tests/handled.feature
features/smoke_tests/sessions.feature
features/smoke_tests/unhandled.feature

Cater for device farms that instrument APKs updated for end-to-end tests.
Sauce Labs behaves differently than BrowserStack in that it instruments the APKs we upload for e2e tests, making them "debuggable" and causing our notifier to report the `releaseStage` as `development` rather than `production`.
This change relaxes the e2e test expectations to accept either `releaseStage` reported by the notifier, whilst also adding a unit test to ensure the notifier logic is properly tested.
Covered by CI and the new unit test.

Relax checking of releaseStage

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt
bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c
gradle.properties

The memory offset for `bsg_app_info_v2` is wrong by one due to the unintentional inclusion of `is_launching`. This means that the first byte of `binary_arch` for persisted v4 structs is loaded into `is_launching`, causing the `binary_arch` to be incorrectly trimmed to '86' or 'rm64'.
Removed `is_launching` from `bsg_app_info_v2` as it was not originally present.
Added additional unit test coverage of the migration function. Manually tested by triggering a fatal crash in v5.7.0, then updating to v5.9.0 to reproduce the behaviour. Confirmed that a local artefact with these changes fixed the issue.

Fix deserialization bug in persisted NDK errors

---

.buildkite/pipeline.full.yml

Allows publishing from the master branch rather than requiring a tag as this fits into our existing publishing process.
Tested by verifying that setting the `build.branch` to `PLAT-6241/publish-on-master` caused the publish step to appear - it's assumed that the publish step itself works as expected.

Allow publishing from master branch

---

features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CrashHandlerScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/ManualSessionSmokeScenario.kt
features/full_tests/batch_1/crash_handler.feature

Fixes a couple of flaky mazerunner tests identified via scheduled builds.
`CrashHandlerScenario` was inherently racy as the log endpoint makes a network request which may or may not be successful before the uncaught exception terminates the process. It has been rewritten so the custom crash handler alters metadata, and the scenario verifies the handler was invoked.
`ManualSmokeSessionScenario` was flaky in very specific circumstances: if the last handled error + unhandled error are written to disk in the same millisecond, and the generated UUID meant the [request order](https://github.com/bugsnag/bugsnag-android/blob/next/bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java#L124) was wrong. The scenario has been updated to ensure that the handled errors are always …

Fix flaky mazerunner tests

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagTestUtils.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt
bugsnag-android-core/src/test/resources/event_redaction.json
bugsnag-android-core/src/test/resources/event_serialization_0.json
bugsnag-android-core/src/test/resources/event_serialization_1.json
bugsnag-android-core/src/test/resources/event_serialization_2.json
bugsnag-android-core/src/test/resources/event_serialization_3.json
bugsnag-android-core/src/test/resources/event_serialization_4.json
bugsnag-android-core/src/test/resources/event_serialization_5.json
bugsnag-android-core/src/test/resources/event_serialization_6.json
features/smoke_tests/handled.feature
features/smoke_tests/unhandled.feature

Adds `projectPackages` to the event payload. This is used to improve deobfuscation when a class in the `projectPackages` package has been minified with ProGuard - `inProject` calculations do not work well here as the class name will be mangled.
- Added unit tests to ensure `projectPackages` is serialized
- Updated smoke tests to add E2E assertions
- Tested errors sent in obfuscated example app

Add projectPackages field to error payloads

---

bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.c
bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h
bugsnag-plugin-android-ndk/src/main/jni/utils/migrate_internal.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.h
bugsnag-plugin-android-ndk/src/test/CMakeLists.txt
bugsnag-plugin-android-ndk/src/test/cpp/test_migrate.c
bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.h
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c

serializer.c was getting too big. The migration code can be self-contained in a separate file.
Re-ran unit tests and e2e tests.

Move migration code from serializer.c to its own file

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.quick.yml
Gemfile
Gemfile.lock
Makefile
docker-compose.yml
docs/MAZERUNNER.md
features/full_tests/batch_1/in_foreground.feature
features/full_tests/batch_1/internal_error_reports.feature
features/steps/android_steps.rb
scripts/run-instrumentation-test.sh

Use the Maze Runner v5, which provides the benefit of running the latest version of Appium available on each Android version (1.20.2 apart from on Android 4.4 which is limited to 1.9.1 on BrowserStack).
A couple of changes were needed in response to differences in Appium behavior:
- Catching and ignoring exceptions raised when attempting to push buttons during an ANR
- Ensuring the orientation is portrait for the scenario that asserts on it (the previous scenario can leave it landscape for some reason).
Covered by a `[full ci]` run.

Use MazeRunner v5

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

Trigger the `bugsnag-js` pipeline when building the Android `next` branch, passing the `BUILD_RN_WITH_LATEST_NATIVES` variable set to "true".  This will cause the React Native e2e tests to be run with the latest version of the Android (and Cocoa) notifier from `next`.
The onus will be on the native notifier maintainers to check the RN test run before making a release.

Trigger RN tests when building next

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ExceptionHandler.java
bugsnag-android-core/src/main/java/com/bugsnag/android/LibraryLoader.java
bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
bugsnag-android-core/src/main/java/com/bugsnag/android/PluginClient.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ExceptionHandlerTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/LibraryLoaderTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/PluginClientTest.kt
bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NdkPlugin.kt
features/fixtures/mazerunner/cxx-scenarios/src/main/cpp/cxx-scenarios.cpp
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/UnhandledNdkAutoNotifyFalseScenario.kt
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/UnhandledNdkAutoNotifyTrueScenario.kt
features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/TestHarnessHooks.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoDetectAnrsFalseScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoDetectAnrsTrueScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/HandledJvmAutoNotifyFalseScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/UnhandledJvmAutoNotifyFalseScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/UnhandledJvmAutoNotifyTrueScenario.kt
features/full_tests/batch_1/auto_notify.feature

Adds non-public methods to support the autoNotify and autoDetectAnrs APIs on Unity, which allow automatic error detection to be switched off after Bugsnag has been initilized: https://docs.bugsnag.com/platforms/unity/configuration-options/#autodetectanrs
- Added `NativeInterface.setAutoDetectAnrs` and `NativeInterface.setAutoNotify`, which will be invoked from Unity
- Refactored `AnrPlugin` and `NdkPlugin` to allow for signal handlers etc to be unregistered in a call to `Plugin#unload()`
- Refactored `ExceptionHandler` to allow uninstalling
- Altered `Client` and `PluginClient` to ensure that any change in `autoNotify/autoDetectAnrs` is propagated to all automatic error detection sources
Added unit tests throughout, and added E2E tests which verify that ANRs/JVM/NDK errors are recorded …

Unity: add methods for setting autoNotify and autoDetectAnrs

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadStateMissingTraceTest.kt

Prevents a rare NPE when capturing thread traces where the stacktrace element is returned as null. If this occurs then the thread trace is simply skipped as there's no way of recording the information.
Added a unit test to verify that the behaviour is fixed.

Prevent rare NPE when capturing thread traces

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ConnectivityCompat.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ContextExtensions.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/SystemBroadcastReceiver.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ConnectivityLegacyTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ContextExtensionsKtTest.kt

Catches exceptions thrown by [Context.registerReceiver](https://developer.android.com/reference/android/content/Context#registerReceiver(android.content.BroadcastReceiver,%20android.content.IntentFilter)) to prevent rare crashes.
Specifically this catches `SecurityException`, which might be [thrown by the OS](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/core/java/com/android/server/am/ActivityManagerService.java;l=15675) if it cannot verify that the package registering the receiver has permission to do so, `DeadSystemException`, which is thrown when the OS is about to restart, and `IllegalArgumentException`, which is thrown when the process UID does not match the caller ID.
Receivers are used to check network connectivity, collect device metadata, …

Catch exceptions thrown by Context.registerReceiver to prevent rare crashes

---

bugsnag-plugin-android-anr/src/main/jni/anr_handler.c

The previous ANR fix had the `enable` flag being set AFTER creating a new thread that depends upon it. This resulted in flakey behaviour.
re-run e2e tests and verify that they don't flake anymore.

Make sure enabled flag is set before installing the ANR handler

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/EventFilenameInfo.kt

Prevent a possible NegativeArraySizeException which could occur when Matcher.groupSize returned a negative value.

Fix NegativeArraySizeException during crash report deserialization

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorInternal.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/NullStackTraceScenario.kt
features/full_tests/batch_1/null_stacktrace.feature

There are rare cases where a throwable has a null `stackTrace`.
Check for null before attempting to iterate the stack trace.
I wasn't able to build a repro case since there's no valid way to set a Throwable's `stackTrace` to null. Attempting to manually set it to null generates a NPE.
Re-ran e2e tests.

Handle edge case where an exception's stack trace is null

---

bugsnag-android-core/src/main/java/com/bugsnag/android/LaunchCrashTracker.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/LaunchCrashTrackerTest.kt

Alters the `LaunchCrashTrackerTest` as the `isLaunching` state might not be updated in the timeout required, as a `Runnable` is submitted to an `Executor`. Therefore the unit test just asserts that the necessary method on the mock is called.

Fix flaky test by verifying scheduled executor is called

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ThreadStateTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt

Avoid capturing all of the thread stacktraces when they won't be reported.
Instead of capturing stacktraces as a default in the constructor, the argument is now nullable and lazy-captured in the `init` block if required.
Existing tests were altered to use the default null value, and a new test was added to ensure that the  `ThreadSendPolicy.NEVER` causes any stacktraces passed to `ThreadState` are discarded.

fix: avoid capturing thread stacktraces when not required to

---

docs/MAZERUNNER.md
docs/RELEASING.md

The latest GPG default algorithm (ed25519) is not supported by the Gradle signing plugin we are using, as such we need to generate RSA/4096 keys manually.
Also reference the RELEASING.md documentation from MAZERUNNER.md when referring to the need for a GPG key.

docs(mazerunner): updated the local setup for GPG changes

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java
features/full_tests/batch_1/internal_error_reports.feature

Change the Bugnag-Internal-Error header to "bugsnag-android"
Modified the `internal_error_reports` feature to expect the new header value instead of "true"

Plat 6481/fix internal error header

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/StrictModeHandler.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ThrowableExtensions.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/RecursiveThrowableCauseTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/UnrollThrowableCausesTest.kt

Avoid errors caused by Throwable.cause chains that are recursive (self-referencing).
Added a method to unroll the cause-chain into a flat List and handle any recursion. 
Added RecursiveThrowableCauseTest to test code that previously had recursion problems, and UnrollThrowableCausesTest to test the contract of the new unroll method.

fix: avoid recursive Throwable cause chains

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceWithState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ObjectJsonStreamer.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Session.java

Add Date support to our JSON serialization layer to avoid making encoding mistakes when writing serialization code
Relied on existing tests to ensure that the format has not changed

refactoring(json): added support for Date directly to ObjectJsonStreamer

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/assets/include/bugsnag.h
bugsnag-plugin-android-ndk/src/main/assets/include/event.h
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/event.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.h

Fix the warnings emitted from the C++ compiler related to writable strings:
```
ISO C++11 does not allow conversion from string literal to 'char *'
```
Relied on existing testing

fix(ndk): clearly marked read-only `char*` arguments as `const`

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
bugsnag-android-core/src/test/java/com/bugsnag/android/AppDataCollectorForegroundTest.kt

Improve the performance of data gathering by only capturing the foreground and battery status once (where we were capturing it twice).
Added a unit-test to cover the different possible outputs of `foregroundDuration`

Plat 6092/improve device data gathering performance

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/MemoryTrimTest.java
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ClientComponentCallbacks.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ClientObservable.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/StateEvent.kt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt

Relay onLowMemory events to the NDK layer through the client Observable so that it will be included in all NDK reports.
Included a heavily mocked unit test to ensure that the events are relayed to the client Observables. This task also requires manual testing.

fix: relay onLowMemory events to client Observers

---

CHANGELOG.md
bugsnag-plugin-android-anr/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/CMakeLists.txt

Stop including the `liblog.so` file in the `aar` files during a build on Linux.
Affects the build process and has been checked on MacOS and Linux

fix(ndk): link directly to liblog without find_library

---

CHANGELOG.md
bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
features/full_tests/batch_1/auto_notify.feature

PLAT-6620
ANRs were not being re-enabled after being disabled via the API.
Don't exit the watchdog thread anymore. Just loop to the next thread wait point and then after being triggered, only do ANR processing if ANRs are currently enabled.
Ran in a unity project that disables and enables error and ANR processing.

Fix disabling/re-enabling ANR after initialization

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-plugin-android-anr/detekt-baseline.xml
build.gradle
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/bugsnag/android/Versions.kt
examples/sdk-app-example/build.gradle
features/fixtures/mazerunner/build.gradle
features/fixtures/minimalapp/app/build.gradle
features/fixtures/minimalapp/build.gradle

Replace the jcenter references with mavenCentral.
- Replace jcenter references with mavenCentral
- Bump detekt to version 1.17.1 to avoid dependencies served only from jcenter
- Rerun the detekt baseline to cover the existing codebase
Relied on existing testing

fix(gradle): replace jcenter references with mavenCentral

---

CHANGELOG.md
bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
features/full_tests/batch_1/auto_notify.feature

Reverts bugsnag/bugsnag-android#1265 - the implementation could lead to duplicate error reports being sent for ANRs.

Revert "Fix disabling/re-enabling ANR after initialization"

---

CHANGELOG.md
bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
features/full_tests/batch_1/auto_notify.feature

https://github.com/bugsnag/bugsnag-android/commit/54130ee7739498ce54d85cd095826c098d20ba51 was incomplete because some old trigger code was left in `bsg_handler_uninstall_anr()`, which could trigger a double-report if called in quick succession (as happened in the e2e tests). Also, Google ANR reporting was incorrectly gated on the `enabled` flag.
In the revised ANR system:
- Installing the ANR handler starts a monitoring thread that waits on a semaphore, triggers the Google ANR handler thread, triggers Bugsnag ANR handling (if enabled), and then resets everything to run again. This thread remains until app termination (so that we can detect multiple ANRs).
- Enabling/disabling ANR handling only changes the `enabled` flag. `SIGQUIT` processing still happens in the Bugsnag handler and gets …

PLAT-6620: Do not shut down ANR thread

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt

Caches the value of `app.backgroundWorkRestricted` as it is unlikely to change over a session. This should improve the performance of subsequent `Bugsnag.notify()` calls as the API call took ~3ms on a OnePlus 7.
Ran the example app with the artefact and confirmed the field is reported correctly.

Cache value of app.backgroundWorkRestricted

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/CallbackState.kt

Bugsnag supplies the ability to set callbacks for when breadcrumbs are added, and when an error or session are captured. Breadcrumbs/errors in particular can be captured many times per second.
By default no callbacks are set. This changeset optimizes the default behaviour by performing an `isEmpty()` check before running the callbacks, which avoids construction of an iterator each time. For the addition of ~1000 breadcrumbs this saves ~3ms in the default case and has negligible impact when callbacks are set.
Verified by profiling the changes in an example app with no callbacks set and observing `runOnBreadcrumbTasks()`:

Optimize execution of callbacks

---

.buildkite/pipeline.full.yml
CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/MemoryTrimTest.java
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/BaseObservable.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ClientObservable.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ContextState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java
bugsnag-android-core/src/main/java/com/bugsnag/android/LaunchCrashTracker.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/MetadataState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
bugsnag-android-core/src/main/java/com/bugsnag/android/UserState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/UserStore.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/StateObserver.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientObservableTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataStateTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/UserStateTest.kt
bugsnag-plugin-android-ndk/detekt-baseline.xml
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NdkPlugin.kt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativeBridge.kt
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/BugsnagReactNativeBridgeTest.java

Optimizes the implementation of the internal system used for notifying observers of state changes.
This new solution avoids the performance disadvantages of the previous solution:
- The `StateEvent` message is lazily created which avoids object instantiation if no observers are registered
- `BaseObservable` avoids creating a `Vector` by replacing `update()` with `onStateChange()` (this also grants additional type safety)
- `BaseObservable` uses `CopyOnWriteArrayList` which avoids the need for synchronization when adding/removing observers. This was seen as acceptable as observers will be added/removed very rarely, whereas the collection will be iterated over many times
The remaining changes entail updating the rest of the code and the tests to use the new method signatures.
Updated …

Optimize implementation of internal state change observers

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataConcurrentModificationTest.kt
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/MetadataDeserializer.java

Bugsnag's stores metadata using a nested `ConcurrentHashMap`. The implementation uses unnecessary type casts, which resulted in unnecessary calls to `TypeIntrinsics.isMutableMap()` that added ~1ms for every ~10000 metadata values added.
Metadata was previously backed by `ConcurrentHashMap<String, Any>`. This has been changed to `MutableMap<String, MutableMap<String, Any>>`.
This more accurately reflects the metadata structure and has allowed for a net reduction in type casts throughout `Metadata.kt`. This has necessitated the addition of some type casts (mainly to maintain backwards compatibility with method signatures that should not change until the next major version).
Relied on existing unit test coverage.
The performance impact of this change ended up being fairly minimal - typically …

Optimize metadata implementation by reducing type casts

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Stacktrace.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/NullMetadataTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/StacktraceSerializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/StacktraceTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadSerializationTest.kt

The notifier trims stacktraces so that they contain a maximum of 200 frames. This means that very large stacktraces such as `StackOverflowError` do not exceed the API's payload limit.
This change ensures that the traces are trimmed _before_ constructing POJOs, which reduces unnecessary object instantiation in this scenario.
- Converted `stacktraceFromJavaTrace` companion object function into a constructor
- Ensured that both constructors in `Stacktrace` trim traces to a maximum of 200 frames
Added unit test for new constructor.

Trim stacktraces to <200 frames before attempting to construct POJOs

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ApiKeyConfigValidationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ApiKeyValidationTest.kt

The API key is currently validated using a regex, which was identified through profiling as taking ~3ms to compile and match. This alters the implementation so that it checks the string length and iterates through the characters instead. Additionally an expensive call to `String.format` has been replaced with concatenation.
Increased unit test coverage and profiled example app to confirm that API key validation does not add on a large amount of time.

Avoid using regex to validate api key

---

CHANGELOG.md
bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MazerunnerApp.kt
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/StartupANRBehaviour.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/ConfigureStartupAnrScenario.kt
features/full_tests/batch_1/startup_anr.feature

Enable AnrPlugin immediately if called on main thread so that Application Not Responding errors can be caught within the application startup.
In the `AnrPlugin` is started on the main-thread `Looper` it starts immediately. If the current thread is not the main, it dispatches the startup logic using `Handler.postAtFrontOfQueue` to ensure we miss as few startup events as possible.
Added new test scenario to the Mazerunner fixture, and modified the `MazerunnerApp.onCreate` to allow startup ANRs to be simulated.
The Mazerunner scenario creates a `SharedPreferences` option (picked up in `MazerunnerApp.onCreate`) and forces the application to terminate.

Enable AnrPlugin immediately if called on main thread

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NdkPlugin.kt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.h
features/smoke_tests/handled.feature
features/smoke_tests/unhandled.feature
features/steps/android_steps.rb

Ensure the `app.binaryArch` field is set for every event. The field would only be set for particular NDK events but is generally useful everywhere for debugging.
PLAT-6813
The NDK plugin sets the binary arch property of the app data collector upon successful initialization of the native components. This way it should be present for all events.
* Added a new JNI function, `NdkPlugin.getBinaryArch()`, which returns the arch or `unknown` as a String.
* Removed now-unused functions for computing the binary arch, instead loading it from event data
* Tested manually to verify the correct archs are sent, in addition to updating the smoke tests to expect the field

fix: add binaryarch to all events

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/LastRunInfoStoreTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/ImmutableConfig.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/AppMetadataSerializationTest.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestData.java

`AppDataCollector` and `Configuration` both get the `PackageInfo` and `ApplicationInfo` from the `PackageManager`. This takes ~3.5ms on a OnePlus Pro 7 so the result should be cached to speed up initialization.

Cache results from PackageManager

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BreadcrumbFilterTest.kt
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BreadcrumbStateTest.kt
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/OnBreadcrumbCallbackStateTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt
bugsnag-benchmarks/src/androidTest/java/com/bugsnag/android/benchmark/CriticalPathBenchmarkTest.kt

Breadcrumbs are stored in a `ConcurrentLinkedQueue` and then trimmed as they are added. This was identified as an area where performance could potentially be improved as over an application's lifecycle thousands of breadcrumbs might be added to Bugsnag.
`BreadcrumbState` has been altered to use a ring buffer instead of a `ConcurrentLinkedQueue`. Every time a breadcrumb is added an index is incremented by one, and the breadcrumb is stored in a backing array. If the number of breadcrumbs logged is greater than `config.maxBreadcrumbs` then the implementation wraps around to zero and overwrites the oldest breadcrumb added.
When an error is captured breadcrumbs must be added to an `Event` in the order in which they were captured. Previously this was a case of transforming a `Queue` into a …

Use ring buffer to store breadcrumbs

---

CHANGELOG.md
bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt

Initializing `Configuration` was taking more time than it needed to due to the construction of some unnecessary sets. The `toSet()` implementation in Kotlin seems like it can be particularly slow in some circumstances, as it constructs a `LinkedHashSet`. This is unnecessary for the purposes of `Configuration`.
- Avoided creation of unnecessary field for `redactedKeys`
- Initialized `plugins` with a `HashSet` rather than a `LinkedHashSet`
- Set `enabledBreadcrumbTypes` to `null` rather than constructing a set - this has the same behaviour as setting all the values
Without these optimizations `Configuration` took ~38ms to initialize, whereas with them it took ~9ms. It's worth noting that this only seems to be on a cold start, suggesting that there is some one-off work required when the JVM …

Avoid expensive set construction in Config constructor

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventFilenameInfo.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java
bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.java
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionStore.java
bugsnag-android-core/src/main/java/com/bugsnag/android/SeverityReason.java
bugsnag-android-core/src/main/java/com/bugsnag/android/SystemBroadcastReceiver.java
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/NativeStackDeserializer.java

Replaces calls to `String.format` with concatenation. This was specifically found to be a problem in `DeviceDataCollector` which added ~1ms onto `Bugsnag.start()`, and profiling shows that using concatenation takes ~0.1ms instead.
As `String.format` isn't required in most cases throughout the codebase, it has been replaced with concatenation instead.

Replace calls to String.format() with concatenation

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Stacktrace.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt

Adds some additional optimizations for capturing thread traces. Namely:
- Use `any()` rather than a for loop, which saves on iterator creation when the collection is empty and marginally improves performance
- Store the result of `getClassName()` to avoid multiple lookups
- Avoid calling `Thread.currentThread()` when `sendThreads` should not collect this information

Optimize capture of thread traces

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java

Fixes an instrumentation test that was failing on CI. This could occur because connectivity changes (which trigger automatic breadcrumbs) could happen at anytime, which alters the breadcrumbs reported by `Client`. It seems that this has been exacerbated by changes to how breadcrumbs are copied in #1286. As the test isn't asserting anything specific about automatic breadcrumbs, this disables them.

Fix flaky instrumentation test

---

features/full_tests/batch_1/startup_anr.feature

Explain why we skip the startup ANR Mazerunner test on Android 10 devices

Explain why the startup_anr.feature is skipped on Android 10

---

docs/RELEASING.md

With keys.gnupg.net no longer being a valid upload target, this PR changes the `RELEASING` documentation to point to `keyserver.ubuntu.com` and also includes a link to the full Sonatype GPG documentation

Replaced the suggested GPG key-server in RELEASING.md

---

CHANGELOG.md
bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/ConnectivityCompat.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ConnectivityLegacyTest.kt

Handle cases where `ConnectivityManager.getActiveNetworkInfo` throws a NullPointerException instead of returning `null` (as expected).
Treat the `NullPointerException`s as `null` values, and leave all other exceptions to propagate as normal to avoid breaking existing error-handling logic.
Tested using mocking in unit tests as this has only been seen in very limited real-world situations.

Handle NullPointerExceptions from getActiveNetworkInfo

---

bugsnag-android-core/src/main/java/com/bugsnag/android/internal/DocumentPath.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/DocumentPathDirective.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/DocumentPathTest.kt
bugsnag-benchmarks/src/androidTest/java/com/bugsnag/android/benchmark/DocumentPathBenchmarkTest.kt

DocumentPath parses a document path string into directives, which can then be used to modify a document at the desired depth and type.
This is a low-level, self-contained piece of the journal system (PLAT-6711). Overall structure:
| …

Journal: DocumentPath

---

bugsnag-android-core/build.gradle
bugsnag-android-core/lint-baseline.xml
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/JournalCommandTest.kt
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/JournalTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/IOUtils.java
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/Journal.kt
bugsnag-benchmarks/src/androidTest/java/com/bugsnag/android/benchmark/JournalBenchmarkTest.kt

`Journal` section of the journaling system (PLAT-6711).
The journal stores entries composed of a document path and a value to apply at that path. This layer also handles serialization of the journal.
```
| …
```

Add the journal type.

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/JournalTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/Journal.kt
bugsnag-benchmarks/src/androidTest/java/com/bugsnag/android/benchmark/JournalBenchmarkTest.kt

Part of PLAT-6711. This PR adds the metadata field to the journal, to support backwards compatibility when changes occur.
This PR only affects the Journal portion.
```
```
Added more unit …

6711 journal metadata

---

bugsnag-android-core/src/test/java/com/bugsnag/android/JournalCommandTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/JournalTest.kt

The journal unit tests were lost in the shuffle. This PR just re-adds them.

Re-add lost journal tests

---

bugsnag-android-core/src/main/java/com/bugsnag/android/internal/MemoryMappedOutputStream.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/MemoryMappedOutputStreamTest.kt

Part of PLAT-6961
This adds an OutputStream that writes to a memory mapped file. Memory mapped files are guaranteed to be consistent with the last memory write, even if the app crashes (because the memory mapping is maintained by the OS, not the app).
This allows us to always serialize the latest document changes, regardless of app conditions, and recover all journal entries on app relaunch.
Added unit tests for the memory mapped stream.

Memory mapped stream

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/BackgroundTaskService.kt

Handles an `InterruptedException` which can be thrown when shutting down bugsnag's executors.

Handle interrupt when shutting down executors

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/JournaledDocument.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/JsonHelper.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/JournaledDocumentTest.kt

JournaledDocument uses Journal and MemoryMappedOutputStream to build a journal-backed document.
Document changes are made via journal commands, which are serialized to the memory-mapped file that MemoryMappedOutputStream writes to. Thus, the document is recoverable no matter when the app crashes.
The document contents can be fetched the same as any `Map<String, Any>`.
Added unit tests for JournaledDocument

Add JournaledDocument

---

CHANGELOG.md
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ConfigSerializer.java

Serializes `enabledBreadcrumbTypes` as `null` when it is null in config, rather than as an empty list. The specification states that null is equivalent to having specified automatic capture of all breadcrumb types.
Verified using the RN test fixtures that an automatic breadcrumb is sent through when the `enabledBreadcrumbTypes` is null:

React Native: allow serializing enabledBreadcrumbTypes as null

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/AppDataCollectorTest.kt
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/BugsnagConfig.kt
features/full_tests/batch_1/multi_process.feature

Captures the process name in the `Event` payload. This helps distinguish which process an error came from in multi-process apps. For API 28+ this uses `Application.processName()`, whereas for lower API levels reflection is used to access the same API using `ActivityThread`.
Updated mazerunner tests to assert the process name is captured, and manually tested on API 16, 19, and 29 to confirm that each solution populates a valid value.

Capture process name in Event payload

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c

Use `calloc()` rather than `malloc()` in NDK code wherever this is possible. `calloc()` ensures that the bytes will always be set to zero before they are read, which ensures there is no possibility of junk data being included in the `bsg_event` struct and leading to undefined behaviour.

Prefer calloc() to malloc() in NDK code

---

bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/NativeBufferedWriterTest.java
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/NativeCrashtimeJournalTest.java
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/NativeNumberToStringTest.java
bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/jni/ctjournal.c
bugsnag-plugin-android-ndk/src/main/jni/ctjournal.h
bugsnag-plugin-android-ndk/src/main/jni/utils/buffered_writer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/buffered_writer.h
bugsnag-plugin-android-ndk/src/main/jni/utils/number_to_string.c
bugsnag-plugin-android-ndk/src/main/jni/utils/number_to_string.h
bugsnag-plugin-android-ndk/src/test/CMakeLists.txt
bugsnag-plugin-android-ndk/src/test/cpp/main.c
bugsnag-plugin-android-ndk/src/test/cpp/test_ctjournal.c
bugsnag-plugin-android-ndk/src/test/cpp/test_helpers.c
bugsnag-plugin-android-ndk/src/test/cpp/test_helpers.h
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_buffered_writer.c
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_number_to_string.c

This PR implements the crash-time journal writing API for the journaling system
Everything in this part must be async-safe, so we can't use JSON libraries to implement it. Fortunately, …

Crash-time journal support

---

examples/sdk-app-example/build.gradle

Fixes the example app build on CI by reverting to an older version of AGP.

Move example app AGP version to 3.6.4

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagMainJournal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/ConcurrentContainers.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/DocumentPath.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/DocumentPathDirective.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/Journal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/JournaledDocument.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/JsonHelper.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagMainJournalTest.kt

This is the top-level API to the journal system:
The journal at this layer is considered to be a read-only map that can only be modified via journal commands. There is an automatic …

Add main journal API

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeDiscScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeFileUriExposeScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeNetworkScenario.kt
features/full_tests/batch_2/strict_mode.feature

Adds a new E2E test that triggers a StrictMode VmPolicy violation, specifically leaking a file URI. This currently only runs on Android <9, which [kills the app with a SIGKILL](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/os/StrictMode.java;l=2308?q=strictmode).
A later changeset will alter these tests to use `penaltyListener()` to call `Bugsnag.notify()` - for now the test simply asserts that no requests are sent.

Add E2E test for strictmode VM policy violation detection

---

bugsnag-android-core/src/main/java/com/bugsnag/android/internal/DocumentPath.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/DocumentPathDirective.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagTestUtils.java
bugsnag-android-core/src/test/java/com/bugsnag/android/DocumentPathTest.kt

Sometimes numeric document values need to be changed relative to their current value (incremented, decremented, added to, subtracted from) - for example counters. These operations must be supported as atomic operations, without requiring access to the original value.
Add support for an "addition" operator: If `+` is appended to the last path component, treat that last component (with the ending `+` character removed) as an instruction that the (assumed numeric) value is to be added to the (assumed numeric) value currently in the document. If there is no value at that place in the document, the document's "existing" value is assumed to be 0.
Note: The `+` character can be escaped, in which case it doesn't represent an addition operator.
Examples:
```
Original document:  {"foo": {"bar": 5}} …
```

DocumentPath add/subtract support

---

CHANGELOG.md
bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/androidTest/java/android/os/strictmode/FakeStrictModeViolation.kt
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/StrictModeViolationTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagThreadViolationListener.java
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagVmViolationListener.java
bugsnag-android-core/src/main/java/com/bugsnag/android/Event.java
bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/StrictModeOnErrorCallback.kt
bugsnag-android-core/src/test/java/android/os/strictmode/FakeStrictModeViolation.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/StrictModeChainedListenerTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/StrictModeFacadeTest.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeDiscScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeFileUriExposeScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeNetworkScenario.kt
features/full_tests/batch_2/strict_mode_legacy.feature
features/full_tests/batch_2/strict_mode_violations.feature
features/smoke_tests/handled.feature

Adds `BugsnagThreadViolationListener` and `BugsnagVmViolationListener` to the public API. These classes implement StrictMode listeners and will call `Bugsnag.notify` if set as part of a [StrictMode policy](https://developer.android.com/reference/android/os/StrictMode).
By default, errors will be captured with a INFO severity level, a 'strictMode' severity reason, and an error message denoting whether it was a thread/vm policy violation. The classes supports chaining of listeners if a user desires this.
Note: this enforces that `Bugsnag.start()` must always be instantiated before setting the StrictMode listener. This was seen as preferable since otherwise a StrictMode violation might occur before bugsnag is initialized, and lead to `Bugsnag.getClient()` throwing an exception.
- Added …

Add Bugsnag listeners for StrictMode violation detection

---

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagThreadViolationListener.java
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagVmViolationListener.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeDiscScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeFileUriExposeScenario.kt

Adds a zero-parameter constructor for the StrictMode listeners. This avoids users having to call `Bugsnag.getClient()` unnecessarily.
The other constructors have been left as-is to allow for multiple `Client` instantiation and setting chained listeners.

Support zero-param constructor for StrictMode detection

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
scripts/run-instrumentation-test.sh

Increase timeout for the instrumentations tests as they have been very variable recently (I've also raised a support ticket with BrowserStack).
Increased timeout and remove duplication of step from the pipeline files.
Covered by CI.

Increase instrumentation test timeout

---

.buildkite/pipeline.full.yml
examples/sdk-app-example/app/build.gradle
examples/sdk-app-example/build.gradle
examples/sdk-app-example/gradle/wrapper/gradle-wrapper.properties
gradle/wrapper/gradle-wrapper.properties

Bumps Gradle/AGP in the example app to the latest available versions without updating all the way to AGP 7.
The example app requires a clean assemble to workaround an apparent bug in AGP/Gradle which would throw a `ZipException` as some build cache exists.

Bump gradle/AGP dependencies

---

bugsnag-plugin-android-ndk/src/androidTest/resources/exception_serialization.json
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.h
bugsnag-plugin-android-ndk/src/test/cpp/main.c
features/smoke_tests/unhandled.feature
features/steps/android_steps.rb

Fix a case where C/C++ events could be resolved to be 2-3 lines off from the actual source location, due to memory address offsets being applied twice. This change relies on the offset adjustment being performed server-side, using the program counter value to determine how much adjustment to apply.
PLAT-6861
Add a program counter indicator to native frames as needed
- manual testing of events to determine the correct resolution of file/line info
- added new step to verify program counter flag is set

fix: remove double-applied address offsets

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/AppDataCollectorTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ClientComponentCallbacks.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/DataCollectionModule.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/AppDataCollectorForegroundTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/AppDataCollectorSerializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/AppMetadataSerializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientComponentCallbacksMemoryCallbackTest.kt

The `app.lowMemory` attribute should be reported in the same way for all errors.
Cache the most recent value sent to `ComponentCallbacks.onLowMemory` and `ComponentCallbacks2.onTrimMemory` in the `AppDataCollector` and report that value instead of looking-up the value at crash-time.
When we receive a trim memory event that indicates any state less than [COMPLETE](https://developer.android.com/reference/android/content/ComponentCallbacks2#TRIM_MEMORY_COMPLETE) we set the cached lowMemory state to `false`.
Manual testing for both native and JVM crashes, and a new unit test to cover the mapping between memory-trim values and the `lowMemory` flag.

fix(lowMemory): align the app.lowMemory field for JVM and NDK

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/MemoryTrimState.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/MemoryTrimStateTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/UpdateMemoryTrimLevelTest.kt

Leave Breadcrumbs for `onTrimMemory` events, with the `memoryTrimLevel` as metadata.
Manual testing, and new unit tests for the `MemoryTrimState`.

Add `Breadcrumbs` for `onTrimMemory` events

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/AppMetadataSerializationTest.kt
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
features/full_tests/batch_2/native_crash_handling.feature
features/smoke_tests/handled.feature
features/smoke_tests/unhandled.feature

General improvements to the automatically reported memory metaData for both the `app` and `device` sections to make them more consistent with user expectations (for example: `device.totalMemory` should reflect the amount of physical memory installed on the device).
* app now reports ART / Java specific attributes (from `Runtime`): `memoryUsage`, `totalMemory`, `freeMemory`, and `memoryLimit`
* device reports `totalMemory` and `freeMemory` for the entire device
* `totalMemory` is considered a static value and is calculated on startup
* `totalMemory` and `memoryLimit` is reported for NDK errors
Added the new attributes to existing tests, and manually tested the changes along with the new dashboard changes to correctly format the new attributes.

Align device and app memory metaData

---

CHANGELOG.md
bugsnag-plugin-android-okhttp/README.md
bugsnag-plugin-android-okhttp/build.gradle
bugsnag-plugin-android-okhttp/gradle.properties
bugsnag-plugin-android-okhttp/proguard-rules.pro
bugsnag-plugin-android-okhttp/src/main/AndroidManifest.xml
bugsnag-plugin-android-okhttp/src/main/java/com/bugsnag/android/okhttp/BugsnagOkHttpPlugin.kt
docs/NEW_MODULE_CHECKLIST.md
docs/PROJECT_STRUCTURE.md
settings.gradle

Adds a new module named `bugsnag-plugin-android-okhttp` which will capture breadcrumbs for requests made by OkHttp. This does not add any functionality as of yet and just adds boilerplate/internal documentation.

Setup bugsnag-plugin-android-okhttp module

---

bugsnag-plugin-android-okhttp/build.gradle
bugsnag-plugin-android-okhttp/lint-baseline.xml
bugsnag-plugin-android-okhttp/src/main/java/com/bugsnag/android/okhttp/BugsnagOkHttpPlugin.kt
bugsnag-plugin-android-okhttp/src/test/java/com/bugsnag/android/okhttp/BasicNetworkBreadcrumbTest.kt
bugsnag-plugin-android-okhttp/src/test/java/com/bugsnag/android/okhttp/NetworkBreadcrumbRequest.kt

Creates a unit test that uses [MockWebServer](https://github.com/square/okhttp/tree/master/mockwebserver) to simulate network requests. This will be used to test the implementation of network breadcrumbs by confirming that `leaveBreadcrumb` is called on the `Client`.

Setup OkHttp MockWebServer unit tests

---

bugsnag-plugin-android-okhttp/src/test/java/com/bugsnag/android/GetRequestIntegrationTest.kt
bugsnag-plugin-android-okhttp/src/test/java/com/bugsnag/android/PostRequestIntegrationTest.kt

Adds some integration tests to cover common scenarios for GET requests, and POST/PUT/PATCH/DELETE requests.

Add simple integration tests for network breadcrumbs

---

bugsnag-plugin-android-okhttp/src/test/java/com/bugsnag/android/CachedRequestIntegrationTest.kt
bugsnag-plugin-android-okhttp/src/test/java/com/bugsnag/android/ComplexRequestIntegrationTest.kt
bugsnag-plugin-android-okhttp/src/test/java/com/bugsnag/android/RedirectedRequestIntegrationTest.kt

Adds some additional integration tests for network breadcrumbs, which cover the following scenarios:
- A request served from a local cache
- Requests that timeout
- A request that is cancelled
- Requests whose body is not closed, which is recommended against in the OkHttp documentation as it leaks resources and prevents the request from finishing
- A redirected request

Add additional integration tests for network breadcrumbs

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java
bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/test/cpp/test_breadcrumbs.c
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c

Increases the default number of breadcrumbs collected to 50. This is required now that network breadcrumbs are anticipated to capture several more requests in a typical application, which would lead to increased breadcrumb churn at 25 items.
- Increased JVM and NDK limits to 50
- Added a migration to copy breadcrumbs correctly from the old `bugsnag_event` struct to the new one
- Altered setting of NDK user information, which was broken by increasing the breadcrumb array size in the struct
Updated existing test assertions. Added extra test cases for the NDK struct migration, which cover the first index in the ring buffer starting at 0 and non-zero values.

Increased default breadcrumb collection limit to 50

---

bugsnag-plugin-android-okhttp/src/test/java/com/bugsnag/android/ComplexRequestIntegrationTest.kt

Fixes a flake in an OkHttp integration test by increasing the timeout. This resolves the intermittent failure seen here:
https://buildkite.com/bugsnag/bugsnag-android/builds/5297#77625949-ac41-4ba7-a3c3-43b941c456a6

Avoid timeout in OkHttp integration test

---

bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/ThreadSerializationTest.kt
bugsnag-plugin-android-ndk/src/androidTest/resources/thread_serialization.json
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.h
bugsnag-plugin-android-ndk/src/test/cpp/main.c
bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c
bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.h

Create and integrate a new structure to carry the NDK thread state information that we will report, not including the required data migration (which is in a separate task). A fixed-size array of `bsg_thread`s are included in `bugsnag_event` and are serialized into our standard JSON payload.
A new unit test was added to test that the new model serializes to JSON correctly.

Introduce the `bsg_thread` structure in the NDK plugin

---

gradle/release.gradle

The NDK version and abiFilters used are now pinned via the Gradle DSL, whereas in the past they were subject to whatever NDK revision was installed. This check needs to be removed to allow publishing as it currently fails. I've confirmed that the 4 supported ABIs are included in the generated AAR.

Remove obsolete abiFilters check in publish script

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/ImmutableConfig.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt

Supports integer values in the buildUuid field rather than assuming the Bundle value will always be a string.
Added unit tests and confirmed in the dashboard that an event with an int buildUuid symbolicates.

Support integer values in buildUuid

---

bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/ThreadSerializationTest.kt
bugsnag-plugin-android-ndk/src/androidTest/resources/thread_serialization.json
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.h
bugsnag-plugin-android-ndk/src/test/cpp/main.c
bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c
bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.h
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c

Ensure that events stored by previous versions of the NDK plugin can be migrated to the new version, which includes space allocated for the `bsg_thread` structures.
As the new fields are at the end of the `bugsnag_event` structure - this migration is a simple copy operation (using `memcpy`) to allow for the expanded space where the threads will be stored. As we are using `calloc` no further action is required to zero the `thread_count`.
Manually tested in the example app, and added migration unit tests.

migrate ndk reports for the new threads property

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/AppDataCollectorForegroundTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java

Uses `SystemClock.elapsedRealtime()` rather than `System.currentTimeMillis()` to track the `duration` and `durationInForeground` values. [SystemClock](https://developer.android.com/reference/android/os/SystemClock) is recommended for timing intervals as it is not affected by CPU power saving mode or the user altering the device time.
`System.currentTimeMillis()` is still used in the codebase elsewhere where accuracy is not as key - for example, adding a timestamp to the filename of persisted errors.
Updated existing test coverage and manually tested to confirm that the values are correct.

Use SystemClock.elapsedRealtime to track `app.durationInForeground`

---

bugsnag-plugin-android-okhttp/src/test/java/com/bugsnag/android/ComplexRequestIntegrationTest.kt

Removes a flaky test case that ensures a manually cancelled request leaves a network breadcrumb. This is effectively covered by the `socketTimeout` test case anyway because the call is cancelled by the OkHttpClient after a certain duration.

Remove flaky test case

---

bugsnag-plugin-android-ndk/src/test/cpp/main.c
bugsnag-plugin-android-ndk/src/test/cpp/test_ctjournal.c
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c

Resolves warnings in the NDK test code that have been introduced in the integration branch. Notably, the use of an old-style GNU field designator extension has been removed. The duplicate use of the `static` modifier and missing return types have also been addressed.

Resolve warnings about field designator extension

---

bugsnag-android-core/src/main/java/com/bugsnag/android/App.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/AppWithState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Device.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceWithState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/JournaledStateObserver.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/NativeStackframe.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Stackframe.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/User.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/DocumentPath.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/DocumentPathDirective.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/Journal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/JournalKeys.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/Journalable.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/JournaledDocument.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/JsonHelper.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagJournalTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/DocumentPathTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/JournalCommandTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/JournalTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/JournaledDocumentStressTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/JournaledDocumentTest.kt
bugsnag-benchmarks/src/androidTest/java/com/bugsnag/android/benchmark/DocumentPathBenchmarkTest.kt
bugsnag-benchmarks/src/androidTest/java/com/bugsnag/android/benchmark/JournalBenchmarkTest.kt

Moved the journalling code into a separate package named `com.bugsnag.android.internal.journal` where possible, as there are now a reasonable amount of classes. This also alters types to be `internal` where they do not need to be publicly visible.

Make journal code internal and in separate package

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/BaseObservable.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagStateModule.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ContextState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/JournaledStateObserver.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/MemoryTrimState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/MetadataState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/NotifierState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
bugsnag-android-core/src/main/java/com/bugsnag/android/StateEvent.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/UserState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/BugsnagJournalEventMapper.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/JournalKeys.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/JournaledStateObserverTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerPauseResumeTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/internal/journal/BugsnagJournalEventMapperTest.kt
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt

Adds a `StateEvent` that is triggered when the `Notifier` information is changed (RN/Unity). This also serializes the `Notifier` object to the journal.
- Created `Client#setNotifier()` and removed `Client#getNotifier()`
- Added a `NotifierState` class which emits a `StateEvent` when the value changes
- Updated `BaseObservable` to have `emitObservableEvent` as an overridable function
- Created `BugsnagJournalEventMapper`, which loads the journal as a map and in future will generate an event
Added unit test coverage and manually verified that the bugsnag journal is logged out in an example app.

Add StateEvent for when notifier info is updated

---

CHANGELOG.md
bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadSerializationTest.kt
bugsnag-android-core/src/test/resources/event_serialization_5.json
bugsnag-android-core/src/test/resources/thread_serialization_0.json
bugsnag-android-core/src/test/resources/thread_serialization_1.json
bugsnag-android-core/src/test/resources/thread_serialization_2.json
bugsnag-android-core/src/test/resources/thread_serialization_3.json
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadDeserializer.java
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadSerializer.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/EventDeserializerTest.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ThreadDeserializerTest.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ThreadSerializerTest.java

Capture and report the [Thread.state](https://developer.android.com/reference/java/lang/Thread.State) of all captured threads to help in diagnosing issues.
This PR is a clone of https://github.com/bugsnag/bugsnag-android/pull/1367
To separate our implementation from any future platform changes or errors, a new Bugsnag `Thread.State` enum was introduced, reflecting the possible thread-states currently available on Android. The new enum also includes an `UNKNOWN` state which is used in cases where we either cannot capture or map the platform state.
Manual testing with the Example app and a debug server. Updated existing unit tests and end-to-end tests to include checks for the new Thread.State field.

Capture and report `Thread.state` for Android Runtime threads

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java

Allow plugins to set the `Notifier` details before the `Client` starts using them.
Add a new package-protected `Notifier` field to `Configuration`. This can be accessed by plugins (such as Unity) to set the details during `Client` initialisation.

Allow Client to be initialised with a Notifier

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionTrackerConfinementTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/User.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/BugsnagJournalEventMapper.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/EventApiTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/internal/journal/BugsnagJournalEventMapperTest.kt
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/UserDeserializer.java

Deserializes the `user` value from the Bugsnag journal entry. This has been achieved by altering the `User` class to [delegate its properties to a map](https://kotlinlang.org/docs/delegated-properties.html#storing-properties-in-a-map), and adding another constructor to `EventInternal` that provides default values.
- Added secondary constructor to `EventInternal` that sets default values
- Converted `User` to have its properties backed by a map. This will be rolled out to other classes on the `Event` interface where appropriate in future changesets
- Updated react native deserialization to use new constructor
- Loaded user from the bugsnag journal
Added unit test coverage.

Deserialize user from bugsnag journal

---

bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/BugsnagJournalEventMapper.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/internal/journal/BugsnagJournalEventMapperTest.kt

Deserializes metadata from any entries in the bugsnag journal and converts it into an `Event`.
Added a unit test case.

Deserialize metadata from bugsnag journal entries

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Breadcrumb.java
bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournalEventMapper.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/test/java/com/bugsnag/android/internal/journal/BugsnagJournalEventMapperTest.kt

Deserializes breadcrumbs from any entries in the bugsnag journal and adds them onto an `Event`. This converts `BreadcrumbInternal` to use a `Map` as a property delegate.
Added unit tests to cover the functionality.

Deserialize breadcrumbs from bugsnag journal entries

---

.buildkite/pipeline.yml

Alters the devices which we will use for BrowserStack instrumentation tests, swapping Android 7 for Android 8, which isn't failing.

Alter browserstack instrumentation device target

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Device.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/NativeStackframe.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Stackframe.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.java
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/AppSerializer.kt
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/DeviceSerializer.kt
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadSerializer.kt

Updates the JSON serializers in the React Native module to use the journal code instead, which reduces duplication. This also  fixes a couple of issues in the journal implementation that were caught by the RN unit tests:
- null values are no longer added to the map for `Stackframe`
- the cpuAbi is serialized as a list rather than an array
- the key for buildUuid now matches the one used in the RN json
Relied on existing unit test coverage

Alter react-native JSON serializers to use journal code

---

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournalEventMapper.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/JournaledStateObserver.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/JournalKeys.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagJournalEventMapperTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/JournaledStateObserverTest.kt

Deserializes projectPackages into an `Event` from entries stored in the journal.
Added unit tests.

Deserialize projectPackages from bugsnag journal

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java
bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagTestUtils.java
bugsnag-benchmarks/src/androidTest/java/com/bugsnag/android/EventHooks.java
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/StartBugsnagTest.kt
bugsnag-plugin-android-ndk/src/main/jni/metadata.c

Avoid crashing on startup with:
```
JNI DETECTED ERROR IN APPLICATION: can't call int java.lang.Integer.intValue() on instance of java.lang.String
2021-10-28 13:28:24.720 7696-7696/com.example.bugsnag.android A/bugsnag.androi: java_vm_ext.cc:545]     in call to CallIntMethod
2021-10-28 13:28:24.720 7696-7696/com.example.bugsnag.android A/bugsnag.androi: java_vm_ext.cc:545]     from void com.bugsnag.android.ndk.NativeBridge.install(java.lang.String, java.lang.String, java.lang.String, int, boolean, int, boolean, int)
```
Parse the string `runtimeVersions.androidApiLevel` as an integer using `strtol`, avoiding changing the internal model and requiring an event migration. `strtol` will return `0` if the string cannot be parsed.
Manual testing, as end-to-end tests and unit tests did not pick …

Fix startup NDK crash

---

Gemfile.lock
bugsnag-android-core/src/main/java/com/bugsnag/android/ClientInternal.kt
features/full_tests/batch_2/native_legacy_struct.feature
features/full_tests/batch_2/native_on_error.feature
features/smoke_tests/unhandled.feature

The following fields are populated in unhandled NDK events when previously they weren't:
```
app.networkAccess
app.totalMemory
device.batteryLevel
device.charging
```
As these fields don't make sense in the context of an unhandled NDK error because they are not updated throughout the application's lifecycle, they should be omitted for now.

Remove unnecessary fields from NDK events

---

Gemfile.lock
bugsnag-android-core/src/main/java/com/bugsnag/android/ClientInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ObjectJsonStreamer.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/DslJsonNormalization.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/FallbackWriter.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/JsonHelper.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagJournalEventMapperTest.kt
features/fixtures/mazerunner/cxx-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/cxx-scenarios/src/main/cpp/cxx-scenarios.cpp
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXComplexMetadataScenario.kt
features/full_tests/batch_2/native_complex_metadata.feature
features/full_tests/batch_2/native_legacy_struct.feature
features/full_tests/batch_2/native_on_error.feature
features/smoke_tests/unhandled.feature
features/steps/android_steps.rb

Adds an E2E test which verifies that complex metadata values are serialized correctly. This has required some alterations/bug fixes to the JSON serializer.
Added an E2E test which has various metadata values. Notably the following have been included:
- A large string, to verify that there are no limits in the payload metadata
- A Date, as this was not being serialized correctly by dsl-json
- An unknown type, which has required updates to serialize a placeholder value rather than dsl-json throwing an exception
- Null values, which the `BugsnagJournalEventMapper` could not handle within a Metadata `Map` value
- A nested map
Unit test coverage has also been increased to cover this change.

Add complex metadata test

---

.gitmodules
bugsnag-android-core/build.gradle
bugsnag-android-core/lint-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/FallbackWriter.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/JsonHelper.kt

Updates bugsnag-android to use a forked version of dsl-json. 
The primary concern against using the dsl-json supplied artefacts is that `DslJson` currently uses `java.awt.*` imports. This results in an Android lint warning that could break the build of end-users of bugsnag-android, necessitating this fork.
Forking the library will also allow us to customize the implementation as needed, and also remove code which isn't used by our project.
- Added dsl-json as a git submodule
- Added dsl-json submodule to the `bugsnag-android-core` sourcesets
- Updated existing code to use forked dsl-json package name
- Suppressed existing lint warnings in dsl-json with a baseline file

Use a fork of dsl-json

---

bugsnag-android-core/src/test/java/com/bugsnag/android/internal/journal/JsonHelperTest.kt
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXComplexMetadataScenario.kt
features/steps/android_steps.rb

Avoids a class cast exception being thrown in a rare edge case by dsl JSON. If dsl-json is provided a list containing a primitive array and some other unrelated type, then it throws an exception.
This changeset updates bugsnag-android to use the fix in [this PR](https://github.com/bugsnag/dsl-json/pull/2). Additionally, it adds some unit test coverage to ensure that an exception is not thrown when serializing JSON with some unusual types.

Avoid ClassCastException in JSON serialization

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
Makefile
docker-compose.yml
dockerfiles/Dockerfile.android-builder
features/smoke_tests/handled.feature
features/smoke_tests/sessions.feature
features/smoke_tests/unhandled.feature

Introduce a debug variant of the Mazerunner test fixture, and run some of the test features against it to.
Modified the `android-builder` job to allow the Gradle task to be specified externally (`assembleRelease` / `assembleDebug`) and to copy *all* generated APK artifacts out, allowing access `debug/fixture.apk`or `release/fixture.apk`.
A full CI test run was used as part of this PR.

Add a new debug-build test fixture and build step

---

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournal.kt

Increases the buffer size used by the journal. This should increase performance when adding large amounts of information in a very short amount of time, by reducing the number of times the buffer needs to flush. This was tested by adding complex breadcrumbs 1000 times, which improved performance by ~10% in manual profiling.

Increase journal buffer size

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c

Increases the resilience of the code used to instantiate a `StackTraceElement` object when calling `bugsnag_notify_env`. There were a couple of potential issues with the existing implementation:
- The return values of `filename` and `method` weren't checked for `NULL`, which could lead to exceptions being thrown in `bsg_safe_new_object`
- The return value of `calloc` was not checked for `NULL`, which could lead to a malformed string if `bsg_safe_new_string_utf` failed, resulting in a [SIGABRT](https://cs.android.com/android/platform/superproject/+/master:art/runtime/jni/check_jni.cc;l=1013?q=CheckNonHeapValue)

Increase resilience of NDK stackframe method capture

---

.buildkite/pipeline.full.yml
.buildkite/pipeline_trigger.sh
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagJournalFailedCreationTest.kt
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/NativeCrashTimeJournalTest.kt
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/NativeStructMigrationTest.kt
features/full_tests/internal_error_reports.feature
features/full_tests/native_event_tracking.feature
features/full_tests/native_legacy_struct.feature
features/full_tests/native_on_error.feature
features/full_tests/onsend_callback.feature
features/smoke_tests/handled.feature
features/smoke_tests/unhandled.feature
features/steps/android_steps.rb

Comment out checks on failing fields pending further investigation, as well as some other CI fixes and improvements.
I've also corrected the inclusion of scenarios for a couple of build steps and made a change to `pipeline_trigger.sh` so that future PRs into integration branches behave like PRs into `next` (which, in particular, means a complete set of e2e tests will get run).
TODO: An instrumentation test failure still needs to be resolved/removed.

Temporarily skip failing e2e test steps

---

bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournalEventMapper.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/JournaledStateObserver.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/StateEvent.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagJournalEventMapperTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/JournaledStateObserverTest.kt
bugsnag-android-core/src/test/resources/event_deserialization_0.json
bugsnag-android-core/src/test/resources/event_deserialization_1.json
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt

Delays the date formatting for breadcrumbs to the point where the event JSON payload is generated, rather than at the point of breadcrumb collection. The journal now stores the breadcrumb timestamp as a `Long`.
Other timestamps are still stored as strings - these can be altered at a future date as they don't impact performance as much as breadcrumb timestamps.
When adding 100 breadcrumbs, the previous implementation spent ~100ms on `toIso8601()` when profiled with a full Java method trace:
Avoiding date formatting has improved performance by ~13%:

Avoid formatting date to improve addBreadcrumb performance

---

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ClientInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceWithState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Stackframe.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/User.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/DocumentPathDirective.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/JournaledDocument.kt
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativeBridge.kt

The journal requires mutable containers and auto-converts anything non-conformant. Make sure anything we pass in is already mutable.
Re-ran all automated tests.

[PLAT-7581] Use mutable maps for anything that can be put in the journal

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/DocumentPath.kt

Allocate a 10-entry array list for document path directives to avoid the overhead of adding to a linked list.

[Plat-7528] improve performance 3

---

bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/Journal.kt

Optimizes the `serialize()` command to avoid the unnecessary instantiation of a `Pair`, and switches to using the cheaper `HashMap` object.
The rest of the method is dominated by dsl-json which doesn't have any low-hanging fruit for optimization.
Verified against a baseline and confirmed that the time taken to instantiate and populate maps reduced from ~55ms to ~25ms.

Optimize Command.serialize()

---

bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/DocumentPath.kt

Creating a `Journal.Command` object initializes a list of `DocumentPathDirective`. This was relatively expensive to calculate and memoization reduces the amount of time required by an order of magnitude. 
Verified that the amount of time dedicated to creating path directives when setting the context drops by an order of magnitude, from ~200ms to ~22ms:

Memoize document path directives

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournalEventMapper.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java
features/full_tests/onsend_callback.feature

Fixes some bugs in how JVM exceptions were deserialized from disk when running an `OnSend` callback. This is down to `BugsnagJournalEventMapper` converting both an `Event` JSON and journal entries into an `Event`.
- Removed unnecessarily verbose logging around the `BugsnagJournal` which may have confused end-users
- Only loaded the duration from the 'runtime' journal entry if it is present, rather than throwing an exception
- Handling a long/string timestamp for breadcrumbs
This has been tested by uncommenting the E2E scenario and existing unit tests.

Allow onSend callbacks to run

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/Event.java
bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/FeatureFlagState.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/EventApiTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventFeatureFlagsCloneTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventMetadataCloneTest.kt
bugsnag-android-core/src/test/resources/event_redaction.json
bugsnag-android-core/src/test/resources/event_serialization_0.json
bugsnag-android-core/src/test/resources/event_serialization_1.json
bugsnag-android-core/src/test/resources/event_serialization_2.json
bugsnag-android-core/src/test/resources/event_serialization_3.json
bugsnag-android-core/src/test/resources/event_serialization_4.json
bugsnag-android-core/src/test/resources/event_serialization_5.json
bugsnag-android-core/src/test/resources/event_serialization_6.json
bugsnag-plugin-android-anr/src/test/java/com/bugsnag/android/AnrDetailsCollectorTest.kt
bugsnag-plugin-android-anr/src/test/java/com/bugsnag/android/BugsnagTestUtils.java
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/EventDeserializerTest.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestHooks.java

Expose `FeatureFlags` on the `Event` object so that they can be altered by crash-time callbacks before being uploaded. The `FeatureFlags` are copied from the client state when the `Event` is created, and can then be altered on a per-event basis before being sent.
A new unit test covers the `FeatureFlags` deep-copy behaviour and per-event changes in the same way as we test per-event `Metadata`

feat(feature flags): added FeatureFlags to `Event`

---

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournal.kt

`unspecialMapPath` is a guard against special characters in a path component, but this is the exception, not the norm. Optimize for the happy path.

[Plat-7528] improve journal performance

---

bugsnag-android-core/src/test/java/com/bugsnag/android/JournaledDocumentTest.kt
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/NativeCrashTimeJournalTest.kt
bugsnag-plugin-android-ndk/src/androidTest/resources/native_crashtime_journal_test.json
bugsnag-plugin-android-ndk/src/main/jni/crashtime_journal.c
bugsnag-plugin-android-ndk/src/main/jni/crashtime_journal.h
bugsnag-plugin-android-ndk/src/main/jni/utils/path_builder.c
bugsnag-plugin-android-ndk/src/main/jni/utils/path_builder.h
bugsnag-plugin-android-ndk/src/test/cpp/test_ctj.c
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_path_builder.c

The crashtime journal needs to support increment operations for an upcoming PR.
Added new unit and integration tests.

Fix journal increment in the crashtime journal

---

bugsnag-android-core/src/test/java/com/bugsnag/android/JsonUtils.kt
bugsnag-android-core/src/test/resources/app_data_serialization_0.json
bugsnag-android-core/src/test/resources/app_data_serialization_1.json
bugsnag-android-core/src/test/resources/breadcrumb_serialization_0.json
bugsnag-android-core/src/test/resources/breadcrumb_state_serialization_0.json
bugsnag-android-core/src/test/resources/event_serialization_6.json

Only remove unquoted whitespace in JSON strings before comparing them. This retains the correct data for comparison, while avoiding changing the keys or values that we are testing for, and keeping test failure messages helpful.
Altered the existing test fixtures to expect whitespace to be transmitted in keys and values.

Only remove unquoted whitespace from JSON strings for comparison

---

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagEventMapper.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadType.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadSerializationTest.kt

Parse threads from stored events into the `Thread` model for processing by `OnSendCallback`s.
Updated the `ThreadSerializationTest` to include deserialization of all the existing thread fixtures

Parse Thread for OnSend Callbacks

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java

Alters the warning for when a non-application context is passed to `Bugsnag.start()`. This now lists why this may be a bad thing (it implies Bugsnag is being started in an activity and may miss certain errors), and gives steps on how to fix/suppress the warning.
The warning looks like this in Logcat:
>2021-11-23 10:26:54.536 7779-7779/com.example.bugsnag.android W/Bugsnag: You should initialize Bugsnag from the onCreate() callback of your Application subclass, as this guarantees errors are captured as early as possible. If a custom Application subclass is not possible in your app then you should suppress this warning by passing the Application context instead: Bugsnag.start(context.getApplicationContext()). For further info see: https://docs.bugsnag.com/platforms/android/#basic-configurati …

Alter warning about non-application context

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/FeatureFlagState.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/FeatureFlagStateTest.kt
bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.h
bugsnag-plugin-android-ndk/src/main/jni/featureflags.c
bugsnag-plugin-android-ndk/src/main/jni/utils/buffered_writer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/buffered_writer.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.h
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c

Ensure that feature flags collected by the NDK are stored during a crash so that they can be recovered later for reporting.
Copied the `buffered_writer` from the Journal with two major changes:
* the buffer is now a fixed size, and stack-local so that no dynamic memory is required.
* writing blocks larger than the buffer is now permitted: the buffer is first flushed, and then the block of data is written through the same function that flushes the buffer (handling `write` retries, etc.)
The buffered writer is used to reduce the number of `write` calls as the feature flags are dynamic and written field-by-field.
Introduced new native unit tests to ensure that the Feature Flags do not cause the serialization of events to fail. The deserialization PR will include checks to ensure the data is …

Serialize NDK Feature Flags

---

features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/TestOnSendCallback.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/OnSendCallbackScenario.kt
features/full_tests/onsend_callback.feature

Add Mazerunner coverage for the OnSend Callback to target next.
Copied the OnSend Mazerunner scenario from the Journal branch.

Mazerunner test for the OnSend callback

---

bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.h
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/featureflags.c
bugsnag-plugin-android-ndk/src/main/jni/featureflags.h
bugsnag-plugin-android-ndk/src/main/jni/utils/buffered_writer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/buffered_writer.h
bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.h
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c
features/fixtures/mazerunner/cxx-scenarios/src/main/cpp/bugsnag-java-scenarios.cpp
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXFeatureFlagNativeCrashScenario.java
features/full_tests/batch_2/native_feature_flags.feature

Load the feature flags stored in NDK events back into memory, and convert them to JSON for delivery.
* Moved `write_string` and `write_byte` functions into the `bsg_buffered_writer`
* Incremented the `bugsnag_event` version from 7 to 8 for feature flag detection
* Serialize feature flags to JSON
Includes both a unit test and a new native Mazerunner scenario to ensure that Feature Flags are synchronised between the Java layer and Native layer.

Load feature flags stored in NDK events

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/FeatureFlagState.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/FeatureFlagStateTest.kt
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/NativeFeatureFlagsTest.kt
bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.h
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/featureflags.c
bugsnag-plugin-android-ndk/src/main/jni/featureflags.h
bugsnag-plugin-android-ndk/src/main/jni/utils/buffered_writer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/buffered_writer.h
bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.h
bugsnag-plugin-android-ndk/src/test/CMakeLists.txt
bugsnag-plugin-android-ndk/src/test/cpp/main.c
bugsnag-plugin-android-ndk/src/test/cpp/test_featureflags.c
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c
features/fixtures/mazerunner/cxx-scenarios/src/main/cpp/bugsnag-java-scenarios.cpp
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXFeatureFlagNativeCrashScenario.java
features/full_tests/batch_1/feature_flags.feature
features/full_tests/batch_2/native_feature_flags.feature

Store feature flags in the NDK Bugsnag environment (`bsg_environment`) when they are changed on the JVM side, reproducing all existing JVM behaviour:
* Adding new flags
* Overwriting existing flags
* Clearing individual flags
* Clearing all flags
New unit tests and end-to-end tests included.

Store Feature Flags for NDK

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/ErrorBreadcrumbsScenario.kt
features/full_tests/breadcrumb.feature

Ensure the at Error Breadcrumbs are created and stored as soon as an `Event` is populated, rather than after the `Event` has been delivered.
Moved the `leaveErrorBreadcrumb` from `DeliveryDelegate` into the `Client` so that it can be called directly after the `Event` has been populated.
Added new unit tests for the `Client` facade, and a new Mazerunner scenario that create an handled error directly followed by an unhandled exception. The unhandled exception should include an Error breadcrumb with details of the handled error.

Leave error breadcrumbs before attempting event delivery

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/Event.java
bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/JsonStream.java
bugsnag-android-core/src/test/java/com/bugsnag/android/EventRedactionTest.kt
bugsnag-android-core/src/test/resources/event_default_redaction.json

Configured `redactedKeys` should be applied to metadata within Breadcrumbs, and not just metadata associated with Events.
Allowed the `JsonStream` class to wrap another `JsonStream` so that the `redactedKeys` can be enforced in `Event.toStream`. This naturally enforces the `redactedKeys` for the entire sub-tree.
Adjusted existing unit tests.

`redactedKeys` now correctly apply to metadata on Breadcrumbs

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXFeatureFlagNativeCrashScenario.java
features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/FeatureFlagScenario.kt
features/full_tests/feature_flags.feature
features/full_tests/native_feature_flags.feature

Mazerunner test feature covering the new feature flags logic. This covers feature flags added globally (using `Bugsnag.addFeatureFlag`) and directly to an `Event` via an `OnErrorCallback`.
Tests include checking for:
* A feature flag with a name only
* A feature flags with names and variants
* Adding a feature flag with a null name (should be ignored and not sent)

test(feature flags): mazerunner feature to test feature flags

---

CHANGELOG.md
bugsnag-benchmarks/build.gradle
buildSrc/src/main/kotlin/com/bugsnag/android/Versions.kt
dockerfiles/Dockerfile.android-common
examples/sdk-app-example/app/build.gradle
examples/sdk-app-example/app/src/main/AndroidManifest.xml
features/fixtures/mazerunner/app/build.gradle
features/fixtures/mazerunner/app/src/main/AndroidManifest.xml
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
features/fixtures/mazerunner/cxx-scenarios-bugsnag/build.gradle
features/fixtures/mazerunner/cxx-scenarios/build.gradle
features/fixtures/mazerunner/jvm-scenarios/build.gradle
features/fixtures/minimalapp/app/build.gradle

Bumps the [compileSdkVersion](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd) to apiLevel 31 from 30. This ensures that our SDK is compiled against the latest version of Android while retaining compatibility for previously supported versions.
- Bumped compileSdkVersion to 31
- Bumped targetSdkVersion where possible (bugsnag-benchmarks is the only place still targetting 30, as the microbenchmark library does not support this yet)
- Avoided closing the system dialogs in the mazerunner fixture as this is [no longer allowed in Android 12](https://developer.android.com/about/versions/12/behavior-changes-all#close-system-dialogs)
Relied on existing test coverage and ran the example app.

Bump compileSdkVersion to apiLevel 31

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java

The in-memory session should be sent first in precedence over sessions which are already persisted. This will reduce the chance of losing the session completely if a signal is raised as it reduces the time spent waiting for sessions to be sent.

Flush in memory session first

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/ConnectivityCompat.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ConnectivityApi24Test.kt
features/steps/android_steps.rb

Android's `ConnectivityManager` always invokes a callback with the current network state when `registerDefaultNetworkCallback` is called. This led to a network connectivity change breadcrumb being logged on Bugsnag initialization for API >= 24, which wasn't strictly a network change as such.
This alters the changeset to ignore the initial change on API 24 and to only log a breadcrumb for subsequent network changes.
Added unit test coverage and manually confirmed that a breadcrumb is no longer left on Bugsnag initialization as a matter of course, but that genuine network changes afterwards are recorded.

Avoid unnecessary network connectivity change breadcrumb

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/FileStoreTest.kt
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/NativeInterfaceTest.java
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionStoreTest.java
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionTrackingPayloadTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceData.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorStore.java
bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.java
bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionStore.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorFilenameTest.kt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java

Backports the `persistenceDirectory` option to allow controlling where errors/native crashes/sessions are stored: https://github.com/bugsnag/bugsnag-android/pull/998
Manually verified that errors make it through to the dashboard in a vanilla Android app and they can be stored in either the cacheDir or filesDir. Added unit test coverage.

Backport persistenceDirectory config option

---

bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c

Clear the stack-trace capture memory to ensure we don't accidentally attempt to use garbage data when calling `NewStringUTF` (or cause other issues).
Manual testing with a fresh app calling `Bugsnag::notify`.

Fix UTF-8 encoding errors in Bugsnag::notify

---

bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NdkPlugin.kt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.h

The ANR plugin was being initialized with a stack unwinder function that used `bsg_global_env->unwind_style` instead of the `bsg_global_env->signal_unwind_style` that signal handlers require (for safety in an async-safe environment).
The ANR handler is triggered from a signal handler, so this PR updates it to use the proper signal-safe unwind style.
Reran all tests and also tested manually.

[PLAT-7680] Use signal stack unwinding mechanism when unwinding an ANR

---

examples/sdk-app-example/app/build.gradle
examples/sdk-app-example/build.gradle

Increases the bugsnag version used in the example app to the latest, as this was getting a bit out of date. This also bumps the appcompat version + AGP version.
Ran the example app manually, ensured that it builds on CI.

Bump example app dependencies

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/cxx-scenarios-bugsnag.cpp

Ensure that `bugsnag_notify_env` does not fail due to uninitialised memory in the captured stack trace.
Added a new function to the native mazerunner scenarios which will "dirty" the stack to emulate the behaviour of a longer running application. The function simply populates a 1Mb temporary array with data and returns.

Clear the stack-trace memory to avoid UTF-8 encoding problems

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/ConnectivityCompat.kt

Builds on #1540 so that an unnecessary network change breadcrumb is not logged on devices running API <24. The `CONNECTIVITY_ACTION` intent is sticky so will always trigger the broadcast receiver.
Verified that E2E tests don't fail on Android 6, and otherwise relied on existing test coverage + manual testing.

Avoid unnecessary network connectivity change breadcrumb on API <24

---

bugsnag-plugin-android-ndk/build.gradle
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/migrations/EventMigrationTest.kt
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/migrations/EventMigrationV4Tests.kt
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV4Tests.cpp

Clean up following discussion in #1551 :broom: - use DSL JSON for deserialization component of migration tests, required a few tweaks to number formatting since internally the library uses longs, big decimal, and a different floating point implementation.
If it passes, it ships :ship:

build(ndk): remove unneeded test dep

---

Gemfile
Gemfile.lock
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
features/full_tests/native_feature_flags.feature

Feature Flags added in Java / Kotlin code need to be included as an array in unhandled NDK events. This requires that the `FeatureFlagState` be observed by the NDK plugin, and that the `featureFlags` be correctly encoded as a JSON array (and not as an object).
Fixed existing Mazerunner tests and upgraded Mazerunner to ensure coverage. This PR will also go through a full CI run to ensure all of the tests are exercised.

Fix feature flags in NDK

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/DefaultDelivery.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryTest.kt

Improve the memory use and performance of `DefaultDelivery.getDeliveryStatus` by avoiding the allocation and searching of a `List<Int>`.
Replaced the `IntRange` and `filter` with an equivalent method `isUnrecoverableStatusCode` which performs a simple set of comparisons.
Additional unit tests added to cover more of the unrecoverable errors

Improve the memory and performance handling delivery response status codes

---

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/BugsnagReactNativePluginTest.kt

Allow ReactNative applications to manipulate feature flags collected and stored in the native Android notifier. The PR covers only the methods required by the ReactNative bridge in [bugsnag-js](https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/android/src/main/java/com/bugsnag/android/BugsnagReactNative.kt).
Covered the direct logic with the same style of unit tests as we already use for the `BugsnagReactNativePlugin`, and also manually ran several end-to-end tests with a ReactNative application and modified `bugsnag-js/react-native` module.

ReactNative Feature Flags

---

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativeBridge.kt
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/BugsnagReactNativeBridgeTest.java

Deliver FeatureFlag events that occur in Android to the ReactNative bridge and JavaScript code. This ensures that the two layers remain in-sync and that events modified in JavaScript contain the expected feature flags.
JavaScript implementation is here: https://github.com/bugsnag/bugsnag-js/pull/1618
New unit test to check the expected event format of the events

Sync feature flags from Android -> ReactNative

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c

Deletes persisted NDK events as soon as they are read back into a `bsg_event` struct. This avoids the chance of a crash loop happening if `NativeInterface.deliverReport()` throws an exception.
Relied on existing E2E test coverage.

Delete persisted NDK events earlier in delivery process

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/event.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.h
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_string.c

Adds null checks for calls to `strlen()` as some input could conceivably be `null` and lead to segfaults.

Add null checks for strlen()

---

bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/event.c
bugsnag-plugin-android-ndk/src/main/jni/handlers/signal_handler.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.c
bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder_libcorkscrew.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.h
bugsnag-plugin-android-ndk/src/main/jni/utils/threads.c
bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c
bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_string.c

We're currently using two `strlen` implementations and three `strcpy` implementations. Pick one proper implementation of each and use it exclusively.
Re-ran all tests, and tested manually.

[PLAT-6090] Harmonize all string copying in the NDK layer

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/DefaultDelivery.kt

Performs a null check if `conn.inputstream` is null, which is the case for unsuccessful requests. This avoids an `IOException` when reading the body that results in the response status code logic being bypassed, which effectively results in large payloads getting stuck on the device.
For good measure this also catches `IOException` that can be thrown when reading the `InputStream/OutputStream` too.
This change was introduced when adding extra logging info [here](https://github.com/bugsnag/bugsnag-android/pull/1077/files#diff-a0f6af1bfd1263d58911c6694d204e09ecac00307eefa65dd4a4f255485e5443R105) so will be present from v5.5.1 onwards.
Manually verified that the request is now sent if it has a 400 status code, and that exceptions are not thrown.

Catch IOException when logging response status code

---

scripts/docker-publish.sh

Avoid creating multiple Sonatype Nexus repositories when publishing releases. Sonatype automatically creates staging repositories based on inbound connections, so using more than one worker can cause multiple staging repositories to be created each one with a subset of the entire release (forcing us to re-run the release).
Manually tested locally

Publish should only have one worker

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/LastRunInfoStore.kt
bugsnag-plugin-android-okhttp/src/main/java/com/bugsnag/android/okhttp/BugsnagOkHttpPlugin.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/LeaveBreadcrumbTest.kt
buildSrc/src/main/kotlin/com/bugsnag/android/Versions.kt
gradle/kotlin.gradle

Updates the project to build with Kotlin 1.4, while targeting an API version of 1.3.

Update project to build with Kotlin 1.4

---

bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/migrations/EventMigrationV8Tests.kt
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_reader.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/migrate.h
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV4Tests.cpp
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV5Tests.cpp
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV6Tests.cpp
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV7Tests.cpp
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV8Tests.cpp
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c
features/steps/android_steps.rb

Added additional changes to event format v8 to expand the size of version code, total memory, and duration values to fit 64-bit integers.
Technically any stored values can now be as large as ~52 bits when delivered as that is how much can fit in a number within the current JSON format (though #1554 mitigates this).
* Fetched values as longs where needed instead of doubles
* Updated storage type of total memory and friends to be `int64_t`
* Added migration for existing app and device contents of events
* Updated existing assertions to use big big numbers

fix(ndk): support storing large ints for memory and time values 

---

bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/event.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.h
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.c

Some Java objects were still leaking, or being removed at the wrong time, and the caches for the JVM handles were getting reloaded on every call (and leaking).
* All class and method handles have been consolidated to jni_cache.c
* Class handles are refreshed on each JNI call because they get deleted when the call returns.
* All JVM handles are now properly disposed of in sub-functions or loops (for top-level JNI functions there's no need since the handles will get reaped as soon as the function returns)
* Functions that weren't being used outside of their files have been marked static.
Reran e2e tests, and tested manually.

Improve JNI safety

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/ExceptionHandler.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ExceptionHandlerTest.kt

Fix edge cases where crashing the app in a disabled `releaseStage` in the `Application.onCreate` method caused the app to hang instead of terminating. This appears to be caused by an interaction between the Android Runtime and it's startup behaviour, and the fact that we were not forwarding the uncaught exception to the default `UncaughtExceptionHandler` leaving the application partly running.
By forwarding uncaught exceptions before discarding them, we allow the default handler to do it's work and the app cleans up and terminates as expected.
Uncaught exceptions that will be discarded by Bugsnag are first forwarded to any previously registered `UncaughtExceptionHandler`.
Manually tested the edge case as described in the ticket, and added a unit test for the new `ExceptionHandler` …

Propagate discarded exceptions to previously registered handlers

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.h
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.h

Fix `SIGABRT` crashes caused by multiple threads reading and writing to the global `bsg_jni_cache` simultaneously.
Replace the global JNI cache with a single cache for each JNI function call. A stack-allocated cache is populated on-entry to the NDK layer and a pointer to the cache is then passed into each function that requires it. This avoids any allocation errors, and ensures that JNI objects don't accidentally cross thread-boundaries.
Manual testing with an app known to cause this issue. Due to the race-condition nature of this crash, no additional automated tests can be added at this time.

Don't attempt to share the `bsg_jni_cache` between threads

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagEventMapper.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt
bugsnag-android-core/src/test/resources/event_serialization_7.json
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXFeatureFlagNativeCrashScenario.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/FeatureFlagScenario.kt
features/full_tests/feature_flags.feature
features/full_tests/native_feature_flags.feature

Fix a bug where configuring an `OnSendCallback` would potentially cause feature flags to be dropped from reports. This was caused by `BugsnagEventMapper` not parsing the feature flags list back into the in-memory model, causing them to be dropped from any `Event` that was stored on disk (although only if an `OnSendCallback` was configured).
Additional unit tests, and new Mazerunner tests to cover this scenario.

Parse FeatureFlags when OnSendCallbacks are configured

---

CHANGELOG.md
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/EventDeserializerTest.kt

Allow React Native applications to override the `Event.apiKey` in their callbacks.
If the `apiKey` field is present and not empty, override it in the `Event` before delivery to the Android layer
Additional unit tests added, and manually tested with the example React Native app.

Fix React Native events that override the apiKey

---

bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.h
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/metadata.h
bugsnag-plugin-android-ndk/src/main/jni/safejni.c

JNIEnv is only valid for the current thread, so we shouldn't be permanently storing it as a global. Store JavaVM instead.
Complete the JNI cache fix by making the cache once again global, ensuring that all object references have been first made global.
Re-ran all automated tests, did manual testing using the example app.

[PLAT-7915] Init JNI cache once, and don't store JNIEnv

---

bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.c

Apply similar JNI fixes to what was applied to the NDK plugin.
This PR simply continues in the tradition of duplicating code from `safejni` in the NDK plugin, and now the JNIEnv getting mechanism from the JNI cache code.
I'd originally tried running both the ANR and NDK plugins from the same code, but JNI started giving weird results like returning a pointer value of 0x1 and 0x19. depending on the order of the calls made (it didn't seem to matter what actual API was called). Since it was behaving so unstably, I've gone back to the simpler code duplication approach.
Reran all e2e tests, ran manually with the example app.

Port JNI safety code to ANR plugin

---

bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/exported_native_symbols-Debug.txt
bugsnag-plugin-android-ndk/src/main/exported_native_symbols-RelWithDebInfo.txt
bugsnag-plugin-android-ndk/src/main/jni/handlers/cpp_handler.cpp
features/fixtures/mazerunner/cxx-scenarios-bugsnag/CMakeLists.txt
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/CXXExceptionSmokeScenario.cpp
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/cxx-scenarios-bugsnag.cpp
features/smoke_tests/unhandled.feature
features/steps/android_steps.rb

Only expose the minimum surface required to make the library work, via a linker [version script](https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_node/ld_25.html). They should be:
* `Java_*` for JNI functions
* `bugsnag_*` for the native API
* `__cxa*`, `__gxx*` and friends for C++ exception handling
* Add linker script to build process
* Remove exception property reporting dependent on arbitrary type info being present
Tested manually that exception handling still worked as expected, though this change should be covered by the existing tests and addition of a specific test for C++ exception handling.

Avoid exporting lib ndk internals

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/AppDataCollectorForegroundTest.kt

This test fails regularly on lower spec'd x86 runs due to variance in the duration.

test: allow larger delta for foreground ms range

---

.buildkite/pipeline.quick.yml

these tests still consistently fail, either due to poor test or device farm quality (unsure how I missed this one in #1612)

ci: remove android 5 builds

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/BackgroundTaskService.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/LaunchCrashDeliveryTest.kt

In a worst case scenario, `BackgroundTaskService.shutdown()` could wait for 4.5 seconds to complete a shutdown, which is dangerously close to the 5s limit for an ANR if this happens on the main thread.
Rework so that all the shutdowns happen at the same time.
Rerun all tests. Unfortunately this manifest as a flake in CI so there's no definitive test for it.

Rework the background task service shutdown procedure to give more headroom against the 5s ANR timeout

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/utils/string.c
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_string.c

Passing a `NULL` source string to `bsg_strncpy` should still `\0` terminate the destination string if there is available space (`dst_size` > 0).
A new unit test was added to cover the functionality

`bsg_strncpy` should terminate `dst` even if `src` is `NULL`

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiThreadedStartupScenario.kt
features/full_tests/threaded_startup.feature

Allow Bugsnag functions (`notify`, `leaveBreadcrumb`, `addMetadata`, etc.) to be safely invoked from background threads, while `Bugsnag.start` is still running.
The additional lock makes [late & multi-threaded startup](https://github.com/bugsnag/bugsnag-android/issues/883) safe.
Added an end-to-end test that flakes (typically failing) when the additional lock is not in place.

Improve `Bugsnag.start` thread-safety

---

bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.h
bugsnag-plugin-android-ndk/src/main/jni/handlers/cpp_handler.cpp
bugsnag-plugin-android-ndk/src/main/jni/handlers/signal_handler.c

The flag to mark that a native crash is being handled was not atomic, leaving room for a race condition should two threads trigger a native crash at the same time.
Use atomics to ensure that no race condition is possible.
Reran all tests.

Ensure handling_crash flag is atomic

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java
bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagApiTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagClientMirrorInterfaceTest.kt

From #1621:
> Add Bugsnag.isStarted so that it is possible to check whether it is safe to call the other methods. Currently to use Bugsnag safely you either have to keep track of this yourself or wrap calls in try/catch.
Raised internally for CI and merge purposes.

[PLAT-8191] Add Bugsnag.isStarted

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/EventFilenameInfo.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java
bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.java
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionFilenameInfo.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionStore.java
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardBigEventsScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldEventsScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldSessionScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldSessionScenarioPart2.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldSessionScenarioPart3.kt
features/full_tests/discarded_events.feature
features/full_tests/discarded_session.feature

To prevent the buildup of old or large files, event and session files will be deleted on a failed send if they meet certain criteria:
- Events if they are older than 60 days or larger than 1MB
- Sessions if they are older than 60 days
New e2e tests

[PLAT-8185] Limit retries of event payloads based on size and age, and session payloads based on age

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiThreadedStartupScenario.kt

Stop `MultiThreadedStartupScenario` from flaking.
Add a 1ms delay into the "leaveBreadcrumb" thread, simulating a small workload without being enough time for `Bugsnag.start` to have completed. This should stop the "leaveBreadcrumb" thread from acquiring the `lock` before `start` can.
Will rerun the full test suite.

Fix MultiThreadedStartupScenario

---

features/steps/symbol_steps.rb

* Improve test result accuracy across compilers
* Make CI results more debug-able without needing to download artifacts and re-symbolicate frames
* Exclude grouping on `__gnu_cxx*` functions
* Print symbolicated frame contents when tests fail
* This is a test-only changeset and includes a full CI run

ndk: improve accuracy of in-project detection in tests

---

bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorType.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventErrorTypeTest.kt

Add `dart` to our available list of `ErrorType`s to support Flutter notifiers
Added the new constant to existing tests.

Add the "dart" ErrorType

---

bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt

`NativeBridge.is32Bit()` had an unnecessary `toList()` call that for some reason was adding 25ms to the startup time. Removing it brings the time back down to sub-millisecond.
Manual testing, reran all tests.

Remove unnecessary toList() call that was slowing down initialization

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.quick.yml
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/Command.kt
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
features/fixtures/mazerunner/app/src/main/res/layout/activity_main.xml
features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/Log.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldEventsScenario.kt
features/full_tests/discarded_events.feature
features/full_tests/discarded_session.feature
features/full_tests/native_event_tracking.feature
features/steps/android_steps.rb
features/support/env.rb

Use Maze Runner's `/command` endpoint to fetch the next action to perform.  Also make various corrections and fixes some flakes.
Avoids the need for costly text entry/button presses by Appium by using a single button press to fetch the next "command" (JSON document) from Maze Runner.
- `run_command` button added to test fixture UI, redundant fields and buttons removed.
- Cucumber steps updated to drive tests using commands.
- Remove ARMv8 64 ABI device for NDK r16 tests as the relevant scenarios `.so`  is not included.
- Extra sleep added to `DiscardOldEventsScenario` as it was flaking heavily on Android 10+.
- Steps added to ensure device returns to portrait after being backgrounded (an Appium bug causes it to go landscape).
Covered by a `[full ci]` run, performed before raising this PR.

e2e tests - use Maze Runner /command endpoint

---

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagEventMapper.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/BugsnagMapper.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/internal/BugsnagMapperTest.kt

Expose the existing `BugsnagEventMapper` logic as an internal API for cross-platform notifiers to use, rather than having to re-invent the JSON serialization & deserialization logic.
Create a new `BugsnagMapper` public class as a member of the `internal` package so that we don't conflict with the existing Java or Kotlin name-spaces.
The class exposes 2 functions:
- `convertToEvent` converts JSON-like `Map` objects to an `Event` if possible
- `convertToMap` converts `Event` object to JSON-like `Map` objects compatible with `convertToEvent`
Added a new unit test which uses existing event JSON fixtures.

Add `BugsnagMapper` to the `internal` package

---

Gemfile
Gemfile.lock
docker-compose.yml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardBigEventsScenario.kt
features/full_tests/discarded_events.feature
features/steps/android_steps.rb

Due to potential flakiness, and to more accurately reflect the processes involved, use the terminating server for testing how the Android notifier handles situations where the payload is rejected by the pipeline due to being too large.

Update payload too large test to be less flakey

---

features/fixtures/mazerunner/app/detekt-baseline.xml
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
features/fixtures/mazerunner/app/src/main/res/layout/activity_main.xml
features/full_tests/auto_notify.feature
features/full_tests/detect_anr_jvm.feature
features/full_tests/detect_ndk_crashes.feature
features/full_tests/discarded_events.feature
features/full_tests/native_event_tracking.feature
features/full_tests/startup_anr.feature
features/full_tests/threaded_startup.feature
features/minimal/detect_anr_minimal.feature
features/smoke_tests/unhandled.feature
features/steps/android_steps.rb
features/support/env.rb

Reinstatement of #1651, having suffered what turned out to be a broken local repo.
Start a thread when the Test Fixture launches to poll Maze Runner for the next command action to perform.
Android likes to throw up system dialogs for crashy apps, which have needed to be closed so that Appium actions aren't blocked.  However, error dialogs aren't always shown and so we've been spending a lot of time trying to dismiss dialogs that are not present (around 4s each time).  With this change the runtime for each full set of e2e tests is reduced by around 10 minutes.
`run_command` button removed, being replaced by a polling thread.
Removal of error dialog closing calls in most situations (still needed for touch events so that ANR scenarios work reliably).

Pull e2e test commands from Maze Runner

---

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagEventMapper.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/BugsnagMapper.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorSerializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/internal/BugsnagMapperTest.kt
bugsnag-android-core/src/test/resources/error_serialization_1.json
bugsnag-android-core/src/test/resources/error_serialization_2.json

Allow cross-platform notifiers to level JSON-like encoding & decoding of Bugsnag `Error` objects.
Additional unit tests to cover the new logic. Also expanded our existing `Error` serialization tests.

Add Error support to BugsnagMapper

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

Combine the coding standard check steps, making for a faster run.  Also try to balance the two batches of e2e tests so they take roughly the same amount of time.
Combined steps covered by a standard CI run and I verified that the `--continue` did result in all checks being performed if one fails using a temporary commit.  
For balancing the batches, I ran a full build and whilst runtimes can always vary, the batches were pretty balanced - within a minute of each other.

Minor CI improvements

---

Gemfile
Gemfile.lock
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
features/fixtures/mazerunner/app/src/main/res/layout/activity_main.xml
features/steps/android_steps.rb
features/support/env.rb

Provide some visual feedback for the current e2e scenario being run.
When a Command is received from Maze Runner, the action and scenario name are displayed in the UI fields.  This can help if a test run goes wrong - to see if something like a popup appears as the scenario is being run.
Instead of adding additional field to the fixture's UI, I've pushed the endpoints into the Command itself and reused the existing fields.  Their presence on the UI was a bit of a hangover and there's no specific need for them to be on the UI.
Covered by a basic CI run.  I've also watched a video back to verify that the values appear and are generally useful.

Visual feedback for e2e tests being run

---

features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXExceptionSmokeScenario.kt
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXSignalSmokeScenario.java
features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/BugsnagConfig.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CustomHttpClientFlushScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardBigEventsScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldEventsScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/ReportCacheScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/SessionCacheScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StartupCrashFlushScenario.kt
features/full_tests/discarded_events.feature

Reinstate and rework e2e test scenario DiscardBigEventsScenario.
This scenario was using the Maze Runner `TerminatingServer` to prematurely terminate big requests (like the real Bugsnag does), but the network doesn't behave consistently with the BrowserStack secure tunnel involved.
Reverts to using the classic Maze mock server, returning a 500 (and 400 in a separate scenario) to test the different code paths.
Covered by CI and I have run it several times (40) locally to gain a good level of confidence in it being flake-free.

Rework test DiscardBigEventsScenario

---

features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoDetectNdkDisabledScenario.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardBigEventsScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeFileUriExposeScenario.kt
features/full_tests/auto_notify.feature
features/full_tests/detect_ndk_crashes.feature
features/full_tests/discarded_events.feature
features/full_tests/strict_mode_legacy.feature

Avoid some idle waiting time in e2e tests by checking for Bugsnag log messages rather than waiting for a set period of time for nothing to happen.
Follows the existing pattern for using the `Bugsnag confirms it has no errors to send` step, it just hasn't been employed uniformally.
Feature files updated to use the step where possible.  Scenario code updated to override `getInterceptedLogMessages`, which is needed so it knows what log messages to look out for.

Use step ‘Bugsnag confirms it has no errors to send’ where feasible

---

features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXDelayedErrorScenario.kt

Reduce change of CXXDelayedErrorScenario flaking.
Any test scenario that depends on timely execution is inherently flaky, but the 250ms allowed here seems a little optimistic  - for it to allow enough time for the first error to be sent within the launch period.
Increased launch duration and added logging in case it continues to flake.
CI shows the scenario still run as intended - only time will tell if the flake is really fixed.

Reduce change of CXXDelayedErrorScenario flaking

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldEventsScenario.kt
features/full_tests/discarded_events.feature

Remove the sleep from `DiscardOldEventsScenario` and adjust the `DiscardOldEventsScenario` tests to remove flakeyness
`Wait for 5 seconds` added to cucumber test to allow for the request to be sent and processed to properly remove he old event.
Sleep removed from `DiscardOldEventsScenario.kt`
`And I wait for 5 seconds` added to `discarded_events.feature` 
Battery of tests run locally and covered by a full CI

DiscardOldEventsScenario Flake

---

features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldEventsScenario.kt
features/full_tests/discarded_events.feature

Enhances the checks performed in `DiscardOldEventsScenario`, whilst also saving a relaunch of the app.
I've built slightly on the existing mechanism that allows us to capture and report specific log messages to Maze Runner.
Updates the log capture mechanism to allow logs that match a regex (rather than just a string) to be sent to Maze Runner.  The test scenario is then reworked to be more specific about the requests that are being received and to check for the log message (saving a relaunch of the app).
Covered by CI and successfully run several times.

Update test DiscardOldEventsScenario to check for Bugsnag log

---

features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt

Avoid Maze Runner commands from being lost by stopping polling for commands once one is received.  
We have seen commands "go missing" in some test runs, causing them to flake.  The Cucumber step includes a check that queued commands are fetched, suggesting they are somehow lost in the test fixture.  The theory behind this change is that it's possible for the fixture to fetch another command before the app crashes (and before the response to the request is received and processed, so there is not sign of it in the logs).
Stop polling after a run_scenario or start_bugsnag command is received.

Stop test fixture from polling once a command is received

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

`cp` the `.git` folder needed by Danger, rather than symlinking to it, as Buildkite won't remove the symlink - causing later builds on the same server to fail.  This was introduced in #1674.
I've also moved the size step to the main pipeline, as Danger only runs its checks for PRs - most of which will not run a full build.
Covered by CI.

Do not symlink folders during a CI build

---

.buildkite/pipeline.yml

Ensure the Android Sizer step can handle a `.git` folder of symlink already being present in the tree.
#1678 was incomplete.  `.git` folders are not removed either by `git clean -xfd` (not surprising on reflection), so I have reverted to the cheaper symlink operation, but ensured it can handle a dirty folder and attempt to leave it clean.
I pushed a temporary commit prior to raising this PR with the step duplicated several times to force it to run all all our servers (including two that were previously broken).

Handle dirty folder and leave it clean

---

Gemfile
Gemfile.lock
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiThreadedStartupScenario.kt
features/full_tests/threaded_startup.feature
features/steps/android_steps.rb

Avoid test flake in `MultiThreadedStartupScenario`.
`MultiThreadedStartupScenario` is designed to verify that calling Bugsnag methods while it is being started on another thread does not raise an exception.  The scenario can occasionally flake if the OS end up starting the `leaveBreadcrumb` thread first (which we cannot control completely, even by setting thread priorities).  If that happens that Bugsnag raises an exception stating that `Bugsnag.start` must be called first.
This change allow a retry in the specific case that the exception is raised because the threads started in reverse order.
Covered by CI and I saw the retry take affect once during development (it's not that easy to reproduce).

Allow retry for specific failure in MultiThreadedStartupScenario

---

.buildkite/pipeline.yml
features/fixtures/minimalapp/Dangerfile
scripts/run-sizer.sh

Fixes the generation of notifier size metrics, which were recently broken after (incompletely) porting the build step from Linux to macOS.
Port `Dangerfile` to macOS, pushing the build commands into a script.
By inspection of the comment on this PR.

Fix generation of notifier size metrics

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
features/steps/android_steps.rb

Attempts to improve CI stability.
- Use Google Nexus 6 in preference, as a higher tier device on BrowserStack
- Move the starting of the thread the polls for test Command to `onResume`, in the hope that the app is "more ready"
- USe `Maze.check.equal` rather than `assert_equal`
Ran a full batch of e2e tests on Android 6 twenty times with no failures due to how the polling started (some other flakes do still exist).

Improve CI stability

---

bugsnag-android-core/src/main/java/com/bugsnag/android/SessionLifecycleCallback.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/SessionLifecycleCallbackTest.kt
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXAutoContextScenario.java
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXDelayedCrashScenario.kt

On SDK 29 and higher use the `onActivityPostStarted` and `onActivityPostStopped` to update the session tracking, ensuring the `Activity` has finished changing state before we fetch new session state attributes.
When the foreground activities are started and stopped we capture flags such as context and `inForeground` and send them to observing layers (such as ReactNative and NDK). By capturing them after the `onStart`/`onStop` methods have returned we ensure that these attributes are properly up-to-date.
TBD

Only update session tracking after Activities have changed state

---

bugsnag-plugin-android-anr/src/main/jni/anr_google.c

The Google signal catcher thread detection heuristic that used the blocked signals mask was too naive, and checked for a specific value (0x1000), which is fragile and broke when the block mask changed to 0x5000 in Android 12.
Instead, change the heuristic to check only that the `SIGQUIT` signal is unblocked, since that's the only signal we actually care about (all other threads default to blocking SIGQUIT).
On very old versions of Android the normal sigblk of a thread is 0x0000000000001204, and the signal catcher has 0x0000000000001000.
On more recent Android versions, the normal sigblk is 0x0000000080001204, and the signal catcher has 0x0000000000001000.
On Android 12, the normal sigblk is 0x0000000080005204, and the signal catcher has 0x0000000000005000.
In all cases, we only need to …

[PLAT-8520] Better heuristics for detecting the signal catcher thread

---

CHANGELOG.md
Makefile
bugsnag-plugin-android-ndk/src/main/jni/event.c
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXRemoveDataScenario.java

Fix a bug when overwriting of clearing metadata, the NDK did not always remove the value as expected leading to phantom metadata values in reports. For example:
```
addMetadata("section", "overwrite", "value1")
addMetadata("section", "overwrite", "value2")
clearMetadata("section", "overwrite")
```
Would typically result in the Event having `"value1"` in its reported metadata, instead of no value as expected.
Introduce a simple compacting function which will remove any duplicates and gaps in the metadata array and compact it.
This new function is used when either:
* an entry or entries are removed from the metadata
* the metadata array is full and a new value is being added
By retaining the insertion order of the metadata we introduce minimal additional overhead on the most common path: …

Avoid phantom values in NDK Metadata

---

bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java

This allows users to do:
```kotlin
config.telemetry.remove(Telemetry.INTERNAL_ERRORS)
```
instead of having to make a copy first (which is ugly in Java).

Make telemetry an EnumSet so that it can be modified

---

bugsnag-plugin-android-ndk/proguard-rules.pro
bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/OpaqueValue.kt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/event.c
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.h
bugsnag-plugin-android-ndk/src/main/jni/metadata.c
bugsnag-plugin-android-ndk/src/main/jni/utils/memory.c
bugsnag-plugin-android-ndk/src/main/jni/utils/memory.h
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXConfigurationMetadataNativeCrashScenario.java
features/full_tests/native_metadata.feature
features/smoke_tests/unhandled.feature

Detect metadata values that cannot be represented directly in the C layer and encode them as `OPAQUE`. This includes breadcrumbs which use a `OpaqueValue` marker object in the `Map` delivered to the C layer for storage.
Introduced a new end-to-end test that add complex metadata via the Java layer. This does not fully function yet as the data cannot be retrieved in the error reports (upcoming functionality). The test does however ensure that the new functionality introduces no other failures when adding the metadata.

Encode opaque metadata

---

bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp
features/fixtures/mazerunner/app/build.gradle
features/fixtures/mazerunner/app/src/main/AndroidManifest.xml
features/full_tests/native_crash_handling.feature
features/steps/symbol_steps.rb
features/support/env.rb

Ensure that `.so` files are reported by name (where possible) when the native libraries are not extracted from the `.apk` file. When packaged correctly, the operating system may load the `.so` files from within the `.apk` file in order to save space and time (see [extractNativeLibs](https://developer.android.com/guide/topics/manifest/application-element#extractNativeLibs) and [useLegacyPackaging](https://developer.android.com/studio/releases/gradle-plugin?buildsystem=ndk-build#compress-native-libs-dsl) for more information).
Symbols for these files were sometimes being reported as coming from `base.apk` instead of the expected `.so` file, and as a result were not displaying the correct symbols on the Dashboard.
Updated the `dladdr` fallback logic in the stack unwinder to look for …

Correctly report native-lib filenames when still packed in APK files

---

bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_reader.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_writer.c
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c

Write opaque metadata to the binary events stored at crash-time, and retrieve them when the events are loaded for reporting.
Included a new unit test to ensure that opaque metadata values added to an event are saved and loaded from the binary.

Store opaque metadata values in binary events

---

bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.h
bugsnag-plugin-android-ndk/src/main/jni/safejni.c
bugsnag-plugin-android-ndk/src/main/jni/safejni.h
features/fixtures/mazerunner/app/detekt-baseline.xml
features/fixtures/mazerunner/cxx-scenarios-bugsnag/detekt-baseline.xml
features/fixtures/mazerunner/cxx-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/cxx-scenarios/src/main/cpp/cxx-scenarios.cpp
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXIgnoredSigabrtScenario.kt
features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/full_tests/ignored_reports.feature

Also filter out NDK events based on the discard classes config setting.
The NDK now queries the JVM to see if an event class is on the discard list before generating a payload to be sent.
Added e2e tests.

Make discard classes apply to native crashes as well

---

bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/OpaqueValue.kt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/event.c
bugsnag-plugin-android-ndk/src/main/jni/utils/memory.c
bugsnag-plugin-android-ndk/src/main/jni/utils/memory.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_reader.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_writer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/json_writer.c
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/cxx-scenarios-bugsnag.cpp
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXSignalSmokeScenario.java
features/full_tests/native_metadata.feature
features/smoke_tests/unhandled.feature
features/steps/breadcrumb_metadata_steps.rb

Encode the opaque JSON values into the Parson JSON model so that they are delivered with the event.
- When not in a signal handler: `free` any opaque values that cannot be referenced
- clear metadata
- clear metadata section
- clear breadcrumbs
- add breadcrumb (when overriding an existing breadcrumb)
- end-to-end tests covering opaque metadata in events and breadcrumbs
- clearing opaque metadata in a C `on_error` callback to ensure we don't deadlock within a signal handler
- small fixes for bugs picked up in end-to-end testing
- new Mazerunner steps to cover metadata within breadcrumbs
- searching breadcrumbs by name instead of index makes the tests more robust
Modified the existing `CXXSignalSmokeScenario` to include a large amount of opaque metadata at both the event level, and within …

Encode opaque metadata into JSON events to be delivered

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/FeatureFlags.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/FeatureFlagsSerializationTest.kt
bugsnag-android-core/src/test/resources/feature_flags_serialization_0.json
bugsnag-android-core/src/test/resources/feature_flags_serialization_1.json
bugsnag-plugin-android-ndk/src/main/jni/featureflags.c
bugsnag-plugin-android-ndk/src/test/cpp/test_featureflags.c

PLAT-8682: Preserve the order of feature flags in the order they were added or modified.
The NDK implementation has been changed to use a linear search, and to do simple compaction when modifying or clearing a flag.
The JVM implementation simply changes to a LinkedHashMap, and synchronizes the public APIs.
Updated the unit tests to verify the new behavior.

Preserve ordering of feature flags

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Event.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/OnSendCallbackScenario.kt
features/full_tests/onsend_callback.feature

Allow feature flags to be accessed from the event object during OnSend callbacks
Updated e2e tests to check accessing the feature flags from OnSend

[PLAT-8704] Allow feature flags to be accessed from the event object during callbacks

---

bugsnag-plugin-android-ndk/detekt-baseline.xml
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/migrations/EventMigrationV10Tests.kt
bugsnag-plugin-android-ndk/src/main/assets/include/event.h
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_reader.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/json_writer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/migrate.h
bugsnag-plugin-android-ndk/src/test/CMakeLists.txt
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV10Tests.cpp

Introduce the `codeIdentifier` stack frame field into the NDK model, so that we can start reporting `Build ID`.
- Added the `code_identifier` to the stack frame model
- Event model is now version 10
- New migration tests for version 10
New unit tests to ensure the migration code works. Manual testing of normal event reporting, and migrations.

Added `codeIdentifier` to the NDK event model

---

bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.h
bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp
bugsnag-plugin-android-ndk/src/main/jni/utils/string.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.h
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_string.c
features/full_tests/native_context.feature
features/full_tests/native_crash_handling.feature
features/full_tests/native_event_tracking.feature

When reporting native stack traces, we need to include the "Build ID" as `codeIdentifier` for each stack frame (when it's available) so that we can later retrieve the correct symbol data.
- Add the "Build ID" to the stack-frames in the NDK event model during a crash
- Use `NativeStackframe` instead of `StackTraceElement` to relay `bugsnag_notify` events to the JVM layer
New unit tests and additional checks on top of existing end-to-end testing

Report "Build ID" as codeIdentifier in NDK stacktraces

---

bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt
bugsnag-plugin-android-ndk/detekt-baseline.xml
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/migrations/EventMigrationV10Tests.kt
bugsnag-plugin-android-ndk/src/main/assets/include/event.h
bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_reader.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/json_writer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/migrate.h
bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp
bugsnag-plugin-android-ndk/src/main/jni/utils/string.c
bugsnag-plugin-android-ndk/src/main/jni/utils/string.h
bugsnag-plugin-android-ndk/src/test/CMakeLists.txt
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV10Tests.cpp
bugsnag-plugin-android-ndk/src/test/cpp/test_utils_string.c
features/full_tests/native_crash_handling.feature
features/full_tests/native_event_tracking.feature

Report the "BuildID" of `.so` files for each frame where it can be identified.
After unwinding the stack, attempt to identify the "Build ID" from `MapInfo` for each frame. The Build ID or MapInfo will be empty if the frame is not backed by a `.so` file (such as Dex frames) or if the module has no `.note.gnu.build-id`. In these cases the `codeIdentifier` will be left as `null`.
New unit tests to cover the new structure and migration, additions to the end-to-end tests.

Report the Build ID in codeIdentifier

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/OpaqueValue.kt
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXConfigurationMetadataNativeCrashScenario.java
features/full_tests/native_metadata.feature

Allow any valid `Collection` to be encoded as OPAQUE NDK metadata
Additional values in the end to end test

Allow any Collection to be encoded as OPAQUE in NDK metadata

---

features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
features/smoke_tests/01_anr.feature

Attempt to reduce flakes in the ANR Smoke Test on Android 4 devices.
The test scenario now taps the screen, then waits 5 seconds, and finally uses the back button to try force an ANR. While this takes a little longer than previously, it more closely mimics expected user behaviour.
Reran the test scenario several times without the ANR scenario flaking.

Reduce flakes in the ANR Smoke Test on Android 4

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/EventStoreConfinementTest.kt

Lower the probability that `EventStoreConfinementTest` fails due to over-strict verification.
`EventStoreConfinementTest` silently relies on the order of files being listed (due to the way `EventStore.flushAsync` works). As a result the assertions sometimes fail when files are not returned in the expected order.
The test does not need to depend on the file order however, and instead is attempting to ensure no unexpected files are being delivered.
Change the `flushAsyncIsThreadConfined` assertion to check each file against a list of "expected" files, and report if an unexpected file is being delivered.
The report will now include the index of the file being checked, alongside the list of files it still expects to see (to aid future debugging).
Rerun the test many times locally without it …

Improve reliability of EventStoreConfinementTest

---

.buildkite/pipeline.full.yml

Add tests against Android 13 Beta to CI.
For now I have just added this to the full CI run.  Once 13 comes out for real (and is available on BrowserStack) we'll put it into the basic CI and push 12 into full.
New pipeline steps for Android 13 Beta.
Covered by a Full CI run.

Add tests for Android 13 to Full CI

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp
features/steps/android_steps.rb

Correct the `frameAddress` to take into account code mapped in with non-zero base offsets, or mapped in from an `apk` file (without extracting the `.so` file).
Additional check in all native mazerunner tests to ensure that the expected contract is being followed.

Offset `frameAddress` by the map base offset

---

bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp

Ensure that the NDK line numbers, frame address and load address always line-up as expected by symbolication.
Set the `frameAddress` according to the expectations in symbolication to avoid the subtle differences that appear from platform-to-platform.
Relied on the new end-to-end tests which enforce the `lineNumber == frameAddress - loadAddress` contract of all NDK reports.

Set NDK lineNumber == frameAddress - loadAddress

---

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagStateModule.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java

Clean up the Client constructor.
Move non-constructor-y code to a separate `start()` function, which must be called before using a client.
Reran all tests to make sure they still pass.

Small cleanups to Client constructor

---

bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/InternalMetricsImpl.kt
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/json_writer.c
features/full_tests/usage.feature

The usage statistics were being put in the wrong place in the payload.
This PR moves the stats to their proper place under "usage".

Fix placement of usage statistics so that they are all placed under "usage" in the payload

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java
bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/ImmutableConfig.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestData.java
features/fixtures/mazerunner/app/proguard-rules.pro
features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DeliverOnCrashScenario.kt
features/full_tests/crash_handler.feature

Attempt to deliver crashes when they happen if configured.
The `DeliveryDelegate.cacheEvent` flag for `attemptSent` now attempts immediate delivery of just that single event
A new test scenario was introduced to test that a crash can be delivered without a fixture restart.

Attempt delivery on crash if configured

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/JavaHooks.java
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/TestHarnessHooks.kt

Avoid reflection in `createDefaultDelivery` in the Maze Runner fixture, as it's fragile and the order of constructors is subject to change.
`DefaultDelivery` is `internal` and so can be accessed directly by Java code (although with a warning). 
This change would fail the Maze Runners compile instead of at runtime, so makes tests more robust.

Don't rely on reflection to construct DefaultDelivery in Maze Runner tests

---

features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt

Use a dedicated `Handler` to deliver work to the main thread in Maze Runner instead of relying on `runOnUiThread` and the `decorView.postDelayed` (which may lose work).
This issue may be causing some test flakes.

Use a dedicated "main" handler in Maze Runner

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/BackgroundTaskService.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/BackgroundTaskServiceTest.kt

Avoid possible thread starvation when submitting tasks to the `BackgroundTaskService`.
Changed the `BackgroundTaskService` to internally be able to identify its threads. When the result of a `Future` is queried it will first check to see if the task is incomplete `&&` is queued to be executed on the current thread. If so the task is run immediately and the result is returned.
A new unit test was added that causes thread starvation by adding a task to each queue, which then adds a task to the same queue and then blocks on both tasks to await their completion. This triggers a deadlock as the first task waits for itself to complete.

Avoid thread-starvation in BackgroundTaskService

---

features/full_tests/native_crash_handling.feature
features/full_tests/native_throw_crash.feature
features/smoke_tests/04_unhandled.feature
features/steps/symbol_steps.rb

Allow NDK testing with symbolication on Android 7.1 devices.
Stackframes with a file located in `/system_root/*` will no longer be considered "significant" and will be discarded before validating the stacktrace.
Re-enabled all the pending tests on Android 7.1

Fix significant stackframe check for Android 7.1

---

features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXBackgroundNotifyScenario.kt
features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXDelayedCrashScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/InForegroundScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt
features/full_tests/in_foreground.feature

Fix a couple of test flakes and make the fixture output less noisy in some cases.
- Safely get JSON element values in the test fixture to avoid ugly stack traces (if Maze Runner were to change behaviour, for example).
- Trigger scenario actions on the main thread to make times more consistent and avoid flakes in 2 scenarios
- Stop the test fixture polling for commands as soon as a positive action is received, to avoid noisy output in the device log.
Covered by a basic CI run, and I've rerun the flaky scenarios 100 times locally to verify they are fixed (except in the case of  
CXXDelayedCrashScenario which needs more work, but is no worse than it was).

e2e test improvements

---

.buildkite/pipeline.full.yml

Remove trigger of RN tests in the build.
A new mechanism for testing our cross-platform notifiers is being developed and the older mechanism has already been removed from bugsnag-js.
Covered by CI.

Remove trigger of RN tests

---

bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/FeatureFlagScenario.kt

Add a safety null-check to `setStaticJsonData` to avoid a null-deref of `bsg_global_env`.
While it should not be possible based on our standard initialisation path, the additional check aligns the function with our other functions in this path.

Add null-check to native setStaticJsonData

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/featureflags.c

Fix an off-by-one error in the `memmove` call of `remove_at_index_and_compact` (typically seen when calling `addFeatureFlag`).
Relied on existing tests still working as expected

Fix memcpy error when removing or replacing feature flags

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/StringUtils.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/internal/StringUtilsTest.kt

Trim strings nested in complex metadata (nested lists, maps or other collections) when they are over the configured "maximum length".
Introduced a new unit test for `StringUtils` to ensure all the string trimming code is properly covered

Correctly truncate long strings from nested metadata structures

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/cxx-scenarios-bugsnag.cpp
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXRefreshSymbolTableDuringCrashScenario.kt
features/fixtures/mazerunner/cxx-scenarios/src/main/cpp/cxx-scenarios.cpp
features/full_tests/native_crash_handling.feature

Avoid race conditions between the refreshing of the crash-time stack unwinder in the NDK module, and the `refreshSymbolTable` functions.
- `bsg_unwinder_refresh` now completely rebuilds the crash-time stack unwinder and only updates the pointer once the new unwinder is fully initialised.
- `bsg_unwind_crash_stack` localises its reference to the crash-time unwinder upon entry to keep the reference stable.
- `unwinding_crash_stack` is used to ensure that the unwinder used by `bsg_unwind_crash_stack` is not destroyed by a concurrent `bsg_unwinder_refresh`
A new mazerunner scenario was introduced that crashes the app while repeatedly rebuilding the unwinder. This scenario will break (most of the time) if the refresh interferes with the stack unwind. Under manual testing this break happens for …

Avoid race conditions in refreshSymbolTable

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/DataCollectorTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/DataCollectionModule.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStorageModule.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java
bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java
bugsnag-android-core/src/main/java/com/bugsnag/android/LibraryLoader.java
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
bugsnag-android-core/src/main/java/com/bugsnag/android/TrackerModule.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/BackgroundTaskService.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/dag/DependencyModule.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigChangeReceiverTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/DeviceDataCollectorSerializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/DeviceMetadataSerializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventFilenameTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventStoreMaxLimitTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/InternalEventPayloadDelegateTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/LaunchCrashDeliveryTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerPauseResumeTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/internal/BackgroundTaskServiceTest.kt

Allow first-party plugins to access the `BackgroundTaskService` and consider it stable internal API.
Moved the `BackgroundTaskService` to the `internal` package and made it `public` instead of `internal`. Updated use cases and tests.

Move BackgroundTaskService to the internal package

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/Log.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/BugsnagInitScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationFromManifestScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationKotlinScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiThreadedStartupScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt

Report the time taken calling `Bugsnag.start` within the MazeRunner test fixture, by logging the data to the device logs.
Introduced `reportDuration` to measure report the time taken by a tagged block of code. For now this is delivered in the device logs.
Manually checked the reporting in the device logs

Report the duration of Bugsnag.start calls in MazeRunner

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

A repeat of #976 .
Allows tests on Android 6 and 7 to soft fail whilst the secure tunnel outage at BrowserStack is resolved.
Once the outage is resolved and the jobs start running again we should remove the soft fails.
Covered by CI.

Temporary soft fail of tests on Android 6 and 7

---

features/full_tests/breadcrumb.feature
features/full_tests/multi_process.feature
features/steps/android_steps.rb

Avoids a flake in `ErrorBreadcrumbsScenario` where the errors can be received out of order.
Sorts the requests received in that scenario and refactors the existing scenarios that sort requests to use the step available in Maze runner.
Covered by CI (once the device farm starts working again).

Sort received requests to avoid test flakes

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

Remove soft fails for Android 6 and 7 e2e tests.
A persistent problem with the BrowserStack secure tunnel meant that these tests were consistently failing for a number of days.  The problem is now confirmed as fixed and so these soft_fails can now be removed.
Covered by CI.

Remove soft fails for Android 6 and 7 e2e tests

---

features/full_tests/breadcrumb.feature
features/smoke_tests/02_handled.feature
features/steps/android_steps.rb

Fixes the build after `the event has {int} breadcrumbs` was added to Maze Runner, causing a Cucumber ambiguous step error.
Also takes the opportunity to remove `the event has a {string} breadcrumb with the message {string}` in favour of `the event has a {string} breadcrumb name {string}` (no "the"), also already defined in Maze Runner.

Reconcile Cucumber steps

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

Upload each test fixture app to BrowserStack just once, saving time and reducing our exposure to any problems with the upload interface.
Follows the existing pattern on bugsnag-cocoa (and others).  Writing ids to files and uploading at Buildkite artifacts is a little clunky, but it's the nature of the tooling.

Upload e2e test fixtures just once

---

features/full_tests/in_foreground.feature
features/full_tests/native_event_tracking.feature
features/steps/android_steps.rb

Allow a retry for some e2e scenarios in specific situations.
These scenarios are known to be flaky and a ticket exists to investigate further.  This PR uses a feature of Maze Runner to allow a single retry in a specific circumstance - in this case if `"app.inForeground"` is `true`.  If any other difference occurs or the request is not received, then the scenario will fail.
Covered by CI and I ran a scenario multiple times locally to verify what happens on a retry.

Allow a single retry on flaky scenarios

---

docs/MAZERUNNER.md
features/fixtures/mazerunner/app/detekt-baseline.xml
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt

The test fixture is currently hard-coded to reach Maze Runner on [bs-local.com:9339](http://bs-local.com:9339/).  We’re moving to BitBar, so that address will need to change - but also we’re going to use public IP address that we’ll need to determine dynamically.
Maze Runner is being updated to write its address to a “Fixture config” (json) file and push this to the app using Appium.  
This PR updates the fixture app to poll/watch for the arrival of the file and read the Maze Runner address before it continues with what it normally does (poll the command endpoint for stuff to do).
The file is called `fixture_config.json` and will be located in `/sdcard/Android/data/<app package>/files` .  Contents is a simple JSON object:
```
{
"maze_address": "bs-local.com:9339"
}
```
If the config file …

Read mazerunner address from config file

---

CHANGELOG.md

Avoid buffer overruns (and the resulting `SIGSEGV`) when parsing the `/proc/<pid>/maps` files.
Updated our internal `libunwindstack` to a version that checks the length of the buffer when parsing the file. If the end of the buffer is reached while parsing a line, the file is rejected as invalid data.
Manual saturation testing

Avoid running over the end of the `maps` file buffer

---

.buildkite/pipeline.bb.yml
.buildkite/pipeline.bs.yml
.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
docker-compose.yml

Do not attempt to run tests on Android 6 devices on BrowserStack, as they have deprecated them.
BrowserStack have made it clear that they do not intend on maintaining support for Android 6.  I've completely removed the Buildkite steps that run on BrowserStack, but added them to the BitBar pipeline steps with a `soft_fail` so that we can start experimenting with it.
I've also changed the docker-compose service for BitBar to pick up the integration branch on Maze Runner for making BitBar improvements.
Covered by CI and an intermediate build for BitBar.

Remove Android 6 from BrowserStack

---

CHANGELOG.md
bugsnag-plugin-android-ndk/detekt-baseline.xml
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/migrations/EventMigrationV12Tests.kt
bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/featureflags.c
bugsnag-plugin-android-ndk/src/main/jni/utils/seqlock.c
bugsnag-plugin-android-ndk/src/main/jni/utils/seqlock.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_reader.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_writer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/migrate.h
bugsnag-plugin-android-ndk/src/test/CMakeLists.txt
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV11Tests.cpp
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV12Tests.cpp

Avoid reporting feature flags that were corrupted by being modified when a native crash was in progress.
Added a new spin lock structure similar to a sequence-lock to protect the NDK-side feature flags. When altering feature flags its counter value will be odd (strictly `(counter & 1) != 0`) and when no changes are taking place the value will be even (strictly `(counter & 1) == 0`).
The signal handler takes a snapshot of the counter before and after writing the feature flags to the event dump. These two values are compared and a "verification" flag of one byte is written. If this value is zero (invalid) when loading the feature flags, all feature flags for the event are discarded (as they will have been corrupted).
This approach avoids the signal handler possibly having to wait on the …

Fix rare cases of corrupt feature flags in NDK reports

---

features/fixtures/mazerunner/app/detekt-baseline.xml
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/NetworkStatus.kt

Make MazeRunner slightly less network-chatty by checking with the `ConnectivityManager` for the current internet status instead of trying to ping external services.

Check ConnectivityManager for network status

---

features/full_tests/internal_error_reports.feature
features/smoke_tests/01_anr.feature
features/smoke_tests/02_handled.feature
features/smoke_tests/04_unhandled.feature

Relax checks on device orientation to avoid unnecessary flakes.
The device orientation in the test environment can be quite unreliable, as discussed here:
https://www.browserstack.com/docs/app-automate/appium/troubleshooting/app-orientation-issues
Rather rather battle against those factors, it seems more pragmatic to simply allow either portrait or landscape to be present in the field.

Relax checks on device orientation

---

.buildkite/pipeline.bs.yml

Drop testing on Android 4, it's no longer supported by BrowserStack.
Covered by CI.

Drop testing on Android 4

---

docs/RELEASING.md

Update the RELEASING guide inline with our current process:
- Changes to the version number are done on a `release` branch before being merged
- Tagging is done from `master` and as part of creating the GitHub release

Update RELEASING guide to use release branches

---

features/full_tests/auto_notify.feature
features/full_tests/detect_anr_cxx.feature
features/full_tests/detect_anr_jvm.feature
features/minimal/detect_anr_minimal.feature
features/smoke_tests/01_anr.feature
features/support/env.rb

Enable ANR test scenarios on BitBar.
We discovered that the ANR scenarios were not working on BitBar due to the developer options.  They have now been updated and the ANR scenarios pass.
As part of the investigation, I changed the scenarios to go back to tapping the screen rather than pressing the back button.  I don't think it was strictly necessary, but have kept the change in having retested it like that.  I don't think there's really anything between tapping and using the back button anyhow. 
I've also tagged all the ANR scenarios with `@anr` for future convenience.
Retested against BitBar on CI before raising this PR.

Enable ANR test scenarios on BitBar

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/RootDetector.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/RootDetectorTest.kt

Slightly improve the `RootDetector` overhead.
- Use `any` instead of `count() > 0` to early exit when checking the system build-props
- Use a `volatile boolean` instead of `AtomicBoolean` to check library-load (no CAS operations are used)
- Use a `Reader.isNotBlank` function instead of `Reader.readText().isNotBlank()`
Modified the unit test, and added a new test for the `which su` check returning a blank (but not empty) string

Trivial improvements to RootDetector

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/ActivityBreadcrumbCollector.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ActivityLifecycleBreadcrumbTest.kt

Fix [1817](https://github.com/bugsnag/bugsnag-android/issues/1817) by associating the "previous" state with its Activity.
Replace the global "previous" state with a `WeakHashMap<Activity, String>`. When an `Activity.onDestroy` is called the `Activity` is preemptively removed from the map. Since the activity lifecycle callbacks are always invoked from the main thread, access to the `WeakHashMap` is left unsynchronized.
A new unit test was added testing interleaved Activity lifecycles.

Activity breadcrumbs should report their own "previous" state

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java

Metadata is mutable in initial breadcrumb
Metadata is mutable when initialising a client with breadcrumb
A unit test for metadata mutability

Mutability of metadata in initial client with breacrumb

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
features/full_tests/auto_notify.feature
features/full_tests/detect_anr_jvm.feature
features/smoke_tests/01_anr.feature
features/support/env.rb

Skip ANR scenarios on Samsung devices.
Samsung devices behave different in the ANR scenarios and for the time being it's easier to skip those specific scenarios.  We've done that before by skipping "Android 8.1", but that's just because the BS device we used for 8.1 happened to be a Samsung.  This change means we're more intelligent about it.
I've also tweaked the Buildkite labels to better discern between BitBar and BrowserStack steps.
Covered by CI.

Correct skips for ANR scenarios

---

.github/workflows/build.yml
features/full_tests/auto_notify.feature
features/full_tests/detect_anr_cxx.feature
features/full_tests/detect_anr_jvm.feature
features/minimal/detect_anr_minimal.feature
features/smoke_tests/01_anr.feature

No not run any ANR scenarios on Samsungs.
Follow on to #1831, not all ANR scenarios were considered.
Covered by CI.

Do not run any ANR scenarios on Samsungs

---

features/full_tests/strict_mode_violations.feature

Reduce CI noise by skipping a known-flaky test pending further investigation.
Covered by CI.

Skip flaky test "StrictMode Exposed File URI violation"

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/ImmutableConfig.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/dag/ConfigModule.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt

Fallback to using the `dex` signature derived `buildId` when no `BUILD_UUID` metadata is present.
If no `BUILD_UUID` metadata is present when constructing the `ImmutableConfig` we fallback to building the `buildUuid` using the new `DexBuildIdGenerator` class. If for any reason that fails we revert to `null`.
The retrieval of the `dex` signatures is run on the `BackgroundTaskService` IO thread in order to avoid StrictMode violations.
Tested manually with the example app.

Use the DexBuildIdGenerator when no `BUILD_UUID` is present

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

Make sure all Maze Runner CI jobs are consistently set to `--fail-fast`.

Consistently fail fast in e2e tests

---

.buildkite/pipeline.yml
bugsnag-android-core/api/bugsnag-android-core.api
bugsnag-plugin-android-ndk/api/bugsnag-plugin-android-ndk.api
bugsnag-plugin-android-okhttp/api/bugsnag-plugin-android-okhttp.api
bugsnag-plugin-react-native/api/bugsnag-plugin-react-native.api
build.gradle
buildSrc/src/main/kotlin/com/bugsnag/android/BugsnagBuildPlugin.kt
features/fixtures/minimalapp/build.gradle

Add binary compatibility validator to ensure backwards compatibility of the public API surface.
Added the [Kotlin compatibility validator](https://github.com/Kotlin/binary-compatibility-validator) plugin to the build process, and a new step in BuildKite that will fail if the API surface changes.
Manually tested by introducing incompatible changes and checking for expected failure.

Add Binary compatibility validator

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeFileUriExposeScenario.kt

Reduce the changes of flakes in the `StrictModeFileUriExposeScenario` test
Provide a list of "leaky" `Intent`s and attempt to find one that will resolve on the device before attempting to start it. These should reduce the chance that the scenario fails because the `Intent` cannot be resolved against an installed app (although it does not eliminate it entirely).

Reduce flakes in StrictModeFileUriExposeScenario

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/AppDataCollectorTest.kt
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagKotlinTestUtils.kt
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt

Name of installer / vendor package of the app casing the crash/exception can be viewed in the app metadata 
Add Installer package name in the payload and using packageManager to get InstallerPackageName
Unit tests

Installer package name visible on dashboard

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/SharedPrefMigrator.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/SharedPrefMigratorTest.kt

Prevent rare app crash while migrating old `SharedPreferences` data from older versions of `bugsnag-android`.
Added nullable check and catching exception for shared preferences
Additional unit tests

Rare app crash in shared preferences migrator 

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/DataCollectorTest.kt

Prevent DeviceDataCollector crashing the app when the ActivityManager cannot be reached.
Added try and catch for throwable exception.
Additional unit tests

Prevent device data collector may causing a rare app crash while calculating free memory

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationFacadeTest.java
features/full_tests/in_foreground.feature
features/full_tests/native_event_tracking.feature

Reset persist user default value to match with other platforms.
Changed persist user default value to true
Updated the existing tests

Configuration.persistUser should be true by default

---

features/full_tests/in_foreground.feature
features/full_tests/native_event_tracking.feature

Skip flaking e2e tests

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java
gradle/kotlin.gradle

Disable Kotlin's Intrinsic runtime null-checks so that we can continue to migrate more of our codebase to Kotlin without introducing binary-incompatibilities.
Adding kotlin compiler options for disable null checks
Searching disassembled code to ensure that Intrinsics null checks are not included

Disable kotlin null check intrinsics

---

bugsnag-android-core/src/main/java/com/bugsnag/android/internal/ImmutableConfig.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ApiKeyValidationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt

Fix apikey tests 
Attempting to use a null apiKey will throw an IllegalArgumentException during validation
New unit tests

Fix apikey tests

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/InForegroundScenario.kt
features/full_tests/in_foreground.feature

Skip the `InForegroundScenario` on Samsung devices.

Skip the InForegroundScenario on Samsung devices

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Event.java
bugsnag-plugin-android-exitinfo/api/bugsnag-plugin-android-exitinfo.api
bugsnag-plugin-android-exitinfo/detekt-baseline.xml
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/BugsnagExitInfoPlugin.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/ExitInfoCallback.kt
bugsnag-plugin-android-exitinfo/src/test/java/com/bugsnag/android/BugsnagExitInfoPluginStoreTest.kt
bugsnag-plugin-android-exitinfo/src/test/java/com/bugsnag/android/ExitInfoCallbackTest.kt
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_reader.c
bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventOnDiskTests.cpp

Merge tombstone & trace data into BugSnag `Event`s when available.
Introduced `BugsnagExitInfoPlugin` to correlate `ApplicationExitInfo` data with BugSnag `Event`s before they are sent.
Introduce new unit test and manual test on example app

Enhance events with tombstone and trace files in the BugsnagExitinfo plugin

---

bugsnag-plugin-android-exitinfo/detekt-baseline.xml
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/BugsnagExitInfoPlugin.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/TombstoneEventEnhancer.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/TombstoneParser.kt
bugsnag-plugin-android-exitinfo/src/test/java/com/bugsnag/android/TombstoneEventEnhancerTest.kt
bugsnag-plugin-android-exitinfo/src/test/java/com/bugsnag/android/TombstoneParserTest.kt

Users are able to add `Open File Descriptors` into BugSnag `Metadata` when available.
An open file descriptors control to add `Open File Descriptors` from `ApplicationExitInfo` to  BugSnag `Metadata` 
Unit tests and manual test on example app

Adding open file descriptors to metadata

---

bugsnag-plugin-android-exitinfo/api/bugsnag-plugin-android-exitinfo.api
bugsnag-plugin-android-exitinfo/detekt-baseline.xml
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/BugsnagExitInfoPlugin.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/ExitInfoCallback.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/TombstoneEventEnhancer.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/TombstoneParser.kt
bugsnag-plugin-android-exitinfo/src/test/java/com/bugsnag/android/ExitInfoCallbackTest.kt
bugsnag-plugin-android-exitinfo/src/test/java/com/bugsnag/android/TombstoneEventEnhancerTest.kt
bugsnag-plugin-android-exitinfo/src/test/java/com/bugsnag/android/TombstoneParserTest.kt

An option to add log message from Tombstone file to Bugsnag `metadata`.
Add an option in Bugsnag ExitInfo Plugin to parse the log message from Tombstone file and added it to metadata
Introduce new unit test and manual test on example app

Logcat messages to metadata

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/UserStoreTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/SynchronizedStreamableStore.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/UserStore.kt

Warning log would not show when persisted user file is not loaded
Add persisted user file exist checks and config persist user check in when loading user
Manual test and refactor existing tests

Remove Warning log when persisted user file not loaded

---

bugsnag-plugin-android-exitinfo/api/bugsnag-plugin-android-exitinfo.api
bugsnag-plugin-android-exitinfo/build.gradle
bugsnag-plugin-android-exitinfo/detekt-baseline.xml
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/BugsnagExitInfoPlugin.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/ExitInfoPluginConfiguration.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/ExitInfoPluginStore.kt

Make the `ExitInfoPlugin` a little more Java friendly by adding a dedicated `ExitInfoPluginConfiguration` instead of named arguments / defaults in the `ExitInfoPlugin` constructor.
This PR also includes a few minor tidy-ups detailed in the changeset:
- Moved the plugin config to a new `ExitInfoPluginConfiguration`
- Wrapped `ActivityManager` access in a `safeGetActivityManager` method
- Blocked the `protobuf` plugin from including `tombstone.proto` sources in the library resources (which in turn were leaking into release `.apk` files)
- Removed a debug log message that slipped through

Make ExitInfoPlugin config more Java friendly

---

bugsnag-android-core/src/main/java/com/bugsnag/android/internal/ImmutableConfig.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt

Allow opting-out of the BuildUUID generation by manually setting an empty `BUILD_UUID` metadata value.
Added a unit test for the new behavior, and manually tested the process.

Allow opting-out of BuildUUID generation

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/AppDataCollectorTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/ForegroundDetector.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/internal/ForegroundDetectorTest.kt

Move the foreground/background tracking logic from `SessionTracker` to the new `ForegroundDetector` singleton.
Moved the `lastExitedForegroundMs` and `lastEnteredForegroundMs` timestamps out of `SessionTracker` and into `ForegroundDetector`.
This PR also reworks the "background" trigger slightly to avoid the 700ms timeout when the last `Activity` stops (where possible). Now we use [isChangingConfigurations](https://developer.android.com/reference/android/app/Activity#isChangingConfigurations()) when an `Activity` stops to detect whether we expect the `Activity` to (almost) immediately restart. If this is not the case we send the "inBackground" event immediately.
Modified existing tests.

Move foreground logic out of SessionTracker

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/internal_metrics.c

Avoid possible SIGSEGV when `GetStringUTFChars` in `internal_metrics.c`.
- Sanity check the return value of `bsg_safe_get_string_utf_chars` in `notifyAddCallback` and `notifyRemoveCallback`
- Further `NULL` check the `api` name in `bsg_modify_callback_count`
- Limit the `strlen` check against the maximum expected length

Additional null-checks when handling callback names

---

bugsnag-android-core/api/bugsnag-android-core.api
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationKotlinScenario.kt

Remove `Configuration.getLaunchCrashThresholdMs` and `Configuration.setLaunchCrashThresholdMs` as they were marked as deprecated for removal.

Remove deprecated `Configuration.launchCrashThresholdMs`

---

CHANGELOG.md
UPGRADING.md
bugsnag-plugin-android-exitinfo/README.md

Update the CHANGELOG in preparation for the v6 release. This PR also adds a README to the exitinfo module.

Update CHANGELOG for v6

---

CHANGELOG.md
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ConfigSerializer.java
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ConfigSerializerTest.java
dockerfiles/Dockerfile.android-publisher
features/full_tests/strict_mode_legacy.feature

Fix the publishing step by removing the legacy `bugsnag-android-ndk` module (which was previously replaced by `bugsnag-plugin-android-ndk`).
Also removed the flaky "StrictMode Activity leak violation" scenario as it flakes on Android 7 more than it passes, and does not assert that the notifier is working as expected. Instead it was only running on Android 7 & 8, and asserted that the StrictMode violation was *not* being caught by the notifier (as the notifier is incapable of reporting that violation on those platform versions).
The scenario flaked as it has a hard-dependency on the device being able to open a "leaked" file by Intent. When no third-party app is installed to action the leaking intent the scenario flaked. Handling this case within the scenario would exactly mimic the …

Corrections to fix v6 publishing

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.h
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_writer.c

Avoid possible double-free in `setStaticJsonData` when it is called from multiple concurrent threads
- Replaced the standard `const char*` pointer with an atomic pointer in order to ensure that a double `free` is not possible.
- Added a `NULL` check to the result of `strdup`
- Replace the `strlen(data) == 0` with a quicker de reference check
Relied on existing tests as this specific condition has no reliable repro

Avoid possible double-free in `setStaticJsonData`

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp

Avoid any possibility of multiple conflicting native crash handlers or stack-unwinders running concurrently
Stop using `static` fields as the expected values for `atomic_compare_exchange_strong`. When `atomic_compare_exchange_strong` fails it overwrites these with the actual value that was read, given that we exclusively used this with `bool` values, a rapid series of signals (across different threads) could cause the `expected` value to flip resulting any all further `atomic_compare_exchange_strong` operations to start succeeding.
Neither unit testing nor automated testing can reliably reproduce this behavior. So we rely on our existing tests not starting to fail.

Avoid any possibility of multiple conflicting native crash handlers or stack-unwinders running concurrently

---

bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp

Remove the use of `std::string::substr` from `bsg_check_invalid_libname` to avoid possible deadlocks.
Test the characters of the `filename` one at a time instead of using the `string::substr` method, which can allocate a new string to be returned.

Remove the use of `substr` from `bsg_check_invalid_libname`

---

bugsnag-plugin-react-native/proguard-rules.pro

React Native 0.73 has updated AGP to 8.x, which now runs R8 in "full mode" by default. This causes RN projects with Bugsnag to crash, as the current proguard rule for `BugsnagReactNativePlugin` (`-keepnames`) is not sufficient to prevent the class from being obfuscated.
Updated the proguard rule to use `-keep` instead of `-keepnames`
Tested manually on a React Native project. Test fixtures for `@bugsnag/react-native` will also be updated to enable Proguard once this fix is released.

Update proguard rules for React Native plugin

---

bugsnag-plugin-react-native/proguard-rules.pro

Update proguard rules for React Native plugin (v5)

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt
examples/sdk-app-example/app/build.gradle
gradle.properties

* Fixed proguard-consumer rules in `bugsnag-plugin-react-native` for ReactNative 0.73
[#1963](https://github.com/bugsnag/bugsnag-android/pull/1963)

Release v5.32.1

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagEventMapper.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/JsonWriter.java
bugsnag-android-core/src/test/java/com/bugsnag/android/JsonWriterTest.java

Avoid creating invalid / incomplete event payloads when metadata includes non-finite values (typically via ReactNative).
The non-finite double values (`NaN`, `-Infinity` and `+Infinity`) are now omitted (along with any associated keys) instead of throwing an `IllegalArgumentException`
Adjusted the existing unit tests.

Handle NaN & Infinity values in serialization

---

CHANGELOG.md
bugsnag-plugin-android-exitinfo/detekt-baseline.xml
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/ExitInfoCallback.kt
bugsnag-plugin-android-exitinfo/src/test/java/com/bugsnag/android/ExitInfoCallbackTest.kt
features/fixtures/mazerunner/bugsnag-dependency.gradle
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/ExitInfoScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/BugsnagConfig.kt
features/full_tests/exit_information.feature
features/full_tests/usage.feature

Introduce application exit reason and process importance to BugSnag-ExitInfo Plugin for android 11+ devices and displayed on dashboard under metadata app.
Decoded application exit reason and process importance to strings for app metadata
New unit tests and end to end test

Record process importance for jvm android errors

---

bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NativeEventDecoder.kt
bugsnag-plugin-android-ndk/src/test/java/com/bugsnag/android/NativeEventDecoder64bitTest.kt
bugsnag-plugin-android-ndk/src/test/java/com/bugsnag/android/NativeEventDecoderTest.kt

Decoded C layer `bsg_notifier `and `bsg_app_info` into event `AppWithState` and `Notifier` in Kotlin.
Adding netive decoders for bsg_notifier `and `bsg_app_info` to `AppWithState` and `Notifier` in `Event`
Introduced new tests

Decode bsg notifier and app info into event

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoSessionSmokeScenario.kt
features/smoke_tests/03_sessions.feature

Adds two checks that were missing from a test scenario.
The checks are essential to the test, which is designed to verify that the error report context reflects the Activity that is changed to.

Add missing test expectations

---

.github/workflows/downstream_updates.yml

For whatever reason this wasn't corrected on this branch, and is required for any v5 releases made.

Update the downstream updates action to match the 'next' version

---

CHANGELOG.md
bugsnag-plugin-android-anr/src/main/jni/anr_handler.c

Avoid possible crashes in the ANR handler where the local reference table is exhausted.
Replaced the use of `DeleteLocalRef` with `PushLocalFrame`/`PopLocalFrame` to simplify the handling of the local references.
Manually tested and relied on existing tests

Avoid possible crashes in the ANR handler where the local reference table is exhausted

---

.github/workflows/codeql.yml

It seems that [v2.16.4](https://github.com/github/codeql/releases/tag/codeql-cli%2Fv2.16.4) of the CodeQL library for C++ caused a problem for our autobuild. I've disabled it for now with a ticket to reenable in due course.
Also bumped the CodeQL actions to v3 to silence deprecation warnings.

build: bump CodeQL actions to v3

---

features/steps/android_steps.rb

Prevent test runs from failing due to timeouts with tap/press operations during an ANR.  The press seems to work anyway.
I've also changed `tap` to `press` as the Appium docs seemed to suggest that it works in more cases.
Covered by CI.

Rescue error from Appium press operation during ANRs

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmAnrOutsideReleaseStagesScenario.java
features/full_tests/auto_notify.feature
features/full_tests/detect_anr_jvm.feature
features/steps/android_steps.rb

Rescue failures when calling the Appium `terminate_app` routine, caused when Android already terminated the app.

Guard against errors when terminating the app in e2e tests

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
Gemfile
Gemfile.lock
bugsnag-plugin-android-ndk/src/main/jni/utils/seqlock.h

Refresh the CI pipeline to use our new, more-performant, CI build servers running macOS 14.
We need to bump the License Finder as the new servers use Ruby 3 by default.  A newer version of clangformat also meant making a small formatting change.

Move CI steps to macOS 14 build servers

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/FeatureFlags.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/FeatureFlagsTest.kt

Avoid making defensive copies of the feature flags on the notifying thread (unless they are altered in an `OnErrorCallback`).
Replaced the `LinkedHashMap` with a Copy-On-Write data structure. To avoid multiple levels of locking, and the need for iterators this is a simple encapsulated array which is copied each time a change is required.
The new implementation is slower when adding & removing feature flags (since each addition or removal is now O(n) rather than O(1)), but since there are relatively few feature flags added per run (<1000) this should be a reasonable trade-off as now the feature flags do not need *any* synchronization or defensive copying when an error report is required.
Additional tests for the new implementation and existing tests still pass.

Don't copy FeatureFlags on the crashing thread

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/ObjectJsonStreamer.kt

Reduce the overhead of constructing `ObjectJsonStreamer` instances (and therefore leaving complex breadcrumbs) by sharing the default `redactedKeys` (which is immutable).
An `ObjectJsonStreamer` is allocated internally each time a breadcrumb metadata item needs to be JSON encoded early (because it is too complex for the NDK layer to handle directly). Each of these was causing the default `redactedKeys` pattern to be compiled. Since the default `redactedKeys` set is immutable, it can be safely shared instead.

Avoid compiling regexes in ObjectJsonStreamer

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp

Avoid possible double-free in `bugsnag_refresh_symbol_table` by protecting it with a soft-lock. 
Protected the `bugsnag_refresh_symbol_table` by wrapping it with a soft-lock. Concurrent calls to `bugsnag_refresh_symbol_table` will now be ignored (no-op).
Manually tested & relied on existing tests.

Avoid possible crash in refresh symbol table

---

CHANGELOG.md
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadDeserializer.java
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ThreadDeserializerTest.kt

Allow ReactNative apps to report the thread id as either a number or string.
Don't assume the type of the `thread.id` fields reported by ReactNative, and simply call `toString()` on the resulting object.
New unit testing for both String and Long based thread IDs

ReactNative: Allow strings or numbers to be used for thread-id

---

bugsnag-plugin-android-ndk/src/main/jni/internal_metrics.c

Extra null checks for NDK internal metrics to prevent a potential issue happens when next event is null.
Added event null checks in NDK internal metrics class

fix(test) null check for NDK internal metrics

---

features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/UnhandledExceptionEventDetailChangeScenario.kt
features/full_tests/error_callback_alters_fields.feature

Validates all fields on an event can be altered in an OnErrorCallback.
A new scenario to change all the changeable fields in an event and validated it in an end to end test
Introduce new end to end test

Validate all fields on an Event can be altered in an OnErrorCallback

---

bugsnag-android-core/src/main/java/com/bugsnag/android/Session.java
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTest.kt

Reduce use of Atomics in Session, so the value is more accurate syncing between multiple threads. 
Change autoCaptured type from AtomicBoolean to volatile boolean since it does not use specific atomic method.

Reduce use of Atomics in Session

---

bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c

Small reduction in overhead when leaving breadcrumbs: use integers to represent the `BreadcrumbType` instead of strings.
While the string values for `BreadcrumbType` on the Java/Kotlin code were constants, they required a call to `GetStringUTFChars` and `strcmp` to evaluate which enum value to use.
The new implementation uses an exhaustive `when` which means:
- the transfer values are not sensitive to the ordering of the `enum` values (as `ordinal` would be)
- any adding or removing of `enum` values will cause compiler failures

Don't use strings for `BreadcrumbType` in NDK

---

CHANGELOG.md
bugsnag-plugin-android-ndk/proguard-rules.pro
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/OpaqueValue.kt
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.h
bugsnag-plugin-android-ndk/src/main/jni/metadata.c

Remove the allocation of an `ArrayList` when copying the metadata for breadcrumbs.
The NDK `bsg_populate_crumb_metadata` method now uses the `Map.entrySet.iterator()` instead of first copying the keys to an `ArrayList` and then iterating over that (using `Map.get` for the values). While this is a relatively trivial overhead reduction, it has the added benefit that most `Map` implementation optimize this form of iteration, and avoid the allocation overhead of the `ArrayList`.
Manual testing, and relied on existing end to end tests.

NDK: Iterate over breadcrumb metadata keys directly

---

bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.kt

Replaced failed delivery internal reports with more effective error information 
Removed the error report when a file is not (de)serialized correctly and replaced it with a logger error message. 
Existing tests

Remove Failed delivery internal reports

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
features/full_tests/detect_anr_jvm.feature
features/full_tests/multi_process.feature

Add end-to-end tests for Android 14.
An ANR test has also also been amended, unrelated to the addition of Android 14.  It had been causing Appium issues with Android 8 for some time.
Scenario `Unhandled JVM error` has also been skipped pending further investigation - it's flaked occasionally for a while, but now seems to fail consistently on Android 14.

Add Android 14 tests

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
Makefile
features/fixtures/mazerunner/app/build.gradle
features/fixtures/mazerunner/app/detekt-baseline.xml
features/fixtures/mazerunner/app/proguard-rules.pro
features/fixtures/mazerunner/app/src/main/AndroidManifest.xml
features/fixtures/mazerunner/build.gradle
features/fixtures/mazerunner/cxx-scenarios-bugsnag/build.gradle
features/fixtures/mazerunner/cxx-scenarios-bugsnag/detekt-baseline.xml
features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/AndroidManifest.xml
features/fixtures/mazerunner/cxx-scenarios/build.gradle
features/fixtures/mazerunner/cxx-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/cxx-scenarios/src/main/AndroidManifest.xml
features/fixtures/mazerunner/gradle.properties
features/fixtures/mazerunner/gradle/wrapper/gradle-wrapper.properties
features/fixtures/mazerunner/jvm-scenarios/build.gradle
features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/AndroidManifest.xml
features/smoke_tests/02_handled.feature
features/smoke_tests/04_unhandled.feature

The MazeRunner test fixtures can be built with AGP 8.3.2 to ensure we remain compatible.
Update AGP, Gradle and okhttp version
Existing end to end tests

Update AGP and related versions for mazerunner

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java

Discard the first automatic session when sessions are mixed with manual session
Changing the logic for discarding session method
unit tests

Fixed the logic of discarding session

---

.buildkite/pipeline.yml
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/StrictModeViolationTest.kt
scripts/run-connected-checks.rb

We've had to remove our instrumentation tests from github actions for a variety of reasons.  This change adds a script which should add Android Virtual Devices and SDKs to our MacOS test boxes as required, using them to run the instrumentation tests.  The version of android we're testing against is determined by the API_LEVEL environment variable, which should allow us to run against several different API levels if we see the need to.
It's successfully completed several test runs, and a [negative test run](https://buildkite.com/bugsnag/bugsnag-android/builds/11382#018faa41-5ed4-4b38-83d7-7f79fafa9f8b/62-1093) to ensure the script failed successfully.

Reinstate instrumentation tests using MacOS test boxes as a platform

---

CHANGELOG.md
bugsnag-android-core/src/main/CMakeLists.txt
bugsnag-plugin-android-anr/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
examples/sdk-app-example/app/CMakeLists.txt
scripts/run-cpp-check.sh

Add support for Android 15 when running with a 16kB page size.
Manually tested with the Android 15 16kB AVD images.

Support Android kernels running with a 16kB page size

---

CHANGELOG.md
bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt

Avoid a crash if the `bugsnag-plugin-android-anr.so` library failed to load, when attempting to set the stack unwinder function.
Manually tested by removing the bugsnag-plugin-android-anr.so from a build

Only set ANR unwind function if the bugsnag-plugin-android-anr.so was loaded successfully

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/OomScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/UnhandledJavaLoadedConfigScenario.java

Fixed flaky end to end scenario
Set the `enabledErrorTypes.anr` false in configuration
Existing tests

Disable anr in flaky scenario

---

bugsnag-plugin-android-ndk/src/main/jni/internal_metrics.c

Backport the `NULL` checks in `internal_metrics.c` to v5

Backport: null check for NDK internal metrics (#2012)

---

bugsnag-android-core/proguard-rules.pro

Don't crash apps on startup where the `enum.values()` functions are not included in the `keep` list by default. Fixes #2048 
Included specific Proguard consumer rules for `Telemetry.values()` and `ErrorType.values()`, ensuring that these members are not removed or obfuscated.
Manually tested with app using fully customized Proguard rules.

Proguard rules for ErrorType & Telemetry.values()

---

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/EventDeserializerTest.kt
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestHooks.java

Allow ReactNative apps to add correlation metadata to `Event`s
Attempt to decode and set the `traceId` & `correlationId` when they are both available and valid.
Added new fields to the existing unit tests

Add support for the `correlation` field for ReactNative

---

dockerfiles/Dockerfile.android-publisher

Correct the publishing step by copying the correct `build.gradle.kts` file.

Correctly copy `build.gradle.kts` instead of the old `build.gradle` during publishing

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/ActivityBreadcrumbCollector.kt
features/smoke_tests/03_sessions.feature

Include some more `Intent` metadata in `Activity.onCreate` breadcrumbs to help debugging.
When logging `onCreate` breadcrumbs we now selectively add the following to the breadcrumb metadata:
- [Intent.action](https://developer.android.com/reference/android/content/Intent#getAction())
- [Intent.categories](https://developer.android.com/reference/android/content/Intent#getCategories())
- [Intent.type](https://developer.android.com/reference/android/content/Intent#getType())
- [Intent.flags](https://developer.android.com/reference/android/content/Intent#getFlags())
- [Intent.identifier](https://developer.android.com/reference/android/content/Intent#getIdentifier())
- The keys of extras (no values are included)
We don't log the `Intent.data` as it would be too easy to leak sensitive data. …

Include useful Activity.intent info in onCreate breadcrumbs

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/internal_metrics.c

Avoid racing ourselves during multi-threaded startups.
`request_env_write_lock` now returns the `bsg_environment*` that should captured locally and addressed. If the method returns `NULL` the lock is not acquired (released before returning) so null-checks on the returned `bsg_environment*` can exit immediately (after basic cleanup) without being concerned with releasing the lock.

Ensure NDK environment is properly initialized before using it

---

CHANGELOG.md
bugsnag-android-core/api/bugsnag-android-core.api
bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagEventMapper.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Error.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Event.java
bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Stacktrace.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.java
bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadInternal.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorSerializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/StacktraceSerializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/StacktraceTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadDeserializationTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadFacadeTest.java
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ErrorDeserializer.java
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/NativeStackDeserializer.java
bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadDeserializer.java
bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ThreadSerializerTest.java

Open up more Event model APIs, that users can add new Errors, Threads, and leave breadcrumbs at an `Event` level.
The `Event` class includes new methods to:
- add a new `Thread` object to the `Event`
- add a new `Error` object to the `Event`
- leave additional `Event` level breadcrumbs
The `Error` and `Thread` classes include new methods to add `Stackframe`s.
New unit tests added.

More open Event model

---

.github/workflows/downstream_updates.yml

Adds bugsnags flutter, JS (RN), and unreal repos to the bumpsnag workflow, to update them when a new version of the notifier is released.

Add other downstream repos for automatic updates

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbState.kt
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_writer.c

Stop NDK breadcrumbs from being dropped due to invalid timestamps.
Manually tested that the correct timetstamp is used. Also added to existing unit tests to assert the timestamp is as expected.

Restored the expected timestamp format to NDK breadcrumbs

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
docker-compose.yml

Send Maze Runner test results to Buildkite TestAnalytics.
1. Output tests results from Maze Runner in Junit XML format using the `--format` option (has to be given twice to avoid losing the default `pretty` output).
2. Use the `test-collector` Buildkite pluging to send the results on - this needs the API key to be set in the `BUILDKITE_ANALYTICS_TOKEN` environment variable, which I've done in our s3 bucket.
I've run a full build to make sure I've not broken the pipeline YAML, but it can't be tested fully until it's on `next`.

Send e2e test results to Buildkite TestAnalystics

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/ForegroundDetector.kt

Avoid startup ANRs in apps that have slow startups where sending the fixed 2 second timeout can cause the overall startup time to be long enough that an ANR will be reported.
The startup crash timeout is now calculated based on the amount of time the startup has already taken. The flush timeout is now a *maximum* of 2 seconds (and a minimum of `0`).
Manually checked the calculated timeouts, otherwise relying on existing tests.

Flexible timeout for EventStore.flushOnLaunch

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.kt

Use a reasonable timeout for startup crash delivery in cases when `Bugsnag.start` is called long after the app start.
If the startup crash synchronous timeout would be `<=0` we revert to the old behavior and block for up-to a full 2 seconds.
Relied on the existing tests being more reliable.

Startup timeout fixes

---

CHANGELOG.md
bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/ActivityBreadcrumbCollector.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/ActivityLifecycleBreadcrumbTest.kt

Fix #2082 by wrapping the `Intent.getExtras()` in a `try {} catch {}`
Introduced a new unit test to cover this specific case.

Work around NPEs from `Intent.getExtras`

---

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/FileStoreTest.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/SessionStore.kt

The function had a fairly high overhead, making several copies of the list of files. The goal was to reduce this.
- Return earlier if the number of files is less than the maxStoreCount (previously this wasn't checked until a second copy of the list had already been made)
- Sort the first file list by last modified timestamp, instead of copying into a list and then sorting
- Tests already written for this function are still applicable
- Tested this locally

Simplifying discardOldestFileIfNeeded function

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/event.h
bugsnag-plugin-android-ndk/src/main/jni/handlers/cpp_handler.cpp
bugsnag-plugin-android-ndk/src/main/jni/handlers/signal_handler.c
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_writer.c
bugsnag-plugin-android-ndk/src/main/jni/utils/threads.c
bugsnag-plugin-android-ndk/src/main/jni/utils/threads.h
features/smoke_tests/04_unhandled.feature

Identify the error reporting thread in native crashes
Introduced the error reporting thread boolean marker to the `bsg_thread` structure, and attempt to match the TID with the currently running thread (within the signal handler & C++ exception handler).
Additional steps added to the existing native smoke test

Identify the error reporting thread in native crashes

---

bugsnag-plugin-android-okhttp/src/main/java/com/bugsnag/android/okhttp/OkHttpDelivery.kt
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MazerunnerApp.kt
features/fixtures/mazerunner/jvm-scenarios/detekt-baseline.xml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/OkHttpDeliveryScenario.kt

Reduce flakes for OkHttpDeliveryScenario
- Turn off StrictMode for the OkHttpDeliveryScenario.
- Adjusted the StrictMode penalty for the MazeRunner fixture to also log any StrictMode violations
Relied on the existing tests passing with fewer flakes.

Reduce flakes for OkHttpDeliveryScenario

---

bugsnag-android-core/CMakeLists.txt
bugsnag-plugin-android-anr/CMakeLists.txt
bugsnag-plugin-android-ndk/CMakeLists.txt
buildSrc/src/main/kotlin/com/bugsnag/android/BugsnagBuildPlugin.kt
buildSrc/src/main/kotlin/com/bugsnag/android/Versions.kt
dockerfiles/Dockerfile.android-common
features/fixtures/mazerunner/cxx-scenarios-bugsnag/CMakeLists.txt
features/fixtures/mazerunner/cxx-scenarios/CMakeLists.txt

Bump CMake to version 3.22.1, and minimum required version to 3.19.
Also added the missing `project` directives to CMake will stop warning about them.

CMake version bump

---

bugsnag-plugin-android-exitinfo/src/androidTest/java/com/bugsnag/android/BugsnagExitInfoPluginStoreTest.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/BugsnagExitInfoPlugin.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/ExitInfoPluginStore.kt

Simplify the use of the `ExitInfoPluginStore` by retaining the data in-memory instead of constantly reloading from disk.
Modified existing tests to match the new fields & behaviour

In-memory ExitInfoPluginStore

---

.github/workflows/signing.yml

Adds a workflow that will:
- Download all assets from a given release (set automatically when triggered by a release)
- Create a signature for each asset using our platforms release GPG key
- Confirm that signatures are correct for the asset and key
- Upload the signatures to the release
[A test run can be observed here](https://github.com/Cawllec/node-listener/actions/runs/11839817383/job/32992184486), and [the outcome of the test run can be observed here](https://github.com/Cawllec/node-listener/releases/tag/v1.0.0).  Note that these did not use our platforms release key.
For full testing this will need to be merged and then manually run against a previous release.

Adds signing workflow for releases

---

.github/workflows/codeql.yml
.github/workflows/downstream_updates.yml
.github/workflows/signing.yml
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.kt
bugsnag-plugin-android-exitinfo/api/bugsnag-plugin-android-exitinfo.api
bugsnag-plugin-android-exitinfo/detekt-baseline.xml
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/ApplicationExitInfoMatcher.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/BugsnagExitInfoPlugin.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/CodeStrings.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/EventSynthesizer.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/ExitInfoCallback.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/ExitInfoPluginConfiguration.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/InternalHooks.java
bugsnag-plugin-android-exitinfo/src/test/java/com/bugsnag/android/ExitInfoCallbackTest.kt
dockerfiles/Dockerfile.android-common
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/BugsnagConfig.kt
scripts/copy-build-files.rb

Discard event should not be synthesize.
Added a DiscardEventCallback before ExitInfoCallback so the discarded event would not be synthesized.
Existing tests

Do not synthesize discarded events

---

bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/EventSynthesizer.kt

Minor cleanup of the metadata added to synthesized events.

Don't report PSS/RSS to events when they are <=0

---

.buildkite/block.step.yml
.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
scripts/copy-build-files.rb

General tidy-up of the Buildkite pipeline to:
- Ensure all steps have an adequate but not excessive timeout
- Agent queues are explicitly stated in each file (even if a default is used)
- Generic `macos` queue is used instead of specfic macOS versions where possible

Pipeline tidyup

---

.github/workflows/signing.yml

Reduces the default permissions of the github token to read only

Restrict permissions of default github token in signing workflow

---

.github/workflows/codeql.yml
.github/workflows/scorecard.yml

Bump the version of the `upload-artifact` action for SSF Scorecard to latest to avoid sunsetting of v3.

build(scorecard): bump upload action

---

bugsnag-android/build.gradle.kts

Correct the release scripts (adding the `release` script to the `bugsnag-android` meta-module).
Tested with local publishing

Add license-check and release to the bugsnag-android module

---

Makefile
scripts/bump-version.sh

make bump does no verification of the version syntax, allowing us to accidentally bump to version strings that Gradle cannot order / match and potentially breaking our recommended com.bugsnag:bugsnag-android:5.+ syntax.
Added regex version checking for major.minor.patch on make bump.

Update makefile version checking

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NdkPlugin.kt

First-party pull request for https://github.com/bugsnag/bugsnag-android/pull/2124
Make NdkLinkError and AnrLinkError reports consistent.
The commit 2f5a951 (PR #2070) already added metadata to AnrLinkError, so do the same for NdkLinkError.
Add additional metadata to the bug report of NdkLinkError.

add NdkLinkError to metadata

---

.github/workflows/codeql.yml

Upgrade the CodeQL GitHub Action base image to the latest `ubuntu` runner.
- Updated the image to `ubuntu-24.04`
- Changed the Java version to 17
- Setup CMake 3.22.1

GHA runner upgrade

---

CHANGELOG.md

Retrospectively modified the changelog entry to link to the online docs for the new ANR event synthesising.

docs(changelog): retrospective change of 6.11 to point at online docs

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
features/fixtures/mazerunner/app/build.gradle
features/fixtures/mazerunner/build.gradle
features/fixtures/mazerunner/cxx-scenarios-bugsnag/build.gradle
features/fixtures/mazerunner/cxx-scenarios/build.gradle
features/fixtures/mazerunner/jvm-scenarios/build.gradle
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/UnhandledExceptionEventDetailChangeScenario.kt
features/full_tests/internal_error_reports.feature
features/full_tests/load_configuration.feature
features/smoke_tests/01_anr.feature
features/smoke_tests/02_handled.feature
features/smoke_tests/03_sessions.feature
features/smoke_tests/04_unhandled.feature
features/steps/android_steps.rb

Update AGP and compileSdk version for running android 15 devices
AGP version "8.6.1"
compileSdk version "35"
minSdk version "17"
pipeline tests

update AGP and compileSdk versions

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/handlers/signal_handler.c
features/full_tests/native_crash_handling.feature
features/full_tests/native_signal_raise.feature

Show corresponding signal code for native crashes
Added a table of signal code descriptions for error messages, covering all of the defined signal codes. Having all of the messages pre-generated (via a macro) we avoid possible overflows and undefined behaviour that could occur when generating the error message from within the signal handler.
Existing e2e tests

Report signal codes on native crashes

---

bugsnag-android-core/detekt-baseline.xml
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStorageModule.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java
bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
bugsnag-android-core/src/main/java/com/bugsnag/android/internal/FileQueue.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EmptyEventCallbackTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EmptyJsonObject.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventFilenameTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventStoreMaxLimitTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/LaunchCrashDeliveryTest.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/internal/FileQueueTest.kt
bugsnag-android/build.gradle.kts

Improve the consistency and simplify the implementation of `EventStore`.
Rather the maintaining a secondary in-memory queue within the state of `FileStore` (effectively leaking logic from the processing threads into the object state) we now have a `FileQueue` class which internalises the locking and processing, so processing the files is always done within the context of the `FileQueue` - leading to better consistency that should also be easier to reason.
Where previously retrieving the list of enqueued files would cause `FileStore` to "remember" which files were being processed, `FileStore` requires that a lambda be passed to process files within the queue. This means that the `FileQueue` controls any locking and consistency directly during file processing, rather than relying on the …

Simplify EventStore logic

---

CHANGELOG.md
bugsnag-plugin-android-exitinfo/build.gradle.kts
features/full_tests/startup_anr.feature

Upgrade the version of `protobuf-lite`.

dep: protobuf bump

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

Skip ANR test jobs on Android 10 - all ANR scenarios are skipped on Android 10 anyway.
Covered by CI.

Skip ANR test jobs on Android 10

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/EventPayload.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EventPayloadTrimTest.kt

Trim event threads if the size is  too large
Threads are now be trimmed less equal config `maxReportedThreads`  in `EventPayload` 
Introduced a new unit test to cover `EventPayload.trimToSize`

Trim excess threads onSend

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/NativeJsonSerializeTest.kt
bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/BSG_KSCrashStringConversion.c
bugsnag-plugin-android-ndk/src/test/cpp/main.c
features/support/env.rb

Fix an error in the day/date calculation that runs as part of the NDK crash reporting and is used to format the device time.
Manually tested & introduced new unit tests to cover the edge cases (including a full 20years of formatting in 6 hour increments - ignored for CI).

Fix crash-time date calculation

---

features/steps/android_steps.rb
features/support/env.rb

Ensure that Appium driver failures are handled and reported by Maze runner by using the Appium API methods where implemented (rather than `Maze.driver` directly). 
Some uses of `Maze.driver` remain as they have not yet been implemented in the MR API.  These will be swapped out in due course.

Use Appium API methods where implemented

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/LibraryLoader.java

Work around possible `System.loadLibrary` race conditions by retrying native library loads exactly once if they fail.

LibraryLoader will retry System.loadLibrary exactly once

---

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldSessionScenario.kt
features/full_tests/native_session_tracking.feature

Fixes a couple of e2e test flakes:
- `CXXSessionInfoCrashScenario` will perform the same sequence of notifying errors and causing a crash after the relaunch, because it hangs off of session delivery, so I've updated the scenario to simply expect the additional two handled errors (the 2nd unhandled error is of course not sent because the fixture is not relaunched a second time).
- `DiscardOldSessionScenario` was flaking due to a `NullPointerException` caused when the `bugsnag/sessions` folder had not yet been created.  I've changed the condition to simply retry if null.
Covered by CI.

e2e test flake fixes

---

.buildkite/pipeline.full.yml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldSessionScenario.kt
features/full_tests/native_session_tracking.feature
features/full_tests/naughty_strings.feature
features/full_tests/startup_anr.feature
features/support/env.rb

Add testing on Android 15.
Follows the existing pattern of using BrowserStack for ANR scenarios and BitBar for the rest.  The Android 15 devices we have on BitBar are a little limited currently, but I have asked for some more to be added.

Add testing on Android 15

---

scripts/run-connected-checks.rb

The instrumentation tests fail because the AVD does not boot in 60 seconds. I've increased the timeout to 120 seconds, enough time for the AVD to boot.
Covered by CI

Increase AVD timeout to 120s to cover increased startup time

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java
bugsnag-plugin-android-exitinfo/detekt-baseline.xml
scripts/run-connected-checks.rb

Allow the metadata in leaveBreadcrumb to be null rather than enforcing non-null , aligning `bugsnag-android` with our other SDKs.
Updated existing test

Metadata in leaveBreadcrumb should be nullable

---

bugsnag-android-core/api/bugsnag-android-core.api
bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java
bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java
bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/InternalHooks.java
features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/BugsnagInternals.java

Reduce the chances of ANRs during normal startup on devices with slow I/O.
Moved the `EventStore` blocking to as late as possible during startup to allow more time for devices with slow I/O.
Replied on existing tests as the change should be transparent

Background EventStore start

---

.buildkite/pipeline.yml

Due to issues with running multiple AVD instances on the same box, its best if we move that step to the isolated queue to prevent the steps from erroring when multiple tests are running on the same box.
Covered by CI

Isolate CI step that used AVD

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c

Ensure that the initial `bugsnag_env` allocation is successful before attempting to populate it.
Relying on existing tests.

Check init malloc failure

---

CHANGELOG.md
bugsnag-android-core/api/bugsnag-android-core.api
bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt
bugsnag-android-core/src/main/java/com/bugsnag/android/EndpointConfiguration.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/EndpointConfigValidationTest.kt

Set default endpoints based on API key. If no endpoint is configured, payloads should be sent to `*.insighthub.smartbear.com` if the API key starts with `00000`.
- changed ConfigInternal.kt to return the correct defaults based on api key if no custom endpoints have been configured.
- added comparison methods to EndpointConfiguration class to ensure unit tests compare the values of the endpoints inside rather than the objects. 
Added unit tests

Set default endpoints based on API key

---

CHANGELOG.md
bugsnag-plugin-android-exitinfo/detekt-baseline.xml
bugsnag-plugin-android-exitinfo/src/main/java/com/bugsnag/android/BugsnagExitInfoPlugin.kt

Avoid timeouts and crashes stemming from rate limiting or slow IPC calls when using `setProcessStateSummary` in the ExitInfo Plugin.
The `SessionCallback` now uses the `BackgroundTaskService` to enqueue the call to `setProcessStateSummary` and further swallows any exceptions raised by the call.

Safer setProcessStateSummary in ExitInfo plugin

---

CHANGELOG.md
bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp

Improve the capturing of the `.so` build-id when unwinding native stacks.

Properly scope the build-id capturing in the stack_unwinder

---

CHANGELOG.md
bugsnag-plugin-android-ndk/api/bugsnag-plugin-android-ndk.api
bugsnag-plugin-android-ndk/build.gradle.kts
bugsnag-plugin-android-ndk/src/main/CMakeLists.txt
bugsnag-plugin-android-ndk/src/main/exported_native_symbols-RelWithDebInfo.txt
bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt
bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.c
bugsnag-plugin-android-ndk/src/main/jni/jni_cache.h
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/com/bugsnag/android/gradle/GenerateJNILinkTableTransform.kt
buildSrc/src/main/kotlin/com/bugsnag/android/gradle/JNILinkTablePlugin.kt

Avoid lazy-linking the JNI functions in `bugsnag-plugin-android-ndk`.
This PR introduces a small Gradle plugin to `buildSrc` that generates the JNI natives lists as header files which are `#include`d into `bugsnag_ndk.c`. The plugin means that the Kotlin `external`s and the native code are guaranteed to be in-sync and no new functions can be introduced without their implementation.
Using `JNI_OnLoad` and `RegisterNatives` also helps improve reliability because the entire module will either load, or not load. So we cannot suffer from spurious `LinkError`s when unlinked function cannot be called due to a failed loading of some kind.
Manually tested failure modes, and relied on existing tests.

Use JNI_OnLoad to link the NDK plugin

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

BrowserStack are removing the last of their Android 7 devices, so moving the ANR tests to BitBar.
The ANR tests had been moved to BS in the past due to problems running them on on BB (I forget why exactly), but so far they are running well.  For now I have kept the ANR scenarios in their own Buildkite job as they do tend to be flakier, but in principle we may be able to reunite them with the bulk of the tests in future.

Move Android 7 ANR tests to BitBar

---

docker-compose.yml
dockerfiles/Dockerfile.android-common

Update the `android-publishing` dockerfile with a compatible JDK, and newer versions of the required tooling.
- the platform tools have been upgraded in the publishing image
- excess versions have been removed

Update release dockerfiles

---

.buildkite/pipeline.full.yml

Only use Buildkie plugins once per step, removing a warning that later steps will be ignored in a future version of the agent.
Verified by review only - not easily tested in advance of the next release.

Only use Buildkite plugins once per step

---

CHANGELOG.md
bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java
bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt
bugsnag-android-core/src/test/java/com/bugsnag/android/AppMetadataSerializationTest.kt
bugsnag-android-core/src/test/resources/app_meta_data_serialization_0.json
bugsnag-android-core/src/test/resources/app_meta_data_serialization_1.json
features/smoke_tests/02_handled.feature
features/smoke_tests/04_unhandled.feature

Stop reporting the `app.lowMemory` and `app.memoryTrimLevel` attributes when they are not reported by the OS. Newer versions of Android have deprecated these callbacks, and removing the attributes (unless the callbacks have been triggered) reduces the amount of metadata and noise.
Updated existing unit tests and end-to-end tests.

Do not report `lowMemory` or `memoryTrimLevel` when not available

---

CHANGELOG.md
bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.kt

Fix rare `"Comparison method violates its general contract!"` crashes in `discardOldestFileIfNeeded` when the file timestamps change during the `sort()`.
Capture all of the `lastModified()` timestamps into a stable list before sorting.

Change to discardOldestFileIfNeeded sorting

---

features/steps/symbol_steps.rb

Resolve a common flake caused by incorrect detection of out of project frames.
If a `!` is present in the stackframe file, `symbolicate` was only passing everything after it to `is_out_of_project?`.  But that function expects to receive the whole path to detect out of project frames correctly.  This was causing the `Stack buffer overflow` scenario to flake.  Sometimes the frame is provided as:
```
/apex/com.android.runtime/lib64/bionic/libc.so
```
and sometimes (the flaky case) it is:
```
/apex/com.android.runtime/lib64/bionic/libc.so!libc.so
```
I've also fixed a few style errors highlighted by my IDE.

Correct detection of out of project frames in e2e tests

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/AnrHelper.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/BugsnagConfig.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationFromManifestScenario.kt
features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationKotlinScenario.kt
features/full_tests/usage.feature

Fixes a flake in e2e tests where a test scenario expects there to be no errors to be sent, but where a system generated ANR was produced.  There are already ignored by Maze Runner, but the ANR meant that the step `Bugsnag confirms it has no errors to send` was not always satisfied.
Adds an onError callback for all e2e test scenario configs.
Covered by a full CI and inspection of the device logs for any mention of `Filtering system generated ANR`.

Prevent system generated ANRs from being sent in e2e tests
