bugsnag/bugsnag-android

example/src/main/java/com/bugsnag/android/example/ExampleActivity.java, example/src/main/java/com/bugsnag/android/other/Other.java, src/main/java/com/bugsnag/android/Error.java
- Fixes the project packages code when proguard is used.
=> Server-side projectPackages support

example/src/main/java/com/bugsnag/android/example/ExampleActivity.java
The int has never been a delay. It's a constant with two possible values.
=> Fix toasts

src/main/java/com/bugsnag/android/DateUtils.java
=> Thread Safe DateUtils#toISO8601

src/main/java/com/bugsnag/android/MetaData.java
`HashMap` isn't thread safe, so if adding to tabs from two different thread you might mess is up.
=> Concurrent adding to tabs

build.gradle, example/build.gradle
from 1.0.0 to 1.5.0 and from 0.14.4 to 1.5.0
=> update the gradle build-tools version to 1.5.0

src/main/java/com/bugsnag/android/AppData.java, src/main/java/com/bugsnag/android/AppState.java, src/main/java/com/bugsnag/android/DeviceData.java, src/main/java/com/bugsnag/android/DeviceState.java, src/main/java/com/bugsnag/android/Error.java, src/main/java/com/bugsnag/android/JsonStream.java, src/main/java/com/bugsnag/android/JsonWriter.java, src/main/java/com/bugsnag/android/User.java
This also updates JsonWriter to handle the Boolean case which has been [upstreamed into Gson itself][1].
```
$ ./gradlew clean build connectedCheck | tail -3
BUILD SUCCESSFUL
Total time: 31.71 secs
```
[1]: https://github.com/google/gson/pull/836
=> Remove null checks, instruct JsonWriter to ignore them.

src/main/java/com/bugsnag/android/Bugsnag.java, src/main/java/com/bugsnag/android/Client.java
Its a simple getter that is making me handle this on my application.
=> Add getContext() for logging purposes

.travis.yml, build.gradle, example/build.gradle, gradle/wrapper/gradle-wrapper.properties
Updated tooling, plugins, compile sdk and target.
Removed dependency `classpath 'com.jakewharton.sdkmanager:gradle-plugin:0.12.0'` which caused an error (project builds fine without it).
=> Fix build issues on latest dev environments.

src/androidTest/java/com/bugsnag/android/ClientRejectedExecutionTest.java, src/androidTest/java/com/bugsnag/android/ErrorStoreTest.java, src/androidTest/java/com/bugsnag/android/FileUtils.java, src/main/java/com/bugsnag/android/Async.java, src/main/java/com/bugsnag/android/Client.java, src/main/java/com/bugsnag/android/ErrorStore.java
Queues errors to disk if the max pool size of the Executor is exceeded.
=> Queue errors to disk

src/main/java/com/bugsnag/android/Client.java
Registers a broadcast receiver which detects when network becomes available, and flushes any reports saved to disk.
=> Setup client to send stored reports on disk when connectivity regained

sdk/src/androidTest/java/com/bugsnag/android/ClientRejectedExecutionTest.java, sdk/src/main/java/com/bugsnag/android/Async.java, sdk/src/main/java/com/bugsnag/android/Client.java
Offloads EventReceiver setup to a background thread to reduce startup time.
=> Improve init perf

CHANGELOG.md, gradle.properties, sdk/src/main/java/com/bugsnag/android/Notifier.java
=> Release v4.3.1

sdk/src/main/java/com/bugsnag/android/AppData.java, sdk/src/main/java/com/bugsnag/android/AppDataSummary.java, sdk/src/main/java/com/bugsnag/android/Async.java, sdk/src/main/java/com/bugsnag/android/Breadcrumbs.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Configuration.java, sdk/src/main/java/com/bugsnag/android/DefaultHttpClient.java, sdk/src/main/java/com/bugsnag/android/DeviceData.java, sdk/src/main/java/com/bugsnag/android/ErrorStore.java, sdk/src/main/java/com/bugsnag/android/ExceptionHandler.java, sdk/src/main/java/com/bugsnag/android/Exceptions.java, sdk/src/main/java/com/bugsnag/android/FileStore.java, sdk/src/main/java/com/bugsnag/android/IOUtils.java, sdk/src/main/java/com/bugsnag/android/JsonWriter.java, sdk/src/main/java/com/bugsnag/android/Logger.java, sdk/src/main/java/com/bugsnag/android/MetaData.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java, sdk/src/main/java/com/bugsnag/android/Severity.java, sdk/src/main/java/com/bugsnag/android/StrictModeHandler.java, sdk/src/main/java/com/bugsnag/android/ThreadState.java, sdk/src/main/java/com/bugsnag/android/User.java
This updates the variable names to match the checkstyle rules (in practice this means increasing non-descriptive names to at least 3 chars).
=> Update variable names to match checkstyle rules

sdk/src/main/java/com/bugsnag/android/AppData.java, sdk/src/main/java/com/bugsnag/android/AppDataSummary.java, sdk/src/main/java/com/bugsnag/android/BadResponseException.java, sdk/src/main/java/com/bugsnag/android/Breadcrumbs.java, sdk/src/main/java/com/bugsnag/android/Bugsnag.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/DefaultHttpClient.java, sdk/src/main/java/com/bugsnag/android/DeviceData.java, sdk/src/main/java/com/bugsnag/android/Error.java, sdk/src/main/java/com/bugsnag/android/ErrorReportApiClient.java, sdk/src/main/java/com/bugsnag/android/ErrorStore.java, sdk/src/main/java/com/bugsnag/android/EventReceiver.java, sdk/src/main/java/com/bugsnag/android/Exceptions.java, sdk/src/main/java/com/bugsnag/android/FileStore.java, sdk/src/main/java/com/bugsnag/android/HandledState.java, sdk/src/main/java/com/bugsnag/android/IOUtils.java, sdk/src/main/java/com/bugsnag/android/MetaData.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java, sdk/src/main/java/com/bugsnag/android/SessionStore.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java, sdk/src/main/java/com/bugsnag/android/SessionTrackingApiClient.java
Reduces all line lengths to below 100 lines, as per the Java checkstyle
=> Reduce line length to below 100 chars

README.md
I accidentally merged these changes already, but I added one sentence to the intro, updated all bugsnag.com links to the www version and all http links to https.
=> Implemented minor SEO recommendations

features/disable_auto_notify.feature, features/ignored_exception_scenario.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/DisableAutoNotifyScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/IgnoredExceptionScenario.kt
Adds scenarios for when:
- An exception is set as ignored
- Auto-notify is disabled
=> Add ignored/disabled reporting scenarios

features/array_notify_release_stage.feature, features/inside_release_stage.feature, features/null_notify_release_stage.feature, features/null_release_stage.feature, features/outside_release_stage.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/ArrayNotifyReleaseStageScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/InsideReleaseStageScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/NullNotifyReleaseStageScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/NullReleaseStageScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/OutsideReleaseStageScenario.kt
Adds scenarios for when an exception is captured inside + outside of a notifyReleaseStage
=> NotifyRelease stage scenarios

features/crash_handler.feature, features/empty_stacktrace.feature, features/oom.feature, features/stackoverflow.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CrashHandlerScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/EmptyStacktraceScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/OomScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/StackOverflowScenario.kt
Adds more unusual crash scenarios:
- Empty StackTrace
- OutOfMemoryError
- StackOverflow
- Other crash handler installed
=> Add unusual crash scenarios

features/breadcrumb.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/BreadcrumbScenario.kt
Checks that breadcrumbs are serialised correctly
=> Add breadcrumb scenario

features/app_version.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppVersionScenario.kt
Adds a scenario where the app version is overrided
=> Test app version override

features/meta_data_scenario.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/MetaDataScenario.kt
Adds a scenario which adds metadata in a callback
=> Add metadata scenario

Makefile
The connectedCheck task has moved to the sdk module
=> Update Makefile test step

sdk/src/androidTest/java/com/bugsnag/android/AppDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/BeforeRecordBreadcrumbsTest.java, sdk/src/androidTest/java/com/bugsnag/android/BreadcrumbsTest.java, sdk/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java, sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/ConcurrentCallbackTest.java, sdk/src/androidTest/java/com/bugsnag/android/CustomException.java, sdk/src/androidTest/java/com/bugsnag/android/DeviceDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorReportApiClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorStoreTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/androidTest/java/com/bugsnag/android/EventReceiverTest.java, sdk/src/androidTest/java/com/bugsnag/android/ExceptionHandlerTest.java, sdk/src/androidTest/java/com/bugsnag/android/ExceptionsTest.java, sdk/src/androidTest/java/com/bugsnag/android/HandledStateTest.java, sdk/src/androidTest/java/com/bugsnag/android/JsonStreamTest.java, sdk/src/androidTest/java/com/bugsnag/android/MetaDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/NullMetadataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ReportTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionStoreTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionTrackerTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionTrackingPayloadTest.java, sdk/src/androidTest/java/com/bugsnag/android/StrictModeTest.java
Reduces the line length to below 100 chars, as per the checkstyle guidelines. Also moves CustomException to a top-level class.
=> reduce line length in tests to 100 or below

sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java
Adds tests for some missing coverage in `Error`
=> Improve code coverage in error class

sdk/src/androidTest/java/com/bugsnag/android/ReportTest.java
Adds missing coverage to methods in Report/Notify
=> Improve code coverage for report + notifier classes

features/session_tracking.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/SessionSetAutoCaptureScenario.kt
Adds a case where a user sets auto capture after initialisation
=> Add additional session tracking scenario

sdk/src/androidTest/java/com/bugsnag/android/SessionTrackingPayloadTest.java
Adds missing test coverage as identified by static analysis
=> Adds additional coverage for Session class serialisation

sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java
improves error class code coverage by adding tests for missing methods
=> test: improve error class coverage

sdk/src/androidTest/java/com/bugsnag/android/ClientNotifyTest.java
Improves code coverage by adding tests for async notify methods
=> test: add async notify test coverage

.travis.yml
Caches the gradle wrapper and its cache for future Travis builds, as recommended in the [Travis docs](https://docs.travis-ci.com/user/languages/android/#Caching). This should hopefully speed up our CI jobs a bit as they won't have to download dependencies each time.
=> ci: cache gradle deps

sdk/src/androidTest/java/com/bugsnag/android/UserTest.java, sdk/src/main/java/com/bugsnag/android/User.java
Documents public accessors to User, for use by 3rd party developers and internal API (denoted with marker annotation).
- Made User class public
- Documented public accessors
- Added nullability annotations
Adapted unit tests for JSON serialisation of the class, and added a test for the default value + override value of each accessor.
=> refactor: document public user functions, add nullability annotations

sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/main/java/com/bugsnag/android/AppData.java, sdk/src/main/java/com/bugsnag/android/AppDataSummary.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/DeviceData.java, sdk/src/main/java/com/bugsnag/android/DeviceDataSummary.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java, sdk/src/main/java/com/bugsnag/android/User.java
Add accessors to `Client` for internal API use by the Unity notifier
Public accessors to the Client class
Added unit tests for the accessors
=> Add client accessors

sdk/src/androidTest/java/com/bugsnag/android/DeviceDataSummaryTest.java, sdk/src/androidTest/java/com/bugsnag/android/DeviceDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/DeviceData.java, sdk/src/main/java/com/bugsnag/android/DeviceDataSummary.java, sdk/src/main/java/com/bugsnag/android/Error.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java
Adds public accessors to DeviceData and DeviceDataSummary, for use by 3rd party developers and internal API (denoted with marker annotation).
Note: the intention is for further work to be carried out in a separate PR (e.g. migrating legacy fields to metadata, extracting the data capture to a separate class, etc)
Converted fields/methods to properties (getter/setter backed with a field) in DeviceData and DeviceDataSummary.
Adapted unit tests for JSON serialisation of each class, and added a test for the default value + override value of each accessor.
=> Device data Android Unity changes

sdk/src/androidTest/java/com/bugsnag/android/AppDataSummaryTest.java, sdk/src/androidTest/java/com/bugsnag/android/AppDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionTrackingPayloadTest.java, sdk/src/main/java/com/bugsnag/android/AppData.java, sdk/src/main/java/com/bugsnag/android/AppDataCollector.java, sdk/src/main/java/com/bugsnag/android/AppDataSummary.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Error.java, sdk/src/main/java/com/bugsnag/android/ErrorStore.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java
To separate the collection of application data from its serialisation, supporting the Unity C# layer changes.
- Remove all methods from `AppData` and `AppDataSummary` which aren't accessors or serialisers
- Create `AppDataCollector`, which collects data for `AppData`, `AppDataSummary`, and app `MetaData`.
- Reduce number of packageManager lookups + cache other suitable values in `AppDataCollector` compared to `AppData`
- Generate a new `AppData` instance for each error report.
- Remove error's dependency on `AppData#getActiveScreenClass()`
- Add `Client#populateAppMetaData(MetaData metaData)` method for accessing extra app data as internal API
Ran mazerunner and existing unit test suite. Added unit tests for new methods.
- This pull request is ready …
=> Refactor App data collection

sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/DeviceDataSummaryTest.java, sdk/src/androidTest/java/com/bugsnag/android/DeviceDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/DeviceData.java, sdk/src/main/java/com/bugsnag/android/DeviceDataCollector.java, sdk/src/main/java/com/bugsnag/android/DeviceDataSummary.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java
To separate the collection of device data from its serialisation, supporting the Unity C# layer changes.
- Remove all methods from `DeviceData` and `DeviceDataSummary` which aren't accessors or serialisers
- Create `DeviceDataCollector`, which collects data for `DeviceData`, `DeviceDataSummary`, and device `MetaData`.
- Cache suitable values in `DeviceDataCollector` compared to `DeviceData`
- Generate a new `DeviceData` instance for each error report.
- Add `Client#populateDeviceMetaData(MetaData metaData)` method for accessing extra device data as internal API
Ran mazerunner and existing unit test suite. Added unit tests for new methods.
=> refactor: Device data collection

.github/PULL_REQUEST_TEMPLATE.md
Shortens the pull request template, resolving an action raised in the Platforms retro
=> Shorten PULL_REQUEST_TEMPLATE.md

.travis.yml, CHANGELOG.md, ndk/src/main/jni/handlers/signal_handler.c, ndk/src/main/jni/utils/serializer.c, ndk/src/main/jni/utils/stack_unwinder_simple.c
Ensure common issues in C/C++ code is caught and handled.
`cppcheck` is commonly available tool and easy to install despite the NDK being an unusual environment. It also found things! 😄
=> Enable C++ linting on CI, fix violations

sdk/src/androidTest/java/com/bugsnag/android/BeforeSendTest.java, sdk/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java, sdk/src/androidTest/java/com/bugsnag/android/ClientConfigTest.java, sdk/src/androidTest/java/com/bugsnag/android/ClientNotifyTest.java, sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/ConcurrentCallbackTest.java, sdk/src/androidTest/java/com/bugsnag/android/DeliveryCompatTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorReportApiClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/NullMetadataTest.java, sdk/src/androidTest/java/com/bugsnag/android/UniqueBeforeNotifyTest.java
Adds nullability annotations to overridden implementations, which aids static analysis and detection of potential null problems.
=> Add missing nullability annotations in test code

CONTRIBUTING.md
Updated release instructions following walkthrough
=> docs(contrib): Update release instructions

dockerfiles/Dockerfile.android, tests/features/steps/android_steps.rb
Enables better handling of timeout errors once [this PR](https://github.com/bugsnag/maze-runner/pull/59) is merged.
=> Maze-update: Deal with changed handling of element location

.buildkite/pipeline.yml
Attempts to prevent issues where steps can get stuck without failing, preventing further steps or jobs from running correctly.
=> Add CI step timeouts

.buildkite/pipeline.yml, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/NewSessionScenario.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/ResumedSessionScenario.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/StoppedSessionScenario.kt, tests/features/session_stopping.feature, tests/features/steps/android_steps.rb
After disabling the stopping session scenarios due to flakiness, this PR re-enables them updated to run against Maze V2.
=> Re-enable stopping-session scenarios

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorReader.java
Reverts bugsnag/bugsnag-android#565
=> Revert "Buffer IO when reading cached error reports"

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorReader.java
Buffers IO when reading from cached error reports, improving performance.
=> Buffer io when reading from cached error file

bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
Re-enabling the previous handler (when the handler is the default handler), causes a crash upon the next SIGQUIT as the default handler crashes the process. 
This change instead avoids uninstalling the handler and instead  introduces an `enabled` flag which only writes to the ANR buffer when set. Then the previously installed custom handlers will still be invoked. The `enabled` flag is only altered within the `config` lock and only checked in one place, preventing intermediate states.
=> refactor(plugin-anr): Add enabled bool as proxy for install/uninstall

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionTrackerPauseResumeTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Session.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, features/fixtures/mazerunner/src/main/cpp/bugsnags.cpp, features/native_session_tracking.feature, features/session_stopping.feature, mazerunner-scenarios/src/main/cpp/bugsnags.cpp, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXPausedSessionScenario.java, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/NewSessionScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/PausedSessionScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/ResumedSessionScenario.kt, tests/features/fixtures/mazerunner/src/main/cpp/bugsnags.cpp, tests/features/native_session_tracking.feature, tests/features/session_stopping.feature
Renames `stopSession()` to `pauseSession()` as per the notifier spec, to better reflect what this method does.
=> Rename stopSession() to pauseSession()

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java, bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
Ported fix for text encoding crash. For full details see https://github.com/bugsnag/bugsnag-android/pull/584 and https://github.com/bugsnag/bugsnag-android/commit/80e072d9b9be0632fb71e789f1213fd735bc198e
=> Fix support for native crashes containing multiple text encodings

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientConfigTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/NativeInterfaceTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/OnBreadcrumbStateTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ReportTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionPayloadTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionStoreTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/StrictModeTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/StrictModeWrapper.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ThreadTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/UniqueOnErrorTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/AppData.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Async.java, bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagPluginInterface.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DateUtils.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceData.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ExceptionHandler.java, bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/HandledState.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SystemBroadcastReceiver.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventStateTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataRedactionTest.java
Resolves code style issues detected by the IntelliJ inspector tool. These are best viewed in the individual commits, and resolve issues such as:
- Using property access syntax rather than getters
- Making fields local/private to increase encapsulation
- Simplifying statements
- Adding final modifier to increase immutability of codebase
- Removing redundant clauses
- Weakening access modifier to increase encapsulation
- Resolving potential NPEs by adding null checks/updating annotations
=> Resolve IntelliJ style inspection issues

build.gradle
Updates the Kotlin version used by the library to 1.3.61. The main highlights of this include:
- Improved compiler/runtime performance (1.3.60)
- Improved debugger experience (1.3.30/1.3.50)
Updating the library should not require any functional changes from us or library consumers.  A full set of release notes is available here: https://blog.jetbrains.com/kotlin/category/releases/
=> Update Kotlin version to 1.3.61

tests/features/empty_cache_file.feature
Fixes an undefined assertion in the mazerunner scenarios.
=> Fix undefined mazerunner assertion

UPGRADING.md
Adds documentation for breaking changes and new functionality in the NDK layer.
=> Document upgrade guide for NDK

docker-compose.yml, dockerfiles/Dockerfile.android
Companion to bugsnag/maze-runner#91
=> Maze runner retry on failure and fail fast

dockerfiles/Dockerfile.android-maze-runner
Benefit from the latest fixes and enhancements to Maze Runner immediately.
Standard CI.
=> Roll with the latest Maze Runner release

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt
Fix incorrectly ordered params
Fixes #903
=> swapped order of params to match expected order in constructor

mazerunner-scenarios/build.gradle, mazerunner-scenarios/src/main/java/com/bugsnag/android/JavaHooks.java, tests/features/fixtures/mazerunner/build.gradle, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, tests/features/fixtures/mazerunner/src/main/res/layout/activity_main.xml
Enables easier development and testing of the notifier and associated E2E tests by enabling them to be run locally.
Run several scenarios locally.
=> [PLAT-4818] Add manual testing mode to Maze-runner test fixture

dockerfiles/Dockerfile.android-maze-runner, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXSessionInfoCrashScenario.java, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXStartSessionScenario.java
Attempts to address a couple of flaking tests by adjusting timings on scenarios.
The assumption is that some devices are slower than others on BrowserStack.
See diffs.
This is part of an ongoing investigation and changes are to test scenario files only.
=> Adjust scenario timings

bugsnag-android-core/detekt-baseline.xml, bugsnag-plugin-android-anr/detekt-baseline.xml, bugsnag-plugin-android-ndk/detekt-baseline.xml, bugsnag-plugin-react-native/detekt-baseline.xml, build.gradle, examples/sdk-app-example/build.gradle, features/fixtures/mazerunner/build.gradle
Bumps Bugsnag dependency versions in the project so that we can remain up to date with the latest bugsnag. Additionally updated the detekt plugin for static analysis to use the latest version and updated baseline.xml to use new format.
Ran the example app and generated an APK by hand. Relied on CI to run lint/test tasks.
=> bump bugsnag-android dependency versions

examples/sdk-app-example/gradle.properties, gradle.properties
Increases the maximum memory available for Gradle builds which should help reduce the amount of time taken to build.
=> Increase gradle's max memory

features/session_tracking.feature, features/steps/android_steps.rb
Asserts that the `Bugsnag-Integrity` header is a valid SHA-1 digest, by hashing the payload using mazerunner.
=> Assert that Bugsnag-Integrity header is valid

CHANGELOG.md, bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/main/java/com/bugsnag/android/DefaultDelivery.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryHeaders.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryParams.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryHeadersTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-plugin-android-ndk/detekt-baseline.xml, features/session_tracking.feature, features/steps/android_steps.rb, gradle.properties
=> Integration branch for release stage validation

.buildkite/pipeline.full.yml
Ensures that the example app builds by adding a check to the full CI pipeline which assembles an APK.
=> Build example app on CI

CHANGELOG.md
Made the changelog more informative for the issue with v5.5.1 release (#1096).
=> docs(changelog): update changelog to clarify impact of v5.5.1 release issue

features/steps/android_steps.rb
React to system dialogs popping up in end-to-end tests rather than always trying to dismiss them.
There were a few problems with the previous approach of always attempting to dismiss dialogs, whether they were there or not:
- The 3s delay designed to wait for dialogs to appear adds a lot of time to the overall run when it's not always necessary.
- Scenarios could still flake when dialogs appeared after the 3s.
- The mechanism appears completely unnecessary on Android 7+, where the `Intent` broadcast on app start can be seen to successfully dismiss dialogs.
- Attempting to click button that aren't there generates a lot of noise in the Appium logs.
If flakes still occasionally occur, we can tweak the parameters and retries. With further analysis we can also optimise the delays further - for …
=> Only attempt to clear error dialogs if element is not found

bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
Busy-waiting on the ANR watchdog thread works, but can potentially keep an app in the active state and use more energy.
`sem_wait()` puts the thread to sleep instead of busy-waiting. It's async-safe on Android provided only one thread is waiting on the lock (which is the case here).
The ANR thread now waits on a semaphore by default, falling back on the old polling method if any semaphore function fails.
Re-ran all E2E tests.
=> Use sempaphores in the ANR watchdog thread.

examples/sdk-app-example/app/src/main/cpp/entrypoint.cpp, examples/sdk-app-example/app/src/main/java/com/example/bugsnag/android/BaseCrashyActivity.kt, examples/sdk-app-example/app/src/main/res/layout/main.xml, examples/sdk-app-example/app/src/main/res/values/strings.xml
ANRs now process differently if they are generated in native code. We need a way to demonstrate this.
Added a new button that generates an ANR in native code.
Manually tested that it generated a native trace and sent to Bugsnag backend.
=> Add a Native ANR button to the example app

bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c, bugsnag-plugin-android-ndk/src/main/jni/metadata.c
Tighten up the JNI code even more to ensure that the JNI local reference table cannot be overrun.
Manual testing and re-ran e2e tests.
=> Make sure all strings get fully released

bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
Backports #1166 to the v4-unity branch.
=> Backport: move the mutex unlock back to the end of deliverReportAtPath

bugsnag-plugin-android-anr/src/main/CMakeLists.txt, bugsnag-plugin-android-anr/src/main/jni/anr_handler.c, bugsnag-plugin-android-anr/src/main/jni/utils/string.c, bugsnag-plugin-android-anr/src/main/jni/utils/string.h, bugsnag-plugin-android-ndk/src/main/jni/handlers/cpp_handler.cpp, bugsnag-plugin-android-ndk/src/main/jni/handlers/signal_handler.c, bugsnag-plugin-android-ndk/src/main/jni/metadata.c, bugsnag-plugin-android-ndk/src/main/jni/safejni.c, bugsnag-plugin-android-ndk/src/main/jni/safejni.h, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.c, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder_libcorkscrew.c, bugsnag-plugin-android-ndk/src/main/jni/utils/string.c, bugsnag-plugin-android-ndk/src/main/jni/utils/string.h, bugsnag-plugin-android-ndk/src/test/cpp/test_utils_string.c
Reverts bugsnag/bugsnag-android#1153
=> Revert "String copy and JNI fixes"

features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/cxx-scenarios-bugsnag.cpp, features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXAutoContextScenario.java, features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXExceptionSmokeScenario.kt, features/full_tests/batch_1/error_context.feature, features/full_tests/batch_2/native_context.feature, features/smoke_tests/unhandled.feature
Combine similar scenarios, allowing two to be removed and the overall execution time to be reduced as a result.
Covered by CI.
=> [PLAT-5901] Refactor e2e tests to combine similar scnearios 

dockerfiles/Dockerfile.android-sizer
Fix the Android size reporting CI step.
=> Apt-get update

bugsnag-android-core/src/main/jni/root_detection.c
PLAT-6108
Check if we can create the file `/system/bugsnag_test_file.txt`
Ran manually, and reran tests
=> Root check: See if we can create a file in /system

.buildkite/pipeline.yml
Tweaks the instrumentation test target to android 7, which has more availability on browerstack.
=> Change instrumentation test target to android 7

features/fixtures/mazerunner/cxx-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXDelayedErrorScenario.kt
Fixes a race in `CxxDelayedErrorScenario` between the NDK crash and handled JVM error delivery. Previously the fatal NDK error could terminates the JVM delivery halfway through, which would result in only one error being sent.
The scenario has been improved so that the NDK crash only happens once the first error has been delivered.
=> Alter delay in E2E test

bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.c, bugsnag-plugin-android-ndk/src/main/jni/utils/migrate_internal.h, bugsnag-plugin-android-ndk/src/test/cpp/test_breadcrumbs.c, bugsnag-plugin-android-ndk/src/test/cpp/test_migrate.c, features/smoke_tests/unhandled.feature
PLAT-6250: Increase internal event structure sizes
Re-ran e2e tests
=> 6250 new struct limits

dockerfiles/Dockerfile.android-license-audit
Fixes the license audit check by calling `apt-get update`.
=> Add apt-get update to dockerfile

buildSrc/src/main/kotlin/com/bugsnag/android/BugsnagBuildPlugin.kt, examples/sdk-app-example/app/CMakeLists.txt, examples/sdk-app-example/app/build.gradle, examples/sdk-app-example/build.gradle, examples/sdk-app-example/gradle.properties, gradle.properties
=> Setup example app to use prefab

docs/RELEASING.md
Clarifies that the release should involve updating the bugsnag-js and bugsnag-unity libraries.
=> Add note to release instructions

CHANGELOG.md
Remove some spaces in the changelog at the ends of various lines
=> style(changes): remove trailing whitespace

examples/sdk-app-example/app/build.gradle, examples/sdk-app-example/build.gradle, examples/sdk-app-example/gradle/wrapper/gradle-wrapper.properties
Bumps the bugsnag dependencies in the example app to newer versions as the current versions don't include newly released functionality.
=> Bump bugsnag dependencies in example app

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournalEventMapper.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/internal/journal/BugsnagJournalEventMapperTest.kt
Deserializes the context from entries in the bugsnag journal into an event.
Added unit tests to cover the case where context is present and when it isn't.
=> Deserialize context from bugsnag journal

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournalEventMapper.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/JournaledStateObserver.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Session.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagJournalEventMapperTest.kt
Deserializes the session written in the bugsnag journal if it is present, and adds it to the event.
Added unit test coverage.
=> Deserialize session from bugsnag journal entry

bugsnag-android-core/src/main/java/com/bugsnag/android/FeatureFlag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/FeatureFlagAware.java, bugsnag-android-core/src/test/java/com/bugsnag/android/FeatureFlagTest.java
Define the basic structure and contracts that Feature Flags will implement.
A new unit test was introduced for the `FeatureFlag` class and it's `Map.Entry` contract.
=> Add `FeatureFlag` and `FeatureFlagAware`

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt, gradle.properties
Sync master back into next after v5.15.0 release
=> V5.15.0 master sync

bugsnag-android-core/src/main/java/com/bugsnag/android/ClientInternal.kt
If NDK error detection is not enabled then it isn't necessary to write to the journal, as only unhandled NDK errors use it at present. This changeset disables the journal when it isn't needed.
Relied on the existing minimal test fixture and manual verification. Performance was also benchmarked when NDK error detection is disabled:
=> Disable journal if NDK error detection not enabled

bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, bugsnag-plugin-android-ndk/src/main/jni/metadata.c, bugsnag-plugin-android-ndk/src/main/jni/metadata.h
Breadcrumbs now use the journal, so we don't need to run the legacy path anymore.
=> Plat 7528 remove breadcrumbs legacy path

bugsnag-android-core/src/main/java/com/bugsnag/android/internal/journal/DocumentPath.kt
Optimizes the `apply()` method with a few improvements:
- Avoiding duplicate type checks at the cost of slightly less useful error messaging
- Avoiding the unnecessary construction of an iterator by removing a call to `last()`
Verified that the changes take ~38ms to call `Bugsnag.setContext()` 1000 times, whereas previously they took ~50ms.
=> Optimize Command.apply()

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/NativeInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ActivityBreadcrumbCollector.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagJournalEventMapper.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ClientInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ActivityLifecycleBreadcrumbTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataConcurrentModificationTest.kt
Some immutable maps were missed last pass.
Reran all tests
=> Make more maps mutable

bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagEventMapper.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/SeverityReason.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/EventApiTest.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt
Allow `SeverityReason` to be parsed from it's JSON form back into it's model, so that it can form part of `Event`s to be passed to registered `OnSendCallback`s
Cannot be directly and meaningfully tested, but will be tested as part of upcoming parser tests
=> Parse SeverityReason

docker-compose.yml
Passes buildkite and Bugsnag variables into the test docker container
=> Prep for Mazerunner ft Bugsnag

bugsnag-plugin-android-ndk/detekt-baseline.xml, bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/migrations/EventMigrationV5Tests.kt, bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/migrations/EventMigrationV6Tests.kt, bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/migrations/EventMigrationV7Tests.kt, bugsnag-plugin-android-ndk/src/androidTest/java/com/bugsnag/android/ndk/migrations/EventMigrationV8Tests.kt, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/event_reader.c, bugsnag-plugin-android-ndk/src/test/CMakeLists.txt, bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV5Tests.cpp, bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV6Tests.cpp, bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV7Tests.cpp, bugsnag-plugin-android-ndk/src/test/cpp/migrations/EventMigrationV8Tests.cpp
Similar to #1551, this changeset adds instrumentation tests for the event structure -> disk -> JSON flow for the newer migrations, and provides a safer landing for the changes coming in PLAT-7712.
* Added tests for each migration, adding additional assertions for the fields added or changed
* Fixed a bug in migrations v4 and v5 where grouping hash was truncated after 32 characters.
<details>
<summary>Might be getting carried away here tbh</summary>
</details>
=> Add tests for NDK migrations v5 to latest

features/steps/android_steps.rb
Refactor test assertions to avoid dependencies on items in the global namespace and the brittleness that can bring.
Note that this is a temporary change to stop the next Maze Runner release from breaking the build (is is not inherently a breaking change in itself).  The new class added in this PR will be removed and `Maze.check` used instead.
Covered by CI and I have also successfully run the e2e tests against the Maze Runner release that's currently waiting in the wings.
=> Avoid dependencies on the global namespace

Gemfile, Gemfile.lock, features/steps/android_steps.rb
Use the new `Maze.check` mechanism for making test assertions, avoiding potential problems from using functions in the global namespace.
Covered by a `[quick ci]` run.
=> Use Maze.check

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/AppDataCollectorForegroundTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/AppDataCollectorSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/AppMetadataSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ContextExtensionsKtTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/DeviceDataCollectorSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/DeviceMetadataSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ExceptionHandlerTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/RootDetectorTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SharedPrefMigratorTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SystemBroadcastReceiverTest.kt, bugsnag-plugin-android-okhttp/src/test/java/com/bugsnag/android/BugsnagOkHttpPluginTest.kt, buildSrc/src/main/kotlin/com/bugsnag/android/Versions.kt, examples/sdk-app-example/app/build.gradle, examples/sdk-app-example/build.gradle, examples/sdk-app-example/gradle/wrapper/gradle-wrapper.properties, features/fixtures/mazerunner/build.gradle, features/fixtures/mazerunner/gradle/wrapper/gradle-wrapper.properties, features/fixtures/minimalapp/build.gradle, features/fixtures/minimalapp/gradle/wrapper/gradle-wrapper.properties, gradle/wrapper/gradle-wrapper.properties
Bumps the versions for AGP/Gradle/Ktlint to the latest available versions to ensure that we remain up to date. Relied on existing test coverage on CI.
=> Bump gradle wrapper/static analysis tool versions

bugsnag-plugin-android-ndk/src/main/CMakeLists.txt, bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/jni_cache.c, bugsnag-plugin-android-ndk/src/main/jni/jni_cache.h, bugsnag-plugin-android-ndk/src/main/jni/metadata.c, bugsnag-plugin-android-ndk/src/main/jni/safejni.c
Merges the latest next into the feature flags integration branch.
=> Merge next into feature flags

.buildkite/pipeline_trigger.sh
Always perform a full build for PRs into master.
=> Always perform a full build for PRs into master

Gemfile, Gemfile.lock, features/steps/android_steps.rb
Fixes a problem running Maze Runner locally.  The same issue doesn't occur on CI.
Basic CI covers any regression, tested locally that it fixes the problem.
=> Fix local e2e test runs

.buildkite/pipeline.full.yml, .buildkite/pipeline.quick.yml
Provide multiple device options for Android 6 e2e tests.
Covered by a "quick" CI run.
=> Provide multiple device options for Android 6 e2e tests

features/full_tests/discarded_events.feature, features/full_tests/discarded_session.feature
Consistently format e2e test feature files.
Feature files are currently inconsistently formatted and at odds with the default settings of IntelliJ IDEA (typically making it very irritating to make simple repetitive changes).
**Only** changes the formatting of e2e test feature files.
Covered by CI.
=> Consistently format e2e test feature files

bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer/json_writer.c, scripts/run-cpp-check.sh
Resolve errors found by `cppcheck` locally, also ensuring that CI fails for errors in the future.
I've made the changes that seem appropriate, I don't think they should have any functional bearing.
=> Resolve cppcheck errors

features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
Adds logging to help with the diagnosis of truncated device logs and network failures during end-to-end tests.
Covered by CI and manual inspect of the device logs.
=> Improve test fixture logging

.buildkite/pipeline.full.yml, .buildkite/pipeline.yml
Increase BrowserStack slots to 24.
Covered by CI.
=> Increase BrowserStack slots to 24

.buildkite/pipeline.full.yml
Fix pipeline indentation.
Introduced in #1688.
Covered by a full CI run!
=> Fix pipeline indentation

bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.cpp
Avoid the hidden lazy init in `GetBuildID()` which uses `new` and is therefore not signal-safe.
Modify the signal-handler version of the stack unwinder to use direct access the `MapInfo.elf_fields` and only populate the `BuildID` value if it is already loaded.
Manual testing to ensure the new logic behaves as expected, otherwise relied on existing testing.
=> Avoid lazy-init of Elf data inside signal handler

bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java
Introduce a specialisation of `write` and the `flushAsync` method.
Leverage the existing `write` and `flushEventFile` methods. The `flushEventFile` is called from within a scheduled task with `writeAndDeliver` returning the `Future` handle for that delivery (allowing external synchronisation).
Manually tested in context. The full end-to-end test will be in the next PR.
=> EventStore.writeAndDeliver

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt
Get rid of the generic catch-all "is it a valid JVM class" error in Scenario and make it a little more intelligent when it encounters problems instantiating and running scenarios.
=> Make Scenario a little more error friendly

bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DefaultDelivery.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/internal/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/internal/InternalMetrics.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/internal/InternalMetricsImpl.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/internal/InternalMetricsNoop.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/internal/StringUtils.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestData.java, features/fixtures/mazerunner/cxx-scenarios-bugsnag/detekt-baseline.xml, features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/cxx-scenarios-bugsnag.cpp, features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/MetadataStringsTooLargeScenario.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/JavaHooks.java, features/full_tests/trimming.feature, features/steps/breadcrumb_metadata_steps.rb
PLAT-9019: Trim metadata when the payload is too big
New e2e tests for this
=> Plat 8915 trim metadata

docker-compose.yml
Fixes the build by changing to the correct Maze Runner docker image.
I've also tidied up the compose file a little to avoid repetition and remove an unused service.
Covered by a basic CI run (which covers both BB and BS).
=> Correct and tidy docker-compose.yml

.buildkite/pipeline.yml
Moves Android 12 tests onto BitBar
=> Moves Android 12 tests onto BitBar

.buildkite/pipeline.full.yml, .buildkite/pipeline.yml, Gemfile, Gemfile.lock
Move Android 13 tests to BitBar.
Achieved 3 successful full builds while developing this PR.
=> Move Android 13 tests to BitBar

.buildkite/pipeline.full.yml, .buildkite/pipeline.yml
Move Android 9 & 11 tests to BitBar
=> Move Android 9 & 11 tests to BitBar

CHANGELOG.md, examples/sdk-app-example/app/src/main/java/com/example/bugsnag/android/BaseCrashyActivity.kt
Example app demonstrates global metadata.
Tested Manually.
=> Add global metadata to the example app

docs/ENVIRONMENT_SETUP.md
Added note for setting up JDK version for apple silicon 
Manual test
=> JDK set up for apple silicon

.github/workflows/codeql.yml
Add CodeQL configuration file for non-standard Android build. See new Checks below - all pass.
=> build: add CodeQL config

features/fixtures/minimalapp/build.gradle
Fix size reporting generated by Danger.
Removed apiValidation from minimalapp fixture
Danger should now report non-zero sizes on this PR
=> Fix size reporting generated by Danger.

Gemfile.lock, features/full_tests/trimming.feature, features/steps/android_steps.rb
Fixing the flaky test in trimming payload test
Changing the conditions in the trimming test scenarios
Updated existing tests
=> Reduce flakes in trimming test

bugsnag-android-ndk/README.md, bugsnag-android-ndk/build.gradle, bugsnag-android-ndk/gradle.properties, bugsnag-android-ndk/lint-baseline.xml, bugsnag-android-ndk/src/main/AndroidManifest.xml, settings.gradle
This reverts commit 614167b61f0d94348aa17a01f07a2756ec2a5757.
=> Revert "project(android-ndk) removed bugsnag-android-ndk (#1876)"

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagStoreMigratorTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientUserTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/LastRunInfoStoreTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/LastRunInfoStore.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/UserStore.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/internal/BugsnagStoreMigrator.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/EventStoreMaxLimitTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionStoreMaxLimitTest.kt, features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DiscardOldSessionScenario.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt
Migrating all the cache files to the bugsnag app directory.
Better organise on file system
Relocate all the cache files to the bugsnag app directory.
Introduced new unit tests
=> Bugsnag cache directory

dockerfiles/Dockerfile.android-publisher
Add the exitinfo module to the publishing step
=> Add the exitinfo module to the publishing step

.github/workflows/downstream_updates.yml
Fixes auth by using explicit variable references rather than environment variables, and uses a given bearer token instead of the default.
=> Update workflow to use auth provided by bearer token

CHANGELOG.md, UPGRADING.md
Added a bit more information to the Upgrade Guide, post-release of v6.0.
=> docs(upgrade guide): expanded UG content and a few corrections to changelog

features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/BugsnagInternals.java, features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
Added command to mazerunner fixture for flushing all the stored event files.
Added a `Flush` class to mazerunner package for accessing eventStore flushAsync method
=> Flush command to mazerunner fixture

bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NativeEventDecoder.kt, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/ByteBufferExtensions.kt, bugsnag-plugin-android-ndk/src/test/java/com/bugsnag/android/NativeEventDecoder32bitTest.kt, bugsnag-plugin-android-ndk/src/test/java/com/bugsnag/android/NativeEventDecoder64bitTest.kt
Decoder for bsg_user_info to event 
Moving decoding user info process to NativeEventDecoder in Kotlin
Introduced new tests
=> Decode user info to event

bugsnag-android-core/build.gradle
Gradle config to suppress internal packages being documented.
=> Dokka config

examples/sdk-app-example/app/build.gradle, examples/sdk-app-example/app/src/main/AndroidManifest.xml, examples/sdk-app-example/build.gradle, examples/sdk-app-example/gradle.properties, examples/sdk-app-example/gradle/wrapper/gradle-wrapper.properties
Update Bugsnag Example project aspects to be compatible with newer version IDE
Use AGP 8.+, so that the CI can always build against whatever versions are most recent
Manual testing
=> Update the Example Project to more recent AGP

bugsnag-android-core/api/bugsnag-android-core.api, bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagEventMapper.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/TraceCorrelation.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/resources/event_serialization_8.json
Add the correlation property to the Event model so that trace id / span id can be sent as part of an Event.
Updated existing unit test
=> Add the correlation property to the Event model

features/fixtures/mazerunner/app/build.gradle, features/fixtures/mazerunner/app/src/main/AndroidManifest.xml, features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MazerunnerApp.kt, features/fixtures/mazerunner/jvm-scenarios/build.gradle, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationFromManifestScenario.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationKotlinScenario.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiThreadedStartupScenario.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/SharedPrefMigrationScenario.kt
Integrate `bugsnag-android-performance` into `bugsnag-android` MazeRunner
implement the latest version of `bugsnag-android-performance` to measure the start span
Existing end to end test
=> Integrate bugsnag-android-performance into bugsnag-android MazeRunner

bugsnag-android-core/detekt-baseline.xml, features/fixtures/mazerunner/app/detekt-baseline.xml, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/UnhandledExceptionEventDetailChangeScenario.kt, features/full_tests/error_callback_alters_fields.feature
Fixed and splitted  onErrorCallback e2e tests
Refactored onErrorCallback end to end  scenario logic and feature
Existing and new end to end tests
=> onErrorCallback end to end tests

dockerfiles/Dockerfile.android-publisher
=> Fix docker publish

features/fixtures/mazerunner/app/build.gradle, features/fixtures/mazerunner/app/detekt-baseline.xml, features/fixtures/mazerunner/app/src/main/AndroidManifest.xml, features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, features/fixtures/mazerunner/app/src/main/java/com/bugsnag/android/mazerunner/NetworkStatus.kt, features/fixtures/mazerunner/build.gradle, features/fixtures/mazerunner/gradle/wrapper/gradle-wrapper.properties, features/fixtures/mazerunner/jvm-scenarios/src/main/AndroidManifest.xml, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/JvmCrashLoopScenario.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/SessionStoppingScenario.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/multiprocess/MultiProcessService.kt, features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/multiprocess/ProcessCompat.kt, features/smoke_tests/02_handled.feature, features/smoke_tests/04_unhandled.feature
Bump the version of AGP and  fixed the related tests
Bump the version of AGP and updated line numbers in the tests
Existing tests
=> Bump the version of AGP and update tests

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt
Fix the `MultiProcessHandledExceptionScenario` on Android 14, using the correct `registerReceiver` functions (depending on the SDK level)
`MultiProcessHandledExceptionScenario` should now pass on Android 14
=> Fix MultiProcessHandledExceptionScenario on Android 14

features/fixtures/mazerunner/jvm-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/ManualSessionSmokeScenario.kt
Fix the ManualSessionSmokeScenario end to end test.
Moved the test scenario onto a background thread to avoid ANRs
Relied on the test passing again on CI
=> Fix ManualSessionSmokeScenario

docs/PROJECT_STRUCTURE.md
Update the OkHttp module docs, and add the ExitInfo module
=> Update the PROJECT_STRUCTURE.md docs

.github/workflows/codeql.yml, .github/workflows/downstream_updates.yml, dockerfiles/Dockerfile.android-common
improve Pinned-Dependencies and Token-Permissions scores
=> OpenSSF improvements

.github/workflows/scorecard.yml, CODEOWNERS, README.md, SECURITY.md
Adds the latest branding to the readme, a security policy and codeowners file.
Also adds the OpenSSF scorecard week job and badge to the readme.
=> Docs and OpenSSF scorecard updates

.github/dependabot.yml
Enables Dependabot generating PRs for GitHub Actions and Bundler updates
=> build: enable Dependabot updates

.buildkite/pipeline.full.yml, .buildkite/pipeline.yml, .buildkite/pipeline_trigger.sh, .github/workflows/codeql.yml, UPGRADING.md, docs/RELEASING.md
Updates for changing from `master` to `main` for the root (but not default) branch.
=> changes for master->main move

.github/workflows/scorecard.yml
Gradle wrapper validation check
=> gradle wrapper validation check

features/fixtures/minimalapp/Dangerfile
Update size reporting script to match `bugsnag-android-performance`
Size reports should remain in the same format for this PR
=> Updated size reporting script

gradle/release.gradle, scripts/docker-publish.sh
Fix the `release` Gradle script to point to the correct repository
=> Fix the publishing repository

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt
Synthesised the information in historical device with state with device id
Existing tests
=> Synthesised the correct device id

docs/RELEASING.md
=> Update RELEASING doc

.buildkite/pipeline.yml
Corrects some invalid YAML I stumbled on in the Buildkite pipeline, most likely caused during a merge of branches at some point.
=> Correct pipeline YAML

bugsnag-android-core/api/bugsnag-android-core.api, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagApiTest.kt
Bugsnag includes Grouping Discriminator option
Added Grouping Discriminator getter and setter to Bugsnag 
update existing unit test
=> Added groupingDiscriminator option to Client and Bugsnag

.buildkite/pipeline.yml, scripts/build-test-fixture.rb
Parameterise the fixture build script and use for all pipeline jobs.
=> Parameterise fixture build script

Gemfile, docker-compose.yml, features/steps/android_steps.rb
=> Bump Maze Runner to v10

.buildkite/pipeline.full.yml, .buildkite/pipeline.yml
Add automatic retries to Appium steps for the exit code 103
Covered by CI
=> Add retries to Appium steps
