bugsnag/bugsnag-android

src/androidTest/java/com/bugsnag/android/AppDataTest.java, src/androidTest/java/com/bugsnag/android/AppStateTest.java, src/androidTest/java/com/bugsnag/android/BreadcrumbsTest.java, src/androidTest/java/com/bugsnag/android/BugsnagTestCase.java, src/androidTest/java/com/bugsnag/android/DeviceDataTest.java, src/androidTest/java/com/bugsnag/android/DeviceStateTest.java, src/androidTest/java/com/bugsnag/android/ErrorTest.java, src/androidTest/java/com/bugsnag/android/ExceptionsTest.java, src/androidTest/java/com/bugsnag/android/MetaDataTest.java, src/androidTest/java/com/bugsnag/android/NotificationTest.java, src/androidTest/java/com/bugsnag/android/StacktraceTest.java, src/main/java/com/bugsnag/android/Error.java
The tests were failing because of projectPackages was null (only likely to ever occur in the tests). I also improved the tests to not swallow exceptions so that you can see the true failures rather than an NPE in the tests.
=> Fix for when no project packages are found

src/main/java/com/bugsnag/android/ErrorStore.java
We got this error in a tablet 3Q TS1003T on Android 2.2
I think it's a firmware bug, there must be no NPE because isDirectory() is true
=> Fixes NPE at com.bugsnag.android.ErrorStore$1.run(ErrorStore.java:49)

src/main/java/com/bugsnag/android/Async.java, src/main/java/com/bugsnag/android/Client.java
When uploading a crash, it makes sense to do it from the crashing thread before delegating to the default handler, to guarantee that the crash is either uploaded or saved before the process is killed.
* This change introduces an API that allows one to write a blocking `UncaughtExceptionHandler`.
* I did not change the default exception handler, because this change might slightly delay the appearance of the crash dialog.
* Also fixed `Async` to use a Java Executor instead of the `AsyncTask` garbage. `AsyncTask` should be burnt to the ground.
* The async API is still needed when you want to log a non crashing throwable.
Fixes #63
=> Add blocking API

src/main/java/com/bugsnag/android/Bugsnag.java
The setting and clearing of max breadcrumbs are currently not static methods and hence can never be called.  This pull request corrects the error.
=> make setting and clearing of max breadcrumbs static methods

.gitignore, src/main/java/com/bugsnag/android/DeviceData.java
While just checking for the existence of certain files does not guarantee a device is rooted, it's something we can check with virtually no impact on the user.
I've extended the current type of check with a few more locations.
The previous check only worked if the device was using a specific superuser app.
Additionally, on newer Android versions the app folder hierarchy changed.
=> Jailbreak detection improvement

src/main/java/com/bugsnag/android/DeviceData.java
Potential fix for issue #78, adds a check for resources being non-null before caching device data.
=> Check for context resources before loading data

src/main/java/com/bugsnag/android/Breadcrumbs.java, src/main/java/com/bugsnag/android/Client.java, src/main/java/com/bugsnag/android/ErrorStore.java
`javac` generates package-scoped methods when you access private fields and methods from inner to outer classes (and vise-versa).
```
$ dex-method-count before.dex
443
$ dex-method-count after.dex
436
```
Every bit counts for libraries!
=> Remove the need for synthetic methods.

CONTRIBUTING.md, README.md, build.gradle, example/build.gradle, example/proguard.pro, example/src/main/AndroidManifest.xml, gradle.properties, proguard.txt, src/androidTest/AndroidManifest.xml, src/main/AndroidManifest.xml
=> Distribute the library only as aar (not as jar)

src/main/java/com/bugsnag/android/ErrorStore.java
Limit the number of errors stored for later sending to prevent possible disk space issues (see #23).
Stores up to 100 errors and discards any subsequent errors.  First 100 errors are stored on the basis that they are likely to be the most interesting.  Is this sensible?
=> Limit number of stored errors

src/main/java/com/bugsnag/android/Breadcrumbs.java
Switch breadcrumb store to ConcurrentLinkedQueue to prevent ConcurrentModifictaionException when new breadcrumbs are added/cleared whilst being written out to an error report. Fix for #72.
=> Switch breadcrumb store to ConcurrentLinkedQueue

src/main/java/com/bugsnag/android/Client.java, src/main/java/com/bugsnag/android/DeviceData.java, src/main/java/com/bugsnag/android/ErrorStore.java, src/main/java/com/bugsnag/android/HttpClient.java
=> Format numbers in message strings with US locale

src/androidTest/java/com/bugsnag/android/DeviceDataTest.java, src/main/java/com/bugsnag/android/DeviceData.java
This PR adds the CPU/ABI information to the device information as suggested in https://github.com/bugsnag/bugsnag-android/pull/109
This is done slightly differently to ensure that the tests pass on android v4
=> Add cpu abi to device information

src/androidTest/java/com/bugsnag/android/ExceptionsTest.java, src/main/java/com/bugsnag/android/BugsnagException.java, src/main/java/com/bugsnag/android/Error.java, src/main/java/com/bugsnag/android/Exceptions.java
Currently there are a couple of constructors for the Error object, one takes and exception and the other takes a name, message and stacktrace.
These fields are store separately and every time the details are accessed we have to check which one to use.
This PR adds a new BugsnagException class used to wrap the name, message and stacktrace so that can store them in the exception field.
=> Remove duplicate fields

src/androidTest/java/com/bugsnag/android/AppDataTest.java, src/androidTest/java/com/bugsnag/android/ClientTest.java, src/androidTest/java/com/bugsnag/android/ConfigurationTest.java, src/androidTest/java/com/bugsnag/android/ErrorTest.java, src/androidTest/java/com/bugsnag/android/StacktraceTest.java, src/main/java/com/bugsnag/android/AppData.java, src/main/java/com/bugsnag/android/Bugsnag.java, src/main/java/com/bugsnag/android/Client.java, src/main/java/com/bugsnag/android/Configuration.java, src/main/java/com/bugsnag/android/Error.java, src/main/java/com/bugsnag/android/Notification.java
Currently it is not possible to create a Bugsnag client passing in any additional config. This causes a potential bug related to setting the endpoint and also makes it difficult to add new config settings.
This PR adds a new constructor for the Client which takes a config object, and exposes the Config as public.
=> Add config constructor

src/main/java/com/bugsnag/android/Client.java
This avoids having the error showing up twice in the breadcrumbs.
For reference, this is the PHP implementation: https://github.com/bugsnag/bugsnag-php/blob/v3.4.0/src/Client.php#L258-L283.
Maybe I should move this leaveBreadcrumb line above the code that sends the error to be identical to the PHP implementation?
=> Leave breadrumb for the current error after notifying

src/androidTest/java/com/bugsnag/android/ExceptionsTest.java, src/main/java/com/bugsnag/android/Exceptions.java, src/main/java/com/bugsnag/android/JsonStream.java, src/main/java/com/bugsnag/android/JsonWriter.java
This changeset allows for customizing the serialization of Throwables within payloads sent to Bugsnag. It allows integrations to attach additional stacktrace information or interact with the `inProject` property of the stacktrace.
=> Allow customized Throwable serialization

src/main/java/com/bugsnag/android/Bugsnag.java
A couple of methods on the Bugsnag object should be static
This is to address https://github.com/bugsnag/bugsnag-android/issues/129
=> Changed methods that should have been static

src/main/java/com/bugsnag/android/ExceptionHandler.java
Fixes #136. It seems like we should always block on uncaught exception. This is untested for now.
=> Notify blocking on uncaught exception

src/main/java/com/bugsnag/android/Client.java, src/main/java/com/bugsnag/android/ExceptionHandler.java
Previously, unhandled exceptions were sent immediately to the server,
blocking the current thread. In the case that the blocked thread was the
main thread, this caused an exception and prevented the report from
being sent or cached after the fact because the app would then terminate.
This change introduces a third delivery style (in addition to blocking
and non-blocking) which writes the report to the error cache and then
delivers asynchronously (`ASYNC_WITH_CACHE`).
Fixes #138
=> Cache unhandled exceptions prior to delivery

src/main/java/com/bugsnag/android/AppData.java, src/main/java/com/bugsnag/android/Breadcrumbs.java, src/main/java/com/bugsnag/android/Bugsnag.java, src/main/java/com/bugsnag/android/Client.java, src/main/java/com/bugsnag/android/Configuration.java, src/main/java/com/bugsnag/android/DeviceData.java, src/main/java/com/bugsnag/android/Error.java, src/main/java/com/bugsnag/android/Exceptions.java, src/main/java/com/bugsnag/android/MetaData.java, src/main/java/com/bugsnag/android/NativeInterface.java, src/main/java/com/bugsnag/android/NotifyType.java
We are working towards allowing notifies from Android NDK. This will be done using a separate library that depends on the bugsnag-android library.
This PR adds ways for the new NDK library to read and write data from this library:
- Adds a `NativeInterface` class, which is used as the main access point for JNI
- Makes the client class `Observable`, and raises `notifyObservers()` when data gets changed
=> Updates to allow Android NDK plugin to work

src/androidTest/java/com/bugsnag/android/BugsnagTestCase.java, src/androidTest/java/com/bugsnag/android/ClientTest.java, src/androidTest/java/com/bugsnag/android/DeviceDataTest.java, src/main/java/com/bugsnag/android/Client.java, src/main/java/com/bugsnag/android/DeviceData.java
This replaces the use of Settings.Secure.ANDROID_ID with a random UUID, which is generated on each install of the app.
=> Replace android ID with per-install random UUID

example/build.gradle, example/src/main/AndroidManifest.xml, src/androidTest/java/com/bugsnag/android/ClientTest.java, src/main/java/com/bugsnag/android/Client.java
Configuration values can now be supplied as meta-data elements in the manifest, which allows for the use of manifest placeholders.
=> Allow loading different configurations depending on build variant

src/main/java/com/bugsnag/android/AppState.java, src/main/java/com/bugsnag/android/Error.java
Use the activity's class name if no other context has been supplied
=> Update context logic to use activity screen name

src/main/java/com/bugsnag/android/IOUtils.java
In the case that the Closeable throws some other exception (which can
happen on certain devices), this handling gets quite noisy.
Fixes #149
=> Close closeables even more quietly

example/src/main/java/com/bugsnag/android/example/ExampleApplication.java, src/main/java/com/bugsnag/android/Bugsnag.java, src/main/java/com/bugsnag/android/Client.java, src/main/java/com/bugsnag/android/LifecycleBreadcrumbCompat.java, src/main/java/com/bugsnag/android/LifecycleBreadcrumbLogger.java
Automatically leaves breadcrumbs for any change in the Activity Lifecycle for the Application. The breadcrumb includes the name of the Activity, and the name of the lifecycle callback. If the device is below API 14 (<1% of market share), a warning message is logged out.
=> Automatically leave breadcrumbs for Activity Lifecycle callbacks

example/src/main/java/com/bugsnag/android/example/ExampleApplication.java, src/main/java/com/bugsnag/android/Client.java
I observed a crash when rotating the screen on the emulator, due to the eventReceiver not being registered - I believe this should stop that particular case.
=> Fix crash when rotating screen due to EventReceiver

src/main/AndroidManifest.xml, src/main/java/com/bugsnag/android/Client.java, src/main/java/com/bugsnag/android/DefaultHttpClient.java, src/main/java/com/bugsnag/android/ErrorStore.java
This prevents the device radio from powering on when no connection isn't available, which would waste battery.
=> Always check for network connection prior to starting http requests

src/androidTest/java/com/bugsnag/android/EventReceiverTest.java, src/main/java/com/bugsnag/android/Breadcrumbs.java, src/main/java/com/bugsnag/android/EventReceiver.java
Shortens the metadata key if it is originates from an Android package. This prevents the scenario where text such as `android.media.SCO_AUDIO_STATE_CHANGED` is truncated on the dashboard. Also sorts metadata alphabetically in the JSON payload for a more consistent display.
=> Shorten event receiver keys

.travis.yml, example/build.gradle, src/androidTest/java/com/bugsnag/android/ErrorStoreTest.java
Travis CI have switched over to a newer Ubuntu image which doesn't have Android images installed by default. I've also updated the ErrorStoreWriteTest to use a baseline count of files, as it's been a bit flaky
=> Attempt travis fix

sdk/src/androidTest/java/com/bugsnag/android/ClientRejectedExecutionTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorStoreTest.java, sdk/src/androidTest/java/com/bugsnag/android/NullMetadataTest.java, sdk/src/main/java/com/bugsnag/android/Bugsnag.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Configuration.java, sdk/src/main/java/com/bugsnag/android/Error.java, sdk/src/main/java/com/bugsnag/android/MetaData.java
If null is passed in as a metadata parameter, constructs an empty object instead.
I believe this is the most likely cause for #194, where `addToTab` resulted in a NPE.
=> Prevent null metadata

sdk/build.gradle
Exposes the support annotations as a transitive dependency, by replacing `implementation` with `api`. This is required for React Native projects, which are much less likely to have the Google Maven Repo specified than Android projects:
https://github.com/bugsnag/bugsnag-react-native/issues/177
Overview: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#new_configurations
=> Expose Support Annotations dependency transitively

example/build.gradle, example/src/androidTest/java/com/bugsnag/android/CrashReportTest.java, sdk/src/androidTest/java/com/bugsnag/android/LifecycleBreadcrumbLoggerTest.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/LifecycleBreadcrumbLogger.java
Android Lifecycle events can currently be received before the `Client` has been fully constructed, leading to a crash. This updates the `LifecycleBreadcrumbLogger` so that it uses a `Client` object directly, and queues any breadcrumbs if the client is not yet initialised.
=> Enqueue activity lifecycle events when client not initialised

sdk/src/main/java/com/bugsnag/android/Breadcrumbs.java, sdk/src/main/java/com/bugsnag/android/EventReceiver.java
Updates automatic breadcrumbs to capture Intent Actions added in API 26, and removes potentially noisy breadcrumbs from automatic capture. The default maximum breadcrumb store size has also been increased to reflect the fact that we're generally capturing a lot more breadcrumbs automatically.
See #210 for discussion on noisy breadcrumbs appearing on physical devices.
=> Limit auto breadcrumbs

sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Configuration.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
- Respect notifyReleaseStages by not tracking sessions if this config is set
- When autoCaptureSessions is set via config after initialisation, track an existing session if present (required for downstream notifiers)
=> Session tracking amends

sdk/src/main/java/com/bugsnag/android/Bugsnag.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Configuration.java
- Fixes `java.lang.IllegalStateException: You must call Bugsnag.init` crash when enabling auto session capture.
- Remove encapsulation breaking usage of `Bugsnag` client singleton from `Configuration`
- Adds `setAutoCaptureSessions` method to `Client` and `Bugsnag` client singleton
=> Fix crash when enabling auto session capture

sdk/build.gradle
Updates the POM file generation for JCenter so that it creates the same file structure as for mavenCentral. This can be tested by running the `generatePomFileForProductionApplication` task and inspecting the POM file in the build dir.
=> Generate correct pom file for bintrayUpload

.travis.yml, build.gradle, sdk/build.gradle
Adds the `createDebugCoverageReport` task, which generates a Jacoco report under the build folder when run.
=> Enable test coverage with jacoco

example/src/main/AndroidManifest.xml, sdk/src/androidTest/AndroidManifest.xml, sdk/src/androidTest/java/com/bugsnag/android/SessionTrackerTest.java, sdk/src/main/java/com/bugsnag/android/AppData.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
`ActivityManager#getRunningTasks` was deprecated on Lollipop and above. This PR changes the automatic Report context so that it is set as the name of the most recently launched `Activity` which is in the started state, or null if this condition cannot be met.
=> Update context tracking to use lifecycle callbacks

sdk/src/main/java/com/bugsnag/android/DeviceData.java
Guesses whether the app is running on an emulator and adds this to the Device tab.
=> Detect whether running on emulator

features/strict_mode_disc.feature, features/strict_mode_network.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/TestCaseFactory.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeDiscScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/StrictModeNetworkScenario.kt, sdk/src/main/java/com/bugsnag/android/ExceptionHandler.java
Adds a scenario to test Strictmode:
- Disk writes on main thread
- Network requests on main thread
Also prevents the crash handler from crashing due to StrictMode policy violations in the disk write scenario.
=> Add Strictmode scenarios

sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/main/java/com/bugsnag/android/Error.java
The exception message is added to the breadcrumb metadata, which can cause a crash in the NDK when accessing the value via the JNI.
=> Ensure that exception message is never null

sdk/src/androidTest/java/com/bugsnag/android/ConcurrentBeforeNotifyTest.java, sdk/src/androidTest/java/com/bugsnag/android/ConcurrentCallbackTest.java, sdk/src/main/java/com/bugsnag/android/Configuration.java
Prevents a `ConcurrentModificationException` from occurring in the `BeforeNotify` and `BeforeRecordBreadcrumb` callbacks, if an element is added to the collection during or at the same time as `notify` is called.
A `ConcurrentLinkedQueue` is used in place of a `LinkedHashSet` as this retains the order of the callbacks. There's a bit of a tradeoff here with [#127](https://github.com/bugsnag/bugsnag-android/issues/127) - I've added a check to the client method to avoid adding duplicate callbacks, and assumed that anyone adding to the Collection directly knows what they're doing.
=> Prevent ConcurrentModificationException in Before notify/breadcrumb callbacks

features/report_cache.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/ReportCacheScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/Wait.kt
Adds a scenario that checks a report is delivered after caching on disk and the app process is relaunched
=> Add cached report scenario

features/auto_filter.feature, features/manual_filter.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoFilterScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/ManualFilterScenario.kt
Adds a scenario for manually specified and automatic filters to remove sensitive metadata.
Note: the automatic scenario fails due to a bug in the Notifier (separate PR inbound)
=> Add metadata filter scenarios

sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
Ensures that when a custom session tracking api client is set on the client, the sessionTracker field is also updated.
=> Allow setting custom session tracking api client

sdk/src/androidTest/java/com/bugsnag/android/MetaDataTest.java, sdk/src/main/java/com/bugsnag/android/Configuration.java, sdk/src/main/java/com/bugsnag/android/MetaData.java
MetaData filters are currently left as null unless they are explicitly set. This adds a fix and test coverage to prevent this scenario.
Additionally I've added coverage in 2 Maze Runner scenarios: https://github.com/bugsnag/bugsnag-android/pull/262/files
=> add tests for setting metadata filters by default

sdk/src/androidTest/java/com/bugsnag/android/BeforeRecordBreadcrumbsTest.java, sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorStoreTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/androidTest/java/com/bugsnag/android/ExceptionHandlerTest.java, sdk/src/androidTest/java/com/bugsnag/android/JsonStreamTest.java, sdk/src/androidTest/java/com/bugsnag/android/NullMetadataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ReportTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionStoreTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionTrackerTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionTrackingPayloadTest.java, sdk/src/androidTest/java/com/bugsnag/android/StrictModeTest.java
Addresses the following checkstyle warnings in test code:
- Identifiers with <3 alphanumeric chars
- Missing JavaDoc from setup/teardown methods
- Declaration distance from actual usage (addressed by moving closer to usage or adding final modifier)
=> Address remaining test warnings

features/async_error_flush.feature, mazerunner/src/main/java/com/bugsnag/android/TestHarnessHooks.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AsyncErrorConnectivityScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AsyncErrorDoubleFlushScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AsyncErrorLaunchScenario.kt
Adds scenarios which ensure that only 1 request is sent for the following scenarios:
- Connectivity changes immediately before onLaunch flush
- Connectivity changes immediately after onLaunch flush
- Connectivity changes in quick succession
=> Add scenarios for asynchronously flushing error store

sdk/src/androidTest/java/com/bugsnag/android/MetaDataTest.java
Test coverage was previously missing for `metaData.clearTab`, this adds a simple case.
=> Adds coverage for metadata clearTab serialisation

sdk/src/androidTest/java/com/bugsnag/android/ClientConfigTest.java
Adds test coverage in `Client` for miscellaneous properties. Most of these methods call getters on `Configuration`.
=> Add coverage for public methods in client

sdk/src/androidTest/java/com/bugsnag/android/ConfigurationTest.java
Adds test coverage in `Configuration` for miscellaneous properties.
=> Add coverage for public methods in configuration

sdk/src/androidTest/java/com/bugsnag/android/JsonStreamTest.java, sdk/src/main/java/com/bugsnag/android/JsonStream.java
Previously, if the file input was null or empty, an additional comma was added by the JSON serialiser as a separator, leading to invalid JSON, e.g. `[{}, , {}]`. This can lead to session/error payloads being dropped as invalid.
This fixes JSON serialisation so that a comma is not included in this case, e.g. `[{}, {}]`
This doesn't fix the case where a file is non-empty but isn't valid JSON, which will be addressed separately.
=> Avoid adding extra comma separator if File input is empty or null

features/multi_client.feature, mazerunner/src/main/java/com/bugsnag/android/TestHarnessHooks.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoSessionScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/ManualSessionScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiClientApiKeyScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiClientEndpointScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiClientNotifyScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiClientOnlineScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiClientSessionScenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/Wait.kt
Adds the following scenarios when multiple clients are initialised:
- Calling notify while offline is only sent to original client
- Unhandled error while offline is sent twice with different API key for each
- Unhandled error while online is sent twice with different API key for each
- Unhandled error while offline is sent twice with different endpoint for each
- Cached sessions with different API keys are only sent to original client
This also includes a minor change to the TestHarnessHooks which is required to flush the sessions on a per-client basis
Relies on #286
=> Additional multi client scenarios

build.gradle, sdk/build.gradle
Adds a gradle plugin to the sdk which outputs method count on each build.
It may be worth adding a limit that fails the build using `maxMethodCount`, e.g. 1,200. This would prevent the case where a large library inadvertently gets added as a dependency, or where the number of methods creeps up over time without adding new functionality.
It may be worth investigating similar tooling for other platforms.
=> Track dex count

mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt
Reads the metadata flag set by mazerunner, and parses it into the scenario. This can be useful if a scenario requires two or more distinct types of behaviour, as `eventMetaData` can be set to different values e.g. `"foo"` and `"bar"`
Originates from #286
=> test: add event metadata flag to mazerunner

sdk/src/androidTest/java/com/bugsnag/android/ErrorStoreTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionStoreTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionTrackingPayloadTest.java, sdk/src/main/java/com/bugsnag/android/ErrorStore.java, sdk/src/main/java/com/bugsnag/android/FileStore.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
We sometimes receive invalid payloads with an empty/malformed array where an error/session should be - e.g. `[]` or `[,]`. My hypothesis is that this occurs when the max limit of Error/Sessions are cached on disk. When the app is relaunched, if `write` is called just before the payload is serialised, then this can lead to the oldest File being deleted, which means there is no data to serialise.
This attempts to address this scenario by retaining a reference to any Files which are currently being flushed, and not deleting them.
A potential downside to this implementation is that it currently requires manually calling `cancelQueuedFiles` and `deleteStoredFiles`, which could be forgotten.
=> Filestore thread safety fixes

sdk/src/androidTest/java/com/bugsnag/android/BreadcrumbLifecycleCrashTest.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
Change `SessionTracker` to ignore exceptions when creating lifecycle breadcrumb before a client is fully constructed. This uses the same logic as `EventReceiver`.
=> fix: prevent potential lifecycle breadcrumb crash

sdk/build.gradle, sdk/src/main/java/com/bugsnag/android/StrictModeHandler.java
Run all android lint inspections, and fail the build with an error if any warnings are found. Suppresses the one existing warning in the module.
=> build: make android lint stricter

sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java
Adds test coverage for addToTab and clearTab client methods. The metadata internals themselves are already covered in existing tests
=> Add coverage for client metadata tab methods

sdk/src/androidTest/java/com/bugsnag/android/BreadcrumbsTest.java, sdk/src/main/java/com/bugsnag/android/Client.java
The breadcrumb message should be serialised as part of the metadata, not as the name attribute.
=> Fix: serialise breadcrumb message correctly

sdk/src/androidTest/java/com/bugsnag/android/ClientNotifyAsyncTest.java, sdk/src/androidTest/java/com/bugsnag/android/ClientNotifyTest.java
Uses a countdown latch rather than sleeping for 1ms to check whether a method is async. This seems to fail rather consistently at the moment on Travis API 21 emulators, which are faster than the 16/19 ones.
This implementation splits the test into two classes - one with blocking calls, and one with async.
=> refactor: potential fix for flaky async client notify tests

sdk/src/androidTest/java/com/bugsnag/android/JsonWriterTest.java, sdk/src/main/java/com/bugsnag/android/DefaultHttpClient.java, sdk/src/main/java/com/bugsnag/android/FileStore.java, sdk/src/main/java/com/bugsnag/android/JsonStream.java
`FileReader` and `FileWriter` are not buffered, meaning they are slow. This change wraps all IO streams in a buffered reader/writer which in an (unscientific) unit test of the ErrorStore, reduced the write of an error from ~230ms to ~115ms.
This also allows us to specify the charset encoding explicitly, which is a potential (but unproven) cause for File serialisation issues on devices from certain manufacturers.
=> Perf: use buffered streams for IO

sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java
Adds tests which cover client breadcrumb methods directly - other tests already verify the behaviour of the breadcrumbs class itself.
=> Add client breadcrumbs code coverage

sdk/src/androidTest/java/com/bugsnag/android/JsonWriterTest.java
Improve code coverage for JsonWriter by using existing tests in GSON repository. This should give more confidence to update the library in future.
A test from the [GSON repo](https://github.com/google/gson/blob/ada597e69a78b8b99f79f79493cbf51e16045202/gson/src/test/java/com/google/gson/stream/JsonWriterTest.java).
I've done a little monkey-patching by adding `Test` annotations to get this running on our current setup. I have also edited `testTopLevelValueTypes` as the API syntax appears to have changed in later versions of GSON, and omitted `testNonFiniteDoublesWhenLenient` entirely as it appears our notifier contains an older version of JsonWriter which is affected by this bug.
Should we also update JsonWriter with this change?
- This pull request …
=> test: Add JsonWriter test from GSON repo

sdk/src/main/java/com/bugsnag/android/EventReceiver.java
Removes duplicate keys from the `EventReceiver` map, detected via an Android Studio Lint warning
=> refactor: Removes duplicate keys from eventreceiver map

Makefile, README.md
Invoke ~arcane magic~ awk to update the badge for library sizes when running the release and bump tasks. Also added more checks to ensure the git status is clean before running.
=> build: Automatically update dex / size / count badge during release

CHANGELOG.md, features/startup_crash.feature, features/steps/build_steps.rb, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/StartupCrashFlushScenario.kt, sdk/src/main/java/com/bugsnag/android/ErrorStore.java
Some unhandled error reports aren't being sent immediately on Android P and in situations with no connectivity.
Internally `FileStore` retains a `Collection` of files which have previously been found for a request, to prevent duplicate reports being sent. This puts the onus on the calling code to cancel or delete the files once the request has been completed. 
This changeset ensures that these files are only requested once when calling `flushOnLaunch`, then cancels all files after delivery has taken place (successfully or not), which resets the `FileStore` state.
After this, `flushAsync` is then called, which will flush any remaining reports that have not yet been delivered.
`FileStore` (see above description)
Manual test on Android P simulator of unhandled crashes. Mazerunner scenario …
=> Android P FileStore flush fix

build.gradle, example/build.gradle, examplelib/build.gradle, mazerunner/build.gradle, sdk/build.gradle
JCenter started silently proxying the google maven repo, whose artefacts have incorrect checksums. This results in a 409 status code, meaning gradle is unable to resolve required google dependencies and the entire build breaks
`google()` is specified before `jcenter()`, which alters the order of resolution of dependencies.
Move away from jcenter in favour of maven central.
=> Fixes jcenter breaking our build by specifying the google repo first

CHANGELOG.md, features/trimmed_stacktrace.feature, mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/TrimmedStacktraceScenario.kt, sdk/src/androidTest/java/com/bugsnag/android/StacktraceTest.java, sdk/src/main/java/com/bugsnag/android/ExceptionHandler.java, sdk/src/main/java/com/bugsnag/android/Stacktrace.java
Trims very long stacktraces by ensuring that only the first 200 stack frames are serialised. This should ensure that for a stacktrace with 10^6 stackframes, the notifier will still deliver unhandled errors, and the pipeline won't drop the request.
Additionally, `Logger` is used rather than `printStacktrace`. The former is redirected by Android to logcat, but a message limit can result in
an SSLException being thrown for large messages. `Logger` uses logcat internally and is disabled in production by default, which should prevent these issues affecting users.
- Stacktrace serialisation now ends after 200 frames have been processed.
- Throwables are put through the `Logger` rather than `printStacktrace`.
Added a mazerunner scenario and JUnit test.
I've picked 200 frames as it seemed like a …
=> Trim very long stacktraces

sdk/src/main/java/com/bugsnag/android/Report.java
Document existing public accessors on the Report object, and add nullability annotations.
- Nullability annotations
- Accessors/JavaDoc
- Deprecated notifier proxy methods in favour of accessing the `notifier` object directly
=> refactor: Document Report accessors

sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Error.java
Adds public accessors to Error, for use by 3rd party developers and internal API, and nullability annotations.
Note: the intention is for further work to be carried out in a separate PR (extracting the data capture to a separate class, etc)
Converted fields/methods to properties (getter/setter backed with a field) in Error.
Adapted unit tests for the default value + override value of each accessor.
=> feat: add public accessors to error class

sdk/src/androidTest/java/com/bugsnag/android/NotifierTest.java, sdk/src/main/java/com/bugsnag/android/Notifier.java
Adds public accessors to Notifer, for use as internal API (denoted with marker annotation).
Converted fields/methods to properties (getter/setter backed with a field) in Notifier.
Added a unit test for JSON serialisation, and a test for the default value + override value of each accessor.
=> refactor: Add accessors for notifier class

sdk/src/main/java/com/bugsnag/android/Breadcrumb.java
We need to be able to read all of the breadcrumb properties from the unity notifier and this is the only one that is missing
=> Add timestamp accessor to breadcrumb

sdk/build.gradle
This contains a few fields and a class which is useless to consumers and unused by the library. It's removed by ProGuard and R8, but by not even generating it those bytes are saved for all consumers.
=> Disable BuildConfig generation

sdk/src/androidTest/java/com/bugsnag/android/AppDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/BeforeNotifyTest.java, sdk/src/androidTest/java/com/bugsnag/android/BreadcrumbLifecycleCrashTest.java, sdk/src/androidTest/java/com/bugsnag/android/ConfigurationTest.java, sdk/src/androidTest/java/com/bugsnag/android/DeviceDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/androidTest/java/com/bugsnag/android/ExceptionsTest.java, sdk/src/androidTest/java/com/bugsnag/android/JsonStreamTest.java, sdk/src/androidTest/java/com/bugsnag/android/ReportTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionStoreTest.java
[This](https://travis-ci.org/bugsnag/bugsnag-android/jobs/392772873) test run failed. While our CI problems are far better since merging #326, it seems as though a few tests still generate a client without cancelling Async tasks as part of their teardown. 
This PR addresses that by cancelling tasks in any test where it is not immediately obvious that Async tasks aren't invoked.
Longer term we should fix this by separating out the initialisation of background tasks to a separate method in the `Client`, rather than the constructor.
=> test: cancel any background tasks in test runs

CHANGELOG.md, sdk/build.gradle, sdk/proguard-rules.pro
Adds ProGuard keep rules to the AAR artefact. This means that the library will work correctly when minification is enabled, without relying on the bugsnag gradle plugin to edit the library's proguard files.
This allows users to avoid using the bugsnag gradle plugin if they so wish, without any additional configuration of ProGuard on their part.
Added a proguard file with keep rules for the relevant classes.
Used Android Studio's APK analyzer to verify that an example project without the gradle plugin applied retained the correct classes in its Dex file.
- We may want to consider the task in our gradle plugin which adds these rules automatically. The risk of this is that it could break builds for anyone who doesn't 
read the release notes.
- Do we need to update [the …
=> Specify consumer Proguard files

sdk/proguard-rules.pro
Automatically keep source file and line number information with ProGuard, as otherwise grouping is likely to differ for existing projects.
Related to #345 
=> feat: update proguard rules to keep line number/source info

sdk/build.gradle, sdk/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java, sdk/src/androidTest/java/com/bugsnag/android/ClientConfigTest.java, sdk/src/androidTest/java/com/bugsnag/android/ClientNotifyTest.java, sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/ConfigurationTest.java, sdk/src/androidTest/java/com/bugsnag/android/CustomException.java, sdk/src/androidTest/java/com/bugsnag/android/DeliveryCompatTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorReportApiClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/MetaDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/NullMetadataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ReportTest.java, sdk/src/main/java/com/bugsnag/android/BadResponseException.java, sdk/src/main/java/com/bugsnag/android/Bugsnag.java, sdk/src/main/java/com/bugsnag/android/BugsnagException.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/DeliveryCompat.java, sdk/src/main/java/com/bugsnag/android/DeliveryFailureException.java, sdk/src/main/java/com/bugsnag/android/DeviceData.java, sdk/src/main/java/com/bugsnag/android/JsonWriter.java, sdk/src/main/java/com/bugsnag/android/MetaData.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java, sdk/src/main/java/com/bugsnag/android/NetworkException.java, sdk/src/main/java/com/bugsnag/android/ObjectJsonStreamer.java
Detect compiler warnings introduced in changes to Java code quickly.
- Updated gradle to error on any warnings during compilation
- Suppressed deprecation warnings for use of deprecated APIs (both internal + external)
- Added missing `serialVersionUID` field to serializable classes
- Annotated public methods as deprecated when this had only been done in JavaDoc
- Suppress or address generic warnings (mostly caused by type erasure)
Ran tests on CI, manual test to ensure compilation errors in example project don't break build
=> refactor: fail build on compiler warnings

CHANGELOG.md, sdk/src/androidTest/java/com/bugsnag/android/StrictModeTest.java, sdk/src/main/java/com/bugsnag/android/StrictModeHandler.java
Test compatibility with Android P preview and make any necessary fixes.
- Make StrictMode check insensitive
- Alter the test assertion on P devices for StrictMode. The exception message has changed so that we can't parse the violation code, meaning a full description isn't possible to obtain, although we can still detect that _some_ issue occurred.
- Local unit tests
- Manual tests with dashboard
- Read the new features + changes to find any relevant changes https://android-developers.googleblog.com/2018/07/final-preview-update-official-android-p.html
- Mazerunner scenarios. It's worth noting that unhandled scenarios don't pass because P is more strict about killing the app after an exception, and the notifier would now deliver reports on the next app launch. As the scenarios fail due to …
=> Android P compatibility changes

sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/ConfigFactory.java
This changeset is intended to reduce the complexity of the `Client` class, which is currently 757 SLOC. This is partially achieved by extracting the logic to populate `Configuration` from the AndroidManifest to a separate class.
- Moves code which populates a configuration object from the AndroidManifest into a separate `ConfigFactory` class
- Update test imports to pass build
Ran unit tests, mazerunner
=> refactor: Moves configuration creation for manifest to separate class

Gemfile.lock, features/error_reporting_thread.feature
Adds a mazerunner scenario which validates that only 1 thread sets the `errorReportingThread` flag in the payload, when a handled exception is delivered on the main thread.
=> Add mazerunner scenario for thread id

ndk/build.gradle, sdk/build.gradle
In the bugsnag-android-ndk repository, the `NEXUS_USERNAME` and `NEXUS_PASSWORD` credentials were supplied as an [envar on Travis](https://github.com/bugsnag/bugsnag-android-ndk/blob/master/build.gradle#L96). This changeset alters the SDK + NDK build script to use the previous method of supplying the username/password, which passes the lint/unit test steps.
The mazerunner scenarios seem to have passed one job, but are having a bit of trouble with timeouts. I will try restarting the jobs, but this would be worth keeping an eye on.
=> Fix Travis CI build

CHANGELOG.md, examples/sdk-app-example/proguard.pro, scripts/infer.sh, sdk/build.gradle, sdk/src/main/java/com/bugsnag/android/BadResponseException.java, sdk/src/main/java/com/bugsnag/android/BeforeNotify.java, sdk/src/main/java/com/bugsnag/android/BeforeRecordBreadcrumb.java, sdk/src/main/java/com/bugsnag/android/BreadcrumbType.java, sdk/src/main/java/com/bugsnag/android/BugsnagException.java, sdk/src/main/java/com/bugsnag/android/DateUtils.java, sdk/src/main/java/com/bugsnag/android/DeliveryCompat.java, sdk/src/main/java/com/bugsnag/android/DeliveryFailureException.java, sdk/src/main/java/com/bugsnag/android/DeliveryStyle.java, sdk/src/main/java/com/bugsnag/android/DeviceData.java, sdk/src/main/java/com/bugsnag/android/ErrorReportApiClient.java, sdk/src/main/java/com/bugsnag/android/ErrorStore.java, sdk/src/main/java/com/bugsnag/android/FileStore.java, sdk/src/main/java/com/bugsnag/android/IOUtils.java, sdk/src/main/java/com/bugsnag/android/JsonStream.java, sdk/src/main/java/com/bugsnag/android/JsonWriter.java, sdk/src/main/java/com/bugsnag/android/Logger.java, sdk/src/main/java/com/bugsnag/android/MapUtils.java, sdk/src/main/java/com/bugsnag/android/NetworkException.java, sdk/src/main/java/com/bugsnag/android/NotifyType.java, sdk/src/main/java/com/bugsnag/android/SessionStore.java, sdk/src/main/java/com/bugsnag/android/SessionTrackingApiClient.java, sdk/src/main/java/com/bugsnag/android/StrictModeHandler.java, sdk/src/main/java/com/bugsnag/android/ThreadSafe.java
Removes the need for a compile-time dependency on the infer-annotation artefact.
- Added `@ThreadSafe` annotation to bugsnag package
- Removed imports of infer-annotation 
- Altered build process so that the `infer` property must be set to compile infer-annotation artefact
- Ran `./infer.sh`
- Ran `./gradlew sdk:assemble` to confirm
- Ran `generatePomFileForProductionPublication` task to confirm that the generated POM excludes the infer-annotation dependency.
- Ran existing unit/mazerunner tests on CI
We could attempt forking Uber's [infer plugin](https://github.com/uber-common/infer-plugin), which is deprecated.
Fixes #366 
=> Add ThreadSafe annotation to com.bugsnag.android, remove infer dependency

CONTRIBUTING.md
Updates the release notes to address any unclear points that were discovered when doing a release.
=> docs: update release notes based on previous snags

CHANGELOG.md, features/before_send.feature, features/fixtures/mazerunner/src/main/cpp/bugsnags.cpp, features/fixtures/mazerunner/src/main/cpp/entrypoint.cpp, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/BeforeSendScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/NativeBeforeSendScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/NativeNotifyBeforeSendScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/NotifyBeforeSendScenario.java, sdk/src/androidTest/java/com/bugsnag/android/BeforeSendTest.java, sdk/src/androidTest/java/com/bugsnag/android/CachedThreadTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorReaderTest.java, sdk/src/androidTest/res/raw/error.json, sdk/src/main/java/com/bugsnag/android/BeforeNotify.java, sdk/src/main/java/com/bugsnag/android/BeforeSend.java, sdk/src/main/java/com/bugsnag/android/Breadcrumb.java, sdk/src/main/java/com/bugsnag/android/Bugsnag.java, sdk/src/main/java/com/bugsnag/android/CachedThread.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Configuration.java, sdk/src/main/java/com/bugsnag/android/DateUtils.java, sdk/src/main/java/com/bugsnag/android/Error.java, sdk/src/main/java/com/bugsnag/android/ErrorReader.java, sdk/src/main/java/com/bugsnag/android/ErrorStore.java, sdk/src/main/java/com/bugsnag/android/Exceptions.java, sdk/src/main/java/com/bugsnag/android/HandledState.java, sdk/src/main/java/com/bugsnag/android/Session.java, sdk/src/main/java/com/bugsnag/android/ThreadState.java
Added support for modifying all reports (including native crash reports) prior to delivery.
Added new functionality to convert an Error cached on disk back into an Error object, which is then added to reports. The new callbacks are run on the resulting report object just prior to delivery.
|||
|--|--|
|Source| `15 files changed, 645 insertions(+), 33 deletions(-)`|
|Tests| `14 files changed, 1166 insertions(+), 7 deletions(-)` (mostly fixtures)|
* `ErrorReader` - A collection of static methods to read a report from a file, throwing an exception if the report is in some way invalid (such as broken JSON or missing required fields)
* `Configuration.beforeSend` - New callbacks are added to the configuration directly before calling `Bugsnag.init`
* `Report.errorFile` - when constructed with a …
=> feat: Run report modification callbacks before native crash reports

CHANGELOG.md, features/before_send.feature, features/error_context.feature, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/ArgumentContextScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/NotifyBeforeSendUnsetContextScenario.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/main/java/com/bugsnag/android/AppData.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Error.java
* Moved automatic context detection from during serialization to capture-time, which is in `Client`
* Deleted a test for the context logic in Error
* (Other scenarios cover automatic context assignment and setting context to a new value)
=> feat: Allow setting context to null from beforeSend

CHANGELOG.md, ndk/src/main/CMakeLists.txt, ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java, ndk/src/main/jni/bugsnag_ndk.c, ndk/src/main/jni/external/libunwind/include/__libunwind_config.h, ndk/src/main/jni/external/libunwind/include/libunwind.h, ndk/src/main/jni/utils/stack_unwinder.c, ndk/src/main/jni/utils/stack_unwinder.h, ndk/src/main/jni/utils/stack_unwinder_libunwind.c, ndk/src/main/jni/utils/stack_unwinder_libunwind.h
Small refactor of the API 21+ stack unwinding logic to restrict 32-bit
unwinding style from 64-bit devices. 
While the stack enhancements added in #378 are intended only to be run
on 32-bit devices and gated to the __arm__ build, when 64-bit devices
are running the 32-bit library, the stacktraces for those devices were
unintentionally affected. 
This is the case when an app is configured to only run 32-bit binaries 
(Android cannot run both 64-bit and 32-bit binaries at once), and many
popular libraries (e.g. React Native) only distribute 32-bit libraries.
Added additional improvement to the 32-bit stacktrace resolution by
switching to nongnu libunwind only for those devices. This significantly
improves the number of frames which can be unwound without risk of a
segfault.
* Tested against …
=> fix(ndk): Ensure 64-bit devices running 32-bit binaries do not use 32-bit device unwinding logic

sdk/src/androidTest/java/com/bugsnag/android/NativeInterfaceTest.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java
Adds a method for getting and leaving breadcrumbs, intended for use by downstream notifiers such as Unity.
Additionally, the `getMetaData` method has been changed to return a copy of the metadata store.
Added unit test for `getMetaData` change, performed manual testing of methods in Unity integration.
=> Add additional methods to NativeInterface for use by Unity Notifier

CHANGELOG.md, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/MetaDataNestedNullScenario.kt, features/meta_data_scenario.feature, gradle.properties, sdk/src/androidTest/java/com/bugsnag/android/MetaDataMergeTest.java, sdk/src/main/java/com/bugsnag/android/MetaData.java, sdk/src/main/java/com/bugsnag/android/Notifier.java
Prevent NPE crash when attempting to deliver error reports.
`MetaData` tab values can be `HashMaps`, whose entries can be null. `MetaData.mergeMaps` seemed to assume that the `Map` was always a `ConcurrentHashMap`, whose entries cannot be null. 
On React Native this manifested as a NPE when merging `config.metaData` and `report.metaData` due to `app.activeScreen` being intermittently recorded as null. This can occur on any platform which uses bugsnag-android, however.
Added a null check when adding the base value to the merged map.
Wrote unit test + mazerunner scenario, and manually verified that valid reports are sent from a React Native example app using a local bugsnag-android artefact.
For the pull request …
=> Handle null values in MetaData.mergeMaps, preventing potential NPE

CONTRIBUTING.md, build.gradle
The bintray gradle plugin was updated for [compatibility with gradle 4.8](https://github.com/bintray/gradle-bintray-plugin/pull/243), but we did not update when we last updated the gradle wrapper. This broke the upload of artefacts to bintray when running `./gradlew bintrayUpload` - updating the plugin resolves this issue.
Additionally, the task for uploading artefacts to sonatype specified in the release steps has been wrong since the [NDK integration was altered](https://github.com/bugsnag/bugsnag-android/commits/master/sdk/build.gradle) - the correct task is now specified in the release steps.
=> Fix bintray gradle plugin failure, update release steps gradle task

build.gradle, examples/sdk-app-example/build.gradle, features/fixtures/mazerunner/build.gradle, sdk/build.gradle, sdk/lint-baseline.xml, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/ErrorStore.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
Update the AGP to v3.2+, to enable the `SyntheticAccessor` lint check. Synthetic accessors are generated when an inner class accesses a private method or field in its enclosing class, for example:
```
class Foo {
private Bar bar;
class Baz {
Baz() {
bar.toString(); // creates a synthetic accessor method to access bar
}
}
}
```
- Update AGP to v3.2.1 (latest stable)
- Update Kotlin version to v1.3.10 (latest stable), as AGP v3.2.1 only supports Kotlin 1.2.71+
- Migrate to `kotlin-stdlib` dependency, as the deprecated `kotlin-stdlib-jre` artefact is not available in 1.3.10
- Adds baseline lint file to suppress existing issues for `UnknownNullness` and `KotlinPropertyAccess`.
- Relax visibility of methods/fields identified in `SyntheticAccessor` lint check to package-private, which removes 8 …
=> Update Android Gradle Plugin to v3.2.1

CHANGELOG.md, features/native_api.feature, features/native_crash_handling.feature, ndk/src/main/jni/bugsnag.c, ndk/src/main/jni/metadata.c, ndk/src/main/jni/metadata.h, ndk/src/main/jni/report.h, ndk/src/main/jni/utils/serializer.c, sdk/src/main/java/com/bugsnag/android/AppData.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java
64-bit devices on Android can load 32-bit libraries, as mixing between 32/64 bits is not allowed. This changeset explicitly adds the binary arch used by the app at runtime to handled and unhandled reports, to allow the pipeline to select the correct mapping file for stacktrace deobfuscation.
- Added `bsg_binary_arch` to calculate the current architecture.
- Added field to handled native reports by setting the binary arch on `bugsnag_init`, via the `NativeInterface`.
- Added field to unhandled native reports by setting the binary arch in the serializer.
Altered existing mazerunner scenarios to ensure that a handled/unhandled native exception contain the `app.binaryArch` field.
=> Add binary architecture of application to payload

sdk/lint-baseline.xml, sdk/src/androidTest/java/com/bugsnag/android/ClientConfigTest.java, sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/ConfigurationTest.java, sdk/src/main/java/com/bugsnag/android/Configuration.java, sdk/src/main/java/com/bugsnag/android/Error.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
If public getters/setters are available for a Java field, then this code can be called from Kotlin using the [property access syntax](https://kotlinlang.org/docs/reference/java-interop.html#getters-and-setters). This gives users the choice of using a more Kotlin-esque syntax:
```
config.autoCaptureSessions = false
```
while retaining backward compatibility with the previous interface:
```
config.setAutoCaptureSessions(false)
```
- A public getter and setter were added for the `autoCaptureSessions`, `codeBundleId`, and `notifierType` properties.
- `shouldAutoCaptureSessions()` was deprecated and forward onto `getAutoCaptureSessions()`
- Internal use of `shouldAutoCaptureSessions()` was changed to `getAutoCaptureSessions()` to avoid using deprecated code
- All `KotlinPropertyAccess` checks …
=> Improve kotlin support by allowing property access

CHANGELOG.md, sdk/src/main/java/com/bugsnag/android/Client.java
Calling `bugsnag.notify(exc)` resulted in the creation of a self-referencing breadcrumb. For example, if notify was called once, this would be the result:
This changeset fixes the behaviour so that breadcrumbs about previous errors are only added _after_ an error has been serialised.
The Android Notifier has [3 delivery styles when notifying](https://github.com/bugsnag/bugsnag-android/blob/master/sdk/src/main/java/com/bugsnag/android/Client.java#L873
): delivering immediately on the calling thread, delivering on a background thread, and writing on the calling thread then delivering on a background thread. The first two options can be called by users reporting handled exceptions, whereas the third option can only occur when an unhandled exception is propagated to our handler.
In the old …
=> Prevent errors from leaving a self-referencing breadcrumb

features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/InForegroundScenario.kt, features/in_foreground.feature, features/steps/build_steps.rb, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
If `autoCaptureSessions` is set to false, the `app.durationInForeground` value always equals 0 in reports.
Additionally, if the app is put into the background and then brought back into the foreground within a 30 second threshold, the `durationInForeground` value is not reset, and can be erroneously large.
This changeset fixes these two issues.
Please see the design doc for a detailed overview.
Added a mazerunner scenario to verify that `durationInForeground` is > 0 when `autoCaptureSessions` is false. Additionally, manual testing checked the following scenarios, for both potential values of `autoCaptureSessions`:
- Handled/Unhandled exceptions have non-zero value for `durationInForeground`
- Putting the activity in the background (by clicking the home button then recent tasks button) …
=> Fix calculation of durationInForeground when autoCaptureSessions is false

CHANGELOG.md, features/bugsnag_init.feature, features/fixtures/mazerunner/src/main/AndroidManifest.xml, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/BugsnagInitScenario.kt, sdk/src/main/java/com/bugsnag/android/Bugsnag.java
If `Bugsnag.init` is called multiple times, multiple `Client` objects will be instantiated. This is generally not the desired behaviour, could lead to undesired side-effects, and is also a very expensive operation (approx 100ms for each initialisation on a test device).
For a real world example, if `Bugsnag.init` is called from within `onCreate` in an `Activity` rather than an `Application` subclass, it's possible that multiple clients could be instantiated over the [app's lifecycle](https://developer.android.com/guide/components/activities/intro-activities#mtal).
This changeset alters `Bugsnag.init` so that it will only instantiate a `Client` if one hasn't been created already. For exceptional cases where a user needs to instantiate multiple `Client` objects, it remains possible to do so …
=> Prevent Bugsnag.init from instantiating more than one client

CHANGELOG.md, features/handled_exception.feature, features/native_api.feature, features/native_crash_handling.feature, features/steps/build_steps.rb, features/unhandled_exception.feature, ndk/src/main/jni/utils/serializer.c, sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/DeviceDataSummaryTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorReaderTest.java, sdk/src/androidTest/res/raw/error.json, sdk/src/main/java/com/bugsnag/android/DeviceData.java
The `cpuAbi` field has been added to structured data within the payload, so should ideally be present at `device.cpuAbi`.
The cpuAbi array is now added into the `device` object for both the Java + C report serialisers.
Existing unit tests for JVM serialisation have been updated, and additional steps have been added to mazerunner scenarios to validate the location of this field.
I also manually inspected the payload for handled/unhandled JVM + C crashes, and verified that the field only existed at `device.cpuAbi`.
=> Migrate metaData.device.cpuAbi to device.cpuAbi in JSON payload

CHANGELOG.md, sdk/src/main/java/com/bugsnag/android/Configuration.java
The accessors for `metadata` in `Configuration` are currently `protected`, so are not accessible despite being documented as such. Altering their visibility to `public` will allow these methods to be used as part of our API.
=> Make config.metadata publicly accessible

CONTRIBUTING.md
We upload to Maven Central + JCenter, but the release instructions missed out the task for uploading to Bintray.
=> add missing command to upload to bintray

CHANGELOG.md, ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/DeviceData.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java
On initialisation of bugsnag-android, `calculateFreeDisk` was indirectly invoked, which performs IO on the main thread. This triggers unnecessary [StrictMode](https://developer.android.com/reference/android/os/StrictMode) violations, which can be observed by integrating the SDK into any app, and viewing logcat output on launch.
`getDeviceData()` triggers these calculations. In the case of initialisation, the free disk information is not actually required, so the `DeviceData` class was adapted to add accessors for only the necessary information.
It's worth noting that there will still be a violation when notifying of an error, as we need to calculate the freeDisk information each time at this point.
Added accessors for `device.id` and `device.cpuAbi`.
Enabled StrictMode in the example app …
=> Prevent unnecessary free disk calculations on initialisation

sdk/src/androidTest/AndroidManifest.xml, sdk/src/androidTest/java/com/bugsnag/android/AppDataSummaryTest.java, sdk/src/androidTest/java/com/bugsnag/android/AppDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/BeforeRecordBreadcrumbsTest.java, sdk/src/androidTest/java/com/bugsnag/android/BeforeSendTest.java, sdk/src/androidTest/java/com/bugsnag/android/BreadcrumbLifecycleCrashTest.java, sdk/src/androidTest/java/com/bugsnag/android/BreadcrumbsTest.kt, sdk/src/androidTest/java/com/bugsnag/android/ClientConfigTest.java, sdk/src/androidTest/java/com/bugsnag/android/ClientNotifyTest.java, sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/ConcurrentCallbackTest.java, sdk/src/androidTest/java/com/bugsnag/android/ConfigurationTest.java, sdk/src/androidTest/java/com/bugsnag/android/DeliveryCompatTest.java, sdk/src/androidTest/java/com/bugsnag/android/DeviceDataSummaryTest.java, sdk/src/androidTest/java/com/bugsnag/android/DeviceDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorReportApiClientTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/androidTest/java/com/bugsnag/android/ExceptionHandlerTest.java, sdk/src/androidTest/java/com/bugsnag/android/ExceptionsTest.java, sdk/src/androidTest/java/com/bugsnag/android/JsonStreamTest.java, sdk/src/androidTest/java/com/bugsnag/android/MetaDataTest.java, sdk/src/androidTest/java/com/bugsnag/android/NullMetadataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, sdk/src/androidTest/java/com/bugsnag/android/ReportTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionStoreTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionTrackerTest.java, sdk/src/androidTest/java/com/bugsnag/android/TestRunListener.kt, sdk/src/androidTest/java/com/bugsnag/android/UniqueBeforeNotifyTest.java
Our instrumentation tests currently need to cancel asynchronous tasks which are started within the `Client` constructor, at the end of each test run. The code that achieves this is currently spread out across multiple classes and easy to forget to add to new tests.
JUnit offers a `RunListener` interface, which has a method that is invoked after each test is completed. Specifying this is preferable to using `@After` for teardown, as we only need to cancel asynchronous tasks from one place.
Added a custom `RunListener`, which can be [invoked after each test finishes](https://developer.android.com/reference/android/support/test/runner/AndroidJUnitRunner#typical-usage). This cancels tasks which have been submitted to the Executor.
=> Simplify test teardown using a RunListener

CHANGELOG.md, sdk/src/main/java/com/bugsnag/android/DeviceData.java
By default, we should cache the result of whether the device is rooted or not, as the result is unlikely to change between app launches and the calculation requires IO.
Cached the result of the root check in a field when `DeviceData` is constructed.
Enabled StrictMode in the example app and verified that only one stacktrace was logged on initialisation, when filtering by 'isRooted'.
=> Cache result of device root check

build.gradle, examples/sdk-app-example/build.gradle, gradle/wrapper/gradle-wrapper.properties
Updates the Android Gradle Plugin + Gradle wrapper to the latest versions recommended by Android Studio 3.3. Additionally, the Bugsnag notifier + plugin dependencies have been updated to the latest available release in the example app.
This changeset should have no effect on the compile-time dependencies of the SDK or NDK artefacts.
Ran existing on CI.
=> Update dependencies to latest stable versions

CHANGELOG.md, sdk/src/main/java/com/bugsnag/android/JsonScope.java, sdk/src/main/java/com/bugsnag/android/JsonStream.java, sdk/src/main/java/com/bugsnag/android/JsonWriter.java
The `JsonWriter` class was originally vendored in 2014, and has not been updated since then despite bug fixes to the GSON library.
It was originally suggested that we use the framework version of `JsonWriter`. However, this approach has several issues:
1. The framework class is `final`, therefore cannot be extended in Java, meaning we would need to make substantial modifications to our implementation of `JsonStream`
2. `setSerializeNulls` is not present, meaning we would always serialize null values if we used the framework version
3. The `beforeValue` method is private and therefore cannot be accessed, meaning we would need to make further alterations to `JsonStream` to support serialising a file.
Therefore the lowest risk approach seemed to be updating the vendored GSON dependency, …
=> Update vendored GSON dependency to latest available version

CHANGELOG.md, sdk/src/main/java/com/bugsnag/android/ErrorReader.java
The `ErrorReader` class is hard to read in places which may have contributed to #418. This changeset attempts to improve readability by extracting methods so that each has a single responsibility.
Breadcrumbs, stackframes, and threads are all serialised as a JSON array in the error report. The current implementation completes something like the following steps in a single method:
```
// 1. old scheme
void readBreadcrumbs() {
// create an array
// iterate around array objects
// deserialise a breadcrumb
// end an array
}
```
The step of deserialising individual JSON objects has now been extracted to a separate method, like thus:
```
// 2. new scheme
void readBreadcrumbs() {
// create an array
// iterate around array objects
breadcrumbs.add(readBreadcrumb())
// end an array
}
Breadcrumb …
```
=> Refactor error report deserialisation

CHANGELOG.md, sdk/src/androidTest/java/com/bugsnag/android/RxErrorTest.kt, sdk/src/androidTest/res/raw/rx_error.json, sdk/src/main/java/com/bugsnag/android/BugsnagException.java, sdk/src/main/java/com/bugsnag/android/ErrorReader.java
When a `beforeSend` callback is specified, deserialisation of cached error reports fails if the exception has an [additional cause](https://developer.android.com/reference/java/lang/Throwable.html#getCause()). This prevents delivery of the error report to Bugsnag.
This changeset fixes #417 by altering the `ErrorReader` class to handle this scenario.
The `ErrorReader` class assumed that only 1 exception could be present in an array. The implementation has therefore been altered to serialise every object in the array. The first object is considered the root `Throwable`, and any additional exceptions are deserialised by using [`initCause`](https://developer.android.com/reference/java/lang/Throwable.html#initCause(java.lang.Throwable)). This is effectively just performing the inverse of …
=> Fix cached error deserialisation where the Throwable has a cause

.gitmodules, CONTRIBUTING.md, LICENSE.txt, checkstyle.gradle, ndk/src/main/CMakeLists.txt, ndk/src/main/jni/bugsnag_ndk.c, ndk/src/main/jni/bugsnag_ndk.h, ndk/src/main/jni/handlers/signal_handler.c, ndk/src/main/jni/utils/stack_unwinder.c, ndk/src/main/jni/utils/stack_unwinder.h, ndk/src/main/jni/utils/stack_unwinder_libunwind.c, ndk/src/main/jni/utils/stack_unwinder_libunwindstack.cpp, ndk/src/main/jni/utils/stack_unwinder_libunwindstack.h
When capturing a stacktrace from a signal handler or C++ terminate 
handler different unwinders deadlock on different architectures and/or
Android API levels. This change uses different unwinders based on
whether async signal safety is required or not, by supported API levels.
It introduces libunwindstack as the signal-safe unwinder for API 15+ on
ARM64 and x86/x64 devices. For notify()/C++ exceptions, use libunwind,
nongnu libunwind, or libcorkscrew depending on the API level.
* libcorkscrew hangs when unwinding from a C++ exception on ARM 32-bit.
* libunwind hangs on ARM64 from a signal handler
* nongnu libunwind hangs on ARM32 from a signal handler if raise() is
called directly
The `bsg_environment` object now stores two configured unwinders for a given device/OS:
* …
=> fix(ndk): Switch unwinders based on required async signal-safety

.gitmodules, CHANGELOG.md, CONTRIBUTING.md, LICENSE.txt, checkstyle.gradle, features/fixtures/mazerunner/src/main/cpp/entrypoint.cpp, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXExceptionScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXThrowSomethingScenario.java, features/native_crash_handling.feature, features/steps/build_steps.rb, ndk/build.gradle, ndk/src/main/CMakeLists.txt, ndk/src/main/jni/bugsnag_ndk.c, ndk/src/main/jni/bugsnag_ndk.h, ndk/src/main/jni/handlers/cpp_handler.cpp, ndk/src/main/jni/handlers/cpp_handler.h, ndk/src/main/jni/handlers/signal_handler.c, ndk/src/main/jni/utils/stack_unwinder.c, ndk/src/main/jni/utils/stack_unwinder.h, ndk/src/main/jni/utils/stack_unwinder_libunwind.c, ndk/src/main/jni/utils/stack_unwinder_libunwindstack.cpp, ndk/src/main/jni/utils/stack_unwinder_libunwindstack.h
Handles C++ exceptions in the std::set_terminate function rather than
waiting for the exception to propagate to the signal handler. Improves
the quality of stacktraces by working around issues in abort(), adds the
C++ exception type name as the error class and a description of the
thrown object as the message.
Added a new handler alongside the signal handler to catch C++ exceptions earlier.
* Parses the exception name via the C++ ABI
* Parses the exception message by rethrowing the object and then coercing the result into a string description. For `std::exception` instances, this is the message.
Added new end-to-end tests for handling throwing a C++ exception and throwing a random thing. Checks that the report is valid, the stacktrace is reasonable, and the error class and message match.
=> feat: Add C++ exception handler

CONTRIBUTING.md, ndk/build.gradle
Some configurations (particularly unity) require specific ABIs be
included or excluded. With this change, it can be done via
./gradlew ndk:assemble -PABI_FILTERS=armeabi-v7a,x86
Tested the change manually to ensure that when not specified, all supported ABIs build and when set, only the specified ABIs build.
=> build: Support building with custom ABIs from the command line

CHANGELOG.md, sdk/src/androidTest/java/com/bugsnag/android/ProjectPackagesTest.kt, sdk/src/main/java/com/bugsnag/android/Client.java
`config.projectPackages` is overwritten via the `Client` constructor, as reported in #426. This is confusing when setting the value via the `Configuration` class and inconsistent with the behaviour of other fields. We should respect the value that users have set, and otherwise use a sensible default.
Added a null check when setting the `projectPackages` in the `Client` constructor.
Added unit tests to verify that a default project package is set, and that a custom project package is not overwritten.
=> fix: prevent overwriting config.projectPackages if already set

features/fixtures/mazerunner/src/main/cpp/bugsnags.cpp, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXStartSessionScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXStopSessionScenario.java, features/native_session_tracking.feature, ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java, ndk/src/main/jni/bugsnag_ndk.c, ndk/src/main/jni/metadata.c, ndk/src/main/jni/report.c, ndk/src/main/jni/report.h, ndk/src/main/jni/utils/serializer.c, sdk/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
Adds the ability to stop and resume sessions in the NDK layer. When a session is stopped, session information will not be added to error payloads and handled/unhandled error counts will not be incremented.
For fatal NDK errors, we cannot call the JNI without crashing the process, so we write an error report to disk using C. This PR updates the serialisation code to handle the concept of a stopped session.
See #429 for the Java implementation, and further details.
- Emit a `SESSION_STARTED` observable event from `SessionTracker.java` when a session is started or resumed, which ultimately sets session information on the NDK payload.
- Add a `SESSION_STOPPED` observable event, which sets a boolean flag on `bugsnag_report` that prevents serialisation of session information in fatal NDK error …
=> Support stopSession() and resumeSession() in NDK

Gemfile.lock, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/NewSessionScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/ResumedSessionScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/StoppedSessionScenario.kt, features/session_stopping.feature
Verifies that no session information is present in an error payload when the session is stopped, and that the previous session information is used when the session is resumed.
This PR adds mazerunner test coverage. See #429 for the full implementation and explanation.
=> Add mazerunner scenarios for stopping/resuming a session

features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXStartSessionScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXStopSessionScenario.java, features/native_session_tracking.feature
The E2E test job failed for Android 24 on CI only. I believe this is due to the native code killing the app before the session can be delivered, which is only an issue on Travis CI's slow ARM emulators.
The fix uses a handler to delay this crash for a reasonable period, meaning the session is always delivered in time. This mirrors the approach used in [previous](https://github.com/bugsnag/bugsnag-android/blob/master/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXSessionInfoCrashScenario.java) [scenarios](https://github.com/bugsnag/bugsnag-android/blob/9f69368dd606d6522371b0150fa3ea260e41fb0b/features/native_api.feature).
=> Wait for session scenarios to send session before crashing

CHANGELOG.md, sdk/src/androidTest/java/com/bugsnag/android/BeforeNotifyTest.kt, sdk/src/androidTest/java/com/bugsnag/android/ErrorStoreTest.java, sdk/src/androidTest/java/com/bugsnag/android/ErrorTest.java, sdk/src/androidTest/java/com/bugsnag/android/ExceptionsTest.java, sdk/src/androidTest/java/com/bugsnag/android/NullMetadataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ReportTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionTest.kt, sdk/src/androidTest/java/com/bugsnag/android/SessionTrackerTest.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Error.java, sdk/src/main/java/com/bugsnag/android/Session.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
By default `bugsnag.notify()` captures error reports synchronously, then delivers them asynchronously. The delivery process serialises information about the current session into the error, including counts of handled/unhandled errors that have occurred in the session.
These counts were serialised in the async delivery, from a shared `session` object reference. This meant if `bugsnag.notify()` was called twice, the session object `handledCount` would be incremented twice, _then_ serialised with the incorrect counts.
This PR fixes this behaviour to ensure the counts are correct.
A defensive copy has been made of the session object when populating the error field, meaning mutations made by other errors do not affect the state of other reports.
- Updated `Error.Builder` (and calling code) to …
=> Fix incorrect session handledCount when notifying in quick succession

CHANGELOG.md, Gemfile.lock, features/fixtures/mazerunner/src/main/cpp/bugsnags.cpp, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXStartSessionScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXStopSessionScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/NewSessionScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/ResumedSessionScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/StoppedSessionScenario.kt, features/native_session_tracking.feature, features/session_stopping.feature, ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java, ndk/src/main/jni/bugsnag_ndk.c, ndk/src/main/jni/report.c, ndk/src/main/jni/report.h, ndk/src/main/jni/utils/serializer.c, sdk/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, sdk/src/androidTest/java/com/bugsnag/android/SessionTrackerStopResumeTest.kt, sdk/src/main/java/com/bugsnag/android/Bugsnag.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java, sdk/src/main/java/com/bugsnag/android/Session.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
Adds the ability to stop and resume sessions. This prevents the handled/unhandled error count from incrementing when a session is in the stopped state, which may be desirable if a user manually tracks sessions and does not care about crashes that occur in the background.
Added the public interface for stopping/resuming a session, along with the initial implementation, unit test coverage, and docs.
__NOTE__: NDK support was added in #432 and mazerunner scenarios have been added in #430.
=> Add stopSession() and resumeSession() to Client

features/detect_anr.feature, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingDisabledScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingLongerThresholdScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingShortScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingShorterThresholdScenario.kt
Adds testing scenarios for the ANR detection feature, including testing the threshold configuration.
Disables ANR by default in all other scenarios.
Adds Scenarios testing:
- ANR detection reports when enabled
- ANR detection doesn't report when disabled
- ANR detection doesn't report if response time is under threshold
- ANR detection reports if response time is over custom threshold (but under default)
- ANR doesn't report if response time is under custom threshold (but over default)
=> Tests: Added detect ANR scenarios, disabled ANR by default

sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
Allow registering a session with the `SessionTracker` to be propagated to crash reports. This allows the session to be tracked separately via bugsnag-unity while preserving the stability score.
Related to bugsnag/bugsnag-unity#138
Added a helper to `NativeInterface` to allow updating the current session.
Tested manually as a part of bugsnag/bugsnag-unity#138
=> fix: Add helper for syncing a unity session to native reports

sdk/src/main/java/com/bugsnag/android/SessionTracker.java
Small tweak to the Unity session syncing logic to account for both the NDK and the stop/resume sessions changes.
=> fix(unity): Sync session info to ndk

CHANGELOG.md, ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java, ndk/src/main/jni/bugsnag_ndk.c, ndk/src/main/jni/handlers/cpp_handler.cpp, ndk/src/main/jni/handlers/signal_handler.c, ndk/src/main/jni/report.c, ndk/src/main/jni/report.h, ndk/src/main/jni/utils/migrate.h, ndk/src/main/jni/utils/serializer.c, ndk/src/test/cpp/test_utils_serialize.c, sdk/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
ANR detection delivered in #442 means that the number of unhandled events is no longer necessarily 1 in the latest version of the plugin. This requires a migration of existing payloads to fit the new struct, which adds an explicit `unhandled_events` field, rather than hardcoding 1.
- Added a `NOTIFY_UNHANDLED` message to the native bridge, which is invoked whenever an unhandled event occurs, and ultimately increments `report->unhandled_events`
- Added `unhandled_events` field to `bugsnag_report`, which is serialised rather than '1'
- Created copy of existing struct in `bugsnag_report_v1`
- When reading a report, check the header. If it is v1, read into `bugsnag_report_v1`, then copy the fields over to `bugsnag_report`.
- Added test for session JSON serialisation in native reports
- Added …
=> Add unhandled_events field to native payload

CHANGELOG.md, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
An NPE could occur in `resumeSession()` as it assumed the return value of `startSession()` was always non-null. This is not the case if the sessionEndpoint has been configured incorrectly, as no session would be created in this case.
Manually installed the artefact before and after with the following initialisation code, confirming that no crash occurred after the NPE check was added:
```
val config = Configuration("api-key")
config.setEndpoints("http://localhost:1234", "")
Bugsnag.init(this, config)
Bugsnag.resumeSession()
```
=> fix: prevent NPE occurring when calling resumeSession

examples/sdk-app-example/build.gradle, examples/sdk-app-example/checkstyle.gradle, examples/sdk-app-example/ndk_local_setup.gradle
The example app has sporadically been unable to build due to being unable to find SO files from bugsnag-android-ndk. This alters the example app so that a previously commented out task can be switched on by a flag in the build.gradle.
I could reproduce this behaviour by running a clean build without the bugsnag gradle plugin applied. After applying this task to the example project, the behaviour could not be reproduced.
=> chore: update example app build.gradle to conditionally use local artefact

CHANGELOG.md, ndk/src/main/jni/metadata.c
Boolean metadata fields in fatal native crashes were always serialised as `true` due to a bug where a reference to a `java/lang/Boolean` object was cast to a `bool`. This fix calls `Boolean#booleanValue` instead, so that the true/false value is serialised correctly in native crashes.
Tested the example app on an emulator and Nexus 5x, and verified that `app.emulator` was respectively true and false for a native crash.
=> Ensure boolean object from map serialised as boolean primitive in JNI

.travis.yml, sdk/build.gradle
Our Java code uses checkstyle, but our Kotlin code is not statically analysed with the exception of Android Lint. Using [detekt](https://github.com/arturbosch/detekt) should allow us to detect if there are an excessive number of non-conventional Kotlin code smells.
- Added detekt to gradle build classpath
- Enabled detekt for all Kotlin source files in the sdk module
Ran manually and verified that there are no existing issues with our Kotlin code.
=> Add detekt static analysis plugin

sdk/src/main/java/com/bugsnag/android/ErrorReader.java, sdk/src/main/java/com/bugsnag/android/MetaData.java, sdk/src/main/java/com/bugsnag/android/ThreadState.java
There are two styles to convert a collection to an array: either using a pre-sized array (like c.toArray(new String[c.size()])) or using an empty array (like c.toArray(new String[0]).
In older Java versions using pre-sized array was recommended, as the reflection call which is necessary to create an array of proper size was quite slow. However since late updates of OpenJDK 6 this call was intrinsified, making the performance of the empty array version the same and sometimes even better, compared to the pre-sized version. Also passing pre-sized array is dangerous for a concurrent or synchronized collection as a data race is possible between the size and toArray call which may result in extra nulls at the end of the array, if the collection was concurrently shrunk during the operation.
=> Prefer using zero-based array when converting collection

sdk/src/main/java/com/bugsnag/android/CachedThread.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/DeviceData.java, sdk/src/main/java/com/bugsnag/android/Session.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java
Marking fields as final guarantees that the reference cannot be modified after initialisation. While it's still possible to mutate any fields on the object itself, this is a good first step towards thread safety, and fields should be final by default.
=> Make fields final where possible

sdk/src/main/java/com/bugsnag/android/BlockedThreadDetector.java, sdk/src/main/java/com/bugsnag/android/Exceptions.java
If a field is not used within a class except for one location, it should be converted to a local variable as this confines it to the smallest possible scope.
=> refactor: Convert fields to local variables

sdk/src/main/java/com/bugsnag/android/Error.java, sdk/src/main/java/com/bugsnag/android/ErrorReader.java
This PR makes 3 changes as reported via Android Studio inspection:
- Removing redundant information from type brackets
- Replacing large if statement with switch statement
=> Refactor language level migration

CHANGELOG.md, ndk/src/main/jni/metadata.c
Fix possible memory leak when leaving breadcrumbs or calling `bugsnag_notify()`
=> fix(ndk): Free cache instances when unneeded

CHANGELOG.md, sdk/src/androidTest/java/com/bugsnag/android/BeforeSendSessionTest.kt, sdk/src/main/java/com/bugsnag/android/BeforeSendSession.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Configuration.java, sdk/src/main/java/com/bugsnag/android/SessionTracker.java, sdk/src/main/java/com/bugsnag/android/SessionTrackingPayload.java
We require an internal API for mutating a session payload before it is sent, for notifiers such as React Native/Unity which need to write runtime version info.
- Added `BeforeSendSession` functional interface
- Invoked collection of send session callbacks prior to delivering a session for the first time
Added a unit test that verifies the callback is invoked when sending a session
=> Add internal api for mutating session payload before sending

features/fixtures/mazerunner/build.gradle, features/support/env.rb
Mazerunner previously took ~3 mins to run the `handled_exception.feature` when benchmarked on my machine. The majority of this time was spent performing a clean build and linting the example app, neither of which need to happen.
The build now reuses existing outputs and does not lint the fixture or count dex methods, resulting in an execution time of <1 minute for the scenario.
This will predominantly benefit local development, but should theoretically shave 5-10 minutes off CI as well.
=> test: optimise mazerunner fixture build speed

CONTRIBUTING.md
When making a release the `failOnUploadError` flag causes the bugsnag gradle plugin to fail the build due to a placeholder API key being present in the example app. We should avoid this by only assembling the sdk + ndk modules.
=> build: avoid upload errors when making release

CHANGELOG.md, sdk/src/main/java/com/bugsnag/android/EventReceiver.java
The `RINGER_MODE_CHANGED` action causes a `SecurityException` to be thrown in [Instant Apps](https://developer.android.com/topic/google-play-instant/getting-started/first-instant-app), which crashes the app when running on API <23. We should support Instant Apps by removing this breadcrumb by default.
It's worth noting that bugsnag-android-ndk also seems to have some trouble loading the SO files, and therefore crashes on initialisation. This seems restricted to API <23, so we will address that in a separate PR if needed.
Manually ran an Instant App enabled app on a Nexus 4 running API 21, before and after the fix. See #476 for further details on how to reproduce.
=> fix: remove RINGER_MODE_CHANGED action from broadcast receiver

CHANGELOG.md, features/detect_anr.feature, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingDefaultsScenario.kt, sdk/src/androidTest/java/com/bugsnag/android/AnrConfigTest.kt, sdk/src/main/java/com/bugsnag/android/Configuration.java
With the current implementation we're seeing too many false positives from the ANR detection.
Set the default value for `detectAnrs` to be `false` and update the javadoc config method descriptions.
Unit and end-to-end tests were updated where necessary and all suites run to completion locally.
=> feat: Disable ANR detection by default

features/detect_ndk_crashes.feature, features/fixtures/mazerunner/src/main/cpp/bugsnags.cpp, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/DetectNdkDisabledScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/DetectNdkEnabledScenario.java, features/support/env.rb, sdk/build.gradle, sdk/src/main/java/com/bugsnag/android/Bugsnag.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/Configuration.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java
Add `config.detectNdkCrashes` property, which controls whether the NDK integration is enabled or not. In the bugsnag-android artefact, this value should be disabled by default; in bugsnag-android-ndk it should be enabled.
- Built the NDK lib for the mazerunner fixture by default
- Add `BuildConfig.DETECT_NDK_CRASHES` which is set via a gradle command line parameter
- Add `detectNdkCrashes` property to `Configuration`
- Move NDK initialisation to within `Client` constructor
- Simplify `NativeInterface` to avoid complexity + cost of reflection, by instantiating `NativeBridge` directly
Added mazerunner scenario for when NDK crash detection is explicitly enabled and disabled. The default value is covered by existing tests.
=> Add detectNdkCrashes property to control NDK crash reporting

CHANGELOG.md
Removes LZMA and MIPS code from libunwindstack, reducing artefact size by ~120kb.
For further details see https://github.com/bugsnag/libunwindstack-ndk/pull/1
=> Reduce NDK AAR size

sdk/src/androidTest/java/com/bugsnag/android/ClientTest.java, sdk/src/main/java/com/bugsnag/android/ConfigFactory.java
Make detection options configurable via App Manifest
* Update ConfigFactory to load detectNdkCrashes and detectAnrs from manifest if provided
* Added new test assertions for the default values and overrides via manifest
=> Add detection manifest options

CHANGELOG.md, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CorruptedReportScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/EmptyReportScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/MinimalHandledExceptionScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/MinimalUnhandledExceptionScenario.kt, features/minimal_report.feature, sdk/src/androidTest/java/com/bugsnag/android/ErrorFilenameTest.kt, sdk/src/androidTest/java/com/bugsnag/android/ErrorStoreTest.java, sdk/src/main/java/com/bugsnag/android/Client.java, sdk/src/main/java/com/bugsnag/android/DeliveryStyle.java, sdk/src/main/java/com/bugsnag/android/Error.java, sdk/src/main/java/com/bugsnag/android/ErrorStore.java, sdk/src/main/java/com/bugsnag/android/Report.java, sdk/src/main/java/com/bugsnag/android/Severity.java
If a report cannot be delivered due to delivery failure, it is cached on disk. If this cached report cannot be deserialised, or is only partially written, e.g. due to lack of disk space, then currently no bugsnag report will be sent.
This changeset alters bugsnag-android to send a minimal error report for cached JVM exceptions only, by encoding basic error information in the filename.
- Updated `ErrorStore` to pass a `Delegate` that is invoked whenever a cached file cannot be deserialised
- Implemented `Delegate` in `Client` by sending a report with `DeliveryStyle.NO_CACHE` (this prevents minimal errors from generating other minimal errors if delivery fails and there's a serialisation bug in the notifier)
- Updated `Error` to include `incomplete` field that is set when a report is …
=> Send minimal error report if cached file is corrupted/empty

sdk/src/androidTest/java/com/bugsnag/android/NativeInterfaceTest.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java
Support clearing metadata tabs from the native interface.
A changelog entry was omitted since this is an internal-facing change and `clearTab` is not new functionality.
=> refactor: Expose clearTab to the native interface

CHANGELOG.md, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/SomeException.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/HandledExceptionWithoutMessage.kt, features/handled_exception.feature, sdk/src/main/jni/metadata.c, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/SomeException.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/HandledExceptionWithoutMessage.kt, tests/features/handled_exception.feature
In the event that a metadata value is null, the patched section would
crash in `GetStringUTFChars()`. This is most easily reproduced by calling
notify/throwing on an exception with no message.
Replaces #510
* Manually tested by throwing an exception without a message. This would propagate null through `leaveErrorBreadcrumb()` which would then be serialized by the native layer.
=> fix(ndk): Skip null metadata values from serialization

.buildkite/pipeline.yml
Slashes were previously breaking builds due to docker-registry issues, so an environment script has been added that exports `BUILDKITE_BRANCH` as `BRANCH_NAME` with all `/` replaced by `-`.  This PR changes the `BUILDKITE_BRANCH` occurrences to `BRANCH_NAME`.
=> Fix buildkite tags with slashes

CHANGELOG.md, sdk/src/androidTest/java/com/bugsnag/android/NullMetadataTest.java, sdk/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, sdk/src/main/java/com/bugsnag/android/Configuration.java, tests/features/custom_metadata.feature, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CustomMetaDataScenario.kt
Calling `Bugsnag.setMetaData(MetaData())` crashed the process if the NDK was enabled. This is because the method emits an observable event to the NDK, which was expected as a `Map` in the JNI but sent as a `MetaData`.
Altered the observable to emit a `Map` instead.
Tested the change manually in an example app, and added a mazerunner scenario.
=> Convert metadata to map when notifying the NDK observer

CHANGELOG.md, sdk/src/main/jni/handlers/anr_handler.c
Fixes a bug reported in #502 where the process crashes with `SIGPIPE` if the network connection is lost during a request and ANR detection is enabled.
The following may be useful for further reading: https://www.gnu.org/software/libc/manual/html_node/Signal-Handling.html#Signal-Handling
Our current implementation installs a `SIGQUIT` handler to record when an ANR occurred. When this handler is installed we update the thread mask to block any concurrent `SIGQUIT` signals. After the handler is installed, the thread mask is updated to unblock `SIGQUIT`, so that we can handle incoming signals once more.
However, one apparent issue with the current implementation is that it overwrites all pre-existing values in the thread mask, by using the `SIG_SETMASK` option when calling `pthread_sigmask`. …
=> Prevent overwrite of signal mask when installing ANR handler

build.gradle, examples/sdk-app-example/build.gradle, features/fixtures/mazerunner/build.gradle, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingDisabledScenario.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoSessionScenario.kt, features/session_tracking.feature, tests/features/fixtures/mazerunner/build.gradle
CI needs to be altered to build the new modularised project structure.
- Updated gradle plugin to v4.5.2, which extracts SO files from transitive dependencies
- Removed unused gradle plugins from mazerunner fixture and update to latest version of android gradle plugin, as this caused a CI failure as 3.0.1 is not supported with gradle 5.4.1
- Enabled ANR + NDK error detection by default in the mazerunner fixture, this was previously implicit by depending on `bugsnag-android-ndk`
- Fix flaky auto session test in local scenario
=> Alter CI to build new project structure

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/AppDataTest.java
`AppData` uses `SystemClock.elapsedRealTime()` to calculate the duration that is populated in the JSON payload. On browserstack it appears the unit tests are fast enough that this can sometimes equal zero, and fail the test. This changeset fixes that flakiness.
=> test: fix flaky instrumentation test

.buildkite/pipeline.yml
This changeset moves the order of jobs so that one E2E test, and one instrumentation test are the first to run. This should increase the speed of feedback when tests are broken, as we won't have to wait for five E2E jobs to complete before seeing the failing instrumentation test results.
=> Run instrumentation tests simultaneously with E2E tests

tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoContextScenario.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXAutoContextScenario.java
##Goal
The scenarios under `tests/features` were out of sync with the scenarios under `features`. Updating the scenarios should fix issues where the tests fail on buildkite due to an unexpected request.
=> Attempt to fix mazerunner scenarios by disabling automatic session tracking

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ConfigurationTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionTrackerTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigFactory.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DefaultDelivery.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryCompat.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Endpoints.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
Creates an `Endpoints` class which encapsulates the `notify` and `sessions` fields, and automatically rejects any `null` values for either of these parameters. 
- Added `Configuration#setEndpoints(Endpoints)` method
- Deprecated existing methods, added backwards compatibility
- Removed redundant unit tests which were added when we supported setting the `notify` and `sessions` fields non-atomically
=> immutable config: create Endpoints class, deprecate existing variants

.buildkite/pipeline.yml
Separates the Instrumentation steps into separate groups to avoid overrunning the concurrency limits in place.
This change should avoid having to look at BrowserStack device availability in Maze-Runner
=> Buildkite: Ensure concurrency groups reflect reality

tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CorruptedOldReportScenario.kt, tests/features/minimal_report.feature
Adds the missing scenario present in the local maze-tests but not the BrowserStack enabled ones.
This should now pass both locally and on CI.
=> Add missing old-report scenario

CHANGELOG.md, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BreadcrumbMutabilityTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Breadcrumb.java, bugsnag-plugin-android-ndk/src/main/jni/metadata.c
We have noticed infrequent crashes when adding a breadcrumb and NDK error detection is enabled. This changeset fixes some potential causes of this behaviour.
- Made `Breadcrumb` immutable by taking a defensive copy of the map parameter, and returning a decorated `Collection` from the getter that is unmodifiable.
- Corrected `sizeof` calculation when iterating through breadcrumb metadata
- Added null check for metadata and metadata keys in breadcrumbs
- Added unit tests to verify `Breadcrumb` metadata immutability
- Tested leaving breadcrumbs with metadata in example app
=> Fix potential segfaults when adding breadcrumb with NDK

bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java
Session tracking is enabled by default, but our JavaDoc states the opposite from previous releases when this was not the case.
Fixes #543
=> docs: fix typo in session tracking javadoc

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorReader.java
`ErrorReader` uses a `FileReader` which is unbuffered, meaning when an error report is read from disk it takes far longer than is necessary. Wrapping this value with a `BufferedReader` should notably improve performance at no cost to the implementation.
Relied on existing test coverage
=> Buffer IO when reading cached error reports

CHANGELOG.md, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/NullMetadataTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java
I came across this when testing something else - if config.metadata is set to null, it causes an NPE. I then realized there was a test for this prior to #513, which I completely glossed over. So I added back the test and fixed the issue.
=> fix(config): Avoid NPE if setting metadata to null

bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java, build.gradle, mazerunner-scenarios/lint-baseline.xml
`setNotifierType` is not intended for public use so can be made package-private. If other notifiers need to use it, they should access it via a class in the `com.bugsnag.android` package, rather than exposing it in our public API.
This also disables two lint inspections which fail the CI build whenever a new version of a Gradle dependency is available, and removes the existing baseline warning for this inspection. Android Studio automatically notifies us of new gradle dependency versions so we don't need to fail every branch whenever a new version of a plugin/dependency is released.
=> Make internally used setNotifierType method package-private

scripts/run-linter.sh
Currently JVM tests are run twice, once in the linter and once in the separate image.
=> JVM tests: Ensure tests aren't run twice

dockerfiles/Dockerfile.android-builder
Uses `apt` to install maven rather than curling the download page, which no longer resolves to a valid archive.
=> Use apt to download maven rather than curl

CHANGELOG.md, sdk/src/androidTest/java/com/bugsnag/android/NativeInterfaceTest.java, sdk/src/main/java/com/bugsnag/android/NativeInterface.java
The current revision is missing an interface for clearing a tab.
* Manually and using a new automated test
=> fix(native): Add interface for clearing a tab

CHANGELOG.md, sdk/src/main/java/com/bugsnag/android/NativeInterface.java, sdk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java, sdk/src/main/jni/bugsnag.c, sdk/src/main/jni/bugsnag_ndk.c
Fix a possible crash in `NativeBridge.deliverReportAtPath()` arising from the report payload or release stage containing bytes which cannot be encoded as Modified UTF-8.
NewStringUTF() is not safe to use unless you control the input 100% of
the time. It uses the Modified UTF-8 charset, which may exclude possible 
characters, crashing with "illegal byte" errors. This issue can be mitigated 
by passing the raw byte array to the JVM layer, and then decoding the 
string as UTF-8. Using the `String(bytes[], Charset)` constructor bypasses
possible exceptions, instead replacing unknown bytes with the
unidentified character marker.
This fixes a possible crash where a string value is added to a report
using an encoding other than ASCII or Unicode variants (such as 
SHIFT-JIS, EUC-*, etc) which …
=> [Android] Fix support for native crashes containing multiple text encodings

tests/features/detect_anr.feature, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingDisabledNdkScenario.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingDisabledScenario.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingScenario.kt, tests/features/steps/android_steps.rb
Enables ANR testing against real devices on BrowserStack.
There's potentially optimisation here by reducing the amount of times the screen is tapped in order to produce the correct response.
=> Buildkite tests: Enable ANRs

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionTrackingPayloadTest.java
Fixes the flaky `testPayloadSerialisation()` case, where the timestamp comparison failed.
The cause of this was that the `payload` field generated a new session rather than using an existing field. If executed at the right time these could be serialized as different dates, failing the test.
=> test: use correct session for timestamp comparison

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorStore.java
`FileNotFoundException` can occur due to a race where the oldest file is deleted from disk, and the
`Error` object sends a cached file directly in the request. If this does occur, we should suppress
internal error reports as it is a known issue that we cannot handle.
It is worth noting that redesigning the `ErrorStore` so that the `File` is always deserialized into an `Error` object would prevent this scenario from occurring.
However, given the complexity of these changes and incidence of this situation, it was seen as more appropriate to avoid sending an internal error report instead.
=> Prevent internal error reporting of FileNotFoundException during Delivery

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorStore.java
`cancelQueuedFiles()` prevents a file being sent again in a duplicate error report. This was
inappropriately called in `flushOnLaunch()` before `flushErrorReports()` completed in a background thread, which could result in duplicate error reports if `flushAsync()` was called while waiting for completion. 
This changeset removes the call and immediately cancels non-launch crash reports. The SDK not relies on `flushErrorReport()`, which cancels/deletes each file once the request has completed.
=> flushOnLaunch() does not cancel previous requests if they timeout, leading to potential duplicate reports

CHANGELOG.md, bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c
If `NULL` is passed as a parameter to `bugsnag_set_user_env` the process will crash with a SIGSEGV, because the method does not check for null.
This changeset adds a check for null in `bsg_byte_ary_from_string` and `bsg_release_byte_ary`. 
The `CxxUserInfoScenario` in `native_api.feature` is now passing, whereas previously it was not. Also verified by passing NULL to all params in an example app.
=> Prevent SIGSEGV when passing NULL to bugsnag_set_user_env

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ErrorReaderNumberTest.kt, bugsnag-android-core/src/androidTest/resources/stackframe_numbers.json, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorReader.java
Some fields in the `StackFrame` object can be non-integers in some cases, but the current implementation assumes that they are always integers. This change uses existing code to deserialize numbers instead, which handles doubles/longs appropriately.
Manually verified that it an error is read from a JSON file if the stackframe objects contain doubles/longs/ints.
=> Deserialize longs/doubles stored in StackFrame object

.buildkite/pipeline.yml
We should run 1 instrumentation test target by default rather than 3, as this will reduce the feedback loop when multiple PRs are pushed to Github and waiting on CI (a regular occurrence).
The existing 2 targets have been moved behind the 'trigger full test suite' blocking step, which are run before a release.
=> Update buildkite test matrix

bugsnag-plugin-android-ndk/src/main/jni/handlers/cpp_handler.cpp, bugsnag-plugin-android-ndk/src/main/jni/handlers/signal_handler.c
Ports the following commit to master: https://github.com/bugsnag/bugsnag-android/commit/e0bfbf9cbfda7d1401d4209fbbeb102e002633f5
=> fix: Avoid duplicate handler installs

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/InternalReportScenario.kt, features/internal_report.feature, features/support/env.rb, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/InternalReportScenario.kt, tests/features/internal_report.feature, tests/features/support/env.rb
Android API 26 introduced `setCacheBehaviorGroup`, which tells the OS to delete all the files in a given directory if space needs reclaiming. Coupled with `setCacheBehaviorTombstone` which truncates files to 0, this could explain the volume of minimal error reports reported by some customers.
We should record this information in our internal error diagnostics to debug the issue further.
Tested against a local artefact on API 23 + 29 which had been altered to always call `recordStorageCacheBehavior` when notifying.
=> Record storagemanager cache behaviour in internal error reports

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.java
`FileNotFoundException` can occur when opening a `FileOutputStream` if it wasn't possible to open the file for reasons beyond our control. If this does occur, we should suppress
internal error reports as it is a known issue that we cannot handle.
See releated PR #594
=> Prevent internal error reporting of FileNotFoundException during serialization

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/AppData.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceData.java, features/internal_report.feature, tests/features/internal_report.feature
Collects the following values under the app/device tabs, using existing collection methods from `AppData` and `DeviceData`:
```
app.duration
app.durationInForeground
app.inForeground
device.freeDisk
```
Added to existing mazerunner scenarios to verify that internal reports contain the new fields
=> Collect additional data in internal error reports

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BeforeRecordBreadcrumbsTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BreadcrumbFilterTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BreadcrumbsSerializationTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ConcurrentCallbackTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/OnBreadcrumbsTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Breadcrumb.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorReader.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventReceiver.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/JsonWriter.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/main/java/com/bugsnag/android/OnBreadcrumb.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbMutabilityTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbsTest.kt, bugsnag-plugin-android-ndk/src/main/assets/include/bugsnag.h, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java, bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c, features/breadcrumb.feature, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/BreadcrumbScenario.kt, tests/features/breadcrumb.feature
Updates the breadcrumb functionality to better match the notifier spec.
- Renamed `breadcrumb.name` to `breadcrumb.message`
- Captured "Bugsnag loaded" breadcrumb when a `Client` is constructed
- Enforce 0-100 limit on valid values for `config.maxBreadcrumbs`
- Change default for `config.maxBreadcrumbs` from 32 to 25
- Removed 140 char limit from breadcrumb message length
- Altered `breadcrumb.metadata` to accept `Object` values rather than just `String`. (Note: this does not currently prevent nested values, which will be addressed in a separate PR that looks more fully at data redaction/serialization)
- Renamed `BeforeRecordBreadcrumb` to `OnBreadcrumb`
- Added `addOnBreadcrumb` and `removeOnBreadcrumb` to `Bugsnag` and `Client`
- Added `enabledBreadcrumbTypes to `Configuration`, which …
=> Update Breadcrumb functionality to match notifier spec

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/AppData.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ConnectivityCompat.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ForegroundDetector.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ConnectivityApi24Test.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConnectivityLegacyTest.kt
System services can throw a `RuntimeException` if the [remote call failed](https://developer.android.com/reference/android/os/RemoteException). We should swallow these in
bugsnag-android and attempt a sensible default rather than terminating the process, such as returning null for serialized values such as `app.inForeground`.
Caught an exception whenever a method is invoked on a system service that can throw a `RuntimeException`. In some cases this handling was already in place, where it wasn't, the following changes were made:
- Catching exceptions from `ConnectivityManager` and returning a sensible default in `ConnectivityCompat`
- Caught `RuntimeException` in `ForegroundDetector` rather than more specific `SecurityException`
- Return nullable values for `app.inForeground` and …
=> Catch throwables when invoking methods on system services

features/_smoke_test.feature, tests/features/_smoke_test.feature
This adds a smoke test feature which runs the most important scenarios first: such as checking that unhandled exceptions result in a report being sent to Bugsnag.
The intention behind this change is to reduce the feedback loop when testing locally and on CI, as now by running this one feature it will be possible to check that the notifier isn't fundamentally broken due to runtime coding mistakes. The feature runs first on CI and covers:
- Handled JVM exceptions
- Unhandled JVM exceptions
- Handled C errors
- Unhandled C errors
- Session tracking
- ANRs
=> Add mazerunner smoke test feature

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/DeviceDataTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceData.java, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, features/steps/build_steps.rb, tests/features/steps/android_steps.rb
Migrates the `time` and `locale` fields from `metaData.device` to `device`, to match the current error API payload structure.
Originally raised in #629
=> Migrate device payload fields

bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadSerializationTest.kt, bugsnag-android-core/src/test/resources/thread_serialization_0.json, bugsnag-android-core/src/test/resources/thread_serialization_1.json
Adds a parameterised JVM serialization test to verify JSON is constructed correctly for the `Thread` interface. This was originally added in the main integration branch.
=> Add serialization test for Thread class

bugsnag-android-core/src/main/java/com/bugsnag/android/JsonStream.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Stackframe.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/StackframeSerializationTest.kt, bugsnag-android-core/src/test/resources/stackframe_serialization_0.json
Adds a JVM serialization test to verify the constructed JSON for the `Stackframe` object.
Additionally, the `customFields` field has been updated to allow nullable values in its map, and the serializer has been updated to allow nullable objects (which are not omitted from serialization by default)
=> Add Stackframe serialization test

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/DeviceDataSummaryTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/DeviceDataTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/EventSerializationTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceBuildInfo.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceData.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/test/java/com/bugsnag/android/DeviceDataSerializationTest.kt, bugsnag-android-core/src/test/resources/device_data_serialization_0.json
Ports changes to `DeviceData` made in this PR to the notifier spec update branch, and adds JVM serialization tests: https://github.com/bugsnag/bugsnag-android/pull/606#discussion_r331988213
- Renames `getDeviceMetadata()` for consistency with `Metadata` capitalization
- Convert `DeviceData` instrumentation tests to single JVM serialization test that verifies JSON structure
- Adds `DeviceBuildInfo`, which holds static `Build` fields directly so that their values can be faked under test
- Updated `DeviceData` to take `DeviceBuildInfo` as a field
=> Update DeviceData and add serialization test case

bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagClientMirrorInterfaceTest.kt
The `Bugsnag` class provides a facade through which any method on the `Client` can be invoked. Historically the two classes have become out of sync.
This changeset synchronises the two classes to share similar method signatures, and adds a test that will fail if the two classes do fall out of sync again.
- Added missing public methods onto `Bugsnag` that were only present on `Client`
- Removed `startFirstSession` from `Client` as this is no longer used by Unity or React Native and is therefore dead code
- Made app/device/breadcrumb/configuration accessors on `Client` package-private, as these should not be part of our public API but are still required by the `NativeInterface` class
Added a unit test to verify that the two classes share the same methods. This works by reflexively getting a …
=> Synchronize Client with Bugsnag facade

bugsnag-android-core/src/main/java/com/bugsnag/android/Error.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorTest.kt, bugsnag-android-core/src/test/resources/error_serialization_0.json
Adds the `Error` interface to conform to the Notifier spec. Note that this PR only adds the interface, and this is not used by the `Event` yet.
Added a JVM serialization test to verify that JSON is constructed correctly.
=> Add Error interface

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagConfiguration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/CallbackAware.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java
Adds a non-public interface which contains the methods for adding/removing callbacks.
According to the notifier spec these methods share the same signatures on both `Client` and `Configuration`, therefore we should ensure they retain consistency by implementing the same interface.
=> Add CallbackAware interface

bugsnag-android-core/src/main/java/com/bugsnag/android/BaseObservable.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/StateEvent.kt
This changeset aims to simplify the communication of state changes from the JVM to the NDK. It does so by focusing on two areas:
1. Reducing the amount of code required to emit an Observable event and ensuring that `setChanged()` is always called
2. Altering the message sent to a sealed class, to improve the type safety and reduce validation on the `Observer`
For context, when the user leaves a breadcrumb, the Notifier sends an `ADD_BREADCRUMB` message to the NDK `Observer` with details of the new breadcrumb. This allows the NDK to keep a copy of the current breadcrumb collection, and serialize it into a report if a fatal native crash occurs.
This is done because it's not possible to make JNI calls after a C signal has been raised, as this would terminate the process, so we need to keep a …
=> Alter observable events to use a sealed class hierarchy

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ThreadStateTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt
Refactors the `ThreadState` implementation to reduce the knowledge required to create an object.
This is not a public interface so does not result in any publicly facing change, but is designed to make the construction of an `Event` easier (and forms the groundwork of a future PR to alter the `Event` interface).
- Removed obsolete constructor which takes a list of Threads, as this was only required when deserializing JSON which we no longer do
- Made `threads` mutable to allow users to alter the value on `Event`
- Alter the constructor so that only a configuration and `Array<StacktraceElement>` are required parameters, and a sensible default is chosen for the current thread/thread trace
- Remove `testSerialization()` test case as this is covered by `ThreadSerializationTest`
=> Refactor ThreadState implementation

bugsnag-android-core/src/test/java/com/bugsnag/android/HandledStateSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/HandledStateTest.java, bugsnag-android-core/src/test/resources/handled_state_serialization_0.json, bugsnag-android-core/src/test/resources/handled_state_serialization_1.json, bugsnag-android-core/src/test/resources/handled_state_serialization_2.json, bugsnag-android-core/src/test/resources/handled_state_serialization_3.json, bugsnag-android-core/src/test/resources/handled_state_serialization_4.json, bugsnag-android-core/src/test/resources/handled_state_serialization_5.json, bugsnag-android-core/src/test/resources/handled_state_serialization_6.json, bugsnag-android-core/src/test/resources/handled_state_serialization_7.json
Adds missing test coverage to verify that `HandledState` constructs JSON correctly.
Added a test case for each severity reason with a JSON fixture. Additionally a redundant throws clause has been removed from the test cases in `HandledStateTest`.
=> Add test coverage for handled state JSON serialization

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.java, bugsnag-android-core/src/main/java/com/bugsnag/android/UserAware.kt
Adds a non-public interface which contains the methods for setting/getting a `User`.
According to the notifier spec these methods share the same signatures on both `Client` and `Event`, therefore we should ensure they retain consistency by implementing the same interface.
=> Add UserAware interface

features/filtering_metadata.feature, tests/features/filtering_metadata.feature
The mazerunner scenarios are still asserting that the value should be `[FILTERED]` rather than `[REDACTED]`, which fails CI.
=> Change [FILTERED] to [REDACTED] for metadata mazerunner scenarios

bugsnag-android-core/src/test/java/com/bugsnag/android/ExceptionHandlerTest.kt
Adds test coverage for the `UncaughtExceptionHandler` implementation, which previously had no unit test coverage.
Added a test that verifies:
- a default global handler is installed
- the handler propagates events to the previous handler
- the handler invokes a `notify()` call on the `Client` to capture an error report
=> Add test coverage for exception handler

bugsnag-android-core/src/test/java/com/bugsnag/android/ConnectivityApi24Test.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConnectivityLegacyTest.kt
Adds unit test coverage for the `Connectivity` class, which detects whether the device has a network connection. This was added as part of a general drive to increase test coverage on the original integration branch for the notifier spec updates.
Added tests for the two `Connectivity` implementations: `ConnectivityApi24`, and `ConnectivityLegacy`, which runs on pre-API 24 devices.
The tests verify that the appropriate callback is registered/unregistered to listen for network callbacks, and that the network state returns an appropriate value.
=> Add unit test coverage for Connectivity implementations

bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-plugin-android-anr/detekt-baseline.xml, bugsnag-plugin-android-ndk/detekt-baseline.xml, mazerunner-scenarios/detekt-baseline.xml
Extracts sanitisation code from `Client` to `ImmutableConfig`, which makes the deep-copy of the user-supplied `Configuration` more testable and reduces the responsibilities of `Client`.
- Extracted `sanitiseConfiguration()` to `ImmutableConfig` 
- Added a test to verify that the projectPackages are set to an appropriate default
=> Extract sanitisation of Configuration to ImmutableConfig.kt

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagApiTest.kt, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.java, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, bugsnag-plugin-android-ndk/src/main/jni/report.c, bugsnag-plugin-android-ndk/src/main/jni/report.h, bugsnag-plugin-android-ndk/src/test/cpp/test_breadcrumbs.c
Removes obsolete and methods which do not comply with the notifier spec from the Bugsnag/Client interfaces.
- Removed ability to clear breadcrumbs and associated test code, as this should now be done with an `OnBreadcrumb` callback
- Removed `clearUser()` in favour of `setUser(null, null, null)`
- Removed `final` from `pauseSession/resumeSession` to allow mocking of `Client` methods
- Removed unused private implementation methods in `Client`
- Added `BugsnagApiTest`, which verifies that the `Bugsnag` facade invokes the appropriate method on `Client`
=> Remove non-compliant methods from Bugsnag/Client interface

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerBreadcrumbTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerPauseResumeTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerTest.java
Adds unit test coverage for the `SessionTracker` class. This was added as part of a general drive to increase test coverage on the original integration branch for the notifier spec updates.
- Converted existing instrumentation tests to run on the JVM
- Added a test to verify automatic breadcrumbs left by the session tracker contain the correct data
- Updated the `SessionTracker` to use getters where necessary as these methods are mockable for tests, whereas fields are not
- Removed redundant check for whether breadcrumbs are enabled
- Enabled [mock-maker-inline](https://stackoverflow.com/questions/14292863/how-to-mock-a-final-class-with-mockito) which is required to appropriately mock the `Activity` class.
=> Increase session tracking test coverage

bugsnag-android-core/src/main/java/com/bugsnag/android/Event.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/TestHarnessHooks.kt
#672 added a `Logger` interface which is injected into `Delivery`, but some mazerunner scenario code was not updated to add the new constructor parameter. This led to a crash when creating `DefaultDelivery` via reflection, which has therefore been updated to pass in a no-op `Logger` implementation that passes the following scenarios:
- async_error_flush
- custom_client
- handled_exception
- unhandled_exception
The `ThreadState` refactor also broke one assertion in the error_reporting_thread feature - this has been addressed by only replacing the thread trace with an exception stacktrace when the exception is unhandled.
It's worth noting that the native_api feature is expected to fail its second scenario as this will rely on changes made in #680 being fully implemented across the codebase.
=> Update mazerunner scenarios to use new constructor

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
Updates the `notify()` call to send a `StateEvent` message rather than `NativeInterface.Message`. This ensures that the NDK keeps session counts up to date and therefore passes the `CXXSessionInfoCrashScenario` mazerunner scenario (once #691 has been passed).
The remaining mazerunner scenarios are expected to fail as the NDK messaging has not yet been fully updated to use `StateEvent`.
=> Update notify to send StateEvent message rather than NativeInterface

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientConfigTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ContextState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
Creates a class named `ContextState` which holds the current context and notifies observers. This passes a failing mazerunner scenario that checks the NDK is informed of any update to context.
- Created `ContextState` class
- Updated change in context to emit a `StateEvent` object as an observable, which passes the 
failing `CXXUpdateContextCrashScenario`
- Deep copy context from `Configuration` to `Client`
- Removed obsolete `UPDATE_CONTEXT` from `NativeInterface`
=> Create ContextState class to encapsulate context

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
Updates the `SessionTracker` class to use `StateEvent` observable messages rather than `NativeInterface`. This is required to pass failing scenarios in the `native_session_tracking` mazerunner feature.
The remaining scenarios are failing due to the integration branch not fully merging all the PRs which update the NDK messaging to use StateEvent.
=> Make SessionTracker use StateEvent messages

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java
Updates the `BreadcrumbState` class to use `StateEvent` observable messages rather than `NativeInterface`. This is required to pass the failing breadcrumb scenarios in the `native_api` mazerunner feature.
=> Make AddBreadcrumb use StateEvent observable message

bugsnag-android-core/src/test/java/com/bugsnag/android/EventRedactionTest.kt, bugsnag-android-core/src/test/resources/event_redaction.json
Adds a test to verify that values are redacted from `Event` fields.
Note that `MetadataRedactionTest` already contains more in-depth coverage to verify how metadata is sanitised - this test case is intended to verify that the functionality is not broken on `Event`.
=> Add test coverage for redaction on event fields

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/NativeInterfaceTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/MetadataAware.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/MetadataState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/test/java/com/bugsnag/android/EventTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataRedactionTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/NullMetadataTest.java, bugsnag-android-core/src/test/resources/meta_data_serialization_1.json
Ensures that `Metadata` changes are synced to the NDK layer by using the `StateEvent` message rather than the obsolete `NativeInterface.Message` object.
- Added `MetadataState` which now sends `Observable` messages when the `Metadata` changes
- Updated `addMetadata()` so that the `key` is not null when it is an explicit parameter
- Changed return type of one `getMetadata()` to a more specific `Map` type
- Held `metadata` in a `MetadataState` field within `Client` that is copied from `Configuration`
- Updated existing test code to use new `addMetadata()` and `getMetadata()` signatures
- Updated existing test code to check for presence of `StateEvent`
- Added unit test for `MetadataState`
- Updated `MetadataSerializationTest` test fixture to fix incorrect assertion
=> Update Metadata to use StateEvent observable message

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/FileStoreTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionStore.java, bugsnag-android-core/src/test/java/com/bugsnag/android/EventFilenameTest.kt
Removes an unused generic type argument on `FileStore`, along with an unused `Configuration` constructor parameter. Test code has been updated to match these changes.
=> Refactor filestore to remove unnecessary generic type arg

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
Updates the sanitisation of the `Configuration` object to happen in `ImmutableConfig` rather than the method defined in `Client`.
This was originally added in #682 but seems to have been lost in a merge conflict somewhere along the way.
=> Remove unused sanitisation code from Client

bugsnag-android-core/src/main/java/com/bugsnag/android/Event.kt
The `UserAware` interface defines the methods that are used to set/get a `User`. As this is possible on `Event`, it should implement them (this has already been done on Client/Configuration).
=> Make Event implement UserAware interface

bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryParams.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Endpoints.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt
A [data class](https://kotlinlang.org/docs/reference/data-classes.html) in Kotlin automatically generates methods such as `copy()`, `equals()`, and `componentN()`.
These features are not used within `DeliveryParams/Endpoints` and makes it hard to add new properties to these classes in future without causing a [breaking change](https://jakewharton.com/public-api-challenges-in-kotlin/). The modifier has therefore been removed.
=> Remove data class modifier from DeliveryParams/Endpoints

bugsnag-android-core/src/main/java/com/bugsnag/android/User.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventApiTest.kt
Increases test coverage by verifying that when the user/metadata is updated on the `Event` class, the appropriate backing field is altered.
Note that this adds an `equals()/hashcode()` implementation so that the `User` object can be compared by whether its fields match, rather than for referential equality.
=> Add test coverage to Event class

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ReportTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceData.java, bugsnag-android-core/src/main/java/com/bugsnag/android/User.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/CallbackStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConnectivityLegacyTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/DeviceDataSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ExceptionHandlerTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SystemBroadcastReceiverTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/UserRepositoryTest.kt
Removes unused imports revealed by the IntelliJ inspection tool. These are unnecessary and can therefore be removed from the codebase.
=> Remove unused imports

bugsnag-android-core/src/main/java/com/bugsnag/android/ConnectivityCompat.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DateUtils.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Session.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
Removes unused code and alters the public type hierarchy in miscellaneous files.
- Made `NetworkChangeCallback` non-public
- Removed `DateUtils` deserialization function as we no longer deserialize JSON
- Made `Session` final to prevent end-users extending the class
- Removed unused constants + methods from `SessionTracker`
=> Remove unused code from public API

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt, bugsnag-plugin-android-ndk/src/main/jni/metadata.c
Updates `NativeInterface` to use the `ImmutableConfiguration` object rather than `Configuration` to prevent the user from mutating fields by holding onto a reference. This also renames methods for consistency with the Client's terminology.
- Removed non-public getter for `Configuration` on `Client`
- Added non-public getters/setters for `Client` fields as needed
- Removed `Message/MessageType` from `NativeInterface` as these are no longer used
- Renamed methods on `NativeInterface` to match terminology in rest of codebase
- Updated `NativeInterface` to use getters on `Client` rather than direct field access
- Updated JNI calls to use new method names
- Added a unit test to verify that `NativeInterface` calls the appropriate method on `Client`
=> Make native interface use immutable configuration

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
When a [StrictMode](https://developer.android.com/reference/android/os/StrictMode) exception is captured by our `UncaughtExceptionHandler` we attempt to extract additional information about the reason for the strictmode violation from the throwable object. This information is attached to the `Event` via a `Metadata` object passed to a notify call.
The implementation of `Client` did not merge this metadata object with the global metadata store, so the strictmode information was not included in events. This change fixes the `strict_mode.feature` scenarios which are only triggered on a full test run.
=> Merge strictmode metadata with global Metadata

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java, bugsnag-android-core/src/test/java/com/bugsnag/android/InternalReportDelegateTest.kt
Extracts the logic for sending an internal bugsnag report from the `Client` to its own class.
There should be no functional change here, but this enables the addition of a unit test to verify the behaviour of internal reporting on top of existing E2E tests. It also reduces the responsibilities of the large `Client` class.
=> Extract InternalReportDelegate class from Client

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagPluginInterface.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Error.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Logger.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt
Explicitly lists the types on public interfaces where they were not already listed, to reduce the chance of type inference causing a breaking change if the implementation changes.
For example, if we expose an API like thus:
```
fun foo() = mutableListOf("bar")
fun foo2(): List<String> = mutableListOf("bar")
```
If we decide to change `foo2()` to return a `Set` instead, the build will only break if the type is explicitly listed:
```
fun foo() = mutableSetOf("bar") // does not break compilation
fun foo2(): List<String> = mutableSetOf("bar") // breaks compilation
```
Therefore we want to list types explicitly for all our public interface that is written in Kotlin. Further reading on this topic is available here: https://jakewharton.com/public-api-challenges-in-kotlin/
Specified return type …
=> Explicitly specify types on public interfaces

bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbState.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt
Removes the payload size limit on breadcrumb metadata, as this is no longer in the notifier specification.
We plan on adding a more holistic method of reducing overall payload size at a later date.
=> Remove payload size limit on breadcrumb metadata

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/OnBreadcrumbStateTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/UniqueOnErrorTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/CallbackState.kt
An `OnError/OnSession/OnBreadcrumb` callback should be added regardless of whether it is already in the collection. This changeset brings the implementation in line with the latest version of the notifier spec.
=> Add duplicate callbacks if already in collection

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NdkPlugin.kt
`Client` is a public type and should therefore use composition rather than inheritance to emit observable events. This gives us a free hand to change the implementation of observable messaging in the future, whereas otherwise we would remain constrained to inheriting from `Observable` unless we wished to introduce a breaking change.
This changeset makes `Client` use composition by providing a method to register an `Observer` on all its `Observable` fields. Additionally, it removes an obsolete call to `setChanged()` that was present in `DeliveryDelegate`.
=> Client should not extend Observable

bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java
The notifier spec states that 32 events should be stored by default - this updates the implementation from the previous 128.
=> Reduce event storage size to 32

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/main/java/com/bugsnag/android/UserAware.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt
The notifier specification states that `setUser()` should not have overloads for individual methods and `null` should be passed instead. This changeset updates the implementation to match the spec.
=> Remove setUser() overloads

bugsnag-android-core/src/main/java/com/bugsnag/android/Event.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventStateTest.java
According to the notifier spec `ignoreClasses` should apply to all errors in an event. This updates the implementation to consider all errors rather than just the first one, and adds test cases for this scenario.
=> IgnoreClasses should apply to all errors in an event

bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java
The change suggested in https://github.com/bugsnag/bugsnag-android/pull/700#discussion_r356149561
was suggesting just abstracting the code for caching to file and reusing it everywhere the class
deals with caching to file. I think it still makes sense for `deliver` to determine whether to
deliver or cache.
=> refactor(DeliveryDelegate): encapsulate event caching code only

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt
Adds support for loading all primitive configuration values from the manifest. This changeset loads the fields which were missing from the previous implementation:
- appType
- codeBundleId
- autoTrackSessions
`loggingEnabled` has been removed as it is obsolete and replaced by `logger`. Additionally, a `Configuration.load()` method has been added to match the notifier spec implementation.
=> Support loading all primitive values from manifest

bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java
Updates the warning message for calling `Bugsnag.init` multiple times to the message written in the spec.
=> Update warning message for multi init

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BreadcrumbStateTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt
Runs the `OnBreadcrumb` callback in `BreadcrumbState` rather than in `Client`. This means callers of `BreadcrumbState#add()` don't need to know that a callback must be run before adding a breadcrumb.
```
// old internal API
callbackState.runOnBreadcrumbTasks(crumb)
breadcrumbstate.add(crumb)
// new internal API
breadcrumbstate.add(crumb)
```
This fixes one bug where a callback wasn't run in the `leaveErrorBreadcrumb()` method of `DeliveryDelegate`.
Updated `BreadcrumbState` to run `OnBreadcrumb` tasks before adding a breadcrumb, and removed this functionality from `Client`. A unit test has been added to verify this and existing tests updated.
=> Run OnBreadcrumb callback in BreadcrumbState

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ThreadTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Error.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadSerializationTest.kt, bugsnag-android-core/src/test/resources/thread_serialization_0.json, bugsnag-android-core/src/test/resources/thread_serialization_1.json
Uses enums rather than strings for `ErrorType/ThreadType`. This matches the notifier spec and also constrains the notifier to explicitly support android/browserjs/c thread traces. If we wish to support additional types of error/thread in future, we will have to explicitly add these in and perform any work required to parse stack frames differently, rather than blindly accepting any string value for `type`.
Added `ErrorType` and `ThreadType` and updated existing code and test coverage to use these rather than strings.
=> Use enums rather than strings for Error/Thread type

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt
Renames `persistUserBetweenSessions` to `persistUser`. This achieves consistency with the latest version of the notifier spec.
=> Rename persistUserBetweenSessions to persistUser

bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagPluginInterface.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagPluginInterfaceTest.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/CustomPluginExample.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CustomPluginNotifierDescriptionScenario.kt, features/plugin_interface.feature, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/CustomPluginExample.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CustomPluginNotifierDescriptionScenario.kt, tests/features/plugin_interface.feature
Fixes an issue where a plugin cannot be configured until _after_ Bugsnag
is started, potentially sending reports prior to a plugin being able to
modify them.
=> feat: (internal) Support initializing custom plugins before init

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientConfigTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/OnBreadcrumbStateTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ProjectPackagesTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/AnrConfigTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ApiKeyValidationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/InternalReportDelegateTest.kt, bugsnag-plugin-android-anr/src/test/java/com/bugsnag/android/BugsnagTestUtils.java, examples/sdk-app-example/src/main/AndroidManifest.xml, tests/features/fixtures/mazerunner/src/main/AndroidManifest.xml, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, tests/features/support/env.rb
Validates the API key to be 16 hexadecimal characters long, as per the notifier spec.
- Made `Bugsnag.init(apiKey: String)` load `Configuration` with an `apiKey` override, rather than just use a `Configuration` object
- Validated that an API key supplied to `Configuration` must be 32 chars in length and only contains hexadecimal alphanumerics
Added additional unit test coverage for `Configuration` API key validation, and updated existing test cases to pass in a valid API key.
=> Validate API key to be 16 hexadecimal characters long

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, features/breadcrumb.feature, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/BreadcrumbScenario.kt, tests/features/breadcrumb.feature
The "Bugsnag Loaded" breadcrumb should be of type Navigation according to the spec. This changeset updates the type to match the spec, and test assertions to pass the change.
=> Alter bugsnag loaded breadcrumb type

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/OnBreadcrumbCallbackStateTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/UniqueOnErrorCallbackTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/CallbackAware.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/CallbackState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/main/java/com/bugsnag/android/OnBreadcrumbCallback.java, bugsnag-android-core/src/main/java/com/bugsnag/android/OnErrorCallback.java, bugsnag-android-core/src/main/java/com/bugsnag/android/OnSession.java, bugsnag-android-core/src/main/java/com/bugsnag/android/OnSessionCallback.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/CallbackStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConcurrentCallbackTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/OnErrorCallbackTest.kt
Renames the `OnError/OnBreadcrumb/OnSession` callbacks to have a "Callback" suffix as their type. The actual usage in fields and methods should remain as `OnError` without the suffix.
The method name has also been updated from `run()` to `onX()`, as this will be more descriptive for Java consumers of our library.
=> Rename Callback interfaces

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ThreadTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Error.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadSerializationTest.kt
The casing we use for enums is inconsistent in the codebase. While [both are valid for Kotlin](https://kotlinlang.org/docs/reference/coding-conventions.html#property-names), we should try and pick one to ensure our API remains consistent.
Changed `Error.Type` and `Thread.Type` to use upper-case. Existing test code was also updated to use these new names.
=> Use consistent case for enums

bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EndpointConfiguration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
Renames `Endpoints` to `EndpointConfiguration` to match the notifier spec. Note that the field name should rename the same and only the type should change.
=> Rename Endpoints -> EndpointConfiguration

bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventMetadataCloneTest.kt
Clones metadata when setting the initial Client value from Configuration, and setting metadata on an Event. This matches the notifier spec and avoids global state mutating event payloads in-flight.
Made `Metadata` a data class which allows for its values to be cloned via a `copy()` method when setting on the `Event`.
Added unit tests to verify that metadata is deep-cloned when necessary.
=> Clone metadata for configuration and event

bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt
Updates the error breadcrumb metadata to include fields defined in the notifier spec, and updates test coverage to verify this.
=> Update error breadcrumb metadata

bugsnag-android-core/src/test/resources/event_redaction.json, bugsnag-android-core/src/test/resources/event_serialization_6.json
Fixes the ordering of a JSON test fixture to pass the `EventRedactionTest` and `EventSerializationTest`, which were failing. Currently these tests serialize JSON to a string which is then compared for equality against a JSON fixture, so the ordering of elements in the file matters. The failure seems to have been introduced in a merge conflict.
=> Fix test fixture ordering

CHANGELOG.md, build.gradle, features/fixtures/mazerunner/build.gradle, tests/features/fixtures/mazerunner/build.gradle, tests/features/fixtures/minimalapp/build.gradle
bugsnag-android used [version 1.3.21](https://github.com/bugsnag/bugsnag-android/blob/master/build.gradle#L10) of Kotlin, which has a security vulnerability [CVE-2019-10101](https://nvd.nist.gov/vuln/detail/CVE-2019-10101).
Updating to a newer version of Kotlin prevents the possibility of a MITM attack when downloading the Kotlin library dependency.
Fixes #738
=> Fix: address CVE-2019-10101 by increasing Kotlin version to 1.3.61

bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt
Improves the stacktrace logged when something goes wrong reading the manifest, by setting a cause on the throwable.
=> log exception as cause when loading manifest

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/ClientConfigObserver.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java, bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt, bugsnag-plugin-android-anr/src/main/jni/anr_handler.c, bugsnag-plugin-android-anr/src/main/jni/anr_handler.h, bugsnag-plugin-android-anr/src/main/jni/bugsnag_anr.c
Currently the previously installed signal handler is always invoked for SIGQUIT. In Unity apps invoking the previous handler triggers a SIGSEGV in the Unity signal handler, which is an apparent bug in the implementation. As the handler only appears to print a dump of the threads to the console, we should therefore avoid calling it as doing so will allow us to detect ANRs on Unity.
This is controlled by adding a non-public `unityApp` flag to `Configuration`, which is set by Unity during initialisation, then passed onto the `AnrPlugin` and ultimately the native layer.
Methods which enable/disable native error capture such as `enableAnrReporting/disableAnrReporting` have also been tweaked so that they do not flip the configuration option when invoked. This is because when the releaseStage …
=> Allow disabling previous signal handler invocation for Unity ANRs

bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/TrimmedStacktraceScenario.kt
Removes a `notify()` method variant that accepts a name, message, and stacktrace. It is possible to achieve this by using a `Throwable` with a custom stacktrace set on it and altering the name/message in a callback. This variant should therefore be removed.
=> Remove notify method variant

features/fixtures/mazerunner/src/main/cpp/entrypoint.cpp, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXThrowSomethingReenabledScenario.java, tests/features/fixtures/mazerunner/src/main/cpp/entrypoint.cpp, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXThrowSomethingReenabledScenario.java, tests/features/ignored_reports.feature
Fixes `ignored_report.feature` which was failing on Android 6 browserstack devices, but passing locally.
This fix comes in 4 parts:
1. Add missing C++ methods that are called by the JNI. As these weren't present the scenario would always crash prior to execution
2. Set `setDetectNdkCrashes` to `true` after altering the release stages, required since #736 
3. Set the `eventMetaData` variable for scenarios in the fixture app. The `eventMetaData` variable was not set by default in the browserstack fixture but was set in the local fixture, which led to the scenario failing _only_ when run on browserstack under a specific set of circumstances
4. Fix an incorrect assertion that used mazerunner v1 steps, rather than v2
**Note**: we should possibly consider different approaches for verifying that …
=> Fix ignored reports mazerunner test

.buildkite/pipeline.yml
Use docker-compose-buildkite-plugin v3.1.0 in preparation for move to Buildkite agent 4.3.5
To allow the Buildkite agent to be updated to 4.3.5.  We found previously that Docker push commands were not being executed if placed in the same pipeline step as a build.
Buildkite pipeline only.
Implicitly tested by a successful Buildkite build.
=> chore (build): bump docker-compose-buildkite-plugin to latest version

bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagClientMirrorInterfaceTest.kt, bugsnag-plugin-android-ndk/src/main/assets/include/bugsnag.h, bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c, examples/sdk-app-example/src/main/java/com.bugsnag.android/example/ExampleApplication.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoSessionScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/BugsnagInitScenario.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
Renames `Bugsnag.init()` to `Bugsnag.start()` to achieve compliance with the notifier spec naming conventions.
=> Rename Bugsnag.init to Bugsnag.start

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt
Converts the `sendThreads` configuration option from a boolean to an enum type. This allows for multiple states to be specified in future, and also allows for a distinction between always reporting thread traces, never reporting, and reporting only for unhandled errors.
- Updated `Event` logic that gates whether a thread trace should be collected or not
- Removed `com.bugsnag.android.SEND_THREADS` as a key that can be specified in the manifest as this is no longer a primitive type
- Updated existing test coverage to assert the new default values/overrides for the `sendThreads` option
=> Convert sendThreads from boolean to enum

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt
Allows setting an initial `User` object on `Configuration`, which brings bugsnag-android into line with the notifier spec.
Made `Configuration` implement `UserAware` and copied `user` field to `Client` if it has been mutated from the default
Added an instrumentation test to verify the behaviour for when user should and shouldn't be cloned
=> Allow setting user on Configuration object

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt
If an array value is null, it should be interpreted as having all potential values in it. This applies specifically to the `enabledReleaseStages` and `enabledBreadcrumbTypes` configuration options - if a value is null here, we should always report an error/breadcrumb.
- Made `enabledReleaseStages/enabledBreadcrumbTypes` nullable
- Updated code to handle nullability of fields
- Updated existing unit test assertions to add a check for behaviour when a field is null
=> Null array values should be interpreted as true

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ClientObservable.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorTypes.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EnabledErrorTypesTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingDisabledNdkScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingDisabledScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AppNotRespondingScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoDetectNdkDisabledScenario.java, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AutoDetectNdkEnabledScenario.java, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DisableAutoDetectErrorsScenario.kt, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
Reworks the configuration for controlling error capture to match the notifier spec, by adding an `ErrorType` class
- Replaces the previous boolean flags with `ErrorType` class on `Configuration`
- Removes the ability to set ANR/NDK/Exception detection from the manifest as these are no longer represented on `Configuration` as primitive types
- Updated existing code to use new `ErrorType` field
Updated existing test code to use new `ErrorType` field.
=> Add enabledErrorTypes configuration option

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorTypes.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EnabledErrorTypesTest.kt
Adds the `autoDetectErrors` flag to `Configuration` which disables all error capture, matching the notifier spec.
- Added `autoDetectErrors` boolean field to `Configuration`
- Added `com.bugsnag.android.AUTO_DETECT_ERRORS` as boolean field that can be read from manifest
- Disabled all error detection if `autoDetectErrors` is false when constructing an `ImmutableConfig` object
Added to existing unit/instrumentation tests.
=> Add autoDetectErrors flag to Configuration

features/async_error_flush.feature, features/detect_anr.feature, mazerunner-scenarios/src/main/java/com/bugsnag/android/JavaHooks.java, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AsyncErrorConnectivityScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AsyncErrorDoubleFlushScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/AsyncErrorLaunchScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DeletedReportScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DeletedSessionScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/TestHarnessHooks.kt, tests/features/async_error_flush.feature, tests/features/detect_anr.feature
Note: This is reopened PR #755 due to a requested rename of the base branch.
Fixes silent failures of the following, as detected by browserstack logs on the latest mazerunner run:
```
AsyncErrorConnectivityScenario
AsyncErrorDoubleFlushScenario
AsyncErrorLaunchScenario
AppNotRespondingLaterDisabledScenario
DeletedReportScenario
DeletedSessionScenario
```
1. `AppNotRespondingLaterDisabledScenario` tests that ANR detection can be dynamically enabled/disabled, which is no longer relevant as the notifier spec states that this should be decided up-front. The Java scenario which tested this was removed but the scenario was not.
2. `AsyncErrorConnectivityScenario` was failing due to `event.app` and `event.device` being [lateinit properties](https://github.com/bugsnag/bugsnag-android/blob/configur …
=> Fix silently failing mazerunner scenarios

bugsnag-plugin-android-ndk/src/main/assets/include/bugsnag.h, bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.h, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/handlers/cpp_handler.cpp, bugsnag-plugin-android-ndk/src/main/jni/handlers/signal_handler.c, bugsnag-plugin-android-ndk/src/test/CMakeLists.txt, bugsnag-plugin-android-ndk/src/test/cpp/main.c, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c, features/fixtures/mazerunner/src/main/cpp/bugsnags.cpp, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXExceptionOnErrorFalseScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXExceptionOnErrorTrueScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXSignalOnErrorFalseScenario.java, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXSignalOnErrorTrueScenario.java, features/native_on_error.feature, tests/features/fixtures/mazerunner/src/main/cpp/bugsnags.cpp, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXExceptionOnErrorFalseScenario.java, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXExceptionOnErrorTrueScenario.java, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXSignalOnErrorFalseScenario.java, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXSignalOnErrorTrueScenario.java, tests/features/native_on_error.feature
Note: This is reopened PR #744 due to a requested rename of the base branch.
Adds an `on_error` implementation which consists of a callback that is invoked when a fatal signal/exception occurs. This will allow users to discard native errors at the time of capture and to append additional metadata if required.
It's worth noting that the intention is to expose more methods that will allow for the manipulation of the `bugsnag_event` struct in future PRs. This changeset focuses mainly on the ability to add/remove `on_error` callbacks and only adds mutators as required for testing.
- Added a public `on_error` typedef that consists of a single-param method with an `intptr_t` to a non-public `bugsnag_event` struct
- Added `add_on_error/remove_on_error`, which sets the value of a single global …
=> Implement on_error in NDK layer

bugsnag-plugin-android-ndk/src/main/assets/include/bugsnag.h, bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c
Adds accessor methods for manipulating the fields on `event.app`. This is necessary now that the `bugsnag_event` pointer is exposed in an `on_error` callback, and allows users to mutate the generated report.
Added get/set methods for each field defined on `event.app` that is present in the notifier spec.
Added unit tests for each new accessor method.
=> Add ndk accessor methods for event.app

bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/metadata.c, bugsnag-plugin-android-ndk/src/main/jni/metadata.h, bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c, bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c
Adds accessor methods for manipulating the fields on `event.device`. This is necessary now that the `bugsnag_event` pointer is exposed in an `on_error` callback, and allows users to mutate the generated report.
- Added get/set methods for each field defined on `event.device` that is present in the notifier spec.
- Updated `bugsnag_event_set_orientation` to use new public accessor method
- Added a migration for `bsg_device_info_v1` as the struct value has changed
**Note:** this PR does _not_ include accessors for `cpuAbi` and `runtimeVersions`. I'm not 100% sure how we'd want to approach exposing array values from the `bugsnag_event` struct, and am also not convinced that users would want to manipulate these fields in the context of a crashing process.
Added unit tests for each new …
=> Add ndk accessors for event.device

bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c
Adds accessor methods for manipulating the fields on `event.error`. This is necessary now that the `bugsnag_event` pointer is exposed in an `on_error` callback, and allows users to mutate the generated report.
Added get/set methods for each primitive field defined on `event.error` that is present in the notifier spec.
Added unit tests for each new accessor method.
=> Add accessors for ndk error class/message/type

bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c
Adds accessor methods for manipulating `event.user`. This is necessary now that the `bugsnag_event` pointer is exposed in an `on_error` callback, and allows users to mutate the generated report.
Added a setter method for `event.user`.
Note that a getter method has not been added. This would also require adding a getter method to the main `Bugsnag` interface, and exposing some form of a `bsg_user` struct - as this would be an additive change this has been left for #768 
Added unit tests for each new accessor method.
=> Add setUser accessor to event

bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/handlers/cpp_handler.cpp, bugsnag-plugin-android-ndk/src/main/jni/handlers/signal_handler.c, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c, bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c
Adds accessor methods for manipulating the `unhandled` and `severity` fields on `event`. This is necessary now that the `bugsnag_event` pointer is exposed in an `on_error` callback, and allows users to mutate the generated report.
Added get/set methods for `severity`, and a getter only for `unhandled`.
Added unit tests for each new accessor method.
=> Add accessors for unhandled/severity

bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.h, bugsnag-plugin-android-ndk/src/test/cpp/main.c, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c, bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.h
Adds an accessor method for getting `event.user`.
Note that this method returns a public exposed struct. I believe this is the most idiomatic way of achieving compliance with the notifier spec. One alternative would be to return a pointer to the event (or user) struct, and add separate accessor methods for each individual field on the struct.
Related to #764 
- Added a getter to return the `event.user` value
- Renamed `bugsnag_user` to `bugsnag_user_t` for consistency with other types in event.h
- Avoided using macro to size `bugsnag_user_t` fields of the struct as this can be overridden by end-users
- Added a test to verify the accessor method retrieves the struct
=> Add getter for user struct on event

bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c, bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c
Adds `grouping_hash` to `bugsnag_event` so that users can alter the grouping on the `bugsnag_event` exposed in an `on_error` callback.
Added unit tests for each new accessor method, and to verify that the new field is serialized correctly.
=> Add grouping_hash to ndk event interface

UPGRADING.md
Note: This is reopened PR #757 due to a requested rename of the base branch.
Adds an upgrade guide from v4 -> v5 of the notifier.
I've tried to focus on mapping legacy method signatures onto the replacement APIs, and linked off to the docs when an in-depth explanation is required (as the upgrade guide will inevitably get out of sync with the docs as time goes on).
I've borrowed a few bits and pieces from the JS upgrade guide so feedback might apply there also: https://github.com/bugsnag/bugsnag-js/blob/v7/UPGRADING.md#6x-to-7x
=> Add v5 upgrade guide

bugsnag-plugin-android-ndk/src/androidTest/resources/app_meta_data_serialization_0.json, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/metadata.c, bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c, bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c
Removes the `packageName` and `versionName` fields from the serialized payload in `event.app`. These are replaced by `id` and `version` respectively, so are redundant.
The fields have already been removed from the JVM payload - this removes them from the NDK payload.
Verified in an example app that the payload is not present for a fatal C error.
=> Remove versionName/packageName from NDK payload

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientConfigTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/EventPayloadTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DefaultDelivery.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Delivery.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventPayload.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventPayloadSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/InternalEventPayloadDelegateTest.kt, bugsnag-plugin-android-anr/src/test/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/JavaHooks.java, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DeletedReportScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/DeletedSessionScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/Scenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/TestHarnessHooks.kt
Renames the `Report` class to `EventPayload`. This is consistent with how `SessionPayload` is named.
=> Rename Report to EventPayload

bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c
Allows accessing and manipulating data in the NDK `bugsnag_event` struct.
As C doesn't allow overloading methods this implementation deviates slightly from the notifier spec. The changes include:
- Made `bsg_metadata_t` a public type
- Added method for getting metadata for char/bool/double: `bsg_get_metadata_<type>`
- Added method for adding metadata for char/bool/double: `bsg_add_metadata_<type>`
- Added `bsg_clear_metadata/bsg_clear_metadata_section`
- Added `bsg_has_metadata` - it is expected that users call this to discern the type of metadata for the given key/section, if any
**Note**: this implementation focuses on adding these methods to access fields on the `bugsnag_event` payload only. Once this PR has been approved a similar approach will be followed on the `bugsnag` interface …
=> Allow editing metadata in ndk payload

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadSendPolicyTest.kt
Supports loading the `sendThreads` and `endpoints` options from the manifest, as per the notifier spec.
- Read `com.bugsnag.android.SEND_THREADS` as a string from the manifest, and coerced it into `ThreadSendPolicy`, reverting to a default if the option is not recognised
- Read `com.bugsnag.android.ENDPOINT_NOTIFY` and `com.bugsnag.android.ENDPOINT_SESSIONS` from the manifest
Added a new unit test for `ThreadSendPolicy`, relied on existing test coverage for endpoint loading
=> Support loading additional options from manifest

bugsnag-android-core/src/main/java/com/bugsnag/android/SystemBroadcastReceiver.java, bugsnag-android-core/src/test/java/com/bugsnag/android/SystemBroadcastReceiverTest.kt
The default breadcrumb type should be state, rather than log, as a broadcast better reflects a state change in the application than a user writing a message to a logger.
=> Change default system broadcast breadcrumb type to state

CHANGELOG.md, bugsnag-android-core/src/main/AndroidManifest.xml
Opening in favour of #782 so that CI can be run.
=> Remove uses-library android.test.runner

bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorTypes.kt
Aligns the KDoc to match what has been written for the docs website on Configuration Options. This aims to cover only properties which are unique to `Configuration` at this stage - `Client` methods will be documented once a corresponding docs PR has been raised for this section.
There have been minor edits to reference code where possible - e.g. `[releaseStages]` would link to the `releaseStages` property. Configuration options have also been slightly reworded when the documentation format would not make sense. For example, some docs state this:
```
If you wish to update this property, do the following:
```
Which does not make sense for this particular format.
=> Add docs for Configuration options

bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/jni/bugsnag.c, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.h, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.c, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder.h, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder_libcorkscrew.c, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder_libcorkscrew.h, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder_libunwind.c, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder_libunwind.h, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder_libunwindstack.cpp, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder_libunwindstack.h, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder_simple.c, bugsnag-plugin-android-ndk/src/main/jni/utils/stack_unwinder_simple.h, bugsnag-plugin-android-ndk/src/test/cpp/main.c, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c, bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.h
Allows editing the stacktrace in the NDK event payload, as per the notifier spec.
Users can request the size of the stacktrace, and then get a stackframe at a particular index and inspect/mutate it. This was seen as preferable to exposing the entire array.
Additionally, `bsg_stackframe_t` has been added as a public type.
Added a unit test for getting/mutating a stacktrace
=> Allow editing stacktrace in ndk payload

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/test/java/com/bugsnag/android/DeviceDataCollectorSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/InternalEventPayloadDelegateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt
Serializes `device.time` correctly in JVM reports, rather than always sending `Date(0)`.
This would have affected the breadcrumb times displayed in the dashboard as they would have based the calculations of 1 Jan 1970. I have verified the fix by sending an example report to the dashboard and inspecting breadcrumb times and `device.time`.
=> Serialize device.time correctly

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/OnBreadcrumbCallbackStateTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ConnectivityCompat.kt, features/breadcrumb.feature, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/BreadcrumbScenario.kt, tests/features/breadcrumb.feature
Adds a breadcrumb which is logged when the connectivity changes. This makes the notifier conform with the notifier spec.
- Updated the `NetworkChangeCallback` to pass `networkState` as a parameter also
- Left a breadcrumb in the network change callback implementation
- Reordered `Client` constructor so that the `OnBreadcrumb` callback that implements `enabledBreadcrumbTypes` filtering is always set before the connectivity change callback. This avoids a race where the connectivity breadcrumb might potentially be added before this filter is set
Manually verified that a breadcrumb appears as expected when changing the connectivity in an emulator.
Updated the unit tests and mazerunner scenarios so that the connectivity changed/bugsnag loaded breadcrumbs are filtered out from tests, and so …
=> Add connectivity change breadcrumb

bugsnag-android-core/src/main/java/com/bugsnag/android/AppDataCollector.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt
The `releaseStage` was not set on the `ImmutableConfig` object when a `Client` was initialised, meaning it remained null if not set explicitly. This updates the sanitiser function to set a default value on the field, rather than just the serialized payload.
Moved the `guessReleaseStage` method to `ImmutableConfig` which is populated on `Client` initialisation.
Added a unit test to verify that the field is set to a sensible default.
=> Populate releaseStage in config during initial sanitisation

bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ApiKeyValidationTest.kt
Allows setting the API key in configuration after an object has been initialised. Previously this field was immutable.
=> Allow setting api key in config

bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt
Makes `config.appType` nullable as per the notifier spec.
=> Make config.appType nullable as per spec

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.kt
Makes `event.session` non-public as per the notifier spec.
This has been defined as an internal JVM field instead, so that we can continue to access it from Java and in existing unit tests.
=> Make event.session non-public

.buildkite/pipeline.yml, dockerfiles/Dockerfile.android, tests/features/strict_mode.feature, tests/features/support/env.rb
Add Android 8.1 and 10.0 Maze Runner tests, as well as Instrumentation tests on Android 10 to the CI build.
Following existing pattern for builds, except using the "soft fail" functionality of BuildKite for the Maze Runner tests.  We know there are issues causing some tests to fail and these need more investigation in due course, but for now we would rather receive the feedback from running them and failing than having nothing at all.
Pipeline build updated to include new versions.
Logic for determining skipping of tests on specific versions of Android updated to account for new device names in Maze Runner.
Verified by inspecting the build output.
=> Add android 8.1 and 10

bugsnag-plugin-android-ndk/src/main/jni/metadata.c
Prevents a crash when adding non-string metadata to breadcrumbs. This bug became apparent when syncing the new navigation breadcrumbs to the NDK layer, as these contain a boolean value - this can be triggered by running the example app with ndk detection enabled.
Performed a type check of the metadata value when syncing a breadcrumb value.
Confirmed that the example app no longer crashes when loading a local artefact.
=> Prevent crash when adding non-string metadata in breadcrumbs

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/MetadataState.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataStateTest.kt, bugsnag-plugin-android-ndk/src/main/jni/metadata.c
Syncs initial metadata values added in `Configuration` over to the NDK layer.
This changeset relies on #804 which has not yet been merged.
Added a method to `MetadataState` which sends an observable message `StateEvent.AddMetadata` for each piece of metadata added in `Configuration`. Fired this message in the `Client` after initialising the NDK plugin.
Ran an example app with a local artefact and confirmed that metadata added in `Configuration` makes it to the payload. Also added unit test coverage to the delivery of the `Observable` message in `MetadataState`.
=> Sync initial metadata values over to NDK

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/EventPayloadTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/BugsnagPluginInterface.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Error.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Event.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventImpl.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java, bugsnag-android-core/src/test/java/com/bugsnag/android/CallbackStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConcurrentCallbackTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/EventMetadataCloneTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventNameTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventRedactionTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventStateTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/EventTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/InterceptingLogger.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/InternalEventPayloadDelegateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NullMetadataTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/OnErrorCallbackTest.kt
Logs a warning when null values are supplied to Event, rather than throwing an exception.
It may be easier to review the first two commits in isolation. The first implements code changes, whereas the second implements docs changes.
- Renamed `Event.kt` to `EventInternal.kt` and made it non-public
- Added `Event.java` which uses the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) on a `EventInternal` field and acts as the public interface
- If a null value is passed to a non-null config option, a warning is now logged
- Moved code documentation to `Event.java`
- Updated existing code to match nullability of latest version of notifier spec and to pass tests
- Altered errors/breadcrumbs/threads on `Event` to be a readonly mutable list, as this better reflects the spec as …
=> Log a warning when null values are supplied to Event, rather than throwing an exception

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java
Logs a warning when null values are supplied to Client, rather than throwing an exception.
Note: this also applies to the `Bugsnag.java` facade. It is assumed that the `BugsnagApiTest` suite gives sufficient coverage to test that class.
- If a null value is passed to a non-null parameter, a warning is now logged
- Added a package-visible constructor to allow injection of mocks for unit testing
Added unit tests to verify that the correct method on a `Client` field is invoked when a method on the public API is invoked, and that a message is logged when appropriate.
=> Log a warning when null values are supplied to Client, rather than throwing an exception

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionV1PayloadTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionV2PayloadTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Session.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTest.kt
Logs a warning when null values are supplied to Session, rather than allowing an NPE if the user invokes a getter.
- If a null value is passed to a non-null option, a warning is now logged
- Passed in `logger` as required to `Session` constructors
Added unit tests to verify that the correct method on `Session` is invoked when a valid value is set, and that a warning message is logged when null is passed.
=> Log a warning when null values are supplied to Session

bugsnag-android-core/src/main/java/com/bugsnag/android/Device.kt
Makes fields on `device` nullable - these were not conforming to the notifier spec so can be altered.
=> Allow null values on device field

bugsnag-android-core/src/main/java/com/bugsnag/android/Error.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorImpl.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorType.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NullMetadataTest.java
Logs a warning when null values are supplied to Error, rather than throwing an exception.
It may be easier to review the first two commits in isolation. The first implements code changes, whereas the second implements docs changes.
- Renamed `Error.kt` to `ErrorImpl.kt` and made it non-public
- Added `Error.java` which uses the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) on a `ErrorImpl` field and acts as the public interface
- If a null value is passed to a non-null config option, a warning is now logged
- Moved code documentation to `Error.java`
- Updated existing code to match nullability of latest version of notifier spec and to pass tests
- Passed in `logger` as required to `Error` constructor
- Moved `Error.Type` to its own file
Added unit tests to verify …
=> Log a warning when null values are supplied to Error, rather than throwing an exception

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BreadcrumbStateTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Breadcrumb.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Breadcrumb.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/BreadcrumbState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbMutabilityTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/CallbackStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConcurrentCallbackTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventRedactionTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/JsonStreamTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt
Logs a warning when null values are supplied to Breadcrumb, rather than throwing an exception.
It may be easier to review the first two commits in isolation. The first implements code changes, whereas the second implements docs changes.
- Renamed `Breadcrumb.kt` to `BreadcrumbImpl.kt` and made it non-public
- Added `Breadcrumb.java` which uses the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) on a `BreadcrumbImpl` field and acts as the public interface
- If a null value is passed to a non-null config option, a warning is now logged
- Moved code documentation to `Breadcrumb.java`
- Updated existing code to match nullability of latest version of notifier spec and to pass tests
- Passed in `logger` as required to `Breadcrumb` constructor
- Updated breadcrumb properties …
=> Log a warning when null values are supplied to Breadcrumb, rather than throwing an exception

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ThreadTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadImpl.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadSendPolicy.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadType.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadSendPolicyTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadSerializationTest.kt
Logs a warning when null values are supplied to Thread, rather than throwing an exception.
It may be easier to review the first two commits in isolation. The first implements code changes, whereas the second implements docs changes.
- Renamed `Thread.kt` to `ThreadImpl.kt` and made it non-public
- Added `Thread.java` which uses the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern) on a `BreadcrumbImpl` field and acts as the public interface
- If a null value is passed to a non-null config option, a warning is now logged
- Moved code documentation to `Thread.java`
- Updated existing code to match nullability of latest version of notifier spec and to pass tests
- Passed in `logger` as required to `Thread` constructor
- Updated properties to be mutable on `Thread.kt`
- …
=> Log a warning when null values are supplied to Thread, rather than throwing an exception

bugsnag-plugin-android-ndk/src/androidTest/resources/breadcrumbs_serialization_0.json, bugsnag-plugin-android-ndk/src/androidTest/resources/custom_meta_data_serialization_0.json, bugsnag-plugin-android-ndk/src/androidTest/resources/exception_serialization_0.json, bugsnag-plugin-android-ndk/src/androidTest/resources/handled_state_serialization_0.json, bugsnag-plugin-android-ndk/src/androidTest/resources/session_serialization_0.json, bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c
Fixes the native serialization tests using uninitialized values in their test data. This could lead to undefined behaviour and has resulted in flaky tests.
- Updated each function which loads a struct to populate a valid value for all fields on the struct
- Updated the expected JSON fixture to reflect the new values
- Improved test coverage generally for serialization of breadcrumbs/metadata/handledState by populating valid values
- Organised existing functions to populate fields in a struct in the order in which the struct is defined. This makes it easier to visually see when a field has been missed.
=> Improve native serialization test assertions

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt
`config.logger` is null by default and is then set to a default value during the `Client` constructor. This can cause a NPE when an invalid option is supplied.
This alters the notifier to set the field to `DebugLogger` by default, and then if the `releaseStage` equals "production" in the `Client` constructor, sets the logger to a `NoopLogger`. This allows us to log error messages when a user has initialised configuration wrong but otherwise retain the default behaviour. It is still possible to disable logging entirely by setting a custom logger on `Configuration`.
This also fixes a bug caused by ordering, where the logger was set before the releaseStage in the Configuration sanitisation. `sanitiseConfiguration()` has therefore been moved as far up the `Client` constructor as possible.
- …
=> Prevent logger from throwing NPE in Configuration

bugsnag-plugin-android-ndk/src/androidTest/resources/breadcrumbs_serialization_0.json, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/metadata.c, bugsnag-plugin-android-ndk/src/main/jni/metadata.h, bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_breadcrumbs.c, bugsnag-plugin-android-ndk/src/test/cpp/test_serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c
Migrates the NDK layer to use the new `bugsnag_metadata` struct. This allows for numeric/boolean values to be added as metadata in breadcrumbs, and simplifies the implementation by keeping the same sort of metadata for both fields.
- Replaced `bsg_char_metadata_pair` with `bugsnag_metadata` on the event interface
- Added a migration to handle previously serialized structs
- Altered non-public methods for manipulating metadata to take a `metadata` parameter, rather than just a `bugsnag_event`, to allow code reuse between event/breadcrumb metadata manipulation
- Supported setting boolean and numeric values on breadcrumb metadata
- Manually verified that a boolean metadata value can be added to a breadcrumb from Java, and that it is displayed in fatal NDK errors.
- Updated existing test …
=> Migrate NDK breadcrumb metadata to use new struct

bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-plugin-react-native/README.md, bugsnag-plugin-react-native/build.gradle, bugsnag-plugin-react-native/detekt-baseline.xml, bugsnag-plugin-react-native/gradle.properties, bugsnag-plugin-react-native/lint-baseline.xml, bugsnag-plugin-react-native/proguard-rules.pro, bugsnag-plugin-react-native/src/main/AndroidManifest.xml, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/AppSerializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BreadcrumbSerializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ConfigSerializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/DeviceSerializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/InternalHooks.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadSerializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/WritableMapSerializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/AppSerializerTest.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/BreadcrumbSerializerTest.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ConfigSerializerTest.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/DeviceSerializerTest.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestData.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ThreadSerializerTest.java, bugsnag-plugin-react-native/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker, dockerfiles/Dockerfile.android-base, dockerfiles/Dockerfile.android-builder, dockerfiles/Dockerfile.android-instrumentation-tests, dockerfiles/Dockerfile.android-jvm, dockerfiles/Dockerfile.android-sizer, settings.gradle
Adds `bugsnag-plugin-react-native` as a module to the project, rather than hosting a substantial amount of Android code in the bugsnag-js repo. This grants us several benefits:
- Less context-switching between bugsnag-android and bugsnag-react-native
- Less effort spent setting up static analysis for separate projects
- Easier to test native changes, as this would simply be a case of publishing to `mavenLocal` rather than altering vendored code in node_modules
- Greater clarity over whether the code should be owned by Android/JS custodians
For the equivalent JS changes, see https://github.com/bugsnag/bugsnag-js/pull/753
**Note**: the intended design for the module's interaction with bugsnag-js has been listed below, but this has not been implemented in full (as the bugsnag-react-native …
=> Add bugsnag-plugin-react-native as a module

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/AppSerializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BreadcrumbSerializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ConfigSerializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/DeviceSerializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/MapDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/MapSerializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/MapUtils.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadSerializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/UserDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/UserDeserializerTest.kt
The `dispatch()` method on `BugsnagReactNativePlugin` accepts a map from the JS layer which contains information about a JS error. We need to deserialize this from a map into an `Event`.
This changeset adds an interface to do this and implements a deserializer for the `User` field. Other deserializers will be implemented in future PRs.
- Renamed `WritableMapSerializer` to `MapSerializer` to more accurately reflect responsibility
- Created `MapDeserializer` interface
- Implement deserializer for user information
Added a unit test for the deserialization
=> Add deserializer interface for User

bugsnag-android-core/src/main/java/com/bugsnag/android/Stacktrace.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ErrorDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/MapUtils.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/StackframeDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/UserDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ErrorDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/StackframeDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ThreadDeserializerTest.kt
Adds deserializers which convert a `Map` into `Error`, `Thread`, and `Stackframe`. This is required by the React Native plugin when a JS error is sent over the React bridge for the native layer to deliver.
- Added deserializers for `Error/Thread/Stackframe`.
- Added `MapUtils` with convenience methods for retrieving values from a map with type safety, either returning null or throwing an exception
- Added additional constructor to `Stacktrace`
- Minor tweak of `UserDeserializer` implementation
Added unit tests to cover each deserializer.
=> Add deserializers for error, thread, and stackframe

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/MetadataState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/StateEvent.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/UserState.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/UserStateTest.kt, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativeBridge.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/MessageEvent.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/BugsnagReactNativeBridgeTest.java
Captures state events relevant to React Native and converts them to a `MessageEvent` class, which will be sent across the React Native bridge. The JS layer needs to be informed of 3 changes on the native layer: context, user, and metadata. This changeset subscribes to these events and converts them to an agreed interface the JS layer can understand.
**Note**: the actual emission of the event data across the React Native bridge has not been included and will be implemented in a separate PR.
- Added `BugsnagReactNativeBridge` which converts state events to `MessageEvent` then invokes a callback
- Subscribed the plugin to events for context/user/metadata
- Converted separate user StateEvent types into one, `UpdateUser`
- Renamed old `StateEvent` types to `ClearMetadataSection` and …
=> Capture state events relevant to react native

bugsnag-android-core/src/main/java/com/bugsnag/android/DateUtils.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BreadcrumbDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/MetadataDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/BreadcrumbDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/MetadataDeserializerTest.java
Adds deserializers which convert a `Map` into `Breadcrumb` and `Metadata`. This is required by the React Native plugin when a JS error is sent over the React bridge for the native layer to deliver.
- Added deserializers for `Breadcrumb/Metadata`.
- Added `MapUtils` with convenience methods for retrieving values from a map with type safety, either returning null or throwing an exception
- Minor tweak of `UserDeserializer` implementation
Added unit tests to cover each deserializer.
=> Add deserializers for Breadcrumb and Metadata

.buildkite/pipeline.yml
We now have access to ten BrowserStack App Automate parallel tests.  This change updates the pipeline concurrency setting to make use of them. 
Pipeline setting updated accordingly.
BuildKite pipeline.yml only.
Tested as part of standard CI.
=> Increase build concurrency setting for extra BrowserStack slots

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/main/java/com/bugsnag/android/App.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/AppWithState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DateUtils.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceWithState.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/test/java/com/bugsnag/android/EventRedactionTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/AppDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/DeviceDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/AppDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/DeviceDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/DeviceSerializerTest.java, mazerunner-scenarios/src/main/java/com/bugsnag/android/JavaHooks.java
Adds deserializers which convert a `Map` into `AppWithState` and `DeviceWithState`. This is required by the React Native plugin when a JS error is sent over the React bridge for the native layer to deliver.
- Added deserializers for `AppWithState/DeviceWithState`.
- Altered `App/AppWithState` constructors to allow passing in buildUuid and other fields without a `ImmutableConfig` object
- Added `MapUtils` with convenience methods for retrieving values from a map with type safety, either returning null or throwing an exception
- Minor tweak of `UserDeserializer` implementation
Added unit tests to cover each deserializer.
=> V5 app device deserialize

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ThreadStateTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/InternalHooks.java
Moves the logic for determining whether to collect a thread trace from `Event` into `ThreadState`. This allows for the React Native implementation to return an empty list of threads if `config.sendThreads` is not enabled for the given error.
- Moved logic for collecting thread trace from `Event` to `ThreadState` constructor
- Updated `getPayloadInfo()` to accept a boolean value which holds the unhandled state
Updated existing test coverage to handle new `ThreadState` constructor
=> Move thread serialization logic into ThreadState

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt
Moves `Client` setup code to `load()` rather than `configure()`, to simplify implementation.
=> Move client setup code to load()

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Device.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceBuildInfo.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceDataCollector.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/DeviceDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/EventDeserializerTest.kt
Implements the `dispatch()` method on React Native, which sends an error from the JS layer to the native layer.
- Added a `getLogger()` method to `Client` to allow mocking rather than using direct field access
- Updated `DeviceBuildInfo` and related code to take nullable fields, as these values may have been set to null in a JS `OnError` callback
- Fixed wrong nullability annotation on `NativeInterface`
- Added `EventDeserializer` which deserializes a `Map` into an `Event`
Added a unit test for deserialization.
=> Implement react native dispatch method

bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorType.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadType.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadFacadeTest.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/DeviceDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/MapUtils.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ErrorDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/EventDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ThreadDeserializerTest.kt
Fixes bugs in the RN module implementation which prevented the example app from receiving errors during integration testing.
- Altered error/thread types 'browser_js' to 'reactnativejs'
- Coerce int/long/double values into `Number` rather than casting directly to Int/Long, as this led to a crash since the JS layer could serialize these values as doubles.
Relied on existing test coverage and manual testing within a RN example app.
=> React Native fixes after integration testing in example app

bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorInternal.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NullMetadataTest.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ErrorDeserializer.java
Ensures that frames are always trimmed to a maximum of 200 by using Stacktrace class in the Error constructor.
This prevents the scenario where a user can supply a large stacktrace from React Native (e.g. 500 frames) which would not be trimmed, due to the `bugsnag-android-core` code assuming that the `List<Stackframe>` has already been sanitised.
Verified by existing unit test and E2E test coverage.
=> Ensure frames are always trimmed by using Stacktrace class in Error

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/BugsnagReactNativePluginTest.kt
Exposes an internal API for registering a callback on the react native plugin which is invoked when a state change occurs. This allows the `BugsnagReactNative` class in the JS repo to emit the event across the React Native bridge by calling `registerForMessageEvents()` during initialisation. This aspect of the change will be raised in a separate PR in the bugsnag-js repo.
=> Allow registering for callbacks on the react native plugin

bugsnag-android-core/src/main/java/com/bugsnag/android/Stackframe.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Stacktrace.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/StackframeSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/StacktraceSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadFacadeTest.java, bugsnag-android-core/src/test/resources/stackframe_serialization_0.json, bugsnag-android-core/src/test/resources/stacktrace_serialization_1.json, bugsnag-android-core/src/test/resources/stacktrace_serialization_2.json, bugsnag-android-core/src/test/resources/stacktrace_serialization_3.json, bugsnag-android-core/src/test/resources/stacktrace_serialization_5.json, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ErrorDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/StackframeDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/StackframeDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ThreadSerializerTest.java
Adds the code and columnNumber properties to the Stackframe class. These are used by JavaScript but are not present in the React Native layer.
- Added `code` and `columnNumber` fields to the `Stackframe` interface as per the notifier spec
- Updated serializer to write new fields to JSON
- Updated `bugsnag-plugin-react-native` deserializer to grab `code` + `columNumber` from Map passed over the React bridge
- Reduced duplication in how the stacktrace length is trimmed by extracting generic function
- Converted the 2nd `Stacktrace` constructor to take a `List<Stackframe>` instead. Previously it took `List<Map>`, but this is unused outside of test code so has been replaced to gain more type safety
Relied on existing test coverage and expanded serialization tests.
=> Add code and columnNumber properties to Stackframe class

bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorTypes.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EnabledErrorTypesTest.kt
Adds the `unhandledRejections` reason to `enabledErrorTypes` to allow it to be accessed from the JS layer. This is required by the JS project.
=> Add unhandledRejections to enabledErrorTypes

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ContextState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/MetadataState.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/UserState.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataStateTest.kt, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NdkPlugin.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt
Syncs the initial state with any observers for the Metadata, User, and Context values. This alters the implementation so that the initial state is synced in both the NDK and React Native plugins.
- Created `syncInitialState()` which sends observable messages that describe the user/context/metadata to the NDK + RN observers
- Altered the RN + NDK plugins to call `syncInitialState()` after they have registered observers so that the message is always received
Added an instrumentation test to verify that the user/context/metadata message is sent when a `Client` is initialised and `syncInitialState()` is invoked.
=> Sync initial state with observers

CONTRIBUTING.md, Makefile, bugsnag-plugin-android-anr/build.gradle, bugsnag-plugin-android-ndk/build.gradle, dockerfiles/Dockerfile.android-builder, dockerfiles/Dockerfile.android-instrumentation-tests, dockerfiles/Dockerfile.android-jvm, dockerfiles/Dockerfile.android-sizer, examples/sdk-app-example/build.gradle, gradle/release.gradle
As per #615 - removes the now unsupported "armeabi" ABI from the default build.
* bugsnag-plugin-android-anr/build.gradle - removed "armeabi" from default list of targets
* bugsnag-plugin-android-ndk/build.gradle - removed "armeabi" from default list of targets
* examples/sdk-app-example/build.gradle - removed "armeabi" from default list of targets and added ABI_FILTERS property for consistency with main build
* Makefile - added full list of ABIs for inclusion when making a release
* gradle/release.gradle - added check during before assembleRelease to throw exception if the NDK library version or ABI list is unexpected (supports both Android and Unity ABI lists). 
Run locally to verify validation check, CI will show no difference without "armeabi".
=> Remove armeabi from default build

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BreadcrumbStateTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Breadcrumb.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt, features/breadcrumb.feature, features/native_api.feature, features/steps/build_steps.rb, tests/features/breadcrumb.feature, tests/features/native_api.feature, tests/features/steps/android_steps.rb
Currently `Bugsnag.leaveBreadcrumb("Button tapped")` creates a breadcrumb with `type=manual`, `name="manual"` and a single metadata item with a key of "message" and a value of "Button tapped".
This should be changed to set the name to the provided text "Button tapped" and no metadata, to match the notifier spec.
Altered the `message` constructor parameter to serialize as the `name` field instead.
Updated existing unit test coverage and E2E tests. Note that an existing mazerunner v1 step was added to the local build steps rather than updating it in the mazerunner repository - this is because the step has been removed from v2 as it was only used on Android.
=> Use 'name' field in manual breadcrumbs

CONTRIBUTING.md, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BreadcrumbFilterTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BreadcrumbStateTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SystemBroadcastReceiver.java, bugsnag-android-core/src/test/java/com/bugsnag/android/SystemBroadcastReceiverTest.kt, features/breadcrumb.feature, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/BreadcrumbAutoScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/BreadcrumbDisabledScenario.kt, tests/features/breadcrumb.feature, tests/features/steps/android_steps.rb
The new `enabledBreadcrumbTypes` should only affect the automatically collected breadcrumbs and should disable the hooks to listen for the breadcrumbs to avoid unnecessary computations.
* Created `leaveAutoBreadcrumb` in `Client` for internally-left breadcrumbs to wrap the config check
* Wrapped the various hooks for listening to system events with a check of the config and didn't register the hook if it is disabled
* Unit tests updated
* End-to-end tests for no breadcrumbs, manual and the loaded 'state' breadcrumb.
=> Change enabledBreadcrumbTypes to affect automatic breadcrumb hooks only

dockerfiles/Dockerfile.android-builder, gradle/release.gradle
Reduced scope of the new ABI validation checks to be for the publish and bintrayUpload only - not assembleRelease as this requires extra switches unnecessarily in the e2e tests.
=> Amended ABI validation to be for publish and bintrayUpload only

bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.h, bugsnag-plugin-android-ndk/src/test/cpp/test_breadcrumbs.c
Alters the size of fields in the `bugsnag_event` struct to that specified in the notifier spec, and updates existing test coverage to ensure that the migration works as expected.
This alters the breadcrumb array length from 30 to 25, and the breadcrumb name field to 64 from 33.
=> Alter NDK event field sizes

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ObserverInterfaceTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/OnBreadcrumbCallbackStateTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SystemBroadcastReceiver.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ClientFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SystemBroadcastReceiverTest.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/LeaveBreadcrumbTest.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/BreadcrumbScenario.kt
Rearranges the `leaveBreadcrumb` parameter to match the notifier spec.
=> Rearrange leaveBreadcrumb param

examples/sdk-app-example/src/main/AndroidManifest.xml
AUTO_DETECT_ANRS and AUTO_DETECT_NDK_CRASHES are now set in `enabledErrorTypes` not through manifest.
=> Removed old settings from manifest in example

Makefile, bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt
Fixes the makefile script used to update the version reported in error/session payloads. This has changed as `Notifier` is now implemented as a Kotlin class rather than Java.
=> Fix version bump script

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ConfigSerializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ConfigSerializerTest.java
Serializes the `unhandledRejections` flag in the React Native plugin, which is required information for the JS notifier to configure.
Serialized `enabledErrorTypes.unhandledRejections` as a boolean field that is passed to react-native.
Added a unit test to verify the serializer.
=> Serialize enabledErrorTypes.unhandledRejections for React Native

bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorTypes.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EnabledErrorTypesTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-android-ndk/build.gradle, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ConfigSerializerTest.java
Enables NDK detection by default as requested by product to give users more insight into NDK errors that may be happening in their apps.
- Flipped `detectNdkCrashes` to true
- Removed `BuildConfig.AUTO_DETECT_NDK_CRASHES` which was used to enable detection when consuming the `bugsnag-android-ndk` artefact, and disable detection when consuming the `bugsnag-android` artefact
Relied on existing test coverage
=> Enable ndk detection by default

examples/sdk-app-example/build.gradle, examples/sdk-app-example/src/main/java/com.bugsnag.android/example/ExampleActivity.kt, examples/sdk-app-example/src/main/java/com.bugsnag.android/example/ExampleApplication.kt
Updates the example app method signature for leaveBreadcrumb, whose parameter order has changed.
Verified that this works by running the example app up manually.
=> Update example app method signatures

tests/features/fixtures/mazerunner/build.gradle, tests/features/load_configuration.feature
- Points the bugsnag-android-gradle-plugin version to the latest release
- Re-enables assertions that passes with the last release
- Local run
=> Re-enabled BuildUUID test

UPGRADING.md
As per review comments - update the upgrade guide to emphasise use of manifest.
I've also condensed some of the content - combining the Client and Bugsnag changes into one table and putting all the Private API moves into a single table.
=> Changes to upgrade guide following review

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/BugsnagReactNativePluginTest.kt
Alters the react native plugin so that an observer for native events is only registered once.
This is required because the JS layer can be hot reloaded at runtime, and therefore `registerForMessageEvents` can be called multiple times. Previously this registered multiple callbacks which would be sent to a destroyed React bridge, causing a warning to be logged.
Added a native state observer when `Plugin#load()` is called. When `registerForMessageEvents()` is called, a JS callback is stored in a field, and invoked on any subsequent state changes.
If the JS layer undergoes a hot reload, the JS callback will be reassigned when `registerForMessageEvents()` is invoked again.
Relied on existing unit test coverage.
=> Register react native observer once only

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
The spec is a little inconsistent in using present tense for orientation and connectivity breadcrumb messages. Correcting it to make them all past-tense.
=> fix(breadcrumbs): make connectivity and orientation breadcrumbs past tense

bugsnag-android-core/src/main/java/com/bugsnag/android/LibraryLoader.java, bugsnag-android-core/src/test/java/com/bugsnag/android/LibraryLoaderTest.kt, bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NdkPlugin.kt
The ANR + NDK plugins load native libraries to detect errors. On some versions of Android these libraries cannot be loaded (e.g. due to PackageManager bugs) which results in an `UnsatisfiedLinkError` being thrown.
This error is now caught and reported to the Bugsnag dashboard, and the affected plugin(s) is disabled to allow graceful fallback.
- Moved native library loading to `LibraryLoader` class which attempts to load the library once, reporting any `UnsatisfiedLinkError` to bugsnag
- Updated ANR/NDK plugins to use `LibraryLoader` class and only continue loading if successful
Note: the error message format will need to be updated to link to documentation before this is merged. A documentation PR will be raised separately and in the meanwhile the rest of this PR can be reviewed.
Added a …
=> Gracefully fail if native library could not be loaded

bugsnag-android-core/src/main/java/com/bugsnag/android/Thread.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadInternal.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadFacadeTest.java
Makes the `errorReportingThread` property readonly. This prevents a user from setting the value to `true` on more than one thread, while allowing them to read the value in a callback.
=> Make errorReportingThread readonly

UPGRADING.md, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/AppDataCollectorSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/AppMetadataSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-android-core/src/test/resources/app_data_serialization_0.json, bugsnag-android-core/src/test/resources/app_data_serialization_1.json, bugsnag-plugin-android-anr/src/test/java/com/bugsnag/android/BugsnagTestUtils.java, mazerunner-scenarios/src/main/java/com/bugsnag/android/JavaHooks.java, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationKotlinScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationNullsScenario.java, tests/features/load_configuration.feature
The `buildUuid` field should not be settable in Configuration and should be read via the manifest only to prevent the value getting out of date with the value generated by the gradle plugin.
- Removed `buildUuid` accessors from `Configuration` and `ManifestConfigLoader`
- Updated `ImmutableConfig` to load `buildUuid` from manifest only
- Updated upgrading guide
- Removed `buildUuid` accessor/loading tests as appropriate
- Updated `event.app` serialization tests to avoid checking `buildUuid`, as the property cannot currently be mocked or faked for test
- Tested changes in example app and verified that the `buildUuid` is still reported
=> Remove buildUuid from Configuration

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java
Resolve potentially flaking instrumentation test.
Ensure that number of breadcrumbs expected is predictable by disabling all but manual breadcrumbs.
ClientTest.java
Verified by peer review and passing CI run.
=> Ensure number of breadcrumbs is predictable

bugsnag-android-core/build.gradle, build.gradle
Sets up the [Dokka](https://github.com/Kotlin/dokka) plugin for generating documentation, which is necessary now that we use Kotlin + Java files in the project.
Eventually we will want to automate this process to push to the `gh-pages` branch - for now this must be done manually.
=> Setup dokka for generating documentation

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt
Creates the observer before it is registered, otherwise this triggers an exception as the `lateinit var` will not have been initialised. This crashed the Bugsnag react native plugin
Manually verified with a local artefact on the v7-react-native example app
=> Create observer before registering plugin

dockerfiles/Dockerfile.android-maze-runner
Use the 2.0.0 release of Maze Runner.
Maze Runner has now moved to a proper release-based versioning strategy and the `v2` branch of development has ceased.  The Maze Runner image should now be referenced either by full release number or `latest-cli` to roll with the latest release available.
Maze Runner Dockerfile only.
Standard CI pipeline.
=> Use proper 2.0.0 release of Maze Runner

bugsnag-plugin-react-native/proguard-rules.pro, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt
When a JS exception crashes the app, the JS layer handles the offending error, routes it via the normal `onError` callbacks etc., and passes it to the `BugsnagReactNativePlugin` with all the usual metadata. In addition, the native layer receives a JVM exception – an instance of `com.facebook.react.common.JavascriptException` – which contains less information.
This resulted in duplicate events for the same error being delivered to the dashboard, so the aim of this PR is to dedupe such events.
I added an `onError` callback to the native notifier upon `Plugin.configure()` which filters out errors of this class. Previously this was done via the configuration option ignoreClasses but since configuration is now immutable doing it that way seemed off the cards.
- added `onError` callback when …
=> feat(bugsnag-android-plugin-react-native): Dedupe JS crashes

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt
Adds a null check when loading meta-data from the manifest. In a React Native 0.55 example app with no `meta-data` elements present in the manifest, `applicationInfo.metadata` was returned as null by the `PackageManager`.
It's hypothesised that this was caused by a very old targetSdkVersion/compileSdkVersion, and can be demonstrated to be caused by the lack of any `meta-data` elements in the manifest, making this a relatively rare scenario. A null check has been added regardless.
=> Add null check when loading data from manifest

.buildkite/pipeline.yml, docker-compose.yml, dockerfiles/Dockerfile.android-ci-base, examples/sdk-app-example/build.gradle, scripts/build-instrumentation-tests.sh, scripts/run-instrumentation-test.sh, settings.gradle
This changes fixes two main issues:
- Instrumentation tests were not building against the correct NDK version because the environment variable was not being passed to the container.
- BrowserStack have added a check against the two apps needed to run Espresso tests, meaning that they now have to have different bundle Ids.  Because we don't actually need the first uploaded app, we were uploading the same apk twice, which now causes a failure (although we did not detect that).
Any apk would suffice to use as the first Espresso app, but I have chosen the example as this has the added benefit of verifying that the example builds as part of CI.
As well as fixing the underlying failure, I've added a number of checks to `run-instrumentation-test.sh` in order that any such failures should be …
=> Fix instrumentation tests

bugsnag-android-core/detekt-baseline.xml, bugsnag-plugin-android-ndk/detekt-baseline.xml, bugsnag-plugin-react-native/detekt-baseline.xml, build.gradle, examples/sdk-app-example/build.gradle, examples/sdk-app-example/gradle.properties, gradle/dependencies.gradle, gradle/detekt.gradle, mazerunner-scenarios/detekt-baseline.xml, tests/features/fixtures/mazerunner/build.gradle, tests/features/fixtures/minimalapp/gradle.properties
Updates the project's Gradle dependencies in preparation for an AGP version update, and to avoid being stranded on legacy plugin versions.
- Updated detekt static analysis plugin to latest version and updated baseline to suppress existing warnings uncovered by new checks
- Bumped bugsnag gradle plugin + bintray publish plugin
- Removed obsolete check for previously removed infer static analysis dependency
- Added `android.useAndroidx` flag to apps, which is optional in AGP 3 but required for AGP 4
=> Update project gradle dependencies

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt
As per the docs for the [Error Reporting API](https://bugsnagerrorreportingapi.docs.apiary.io/#reference/0/notify), the correct keys for the RN runtime version data are:
- `reactNative` and
- `reactNativeJsEngine`
=> fix(plugin-react-native): Use the correct keys for runtime version data

tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
Enables debug logging in mazerunner. Logging is disabled by default in release mode - this alters configuration to log everything to logcat, which should aid debugging failing mazerunner scenarios.
=> Enable logging in mazerunner

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java
Ensures that plugins are loaded before flushing errors. This avoids the potential for a race condition where a plugin sets a callback that filters out a particular error class.
=> Ensure plugins are loaded before flushing errors

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrDetailsCollector.kt
Respects pre-populated fields on Event when notifying. This prevents the case where an event is populated on React Native and its custom app/device/user etc being overridden by the Android values.
Created `populateAndNotifyAndroidEvent` method which populates the event for errors captured within bugsnag-android. `notifyInternal` does not populate any information. This is in line with how bugsnag-cocoa works.
=> Respect pre-populated fields on Event when notifying

CHANGELOG.md, bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventTest.java, tests/features/stackoverflow.feature
When an unhandled error is captured the process is usually about to terminate. Currently bugsnag attempts to send the request which can lead to a condition where a request is successfully sent but the process is terminated before the SDK can act on the response. This can lead to duplicate error reports on the relaunch of the app (and is theorised to cause flakes in the E2E tests).
Disabling this behaviour for unhandled errors will reduce the likelihood of these duplicate requests being sent. This excludes the following ANRs, because the process will not directly terminate and there's a good chance the request will be delivered in the same session.
Added unit tests to cover ANR calculations.
=> Avoid attempting to flush unhandled error reports in same session

CONTRIBUTING.md, dockerfiles/Dockerfile.android-sizer, examples/sdk-app-example/build.gradle, examples/sdk-app-example/src/main/java/com.bugsnag.android/example/ExampleApplication.kt, gradle/detekt.gradle, tests/features/fixtures/mazerunner/build.gradle, tests/features/fixtures/mazerunner/gradle.properties, tests/features/fixtures/mazerunner/src/main/AndroidManifest.xml, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, tests/features/fixtures/mazerunner/src/main/res/xml/network_security_config.xml, tests/features/fixtures/minimalapp/Dangerfile, tests/features/fixtures/minimalapp/app/build.gradle, tests/features/fixtures/minimalapp/app/src/main/AndroidManifest.xml, tests/features/fixtures/minimalapp/app/src/main/java/com/bugsnag/android/minimalapp/CustomApp.java, tests/features/fixtures/minimalapp/build.gradle
Updates the example app and test fixtures to use the latest AGP version (4.0.0), and updates their dependencies to ensure they are not left abandoned on an obsolete version.
This is part of the groundwork of preparing the entire project to use AGP 4.0.0.
- Updated android sizer task to use 1.0.0 of bundletool
- Updated apps to use latest compileSdkVersion of 29, AGP 4.0.0, Kotlin 1.3.72
- Added one Java file to `minimalapp` fixture to prevent Android Bundle failing to generate APKs with AGP 4.0.0 due to no code being present
- Removed unneeded test dependencies from minimalapp
- Updated android sizer script to get APKs/AABs from new generated location
- Updated test fixture to allow clear text traffic required by bs-local.com, which was failing the scenarios on Android 9 after upgrading …
=> Update example app and test fixture dependencies

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/AppSerializer.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/AppSerializerTest.java
This was a preexisting bug that was exaserbated by #906.
Ensures that `app.type` is populated for events created in JS land.
=> fix(plugin-react-native): appType -> app.type event serialisation differs from config

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/InternalHooks.java
The app and device data that was captured at the last moment in `notifyInternal` is now not included in JS events (as of #906), and this also exposed the fact that they were not available to JS `onError` callbacks anyway.
This sends them across the bridge in `getPayloadInfo()` to fix both issues. A subsequent JS update is required to include them in the event payload that's sent back to the native layer.
I couldn't see a good way to test this.
=> feat(plugin-react-native): Pass device and app metadata to react native

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NotifierSerializationTest.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt
Prevents duplicate notifier dependencies being added when RN's JS layer is reloaded, by resetting the dependency list each time.
Updated existing unit test coverage to ensure the notifier version information serializes correctly.
=> Prevent duplicate notifier dependencies being added

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt
Ensures that the `redactedKeys` is always set appropriately on `event.metadata`. For React Native the `redactedKeys` field was initialized to a default instead which led to the wrong fields being redacted for JS errors.
Verified in an example app by installing a local artefact.
=> Always set config.redactedKeys on Event

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventInternal.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventTest.java
Attempts to deliver promise rejections immediately. This is required for the React Native notifier where promise rejections are set as unhandled but do not terminate the process.
The logic in Android is now that unhandled events should only be delivered in the same process if they are an ANR or Promise Rejection.
=> Attempt delivery of promise rejections immediately

bugsnag-android-core/src/main/java/com/bugsnag/android/HandledState.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt
When the severity is modified in a JS `onError` callback, the original value for `unhandled` was lost. This update takes and applies the `unhandled` value from the JS event payload.
=> [PLAT-4713] RN: Retain unhandled value when parsing a JS event

bugsnag-android-core/src/main/java/com/bugsnag/android/HandledState.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt
The previous PR (#914) didn't completely fix this problem, as when `severity` was parsed and set on the event, the value for `unhandled` was lost again. This refactors the way the `HandledState` object is constructed to avoid further such issues.
=> [PLAT-4713] RN: Refactor event deserialiser to ensure unhandled value is retained

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/UpdateMetadataTest.kt
Splits out the add/removal of metadata to facilitate more accurate synchronisation from the JS layer in RN.
=> [PLAT-4704] RN: Split updateMetadata method into two separate add/clear methods

bugsnag-android-core/src/main/java/com/bugsnag/android/MetadataState.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataStateTest.kt
Metadata updates with a map did not trigger any updates for observers. This fix ensures the observers are notified for each tab that changed.
=> fix(metadata): Ensure metadata updates set with a map notify observers

CHANGELOG.md, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Bugsnag.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagApiTest.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/InternalHooks.java
Adds an accessor for a list of breadcrumbs collected by `Client`. This allows users to access a readonly copy of the collection and resolves #892 
- Altered existing getter on `Client` to be public, and added equivalent method to `Bugsnag` facade
- Removed redundant method from `InternalHooks`
- Updated existing unit test coverage to verify a `List` rather than a `Collection` is used as the breadcrumbs need to be ordered by capture time
- Added unit test to verify `Bugsnag` facade method
=> Add accessor for breadcrumb list on Client

bugsnag-plugin-react-native/proguard-rules.pro
Enabling the flag `enableProguardInReleaseBuilds` on a React Native project with Bugsnag causes the app to crash. This is because the [`BugsnagReactNativePlugin` instance is obtained by reflection](https://github.com/bugsnag/bugsnag-js/blob/2de4bc0251d9d56c6f7c4a68908dfbff38812ff7/packages/react-native/android/src/main/java/com/bugsnag/android/BugsnagReactNative.kt#L55) and when proguard is enabled this class name is obfuscated, so the reflection fails.
An additional proguard rule to keep the name of this class enables the reflection to work.
Rule added to `proguard-rules.pro`.
This was tested manually on a React Native project. Additionally the end to end React Native CI tests will be run against an app with proguard enabled, to prevent regressions in this area.
=> [PLAT-4921] fix(plugin-react-native): Keep name of class for use in reflection

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryHeaders.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java, bugsnag-android-core/src/test/java/com/bugsnag/android/EventFilenameTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/HandledExceptionApiKeyChangeScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/UnhandledExceptionApiKeyChangeScenario.kt, tests/features/event_callback_alters_api_key.feature
Supports changing the apiKey for an `Event` via an `OnErrorCallback`. This is achieved by encoding the apiKey in the filename if an event is cached on disk, and reading this apiKey from the filename at the point of delivery.
- `DeliveryDelegate` uses the apiKey set on `Event` rather than `Configuration`, which covers delivery of handled errors
- `errorApiHeaders()` now takes the `apiKey` as a parameter when generating HTTP headers so that `Bugsnag-Api-Key` is not always set to `config.apiKey`
- `flushEventFile()` reads the apiKey from the filename if present, and otherwise falls back to the `config.apiKey` value if the cached file is in the legacy format
- Fixed a minor bug where 'not-jvm' was always added to a filename if the report was not a startup crash. The presence of 'not-jvm' has …
=> Support changing Event's api key in OnErrorCallback

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataConcurrentModificationTest.kt, bugsnag-android-core/src/test/resources/event_redaction.json, bugsnag-android-core/src/test/resources/event_serialization_6.json, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/MetadataDeserializer.java
Prevents a `ConcurrentModificationException` from being thrown in the internally used `MetaData` class.
`MetaData` does correctly use a `ConcurrentHashMap` as the default value for the `store` property, but within the `copy()` method supplies a regular `HashMap`. Whenever `client.notify()` is invoked the global metadata state is copied, which can result in a `ConcurrentModificationException` being thrown in subsequent edits.
This changeset resolves the problem by enforcing that `store` must be a `ConcurrentHashMap`.
Added a unit test which throws an exception without the changes, and confirmed that it no longer throws an exception.
=> Prevent ConcurrentModificationException thrown from Metadata class

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/Stacktrace.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/BugsnagReactNativePlugin.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/InternalHooks.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/NativeErrorDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/EventDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/NativeErrorDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestData.java
Improves the stack traces reported for React Native promise rejections by including the native stack trace in the reported error.
- Added `NativeErrorDeserializer` class which grabs the `nativeStack` property if set by the JS layer and creates an `Error` object, which is appended as a separate stacktrace
- Passed the JS error to the `NativeErrorDeserializer` and used its error message/class as the default values for the native error
- Moved `inProject` to Stacktrace's [companion object](https://kotlinlang.org/docs/tutorials/kotlin-for-py/objects-and-companion-objects.html) for accessibility from the `NativeErrorDeserializer`
In addition to unit testing of deserialization logic, relied on E2E scenarios from https://github.com/bugsnag/bugsnag-js/pull/1047 and manually verified that the …
=> Improve stack traces and grouping for React Native promise rejections

CHANGELOG.md, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/UserRepository.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/UserRepositoryTest.kt
Ensures that the device ID is set separately to the user ID. Previously if the user ID was set on `Configuration` then the device ID would be incorrectly overridden.
This fix alters the `Client` to load the device ID separately on initialization from the `UserRepository` class.
Added unit and integration tests to verify that the `UserRepository` can read the device ID and that the Client value is set appropriately.
=> Ensure device ID is set separately to the user ID

CHANGELOG.md, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/NativeErrorDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/NativeErrorDeserializerTest.kt
React Native 0.63.2 does not include the 'class' value in stacktraces for Android, and only records 10 frames. As a fallback bugsnag will record the method name only. While this does not allow deobfuscation if an app is obfuscated, it grants more information than would otherwise be available.
Added a unit test to cover deserialization and verified manually in an example app.
=> Improve stack traces and grouping for promise rejections on React Native < 0.63.2

.buildkite/pipeline.yml, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt
Dismiss any system dialogs (but specifically the buttonless "MazeRunner crashed dialog)when the test fiture app (re)launches.
Viewing the video of a previous CI run, it was evident that Android 8.1 scenarios were failing due to the dialog hogging focus and blocking text entry by Appium.  This change appears to have fied that now (2/2 successful runs) and so I have moved the soft fail onto the problematic 8.0 tests (which fail due to a known infrastructure proxy issue).
e2e scenario test fixture and build pipeline.
This is part of a continuing journey, but the Android 8.1 tests now seem to pass and nothing else is worse than it was.
=> Dismiss system dialogs in e2e test scenarios

.buildkite/pipeline.yml, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationKotlinScenario.kt, mazerunner-scenarios/src/main/java/com/bugsnag/android/mazerunner/scenarios/LoadConfigurationNullsScenario.java, tests/features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, tests/features/fixtures/mazerunner/src/main/res/layout/activity_main.xml, tests/features/fixtures/mazerunner/src/main/res/xml/network_security_config.xml
Pass the Bugsnag endpoints in from the UI where possible (i.e. for all scenarios apart from those that load config from the manifest).
This approach has uses for manual testing, but also opens the door to Appium-driven tests setting the endpoints to custom URLs (especially useful for running automated tests locally during development).
e2e test fixture updates, together with the addition of soft fail for the Android 8.1 build step.  This is pending further investigations in the short-term and as a result of flaky infrastructure causing repeated failures and badly impacting productivity. 
The e2e tests would completely fail if this wan't working correctly.
=> Parameterize endpoints

.buildkite/pipeline.yml, dockerfiles/Dockerfile.android-common
Add instrumentation and e2e tests against Android 11 to the pipeline.
The e2e tests are set to soft fail pending further investigation of some failures.
CI pipeline.
Adds tests against Android 11.
=> Add testing against Android 11

CHANGELOG.md, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Metadata.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ObjectJsonStreamer.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/MetadataConcurrentModificationTest.kt
Prevents a `ConcurrentModificationException` from being thrown when `redactedKeys` is set on the `Metadata` of an `Event`. This can manifest as a crash when `notify()` is called concurrently.
- Converted `ObjectJsonStreamer` to use `var Set<String>` rather than `val MutableSet<String>`, as this avoids the problem of mutating a collection concurrently
- Converted `redactedKeys` to a property on `Metadata` rather than a property and function, as this is more consistent
- Removed `ObjectJsonStreamer` from the constructor as there is no need for it to be injectable
Added a unit test to verify that when `redactedKeys` is set on `Metadata` a crash does not occur. Additionally added an integration test which calls `notify()` concurrently to confirm that no further crashes occur with the default …
=> Prevent ConcurrentModificationException when setting redactedKeys

.buildkite/pipeline.yml
Use the Buildkite `depends_on` feature to form a dependency tree of build steps instead of running in a series of parallel steps.  This avoids steps needlessly waiting for steps in previous groups to complete if their dependency steps have already completed, potentially saving elapsed time on the overall build.
Pipeline step `key` and `depends_on` used as documented by Buildkite.
Pipelines ordering and dependency mechanism only.
Covered by standard CI.
=> Update CI pipeline to form Buildkite dependency tree

scripts/run-instrumentation-test.sh
Detect instrumentation tests that result in `error` and stop immediately rather than waiting for timeout.
Covered by passing CI.
=> Stop instrumentation tests on error

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ClientContextInitTest.java
Avoids a crash when initializing Bugsnag in `Application#attachBaseContext()`. Previously Bugsnag always attempted to obtain the application context to avoid leaking short-lived activity context. However, at this point in time the application context will return null, resulting in an `IllegalArgumentException` within the `Client` constructor.
This changeset fixes this by adding a null check. If the context does return null then it is the base context, and its safe to initialize with as it won't leak memory unlike an `Activity`.
Tested manually in an example app as this is not a suitable scenario for mazerunner. Added unit tests to confirm that the original crash does not occur.
=> Avoid crash when initializing bugsnag in attachBaseContext

docker-compose.yml
Trivial change to resolve an annoying warning when running the end-to-end tests.
Passing CI, verifying that the previous warning has gone.
=> Resolve build warning

features/support/env.rb
Account for the recently added Android 11 when skipping/running test scenarios.
This is a quick fix.  The use of device type names will evaporate in the next major MazeRunner release, simplifying the steps here to use simple numeric operations on a configured OS version.
Scenarios skipping steps.
Covered by standard CI.
=> Account for Android 11 when skipping/running scenarios

dockerfiles/Dockerfile.android-maze-runner
Take the Maze Runner image from its releases repository.
maze-runner-releases is a new ECR repository of ours that is dedicated to releases and separate to images built for development branches.  It means that releases will not get swept away as part of our housekeeping policy.
Maze Runner docker file(s).
Covered by standard CI.
=> Take maze runner image from releases repository

.buildkite/pipeline.yml, dockerfiles/Dockerfile.android-maze-runner, features/support/env.rb
This is a relatively straightforward move to using MazeRunner v3.
MazeRunner v3 internalizes the interaction with the Appium driver, meaning that we move from setting environment variables to passing in command line options.  Also, because v3 is more agnostic of specific device farms, it means we need to stop using the `DEVICE_HASH`entries (`ANDROID_6_0` etc) in areas of common code as these are  BrowserStack specific.  v3 provides `MazeRunner.config` to pull certain values from instead.
CI pipeline, Docker file and `env.rb` - the touch points with MazeRunner.
Covered by passing CI, although I have also performed some basic sanity checks that any failures needing retries are covered by existing tickets and that the number of scenario run is the same as before the change.
=> Use MazeRunner v3

CHANGELOG.md, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/FileStoreTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ClientObservable.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/NativeInterface.java, bugsnag-android-core/src/main/java/com/bugsnag/android/StateEvent.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventFilenameTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NativeInterfaceApiTest.kt, bugsnag-plugin-android-ndk/detekt-baseline.xml, bugsnag-plugin-android-ndk/src/main/assets/include/event.h, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c, bugsnag-plugin-android-ndk/src/main/jni/event.c, bugsnag-plugin-android-ndk/src/main/jni/event.h, bugsnag-plugin-android-ndk/src/main/jni/utils/migrate.h, bugsnag-plugin-android-ndk/src/main/jni/utils/serializer.c, bugsnag-plugin-android-ndk/src/test/cpp/test_bsg_event.c, bugsnag-plugin-android-ndk/src/test/cpp/test_utils_serialize.c
Adds support for changing the apiKey on events from the NDK layer. #928 added equivalent functionality for JVM events.
The changeset consists mainly of five alterations:
1. Passing the api key to the NDK layer via a `StateEvent.Install` message
2. Populating the api key on the `bugsnag_event` struct, which requires a migration for legacy persisted structs
3. Adding accessors to the NDK API for altering the API key on an event
4. Decoding the apiKey from C struct in `deliverPendingReports()` and pass to the JVM layer along with the deserialized event payload
Existing unit and integration tests have been updated to match the new assertions. New test cases have also been added for additional coverage and to verify the NDK migration.
Manual testing also covered:
- Unhandled NDK events are …
=> Support changing NDK Event's api key in OnErrorCallback

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/ConnectivityCompat.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ConnectivityApi24Test.kt
Alters the behaviour in the `ConnectivityApi24` class so that requests are allowed by default. The previous implementation has a bug where `hasNetworkConnection()` would return false until the `onAvailable()` callback had been invoked by the Android framework. This has been resolved by querying `connectivityManager#getActiveNetwork()`, which will return null if there is no system default network available.
Relied on existing E2E scenarios. Attempted running the artefact in a local app with and without network connection and confirmed that request delivery was done accordingly.
=> Default to allowing requests when checking connectivity

.buildkite/pipeline.yml, docker-compose.yml
Reinstates the `fail-fast` option, which was accidentally overridden when moving to Maze Runner v3.
Removed the `command` entry from `docker-compose.yml`, which is a bit hidden away as it is, and added to the command arrays in the build steps.  I have omitted the `--tags` option to reduce noise in the pipeline, as the use of `@ignore` appears to be historical.
Docker compose file and e2e testing steps in the pipeline.
Covered by standard CI.
=> Reinstate fast-failing e2e tests

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
Session payloads are persisted on disk if a request to bugsnag was unsuccessful. Delivery of these is only attempted currently when a new session is captured. To increase the speed with which requests are received, delivery should also be attempted on `Client` initialization` and whenever connectivity changes.
Called `flushAsync()` in the client constructor and connectivity change callback. Access to this method is guarded by a Semaphore so concurrent calls will be ignored.
Relied on existing E2E tests, and manually verified that an undelivered session is now delivered when the client is launched or the connectivity is regained.
=> Flush persisted sessions on launch and on connectivity changes

.buildkite/pipeline.yml
Mitigate the impact of an issue with Android 6 and 7 on BrowserStack meaning that we are currently unable to test on them.
Temporarily adds soft fails to Android 6 and 7, which should be removed as soon as the BrowserStack issue is resolved.
I have added Android 4.4, which passed on the first attempt and so have not introduced a soft fail at this stage.  Android 5 appears to have the same problem as 6 and 7, but have added with soft fail for completeness.
CI pipeline only.
No direct impact on the notifier and part of a larger picture for doing the testing we need before release without holding up engineering operations unduly.
=> Temporary soft fail for Android 6/7

CHANGELOG.md, bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt, bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
This is the first step to supporting native stack traces in ANRs caused by native code. The fields `siginfo_t *info` and `void *user_context` are required in order to produce a native stack trace. Since we don't want to tie the ANR plugin to the native plugin, we need to temporarily pass these pointers through the JVM into the NDK plugin (only when it's available)
Both pointers are passed to the Java side as `long` values.
ran unit tests, ran example app triggering both native and JVM ANR, observed them on the dashboard.
=> Support passing siginfo_t *info and void *user_context from the ANR signal handler to the JVM side.

bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ThreadTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ErrorInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Stacktrace.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ThreadState.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ErrorSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/NullMetadataTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/StacktraceSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/StacktraceTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ThreadSerializationTest.kt, bugsnag-plugin-android-ndk/detekt-baseline.xml, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ErrorDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/NativeErrorDeserializer.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/ThreadDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestData.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/ThreadSerializerTest.java
The new ANR native trace functionality will require native code to produce `Stacktrace` objects, however the constructors for `Stacktrace` require a logger, which is only used when converting JVM stack traces. Rather than passing a logger through native code, it's cleaner to move the "Java trace to Bugsnag trace format" code into a helper function.
This change moves the "java to bugsnag" constructor into a helper function in the object's companion. The `Stacktrace` object itself is now a POJO, containing data only.
- Ran unit tests
- Ran example app, triggering crashes and verifying that the stack traces are correct in Java and native crashes.
=> Refactor Stacktrace to not require logger

CHANGELOG.md, bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/main/java/com/bugsnag/android/DefaultDelivery.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryHeaders.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryParams.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Notifier.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryHeadersTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-plugin-android-ndk/detekt-baseline.xml, features/session_tracking.feature, features/steps/android_steps.rb, gradle.properties
Adds the `Bugsnag-Integrity` header to Error API requests whose value is a SHA-1 digest of the payload. If the payload is altered in transit then it will be rejected by the server.
- Added method for computing SHA-1 digest from an `EventPayload` to `DeliveryHeaders` by using a `DigestOutputStream` with a no-op output
- Added `Bugsnag-Integrity` to the request headers for each Error API request
- Simplified `DefaultDelivery` implementation by using [kotlin stdlib](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html) functions
Added unit tests to cover generation of the SHA-1 digest, and updated E2E scenarios so that they assert the header is set on error report payloads. Additionally verified via Android Studio's Profiler that an error request contains the header and the …
=> Add integrity header to verify Error and Session payloads have not changed

CHANGELOG.md, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/EventStoreMaxLimitTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionStoreMaxLimitTest.kt, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionStoreTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionV1PayloadTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SessionV2PayloadTest.java, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java, bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/FileStore.java, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ManifestConfigLoader.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionStore.java, bugsnag-android-core/src/test/java/com/bugsnag/android/BugsnagTestUtils.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ImmutableConfigTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestData.java
The bugsnag-android SDK persists events & sessions to disk if it is unable to deliver them to the API due to network failure. This provides a configuration option to control how many payloads should be stored on disk for both events and sessions.
- Added `maxPersistedEvents` and `maxPersistedSessions` to `Configuration` with a default value of 32
- Added `MAX_PERSISTED_EVENTS` and `MAX_PERSISTED_SESSIONS` for reading configuration options from the manifest
- Updated `EventStore` and `SessionStore` so that they respect the configuration options
- Fixed a bug in `discardOldestFileIfNeeded()`, where in the unlikely scenario that >32 payloads were persisted on disk, the function would delete all the payloads if another payload needed persisting
Added integration tests which verify the …
=> Add configuration option to control maximum number of persisted events/sessions

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/NdkPlugin.kt, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt, bugsnag-plugin-android-ndk/src/main/jni/bugsnag_ndk.c
Since some ANRs can be caused by native code, we need a way to get native stack traces when such ANRs are triggered.
The NDK can generate a native stack trace from signal handler data since it already has signal handlers for fatal exceptions like `SIGILL` and `SIGBUS`. ANRs are signalled via `SIGQUIT` so we can use the same mechanism to get a native stack trace. We don't want a hard link between the ANR and NDK plugins, so we need to pass the signal handler data through the JVM layer so that the ANR plugin can then look up the NDK plugin and use it to generate native trace data when an ANR occurs.
Currently, nothing is done with this stack trace data, and it gets called regardless of where the ANR originated. Further changes to conditionally fetch this data if it's a native ANR and the …
=> Generate native trace from signal info

Gemfile, Gemfile.lock, Makefile, TESTING.md, docker-compose.yml
Refreshes the instructions and mechanics for running end-to-end tests locally (using devices on BrowserStack).
This is the standard approach for using Maze Runner v3.
- Gemfile added to reference Maze Runner Gem (or source)
- Updated Makefile and instructions
- Redundant environment variables removed from `docker-compose.yml`
Updated instructions tested locally prior to raising the PR.
=> Refresh instructions for running end-to-end tests

bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeliveryDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/InternalReportDelegate.java, bugsnag-android-core/src/main/java/com/bugsnag/android/SessionTracker.java
Adds additional logging at the debug level to facilitate debugging of mazerunner/Appium issues.
I can make a follow on PR for the mazerunner test fixture if that would also be helpful.
Manually verified in an example app. Something is now logged out whenever an event or session is captured and before delivery occurs. Example logs can be found here:
>2020-11-05 15:12:40.403 13847-13847/com.bugsnag.android.example D/Bugsnag: SessionTracker#trackSessionIfNeeded() - session captured by Client
2020-11-05 15:12:40.409 13847-13892/com.bugsnag.android.example D/Bugsnag: SessionTracker#trackSessionIfNeeded() - attempting initial delivery
2020-11-05 15:12:42.024 13847-13892/com.bugsnag.android.example I/Bugsnag: Request completed with code 202, message: Accepted, headers: {null=[HTTP/1.1 202 …
=> Improve debugging logging to support mazerunner

features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/MainActivity.kt, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/SecondActivity.kt
Increases logging in the mazerunner fixture to aid debugging. This now logs at several key points:
- When the fixture is launched
- When user data is cleared
- When a scenario is loaded
- When a scenario is executed
=> Improve logging in mazerunner fixture

.buildkite/pipeline.yml, scripts/run-cpp-check.sh
Separates static analysis into individual jobs on CI. This ensures that if multiple static analysis tools are failing, the developer is always aware of the failures without having to push multiple times. Parallelising the steps should also reduce the time taken to get feedback on the static analysis tasks by ~1 minute.
=> Separate static analysis into individual jobs

.buildkite/pipeline.yml, features/in_foreground.feature, features/native_crash_handling.feature, features/native_event_tracking.feature, features/support/env.rb
Removes soft fail from Android 10/11 tests while skipping problematic scenarios.
This should allow us to get some test coverage on these platforms now, and these scenarios can be re-instated once appium issues have been investigated and resolved.
=> [PLAT-5161] Remove soft fail from Android 10/11

features/full/_smoke_test.feature, features/full/detect_anr_cxx.feature, features/steps/android_steps.rb
Adds E2E assertions that the exception stacktrace is equal to the thread stacktrace for unhandled errors. #1001 contains changes so that the stacktrace is reported correctly for C++ `notify()` calls and ANRs - this adds additional test coverage.
=> Assert that exception stacktrace is equal to thread stacktrace

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/NativeStackDeserializer.java, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/NativeStackDeserializerTest.kt
Alters the `nativeStack` property added in #937 so that it is deserialized as a list of `Stackframe` objects, which are set on an individual `Error`. This forms a mixed stacktrace rather than two separate error objects. The `getPlugin` method has also been updated to allow a raw class, so that both the `NdkPlugin` and `AnrPlugin` can be accessed from Java/Kotlin files as needed. This was originally changed [here](https://github.com/bugsnag/bugsnag-android/commit/239d12a613ef770d1bdfb70324dade17b3a9b8e7#diff-c952c857a72826421f5588f79a4f32113c19fb0860aa4f6571408dc6158d521a) but the solution didn't work for React Native - this covers both scenarios.
Updated unit test coverage, and manually tested on React Native to confirm that the nativeStack is set:
=> Encode react native promise rejections as a mixed stacktrace

features/fixtures/mazerunner/src/main/cpp/bugsnags.cpp, features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/CXXBackgroundNotifyScenario.kt, features/native_event_tracking.feature
This should help avoid a source of flakiness in the E2E scenarios by making the foreground/background scenarios use [activity lifecycle](https://developer.android.com/guide/components/activities/activity-lifecycle) callbacks. These are invoked when the activity is put in the stopped state, which is interpreted by bugsnag as when the application is in the background.
Previously the `CXXDelayedNotifyScenario` used an arbitrary 3 second sleep before calling `bugsnag_notify_env` - this is not always long enough for the activity to be put into the background by the Android OS, leading to test failures.
Ran the feature ~5 times on browserstack local.
=> Alter foreground/background scenarios to use activity lifecycle callbacks

CHANGELOG.md, bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/SynchronizedStreamableStoreTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/JsonReadable.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/SynchronizedStreamableStore.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/User.kt, bugsnag-plugin-android-ndk/detekt-baseline.xml
Creates a synchronized store which is used for reading & writing user information. This replaces `SharedPreferences` which is not safe for use in a multi process environment, and does not give control over the location where information is persisted.
- Created `SynchronizedStreamableStore`, which is capable of reading and writing `Streamable` objects
- Synchronized access to the `persist()` and `load()` methods with a `ReentrantReadWriteLock` so that concurrent reads of the information is possible when the file is not being written
- Added method to allow deserialization of `User`, along with `JsonReadable` interface
Created instrumentation tests which verify that data can be persisted and loaded, and that the read lock allows concurrent access.
=> Create synchronized store for user information

.buildkite/pipeline.yml, features/cached_error_reports.feature, features/cached_session_reports.feature, features/steps/android_steps.rb, features/support/env.rb
Skip understood failing tests pending ticketed fix and prepare for MazeRunner 3.6.0.
I am aware that this creates a minor conflict on one of the integration branches, but there are more scenarios across more Android versions that will start failing once MazeRunner 3.6.0 is released.  The fixes coming in MR 3.6.0 that cause this are:
- Waiting for a period of time before checking for no requests in the `I should receive no requests` step
- Detection of received but invalid requests (e.g. invalid JSON or missing body).
- Skip and annotate tests that will fail in the next MR release
- Disable enforcement of the Bugsnag-Integrity header, until the functionality is released.  MazeRunner 3.6.0 will fail tests if the header is not present, unless configured otherwise.
- Fix the `I clear any …
=> Skip failing tests and prepare for MazeRunner 3.6.0

CHANGELOG.md, bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ClientTest.java, bugsnag-android-core/src/androidTest/java/com/bugsnag/android/DeviceIdStoreTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Client.java, bugsnag-android-core/src/main/java/com/bugsnag/android/DeviceIdStore.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/SharedPrefMigrator.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/SynchronizedStreamableStore.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/UserRepository.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SharedPrefMigratorTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/UserRepositoryTest.kt
This changeset makes the notifier use a consistent device ID for apps which initialize Bugsnag in multiple processes. This is achieved by storing the device ID in a single file location which can be accessed concurrently from each process and is protected by a [FileLock](https://developer.android.com/reference/java/nio/channels/FileLock).
- Created `DeviceIdStore` which is responsible for loading/saving the device ID to the file system
- Guarded the device ID file with a `FileLock` to prevent concurrent access in multiple processes, and a `ReadWriteLock` to prevent concurrent access from multiple threads.
- Updated the `Client` to persist a device ID to a file and to migrate any existing device ID from `SharedPreferences` or generating a random UUID if none already exists
- Created …
=> Use consistent device ID for multi process apps

.buildkite/pipeline.full.yml, .buildkite/pipeline.smoke.yml
Reduces the browserstack concurrency from 10 to 9. This makes one device slot will always be available for running local tests, which speeds up the feedback loop without dramatically slowing down CI times.
=> Reduce browserstack concurrency to 9

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/EventPayload.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/EventStore.java, bugsnag-android-core/src/test/java/com/bugsnag/android/DeliveryDelegateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventPayloadSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/EventPayloadTest.kt
Prevents a SHA-1 hash mismatch when the React Native notifier changes the `notifier` field on startup. Because the Android notifier assigns the event payload value by reference from `Client#notifier`, the request payload can change between generating a SHA-1 hash and making the request.
Copied the `notifier` parameter when constructing an `EventPayload`, so that it does not hold a copy of global state.
Added unit test to verify that the `notifier` property is always copied when constructing an `EventPayload`. Additionally ran artefact against failing React Native scenario and confirmed that this change fixes the immediate issue.
=> Prevent potential SHA-1 hash mismatch in Bugsnag-Integrity header

TESTING.md
Tweaks the testing docs so that the command always builds the test fixture, and so that the feature file being run exists.
=> Tweak testing docs

docker-compose.yml, features/support/env.rb
Prepare for the release of MazeRunner v3.6.0.  Also adds a retry for Buildkite steps failed due to lost agents (which occurs due to us using AWS spot instances).
MazeRunner v3.6.0 fixes a long standing problem with the `I should receive no requests` step, meaning that the test harness will now wait for a default time of 30s each time it is used.  As this is longer that the time needed on Android, we can prepare for the release by setting the appropriate config value to 10s, if it is available.
Pipeline files, MazeRunner support file.
All changes for v3.6.0 are now on the MazeRunner master branch and before creating this PR I set the `docker-compose.yml` file to consume the MazeRunner Docker image for that version.  I ensured that both quick and full builds were run, so when v3.6.0 is …
=> Prepare for MazeRunner v3.6.0

RELEASING.md
It's not clear from the docs that the build system expects GPG 1.x files, or how to deal with different versions of GPG.
Added another initial step to RELEASING.md that explains how to set up the GPG keystore.
=> Add information about GPG keys and GPG1 vs GPG2 to RELEASING.md

features/fixtures/mazerunner/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiProcessUnhandledCXXErrorScenario.kt
Loads the `bugsnag-ndk` library for the unhandled multi process scenario. This manifested as a failure on the E2E tests as the scenario tries to call C++ code which has not been loaded: https://buildkite.com/bugsnag/bugsnag-android/builds/2807#b6514d4f-cf03-4550-b11f-02110c44b8ed
=> Load bugsnag-ndk lib for multi process scenario

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/SeverityReason.java, bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/EventDeserializerTest.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/TestHooks.java
Makes `event.unhandled` overridable in React Native errors passed from the JS layer. This allows users to decide whether specific errors apply to their stability score.
Calculate the original unhandled value from the `unhandledOverridden` flag, and pass it to `SeverityReason` when constructing an event.
Added unit tests to verify deserialization of event payload. PLAT-5595 will add E2E tests separately to the JS repo.
=> Make unhandled overridable for React Native errors

bugsnag-plugin-react-native/src/main/java/com/bugsnag/android/EventDeserializer.kt, bugsnag-plugin-react-native/src/test/java/com/bugsnag/android/EventDeserializerTest.kt
Deserialize `unhandledOverridden` from the `severityReason` part of the payload rather than at the root level. This changeset updates the tests also to ensure that the correct field is being deserialized.
=> Deserialize unhandledOverridden correctly for React Native

CHANGELOG.md, bugsnag-android-core/src/main/java/com/bugsnag/android/Session.java, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionSerializationTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerPauseResumeTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTrackerTest.java
Prevents a SHA-1 hash mismatch when the React Native notifier changes the `notifier` field on startup. Because the Android notifier assigns the event payload value by reference from `Client#notifier`, the request payload can change between generating a SHA-1 hash and making the request.
Copied the `notifier` parameter when constructing a `Session`, so that it does not hold a copy of global state.
Added unit test to verify that the `notifier` property is always copied when constructing a `Session`.
=> Prevent potential SHA-1 hash mismatch in Bugsnag-Integrity header for session requests

TESTING.md, gradle/checkstyle.gradle
Updates the `checkstyle` task so that it always runs when the `check` task is run. This means that running `./gradlew check` runs all the static analysis and unit tests in the project, making it easier to run all the tasks locally.
Confirmed this works by running a [build scan](https://scans.gradle.com/s/4vmnjcdhvdl4k/timeline) and checking that the checkstyle task now appears in the build timeline.
=> Update check task to depend on checkstyle task

bugsnag-android-core/detekt-baseline.xml, bugsnag-android-core/src/main/java/com/bugsnag/android/ImmutableConfig.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/BreadcrumbStateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/InternalEventPayloadDelegateTest.kt, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionTest.kt, bugsnag-plugin-android-anr/detekt-baseline.xml, bugsnag-plugin-android-ndk/detekt-baseline.xml, bugsnag-plugin-android-ndk/src/main/java/com/bugsnag/android/ndk/NativeBridge.kt, bugsnag-plugin-react-native/detekt-baseline.xml, config/detekt/detekt.yml, gradle/detekt.gradle
Several static analysis checks commonly need to be suppressed. This changeset tweaks the [default behaviour](https://detekt.github.io/detekt/empty-blocks.html) of Detekt to avoid the need for adding acceptable violations to the baseline file, and addresses some existing violations in the codebase (explanation commented inline).
=> Tweak detekt rules to supress common issues

CHANGELOG.md, build.gradle
Increases the Kotlin dependency version to 1.3.72. This contains the [following changes](https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-3-70-released/) and allows us to keep up to date.
=> Increase kotlin dependency version to 1.3.72

.buildkite/pipeline.full.yml, .buildkite/pipeline.yml
Adds a temporary soft fail to the Android 4, 6, and 7 E2E tests which are experiencing 400 status codes due to BrowserStack network issues.
=> Soft fail Android 4, 6, and 7 E2E tests

features/full_tests/native_throw_crash.feature
#1049 allowed the CI pipeline to build multiple fixture APKs so that a 'minimal' test fixture which only uses `bugsnag-android-core` could be tested. A bad merge with #1055 resulted in two scenarios failing in `native_throw_crash.feature`, due to the old assertions being used. This changeset adds the correct assertions to the test cases.
As part of #1049 the two scenarios were moved to a separate `cxx-scenarios` module to allow the building of a minimal test fixture that doesn't rely on bugsnag's NDK layer. Both two scenarios throw a C++ exception, and were previously asserting that information about the top stackframes were available. Because the scenario code has been migrated to another module they are now in a separate SO file, so the app is unable to obtain the previous information …
=> Use correct assertion for native throw scenarios

.buildkite/pipeline.full.yml, dockerfiles/Dockerfile.android-ci-base, settings.gradle
Adds a job to the CI which runs a Gradle [build scan](https://scans.gradle.com/) on a full run. This will allow us to identify deprecated Gradle elements and highlight performance bottlenecks in the Gradle build.
The gradle scan for this build is available here: https://scans.gradle.com/s/66v3e4ofxhwko
=> Enable gradle build scan on CI

.buildkite/pipeline.full.yml, .buildkite/pipeline.yml, examples/sdk-app-example/app/src/main/AndroidManifest.xml, examples/sdk-app-example/app/src/main/java/com/example/bugsnag/android/ExampleApplication.kt
Most users will want to keep the default directory for their main app. When using a second process it is necessary to set the `persistenceDirectory`, therefore the example app has been configured to set this value only for any process which does not match the main process.
Tested by running the example app and confirming that the file structure appeared as expected in the Device File explorer.
=> Update example app's to only use different directory for background process

build.gradle
Disables generation of the `BuildConfig` class through the use of the [BuildFeatures](https://developer.android.com/reference/tools/gradle-api/4.1/com/android/build/api/dsl/BuildFeatures) DSL which became available in AGP 4.1. The `BuildConfig` class is unused by bugsnag and adds unnecessary size to the final artefact.
This also disables gradle tasks for aidl, renderscript, shaders, and resValues, which are all unused by the plugin.
Confirmed that compared to an [old build](https://scans.gradle.com/s/nbyrg2fdz5y4w/performance/execution) these changes mean [183 tasks](https://scans.gradle.com/s/dl2xe6hn6k3ea/performance/execution) are registered rather than 225, boosting build speed. Inspected AAR in APK analyzer and confirmed that `BuildConfig` is no longer present.
=> Disable generation of BuildConfig class

dockerfiles/Dockerfile.android-common
`git` isn't included in the ubuntu 20.04 image which was causing the Android Size reporting step to fail. No other CI jobs are affected.
=> Add git to docker image

bugsnag-android-core/src/androidTest/java/com/bugsnag/android/ManifestConfigLoaderTest.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/ConfigInternal.kt, bugsnag-android-core/src/main/java/com/bugsnag/android/Configuration.java, bugsnag-android-core/src/test/java/com/bugsnag/android/ConfigurationFacadeTest.java, bugsnag-android-core/src/test/java/com/bugsnag/android/SessionStoreMaxLimitTest.kt
Tweaks the default maxSessions value to 128, to align with the notifier spec.
=> Tweak maxSessions default to 128

Gemfile, Gemfile.lock, features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/cpp/cxx-scenarios-bugsnag.cpp, features/fixtures/mazerunner/cxx-scenarios-bugsnag/src/main/java/com/bugsnag/android/mazerunner/scenarios/MultiProcessUnhandledCXXErrorScenario.kt, features/full_tests/multi_process.feature
Fixes a multi process E2E scenario which failed on Android <6 due to SIGILL rather than SIGTRAP. This appears to be caused by a difference in platform behaviour by the crashing code - this has been simplified by just calling `abort()` so that it's consistent across API levels. The scenario was also failing on 4.4 due to the service finishing before the error could be thrown - running the crashy code on the main thread has resolved this issue.
Additionally this changeset bumps mazerunner to the latest version.
=> Fix failing multi process scenario

.buildkite/pipeline.full.yml, features/full_tests/batch_2/naughty_strings.feature, features/support/env.rb
Disables a test which was failing on Android 5, which was missed due to the presence of a soft fail. This will remain disabled until PLAT-5606 is addressed. This seems to be the only genuine failure in a [full CI run](https://buildkite.com/bugsnag/bugsnag-android/builds/3197#_) at the moment.
=> Disable failing test on Android 5

bugsnag-plugin-android-anr/src/main/CMakeLists.txt, bugsnag-plugin-android-anr/src/main/jni/anr_google.c, bugsnag-plugin-android-anr/src/main/jni/anr_google.h, bugsnag-plugin-android-anr/src/main/jni/anr_handler.c
PLAT-4956 and PLAT-5607
- Re-block SIGQUIT and then signal the Google ANR thread directly.
- Call Java from an async-safe thread.
Manual testing on multiple OS and device types, checking that both Bugsnag and Google get ANR reports.
=> Switch to Google-friendly ANR handler.

.buildkite/pipeline.full.yml, features/full_tests/batch_2/session_stopping.feature, features/support/env.rb
Makes a few tweaks in relation to flaking scenarios:
1. Temporary soft fail on Android 4.4 and 5 whilst we wait for support from BrowserStack
2. Increase timeout for receiving requests to 60s (the theoretical maximum)
3. Remove `@Flaky` tag from scenarios that should now be fixed by MazeRunner v4
Will be fully covered by CI when we come to merge to `next`.
=> Various updates for flaking scenarios

.buildkite/pipeline.full.yml, .buildkite/pipeline.quick.yml, docker-compose.yml, features/full_tests/batch_2/native_api.feature
Remove use of the Resilient Appium driver.
There's a bug in MazeRunner's Resilient Appium Driver that makes it incompatible with the way that the Android test run.  It erroneously treats a `NoSuchElement` exception, which is "normal" in the Android setup, as a broken Appium session.  The simplest thing to do at this stage is to just stop using the flag.
- Stop using the resilient drive
- Use the official MazeRunner release image
- Remove `@Flaky` tag from scenario, as it was down to the resilient driver and not the scenario.
Covered by running a full CI.
=> Do not use the resilient appium driver
